/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-8-java using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=apply_e64a651770
ROOST_METHOD_SIG_HASH=apply_4647ae4ead

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-8-java/1765436562/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/template/NoOpTemplateRendererTests.java
Tests:
    "@Test
void shouldReturnUnchangedTemplate() {
    NoOpTemplateRenderer renderer = new NoOpTemplateRenderer();
    Map<String, Object> variables = new HashMap<>();
    variables.put("name", "Spring AI");
    String result = renderer.apply("Hello {name}!", variables);
    assertThat(result).isEqualTo("Hello {name}!");
}
"
    "@Test
void shouldReturnUnchangedTemplateWithMultipleVariables() {
    NoOpTemplateRenderer renderer = new NoOpTemplateRenderer();
    Map<String, Object> variables = new HashMap<>();
    variables.put("greeting", "Hello");
    variables.put("name", "Spring AI");
    variables.put("punctuation", "!");
    String result = renderer.apply("{greeting} {name}{punctuation}", variables);
    assertThat(result).isEqualTo("{greeting} {name}{punctuation}");
}
"
    "@Test
void shouldNotAcceptEmptyTemplate() {
    NoOpTemplateRenderer renderer = new NoOpTemplateRenderer();
    Map<String, Object> variables = new HashMap<>();
    assertThatThrownBy(() -> renderer.apply("", variables)).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("template cannot be null or empty");
}
"
    "@Test
void shouldNotAcceptNullTemplate() {
    NoOpTemplateRenderer renderer = new NoOpTemplateRenderer();
    Map<String, Object> variables = new HashMap<>();
    assertThatThrownBy(() -> renderer.apply(null, variables)).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("template cannot be null or empty");
}
"
    "@Test
void shouldNotAcceptNullVariables() {
    NoOpTemplateRenderer renderer = new NoOpTemplateRenderer();
    String template = "Hello!";
    assertThatThrownBy(() -> renderer.apply(template, null)).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("variables cannot be null");
}
"
    "@Test
void shouldNotAcceptVariablesWithNullKeySet() {
    NoOpTemplateRenderer renderer = new NoOpTemplateRenderer();
    String template = "Hello!";
    Map<String, Object> variables = new HashMap<>();
    variables.put(null, "Spring AI");
    assertThatThrownBy(() -> renderer.apply(template, variables)).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("variables keys cannot be null");
}
"
    "@Test
void shouldReturnUnchangedComplexTemplate() {
    NoOpTemplateRenderer renderer = new NoOpTemplateRenderer();
    Map<String, Object> variables = new HashMap<>();
    variables.put("header", "Welcome");
    variables.put("user", "Spring AI");
    variables.put("items", "one, two, three");
    variables.put("footer", "Goodbye");
    String template = """
        {header}
        User: {user}
        Items: {items}
        {footer}
        """;
    String result = renderer.apply(template, variables);
    assertThat(result).isEqualToNormalizingNewlines(template);
}
"

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-8-java/1765436562/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/reader/TextReaderTests.java
Tests:
    "@Test
void loadText() {
    Resource resource = new DefaultResourceLoader().getResource("classpath:text_source.txt");
    assertThat(resource).isNotNull();
    TextReader textReader = new TextReader(resource);
    textReader.getCustomMetadata().put("customKey", "Value");
    List<Document> documents0 = textReader.get();
    List<Document> documents = new TokenTextSplitter().apply(documents0);
    assertThat(documents.size()).isEqualTo(54);
    for (Document document : documents) {
        assertThat(document.getMetadata().get("customKey")).isEqualTo("Value");
        assertThat(document.getMetadata().get(TextReader.SOURCE_METADATA)).isEqualTo("text_source.txt");
        assertThat(document.getMetadata().get(TextReader.CHARSET_METADATA)).isEqualTo("UTF-8");
        assertThat(document.getText()).isNotEmpty();
    }
}
"

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-8-java/1765436562/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/transformer/splitter/TokenTextSplitterTest.java
Tests:
    "@Test
public void testTokenTextSplitterBuilderWithDefaultValues() {
    var contentFormatter1 = DefaultContentFormatter.defaultConfig();
    var contentFormatter2 = DefaultContentFormatter.defaultConfig();
    assertThat(contentFormatter1).isNotSameAs(contentFormatter2);
    var doc1 = new Document("In the end, writing arises when man realizes that memory is not enough.", Map.of("key1", "value1", "key2", "value2"));
    doc1.setContentFormatter(contentFormatter1);
    var doc2 = new Document("The most oppressive thing about the labyrinth is that you are constantly " + "being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.", Map.of("key2", "value22", "key3", "value3"));
    doc2.setContentFormatter(contentFormatter2);
    var tokenTextSplitter = new TokenTextSplitter();
    var chunks = tokenTextSplitter.apply(List.of(doc1, doc2));
    assertThat(chunks.size()).isEqualTo(2);

    assertThat(chunks.get(0).getText()).isEqualTo("In the end, writing arises when man realizes that memory is not enough.");

    assertThat(chunks.get(1).getText()).isEqualTo("The most oppressive thing about the labyrinth is that you are constantly being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.");
    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2").doesNotContainKeys("key3");
    assertThat(chunks.get(1).getMetadata()).containsKeys("key2", "key3").doesNotContainKeys("key1");
}
"
    "@Test
public void testTokenTextSplitterBuilderWithAllFields() {
    var contentFormatter1 = DefaultContentFormatter.defaultConfig();
    var contentFormatter2 = DefaultContentFormatter.defaultConfig();
    assertThat(contentFormatter1).isNotSameAs(contentFormatter2);
    var doc1 = new Document("In the end, writing arises when man realizes that memory is not enough.", Map.of("key1", "value1", "key2", "value2"));
    doc1.setContentFormatter(contentFormatter1);
    var doc2 = new Document("The most oppressive thing about the labyrinth is that you are constantly " + "being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.", Map.of("key2", "value22", "key3", "value3"));
    doc2.setContentFormatter(contentFormatter2);
    var tokenTextSplitter = TokenTextSplitter.builder().withChunkSize(10).withMinChunkSizeChars(5).withMinChunkLengthToEmbed(3).withMaxNumChunks(50).withKeepSeparator(true).build();
    var chunks = tokenTextSplitter.apply(List.of(doc1, doc2));
    assertThat(chunks.size()).isEqualTo(6);

    assertThat(chunks.get(0).getText()).isEqualTo("In the end, writing arises when man realizes that");
    assertThat(chunks.get(1).getText()).isEqualTo("memory is not enough.");

    assertThat(chunks.get(2).getText()).isEqualTo("The most oppressive thing about the labyrinth is that you");
    assertThat(chunks.get(3).getText()).isEqualTo("are constantly being forced to choose.");
    assertThat(chunks.get(4).getText()).isEqualTo("It isn’t the lack of an exit, but");
    assertThat(chunks.get(5).getText()).isEqualTo("the abundance of exits that is so disorienting");


    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(1).getMetadata()).containsKeys("key1", "key2", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(2).getMetadata()).containsKeys("key2", "key3", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(3).getMetadata()).containsKeys("key2", "key3", "parent_document_id", "chunk_index", "total_chunks");

    assertThat(chunks.get(0).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(1).getMetadata().get("chunk_index")).isEqualTo(1);
    assertThat(chunks.get(2).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(3).getMetadata().get("chunk_index")).isEqualTo(1);
    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2").doesNotContainKeys("key3");
    assertThat(chunks.get(2).getMetadata()).containsKeys("key2", "key3").doesNotContainKeys("key1");
}
"

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-8-java/1765436562/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/transformer/splitter/TextSplitterTests.java
Tests:
    "@Test
public void testSplitText() {
    var contentFormatter1 = DefaultContentFormatter.defaultConfig();
    var contentFormatter2 = DefaultContentFormatter.defaultConfig();
    assertThat(contentFormatter1).isNotSameAs(contentFormatter2);
    var doc1 = new Document("In the end, writing arises when man realizes that memory is not enough.", Map.of("key1", "value1", "key2", "value2"));
    doc1.setContentFormatter(contentFormatter1);
    var doc2 = new Document("The most oppressive thing about the labyrinth is that you are constantly " + "being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.", Map.of("key2", "value22", "key3", "value3"));
    doc2.setContentFormatter(contentFormatter2);
    List<Document> chunks = testTextSplitter.apply(List.of(doc1, doc2));
    assertThat(testTextSplitter.isCopyContentFormatter()).isTrue();
    assertThat(chunks).hasSize(4);

    assertThat(chunks.get(0).getText()).isEqualTo("In the end, writing arises when man");
    assertThat(chunks.get(1).getText()).isEqualTo(" realizes that memory is not enough.");

    assertThat(chunks.get(2).getText()).isEqualTo("The most oppressive thing about the labyrinth is that you are constantly being forced to ");
    assertThat(chunks.get(3).getText()).isEqualTo("choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.");


    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(1).getMetadata()).containsKeys("key1", "key2", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(2).getMetadata()).containsKeys("key2", "key3", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(3).getMetadata()).containsKeys("key2", "key3", "parent_document_id", "chunk_index", "total_chunks");

    assertThat(chunks.get(0).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(1).getMetadata().get("chunk_index")).isEqualTo(1);
    assertThat(chunks.get(2).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(3).getMetadata().get("chunk_index")).isEqualTo(1);
    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2").doesNotContainKeys("key3");
    assertThat(chunks.get(2).getMetadata()).containsKeys("key2", "key3").doesNotContainKeys("key1");


    assertThat(chunks.get(0).getContentFormatter()).isSameAs(contentFormatter1);
    assertThat(chunks.get(1).getContentFormatter()).isSameAs(contentFormatter1);
    assertThat(chunks.get(2).getContentFormatter()).isSameAs(contentFormatter2);
    assertThat(chunks.get(3).getContentFormatter()).isSameAs(contentFormatter2);

    testTextSplitter.setCopyContentFormatter(false);
    chunks = testTextSplitter.apply(List.of(doc1, doc2));
    assertThat(chunks.get(0).getContentFormatter()).isNotSameAs(contentFormatter1);
    assertThat(chunks.get(1).getContentFormatter()).isNotSameAs(contentFormatter1);
    assertThat(chunks.get(2).getContentFormatter()).isNotSameAs(contentFormatter2);
    assertThat(chunks.get(3).getContentFormatter()).isNotSameAs(contentFormatter2);
}
"
    "@Test
public void pageNoChunkSplit() {

    var doc1 = new Document("1In the end, writing arises when man realizes that memory is not enough." + "1The most oppressive thing about the labyrinth is that you are constantly " + "1being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.", Map.of("file_name", "sample1.pdf", "page_number", 1));
    var doc2 = new Document("2In the end, writing arises when man realizes that memory is not enough." + "2The most oppressive thing about the labyrinth is that you are constantly " + "2being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.", Map.of("file_name", "sample1.pdf", "page_number", 2));
    var doc3 = new Document("3In the end, writing arises when man realizes that memory is not enough." + "3The most oppressive thing about the labyrinth is that you are constantly " + "3being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.", Map.of("file_name", "sample1.pdf", "page_number", 3));
    var doc4 = new Document("4In the end, writing arises when man realizes that memory is not enough." + "4The most oppressive thing about the labyrinth is that you are constantly " + "4being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.", Map.of("file_name", "sample1.pdf", "page_number", 4));
    var tokenTextSplitter = new TokenTextSplitter();

    List<Document> splitedDocument = tokenTextSplitter.apply(List.of(doc1, doc2, doc3, doc4));

    assertAll(() -> assertThat(splitedDocument).isNotNull(), () -> assertThat(splitedDocument).isNotEmpty(), () -> assertThat(splitedDocument).hasSize(4), () -> assertThat(splitedDocument.get(0).getMetadata().get("page_number")).isEqualTo(1), () -> assertThat(splitedDocument.get(1).getMetadata().get("page_number")).isEqualTo(2), () -> assertThat(splitedDocument.get(2).getMetadata().get("page_number")).isEqualTo(3), () -> assertThat(splitedDocument.get(3).getMetadata().get("page_number")).isEqualTo(4));
}
"
    "@Test
public void pageWithChunkSplit() {

    var doc1 = new Document("1In the end, writing arises when man realizes that memory is not enough." + "1The most oppressive thing about the labyrinth is that you are constantly " + "1being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.", Map.of("file_name", "sample1.pdf", "page_number", 1));
    var doc2 = new Document("levels, their care  providers,   legal  representatives    and   families  get the  right home    and                                                                                               \n" + "                  community-based       support   and   services  at the  right time,  in the  right place.  Please   click here  to                                                                                  \n" + "                  go to Community      Living  Connections.                                                                                                                                                           \n" + "\n" + "                  I  am  trying   to  register    as  a consumer,       but   Carina    will  not   recognize      me   or  my                                                                                        \n" + "                  information.       What    should     I do?                                                                                                                                                         \n" + "\n" + "                  Please  double   check   your  form   entries  including   the spelling  of your   name   and  your                                                                                                 \n" + "                  ProviderOne     number,    or last four  digits of your  social  security  number    and   date  of birth. Please                                                                                   \n" + "                  use the  name    you  have  on  file with  the  Department     of Social  and  Health   Services   (DSHS).  Also                                                                                    \n" + "                  make   sure  you  have   a current  or  pending   assessment     with  DSHS.                                                                                                                        \n" + "\n" + "                  If  you  are  having  trouble registering,   please  contact   us or  call  us  at  1-855-796-0605.                                                                                                 \n" + "\n" + "                  The   Home     Care    Referral    Registry     has  been    absorbed       by  Consumer        Direct   Care                                                                                       \n" + "                  Network      Washington        (CDWA).       Who    can   help   me    find  care   on   Carina?                                                                                                    \n" + "\n" + "                  Consumer     Direct  Care  Network    Washington      (CDWA)    has  taken  over  from   the  Home    Care                                                                                          \n" + "                  Referral  Registry  (HCRR).   CDWA     is  responsible  for assisting  consumers     and   Individual  Providers                                                                                    \n" + "                  (IPs) to use  Carina  to find  matches.    CDWA    staff are  available  across   the state  to  assist                                                                                             \n" + "                  consumers    to  sign up  in the  Carina  system    and  help  IPs get  (re)contracted    or hired  to work.                                                                                        \n" + "\n" + "                  What    are   some    good     interview     questions      I should    ask   providers?                                                                                                            \n" + "\n" + "                  Your  approach    to the  interview   is important,   you   are offering   a job to  someone    who   is looking                                                                                    \n" + "                  for work.  The  person    you  interview   may   be  nervous.   Put  them   at ease,  call them   by their  first                                                                                   \n" + "                  name,   maintain   eye  contact   and  tell them   a little  about yourself.   Read  more    tips and  specific                                                                                     \n" + "                  interview   questions   in our  blog:  What   to Ask  Potential   Providers.                                                                                                                        \n" + "\n" + "                  I  am  ready    to  hire  a  home     care   provider!                                                                                                                                              \n" + "\n" + "                  You  found   an Individual   Provider   (IP) that  you  would   like to hire?  That  is exciting!  In order  for                                                                                    \n" + "                  them   to start working,   contact   Consumer     Direct  Care   Network    Washington     (CDWA)     and  request                                                                                  \n" + "                  authorization.   They   cannot   start work   before   you  have   received   an  Okay  to  Work   from   CDWA.                                                                                     \n" + "\n" + "                  Consumers     should   continue   to work   with  their  case  manager,    who   will help  you  create  a  Plan of                                                                                 \n" + "                  Care  and  access   needed   services.\n" + "Once   you  have  decided    on an  IP to work   with,  they  should\n" + "\n", Map.of("file_name", "sample1.pdf", "page_number", 2));
    var doc3 = new Document("3In the end, writing arises when man realizes that memory is not enough." + "3The most oppressive thing about the labyrinth is that you are constantly " + "3being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.", Map.of("file_name", "sample1.pdf", "page_number", 3));
    var tokenTextSplitter = new TokenTextSplitter();

    List<Document> splitedDocument = tokenTextSplitter.apply(List.of(doc1, doc2, doc3));

    assertAll(() -> assertThat(splitedDocument).isNotNull(), () -> assertThat(splitedDocument).isNotEmpty(), () -> assertThat(splitedDocument).hasSize(4), () -> assertThat(splitedDocument.get(0).getMetadata().get("page_number")).isEqualTo(1), () -> assertThat(splitedDocument.get(1).getMetadata().get("page_number")).isEqualTo(2), () -> assertThat(splitedDocument.get(2).getMetadata().get("page_number")).isEqualTo(2), () -> assertThat(splitedDocument.get(3).getMetadata().get("page_number")).isEqualTo(3));
}
"
    "@Test
public void testSplitTextWithNullMetadata() {
    var contentFormatter = DefaultContentFormatter.defaultConfig();
    var doc = new Document("In the end, writing arises when man realizes that memory is not enough.");
    doc.getMetadata().put("key1", "value1");
    doc.getMetadata().put("key2", null);
    doc.setContentFormatter(contentFormatter);
    List<Document> chunks = testTextSplitter.apply(List.of(doc));
    assertThat(testTextSplitter.isCopyContentFormatter()).isTrue();
    assertThat(chunks).hasSize(2);

    assertThat(chunks.get(0).getText()).isEqualTo("In the end, writing arises when man");
    assertThat(chunks.get(1).getText()).isEqualTo(" realizes that memory is not enough.");


    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(1).getMetadata()).containsKeys("key1", "parent_document_id", "chunk_index", "total_chunks");

    assertThat(chunks.get(0).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(1).getMetadata().get("chunk_index")).isEqualTo(1);

    assertThat(chunks.get(0).getContentFormatter()).isSameAs(contentFormatter);
    assertThat(chunks.get(1).getContentFormatter()).isSameAs(contentFormatter);
}
"
    "@Test
public void testScorePreservation() {

    Double originalScore = 0.95;
    var doc = Document.builder().text("This is a test document that will be split into multiple chunks.").metadata(Map.of("source", "test.txt")).score(originalScore).build();

    List<Document> chunks = testTextSplitter.apply(List.of(doc));

    assertThat(chunks).hasSize(2);
    assertThat(chunks.get(0).getScore()).isEqualTo(originalScore);
    assertThat(chunks.get(1).getScore()).isEqualTo(originalScore);
}
"
    "@Test
public void testParentDocumentTracking() {

    var doc1 = new Document("First document content for testing splitting functionality.", Map.of("source", "doc1.txt"));
    var doc2 = new Document("Second document content for testing splitting functionality.", Map.of("source", "doc2.txt"));
    String originalId1 = doc1.getId();
    String originalId2 = doc2.getId();

    List<Document> chunks = testTextSplitter.apply(List.of(doc1, doc2));

    assertThat(chunks).hasSize(4);

    assertThat(chunks.get(0).getMetadata().get("parent_document_id")).isEqualTo(originalId1);
    assertThat(chunks.get(1).getMetadata().get("parent_document_id")).isEqualTo(originalId1);

    assertThat(chunks.get(2).getMetadata().get("parent_document_id")).isEqualTo(originalId2);
    assertThat(chunks.get(3).getMetadata().get("parent_document_id")).isEqualTo(originalId2);
}
"
    "@Test
public void testChunkMetadataInformation() {

    var doc = new Document("This is a longer document that will be split into exactly two chunks for testing.", Map.of("source", "test.txt"));

    List<Document> chunks = testTextSplitter.apply(List.of(doc));

    assertThat(chunks).hasSize(2);

    assertThat(chunks.get(0).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(0).getMetadata().get("total_chunks")).isEqualTo(2);

    assertThat(chunks.get(1).getMetadata().get("chunk_index")).isEqualTo(1);
    assertThat(chunks.get(1).getMetadata().get("total_chunks")).isEqualTo(2);

    assertThat(chunks.get(0).getMetadata().get("source")).isEqualTo("test.txt");
    assertThat(chunks.get(1).getMetadata().get("source")).isEqualTo("test.txt");
}
"
    "@Test
public void testEnhancedMetadataWithMultipleDocuments() {

    var doc1 = Document.builder().text("First document with score and metadata.").metadata(Map.of("type", "article", "priority", "high")).score(0.8).build();
    var doc2 = Document.builder().text("Second document with different score.").metadata(Map.of("type", "report", "priority", "medium")).score(0.6).build();
    String originalId1 = doc1.getId();
    String originalId2 = doc2.getId();

    List<Document> chunks = testTextSplitter.apply(List.of(doc1, doc2));

    assertThat(chunks).hasSize(4);

    for (int i = 0; i < 2; i++) {
        Document chunk = chunks.get(i);
        assertThat(chunk.getScore()).isEqualTo(0.8);
        assertThat(chunk.getMetadata().get("parent_document_id")).isEqualTo(originalId1);
        assertThat(chunk.getMetadata().get("chunk_index")).isEqualTo(i);
        assertThat(chunk.getMetadata().get("total_chunks")).isEqualTo(2);
        assertThat(chunk.getMetadata().get("type")).isEqualTo("article");
        assertThat(chunk.getMetadata().get("priority")).isEqualTo("high");
    }

    for (int i = 2; i < 4; i++) {
        Document chunk = chunks.get(i);
        assertThat(chunk.getScore()).isEqualTo(0.6);
        assertThat(chunk.getMetadata().get("parent_document_id")).isEqualTo(originalId2);
        assertThat(chunk.getMetadata().get("chunk_index")).isEqualTo(i - 2);
        assertThat(chunk.getMetadata().get("total_chunks")).isEqualTo(2);
        assertThat(chunk.getMetadata().get("type")).isEqualTo("report");
        assertThat(chunk.getMetadata().get("priority")).isEqualTo("medium");
    }
}
"Scenario 1: Apply method returns documents unchanged when contentFormatter is null

Details:
  TestName: applyReturnsUnchangedDocumentsWhenContentFormatterIsNull
  Description: This test verifies that when the ContentFormatTransformer is initialized with a null contentFormatter, the apply method returns the documents list without any modifications to the documents.

Execution:
  Arrange: Create a ContentFormatTransformer with null contentFormatter. Create a list of Document objects with default content formatters.
  Act: Call the apply method with the list of documents.
  Assert: Verify that the returned list is the same reference as the input list and that documents remain unchanged.

Validation:
  The assertion verifies that when contentFormatter is null, no processing occurs on the documents. This is important because it ensures the transformer gracefully handles null configuration without throwing exceptions or modifying data unexpectedly.

---

Scenario 2: Apply method processes documents when contentFormatter is provided

Details:
  TestName: applyProcessesDocumentsWhenContentFormatterIsProvided
  Description: This test verifies that when a valid ContentFormatter is provided, the apply method iterates through all documents and processes each one by applying the content formatter.

Execution:
  Arrange: Create a DefaultContentFormatter instance. Create a ContentFormatTransformer with this formatter. Create a list of Document objects.
  Act: Call the apply method with the list of documents.
  Assert: Verify that the returned list contains the same documents and that each document's content formatter has been updated.

Validation:
  The assertion confirms that the transformer correctly applies the content formatter to each document in the list. This is essential for ensuring document content is properly formatted for downstream processing.

---

Scenario 3: Apply method handles empty document list

Details:
  TestName: applyHandlesEmptyDocumentList
  Description: This test verifies that the apply method correctly handles an empty list of documents without throwing any exceptions and returns an empty list.

Execution:
  Arrange: Create a ContentFormatTransformer with a valid DefaultContentFormatter. Create an empty ArrayList of Documents.
  Act: Call the apply method with the empty list.
  Assert: Verify that the returned list is empty and no exceptions are thrown.

Validation:
  The assertion ensures the method handles edge cases gracefully. An empty document list should not cause any errors and should simply return an empty list, maintaining system stability.

---

Scenario 4: Apply method returns the same list reference

Details:
  TestName: applyReturnsSameListReference
  Description: This test verifies that the apply method returns the same list reference that was passed in, not a new list, indicating in-place modification.

Execution:
  Arrange: Create a ContentFormatTransformer with a DefaultContentFormatter. Create a list of Document objects.
  Act: Call the apply method and capture the returned list.
  Assert: Verify that the returned list is the exact same reference as the input list using assertSame.

Validation:
  The assertion confirms that the method modifies documents in-place rather than creating a new list. This is important for memory efficiency and for maintaining any external references to the original list.

---

Scenario 5: Apply method processes single document correctly

Details:
  TestName: applyProcessesSingleDocumentCorrectly
  Description: This test verifies that the apply method correctly processes a list containing only one document.

Execution:
  Arrange: Create a ContentFormatTransformer with a DefaultContentFormatter. Create a list with a single Document object.
  Act: Call the apply method with the single-document list.
  Assert: Verify that the returned list has size 1 and the document's formatter has been updated.

Validation:
  The assertion ensures that the method works correctly with minimal input. Single-document processing is a common use case that must be handled properly.

---

Scenario 6: Apply method processes multiple documents with different formatters

Details:
  TestName: applyProcessesMultipleDocumentsWithDifferentFormatters
  Description: This test verifies that when multiple documents have different content formatters, the apply method processes each document appropriately.

Execution:
  Arrange: Create a ContentFormatTransformer with a DefaultContentFormatter. Create multiple Document objects, each with different DefaultContentFormatter instances.
  Act: Call the apply method with the list of documents.
  Assert: Verify that all documents in the returned list have been processed and their formatters updated.

Validation:
  The assertion confirms that the transformer handles heterogeneous document collections correctly. This is important in real-world scenarios where documents may come from different sources with varying formatter configurations.

---

Scenario 7: Apply method with disableTemplateRewrite set to true

Details:
  TestName: applyWithDisableTemplateRewriteTrue
  Description: This test verifies that when disableTemplateRewrite is set to true, the apply method processes documents but does not rewrite the text template.

Execution:
  Arrange: Create a ContentFormatTransformer with a DefaultContentFormatter and disableTemplateRewrite set to true. Create documents with DefaultContentFormatter having specific text templates.
  Act: Call the apply method with the documents.
  Assert: Verify that documents are processed but the text template remains unchanged from the original document formatter.

Validation:
  The assertion ensures that the disableTemplateRewrite flag is respected during processing. This is crucial for scenarios where preserving the original template structure is required.

---

Scenario 8: Apply method with disableTemplateRewrite set to false

Details:
  TestName: applyWithDisableTemplateRewriteFalse
  Description: This test verifies that when disableTemplateRewrite is set to false (default), the apply method processes documents and includes the text template in the update.

Execution:
  Arrange: Create a ContentFormatTransformer with a DefaultContentFormatter and disableTemplateRewrite set to false. Create documents with DefaultContentFormatter.
  Act: Call the apply method with the documents.
  Assert: Verify that documents are processed and the text template is included in the formatter update.

Validation:
  The assertion confirms that the default behavior includes template rewriting. This ensures backward compatibility and expected default behavior for most use cases.

---

Scenario 9: Apply method merges excluded embed metadata keys

Details:
  TestName: applyMergesExcludedEmbedMetadataKeys
  Description: This test verifies that when processing documents with DefaultContentFormatter, the excluded embed metadata keys from both the document's formatter and the transformer's formatter are merged.

Execution:
  Arrange: Create a DefaultContentFormatter with specific excluded embed metadata keys. Create a ContentFormatTransformer with this formatter. Create documents with their own DefaultContentFormatter having different excluded embed metadata keys.
  Act: Call the apply method with the documents.
  Assert: Verify that the resulting document formatter contains merged excluded embed metadata keys from both sources.

Validation:
  The assertion ensures that metadata exclusion rules are properly combined rather than overwritten. This is important for maintaining data integrity when multiple formatting rules need to coexist.

---

Scenario 10: Apply method merges excluded inference metadata keys

Details:
  TestName: applyMergesExcludedInferenceMetadataKeys
  Description: This test verifies that when processing documents with DefaultContentFormatter, the excluded inference metadata keys from both formatters are properly merged.

Execution:
  Arrange: Create a DefaultContentFormatter with specific excluded inference metadata keys. Create a ContentFormatTransformer with this formatter. Create documents with their own DefaultContentFormatter having different excluded inference metadata keys.
  Act: Call the apply method with the documents.
  Assert: Verify that the resulting document formatter contains merged excluded inference metadata keys from both sources.

Validation:
  The assertion confirms that inference metadata exclusion rules are properly combined. This is essential for controlling what metadata is used during AI inference operations.

---

Scenario 11: Apply method overrides formatter when document has non-DefaultContentFormatter

Details:
  TestName: applyOverridesFormatterWhenDocumentHasNonDefaultFormatter
  Description: This test verifies that when a document has a ContentFormatter that is not a DefaultContentFormatter, the apply method completely overrides it with the transformer's formatter.

Execution:
  Arrange: Create a ContentFormatTransformer with a custom ContentFormatter (non-DefaultContentFormatter). Create documents with different ContentFormatter implementations.
  Act: Call the apply method with the documents.
  Assert: Verify that each document's formatter is replaced with the transformer's formatter.

Validation:
  The assertion ensures that non-DefaultContentFormatter instances are handled by complete replacement rather than merging. This provides a clear fallback behavior when formatters are incompatible.

---

Scenario 12: Apply method preserves document text content

Details:
  TestName: applyPreservesDocumentTextContent
  Description: This test verifies that the apply method only modifies the content formatter and does not alter the actual text content of the documents.

Execution:
  Arrange: Create a ContentFormatTransformer with a DefaultContentFormatter. Create documents with specific text content.
  Act: Call the apply method with the documents.
  Assert: Verify that each document's text content remains exactly the same as before processing.

Validation:
  The assertion confirms that the transformer only affects formatting configuration, not the actual document content. This is critical for data integrity and ensuring documents are not corrupted during transformation.

---

Scenario 13: Apply method preserves document metadata

Details:
  TestName: applyPreservesDocumentMetadata
  Description: This test verifies that the apply method does not modify the metadata of documents, only the content formatter.

Execution:
  Arrange: Create a ContentFormatTransformer with a DefaultContentFormatter. Create documents with specific metadata entries.
  Act: Call the apply method with the documents.
  Assert: Verify that each document's metadata remains unchanged after processing.

Validation:
  The assertion ensures that document metadata is preserved during transformation. Metadata often contains important contextual information that must not be lost or altered.

---

Scenario 14: Apply method handles documents with null content formatter

Details:
  TestName: applyHandlesDocumentsWithNullContentFormatter
  Description: This test verifies that the apply method correctly handles documents that have a null content formatter by applying the transformer's formatter.

Execution:
  Arrange: Create a ContentFormatTransformer with a DefaultContentFormatter. Create documents without setting a content formatter (default/null state).
  Act: Call the apply method with the documents.
  Assert: Verify that the method processes without exceptions and documents receive the transformer's formatter.

Validation:
  The assertion ensures robust handling of documents in various states. Documents may not always have a formatter set, and the transformer should handle this gracefully.

---

Scenario 15: Apply method preserves metadata template from document formatter

Details:
  TestName: applyPreservesMetadataTemplateFromDocumentFormatter
  Description: This test verifies that when updating a DefaultContentFormatter, the metadata template from the original document formatter is preserved.

Execution:
  Arrange: Create a ContentFormatTransformer with a DefaultContentFormatter. Create documents with DefaultContentFormatter having specific metadata templates.
  Act: Call the apply method with the documents.
  Assert: Verify that the resulting formatter retains the original metadata template from the document.

Validation:
  The assertion confirms that document-specific metadata templates are not overwritten during transformation. This preserves custom formatting configurations that may be important for specific document types.

---

Scenario 16: Apply method preserves metadata separator from document formatter

Details:
  TestName: applyPreservesMetadataSeparatorFromDocumentFormatter
  Description: This test verifies that when updating a DefaultContentFormatter, the metadata separator from the original document formatter is preserved.

Execution:
  Arrange: Create a ContentFormatTransformer with a DefaultContentFormatter. Create documents with DefaultContentFormatter having specific metadata separators.
  Act: Call the apply method with the documents.
  Assert: Verify that the resulting formatter retains the original metadata separator from the document.

Validation:
  The assertion ensures that document-specific formatting preferences like separators are maintained. This is important for consistent output formatting across different document processing pipelines.

*/

// ********RoostGPT********

package org.springframework.ai.transformer;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.ai.document.ContentFormatter;
import org.springframework.ai.document.DefaultContentFormatter;
import org.springframework.ai.document.Document;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.ai.document.DocumentTransformer;

class ContentFormatTransformerApplyTest {

	private DefaultContentFormatter defaultFormatter;

	private Document documentWithDefaultFormatter;

	private Document documentWithCustomMetadata;

	@BeforeEach
	void setUp() {
		defaultFormatter = DefaultContentFormatter.builder()
			.withExcludedEmbedMetadataKeys(List.of("key1"))
			.withExcludedInferenceMetadataKeys(List.of("inferKey1"))
			.build();
	}

	@Test
	@Tag("valid")
	void applyReturnsUnchangedDocumentsWhenContentFormatterIsNull() {
		// Arrange
		ContentFormatTransformer transformer = new ContentFormatTransformer(null);
		Document doc1 = new Document("content1");
		Document doc2 = new Document("content2");
		List<Document> documents = new ArrayList<>(List.of(doc1, doc2));

		ContentFormatter originalFormatter1 = doc1.getContentFormatter();
		ContentFormatter originalFormatter2 = doc2.getContentFormatter();
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertSame(documents, result);
		assertSame(originalFormatter1, doc1.getContentFormatter());
		assertSame(originalFormatter2, doc2.getContentFormatter());
	}

	@Test
	@Tag("valid")
	void applyProcessesDocumentsWhenContentFormatterIsProvided() {
		// Arrange
		ContentFormatTransformer transformer = new ContentFormatTransformer(defaultFormatter);
		Document doc1 = new Document("content1");
		Document doc2 = new Document("content2");
		List<Document> documents = new ArrayList<>(List.of(doc1, doc2));
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertSame(documents, result);
		assertEquals(2, result.size());
		assertNotNull(doc1.getContentFormatter());
		assertNotNull(doc2.getContentFormatter());
	}

	@Test
	@Tag("boundary")
	void applyHandlesEmptyDocumentList() {
		// Arrange
		ContentFormatTransformer transformer = new ContentFormatTransformer(defaultFormatter);
		List<Document> documents = new ArrayList<>();
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertNotNull(result);
		assertTrue(result.isEmpty());
	}

	@Test
	@Tag("valid")
	void applyReturnsSameListReference() {
		// Arrange
		ContentFormatTransformer transformer = new ContentFormatTransformer(defaultFormatter);
		Document doc = new Document("content");
		List<Document> documents = new ArrayList<>(List.of(doc));
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertSame(documents, result);
	}

	@Test
	@Tag("valid")
	void applyProcessesSingleDocumentCorrectly() {
		// Arrange
		ContentFormatTransformer transformer = new ContentFormatTransformer(defaultFormatter);
		Document doc = new Document("single content");
		List<Document> documents = new ArrayList<>(List.of(doc));
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertEquals(1, result.size());
		assertNotNull(result.get(0).getContentFormatter());
	}

	@Test
	@Tag("valid")
	void applyProcessesMultipleDocumentsWithDifferentFormatters() {
		// Arrange
		ContentFormatTransformer transformer = new ContentFormatTransformer(defaultFormatter);

		DefaultContentFormatter formatter1 = DefaultContentFormatter.builder()
			.withExcludedEmbedMetadataKeys(List.of("docKey1"))
			.build();
		DefaultContentFormatter formatter2 = DefaultContentFormatter.builder()
			.withExcludedEmbedMetadataKeys(List.of("docKey2"))
			.build();

		Document doc1 = new Document("content1");
		doc1.setContentFormatter(formatter1);
		Document doc2 = new Document("content2");
		doc2.setContentFormatter(formatter2);

		List<Document> documents = new ArrayList<>(List.of(doc1, doc2));
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertEquals(2, result.size());
		assertNotNull(doc1.getContentFormatter());
		assertNotNull(doc2.getContentFormatter());
	}

	@Test
	@Tag("valid")
	void applyWithDisableTemplateRewriteTrue() {
		// Arrange
		DefaultContentFormatter transformerFormatter = DefaultContentFormatter.builder()
			.withExcludedEmbedMetadataKeys(List.of("transformerKey"))
			.withTextTemplate("transformer template")
			.build();
		ContentFormatTransformer transformer = new ContentFormatTransformer(transformerFormatter, true);

		DefaultContentFormatter docFormatter = DefaultContentFormatter.builder()
			.withExcludedEmbedMetadataKeys(List.of("docKey"))
			.withTextTemplate("original template")
			.build();

		Document doc = new Document("content");
		doc.setContentFormatter(docFormatter);
		List<Document> documents = new ArrayList<>(List.of(doc));
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertEquals(1, result.size());
		assertNotNull(doc.getContentFormatter());
	}

	@Test
	@Tag("valid")
	void applyWithDisableTemplateRewriteFalse() {
		// Arrange
		DefaultContentFormatter transformerFormatter = DefaultContentFormatter.builder()
			.withExcludedEmbedMetadataKeys(List.of("transformerKey"))
			.withTextTemplate("transformer template")
			.build();
		ContentFormatTransformer transformer = new ContentFormatTransformer(transformerFormatter, false);

		DefaultContentFormatter docFormatter = DefaultContentFormatter.builder()
			.withExcludedEmbedMetadataKeys(List.of("docKey"))
			.withTextTemplate("original template")
			.build();

		Document doc = new Document("content");
		doc.setContentFormatter(docFormatter);
		List<Document> documents = new ArrayList<>(List.of(doc));
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertEquals(1, result.size());
		assertNotNull(doc.getContentFormatter());
		assertTrue(doc.getContentFormatter() instanceof DefaultContentFormatter);
	}

	@Test
	@Tag("valid")
	void applyMergesExcludedEmbedMetadataKeys() {
		// Arrange
		DefaultContentFormatter transformerFormatter = DefaultContentFormatter.builder()
			.withExcludedEmbedMetadataKeys(List.of("transformerEmbedKey1", "transformerEmbedKey2"))
			.build();
		ContentFormatTransformer transformer = new ContentFormatTransformer(transformerFormatter);

		DefaultContentFormatter docFormatter = DefaultContentFormatter.builder()
			.withExcludedEmbedMetadataKeys(List.of("docEmbedKey1", "docEmbedKey2"))
			.build();

		Document doc = new Document("content");
		doc.setContentFormatter(docFormatter);
		List<Document> documents = new ArrayList<>(List.of(doc));
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertEquals(1, result.size());
		assertTrue(doc.getContentFormatter() instanceof DefaultContentFormatter);
		DefaultContentFormatter resultFormatter = (DefaultContentFormatter) doc.getContentFormatter();
		List<String> excludedKeys = resultFormatter.getExcludedEmbedMetadataKeys();
		assertTrue(excludedKeys.contains("docEmbedKey1"));
		assertTrue(excludedKeys.contains("docEmbedKey2"));
		assertTrue(excludedKeys.contains("transformerEmbedKey1"));
		assertTrue(excludedKeys.contains("transformerEmbedKey2"));
	}

	@Test
	@Tag("valid")
	void applyMergesExcludedInferenceMetadataKeys() {
		// Arrange
		DefaultContentFormatter transformerFormatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys(List.of("transformerInferKey1", "transformerInferKey2"))
			.build();
		ContentFormatTransformer transformer = new ContentFormatTransformer(transformerFormatter);

		DefaultContentFormatter docFormatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys(List.of("docInferKey1", "docInferKey2"))
			.build();

		Document doc = new Document("content");
		doc.setContentFormatter(docFormatter);
		List<Document> documents = new ArrayList<>(List.of(doc));
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertEquals(1, result.size());
		assertTrue(doc.getContentFormatter() instanceof DefaultContentFormatter);
		DefaultContentFormatter resultFormatter = (DefaultContentFormatter) doc.getContentFormatter();
		List<String> excludedKeys = resultFormatter.getExcludedInferenceMetadataKeys();
		assertTrue(excludedKeys.contains("docInferKey1"));
		assertTrue(excludedKeys.contains("docInferKey2"));
		assertTrue(excludedKeys.contains("transformerInferKey1"));
		assertTrue(excludedKeys.contains("transformerInferKey2"));
	}

	@Test
	@Tag("valid")
	void applyOverridesFormatterWhenDocumentHasNonDefaultFormatter() {
		// Arrange
		ContentFormatter customFormatter = new ContentFormatter() {
			@Override
			public String format(Document document) {
				return document.getText();
			}
		};

		ContentFormatTransformer transformer = new ContentFormatTransformer(customFormatter);

		Document doc = new Document("content");
		List<Document> documents = new ArrayList<>(List.of(doc));
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertEquals(1, result.size());
		assertSame(customFormatter, doc.getContentFormatter());
	}

	@Test
	@Tag("valid")
	void applyPreservesDocumentTextContent() {
		// Arrange
		ContentFormatTransformer transformer = new ContentFormatTransformer(defaultFormatter);
		String originalContent1 = "Original content 1";
		String originalContent2 = "Original content 2";

		Document doc1 = new Document(originalContent1);
		Document doc2 = new Document(originalContent2);
		List<Document> documents = new ArrayList<>(List.of(doc1, doc2));
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertEquals(originalContent1, result.get(0).getText());
		assertEquals(originalContent2, result.get(1).getText());
	}

	@Test
	@Tag("valid")
	void applyPreservesDocumentMetadata() {
		// Arrange
		ContentFormatTransformer transformer = new ContentFormatTransformer(defaultFormatter);

		Map<String, Object> metadata1 = new HashMap<>();
		metadata1.put("key1", "value1");
		metadata1.put("key2", 123);

		Document doc = new Document("content", metadata1);
		List<Document> documents = new ArrayList<>(List.of(doc));
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertEquals("value1", result.get(0).getMetadata().get("key1"));
		assertEquals(123, result.get(0).getMetadata().get("key2"));
	}

	@Test
	@Tag("boundary")
	void applyHandlesDocumentsWithNullContentFormatter() {
		// Arrange
		ContentFormatTransformer transformer = new ContentFormatTransformer(defaultFormatter);
		Document doc = new Document("content");
		// Document may have default formatter, not null
		List<Document> documents = new ArrayList<>(List.of(doc));
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertNotNull(result);
		assertEquals(1, result.size());
		assertNotNull(doc.getContentFormatter());
	}

	@Test
	@Tag("valid")
	void applyPreservesMetadataTemplateFromDocumentFormatter() {
		// Arrange
		String customMetadataTemplate = "Custom Metadata: {metadata}";
		DefaultContentFormatter transformerFormatter = DefaultContentFormatter.builder()
			.withExcludedEmbedMetadataKeys(List.of("transformerKey"))
			.build();
		ContentFormatTransformer transformer = new ContentFormatTransformer(transformerFormatter);

		DefaultContentFormatter docFormatter = DefaultContentFormatter.builder()
			.withMetadataTemplate(customMetadataTemplate)
			.build();

		Document doc = new Document("content");
		doc.setContentFormatter(docFormatter);
		List<Document> documents = new ArrayList<>(List.of(doc));
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertEquals(1, result.size());
		assertTrue(doc.getContentFormatter() instanceof DefaultContentFormatter);
		DefaultContentFormatter resultFormatter = (DefaultContentFormatter) doc.getContentFormatter();
		assertEquals(customMetadataTemplate, resultFormatter.getMetadataTemplate());
	}

	@Test
	@Tag("valid")
	void applyPreservesMetadataSeparatorFromDocumentFormatter() {
		// Arrange
		String customSeparator = " | ";
		DefaultContentFormatter transformerFormatter = DefaultContentFormatter.builder()
			.withExcludedEmbedMetadataKeys(List.of("transformerKey"))
			.build();
		ContentFormatTransformer transformer = new ContentFormatTransformer(transformerFormatter);

		DefaultContentFormatter docFormatter = DefaultContentFormatter.builder()
			.withMetadataSeparator(customSeparator)
			.build();

		Document doc = new Document("content");
		doc.setContentFormatter(docFormatter);
		List<Document> documents = new ArrayList<>(List.of(doc));
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertEquals(1, result.size());
		assertTrue(doc.getContentFormatter() instanceof DefaultContentFormatter);
		DefaultContentFormatter resultFormatter = (DefaultContentFormatter) doc.getContentFormatter();
		assertEquals(customSeparator, resultFormatter.getMetadataSeparator());
	}

	@Test
	@Tag("valid")
	void applyWithDefaultConstructor() {
		// Arrange
		ContentFormatTransformer transformer = new ContentFormatTransformer(defaultFormatter);
		Document doc = new Document("content");
		List<Document> documents = new ArrayList<>(List.of(doc));
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertNotNull(result);
		assertEquals(1, result.size());
	}

	@Test
	@Tag("valid")
	void applyWithParameterizedConstructor() {
		// Arrange
		ContentFormatTransformer transformer = new ContentFormatTransformer(defaultFormatter, true);
		Document doc = new Document("content");
		List<Document> documents = new ArrayList<>(List.of(doc));
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertNotNull(result);
		assertEquals(1, result.size());
	}

	@Test
	@Tag("valid")
	void applyProcessesLargeDocumentList() {
		// Arrange
		ContentFormatTransformer transformer = new ContentFormatTransformer(defaultFormatter);
		List<Document> documents = new ArrayList<>();
		for (int i = 0; i < 100; i++) {
			documents.add(new Document("content " + i));
		}
		// Act
		List<Document> result = transformer.apply(documents);
		// Assert
		assertEquals(100, result.size());
		for (Document doc : result) {
			assertNotNull(doc.getContentFormatter());
		}
	}

}