/*
 * Copyright 2023-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-5-java using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=instantiateAvailableModules_76bbb9d97e
ROOST_METHOD_SIG_HASH=instantiateAvailableModules_ad9f8634b7

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-5-java/1764915462/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/util/JacksonUtilsTests.java
Tests:
    "@Test
void usesCorrectClassLoader() throws JsonProcessingException, ClassNotFoundException {
    ClassLoader previousLoader = Thread.currentThread().getContextClassLoader();
    try {

        Thread.currentThread().setContextClassLoader(getClass().getClassLoader().getParent());

        var jsonMapper = JsonMapper.builder().addModules(JacksonUtils.instantiateAvailableModules()).build();
        Class<?> clazz = getClass().getClassLoader().loadClass(getClass().getName() + "$Cell");
        var output = jsonMapper.readValue("{\"name\":\"Amoeba\",\"lifespan\":\"PT42S\"}", clazz);
        assertThat(output).isEqualTo(new Cell("Amoeba", Duration.of(42L, ChronoUnit.SECONDS)));
    } finally {
        Thread.currentThread().setContextClassLoader(previousLoader);
    }
}
"Scenario 1: Verify All Available Modules Are Instantiated When All Dependencies Are Present

Details:
  TestName: allAvailableModulesInstantiatedWhenDependenciesPresent
  Description: This test verifies that when all Jackson module dependencies (Jdk8Module, JavaTimeModule, ParameterNamesModule) are available in the classpath, the method returns a list containing all these modules.

Execution:
  Arrange: No special setup required as the test assumes all standard Jackson modules are available in the classpath.
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list is not empty and contains at least 3 modules (Jdk8Module, JavaTimeModule, ParameterNamesModule). Check that each module type is present in the list.

Validation:
  The assertion verifies that the method correctly discovers and instantiates all available Jackson modules from the classpath. This is significant because proper module instantiation is essential for Jackson to correctly serialize/deserialize Java 8 types, date/time types, and use parameter names for constructor-based deserialization.

---

Scenario 2: Verify Returned List Is Not Null

Details:
  TestName: returnedListIsNeverNull
  Description: This test ensures that the method always returns a non-null list, even if no modules are available.

Execution:
  Arrange: No special setup required.
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list is not null using assertNotNull.

Validation:
  The assertion confirms that the method adheres to good API design by never returning null. This prevents NullPointerException in calling code and ensures predictable behavior.

---

Scenario 3: Verify Jdk8Module Is Included When Available

Details:
  TestName: jdk8ModuleIncludedWhenAvailable
  Description: This test verifies that when the Jdk8Module class is available in the classpath, it is properly instantiated and added to the returned list.

Execution:
  Arrange: No special setup required as Jdk8Module is expected to be in the test classpath.
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list contains an instance of Jdk8Module by checking the class names of the modules in the list.

Validation:
  The assertion confirms that Jdk8Module is correctly discovered and instantiated. This module is important for handling Optional, OptionalInt, OptionalLong, and OptionalDouble types in Jackson serialization.

---

Scenario 4: Verify JavaTimeModule Is Included When Available

Details:
  TestName: javaTimeModuleIncludedWhenAvailable
  Description: This test verifies that when the JavaTimeModule class is available in the classpath, it is properly instantiated and added to the returned list.

Execution:
  Arrange: No special setup required as JavaTimeModule is expected to be in the test classpath.
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list contains an instance of JavaTimeModule by checking the class names of the modules in the list.

Validation:
  The assertion confirms that JavaTimeModule is correctly discovered and instantiated. This module is critical for handling Java 8 Date/Time API types like LocalDate, LocalDateTime, Duration, Instant, etc.

---

Scenario 5: Verify ParameterNamesModule Is Included When Available

Details:
  TestName: parameterNamesModuleIncludedWhenAvailable
  Description: This test verifies that when the ParameterNamesModule class is available in the classpath, it is properly instantiated and added to the returned list.

Execution:
  Arrange: No special setup required as ParameterNamesModule is expected to be in the test classpath.
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list contains an instance of ParameterNamesModule by checking the class names of the modules in the list.

Validation:
  The assertion confirms that ParameterNamesModule is correctly discovered and instantiated. This module enables Jackson to use constructor parameter names for deserialization without requiring @JsonProperty annotations.

---

Scenario 6: Verify Method Returns ArrayList Instance

Details:
  TestName: returnedListIsArrayListInstance
  Description: This test verifies that the returned list is an instance of ArrayList, ensuring it is mutable and can be modified by the caller if needed.

Execution:
  Arrange: No special setup required.
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list is an instance of ArrayList using instanceof check.

Validation:
  The assertion confirms the implementation detail that an ArrayList is returned, which is important for callers who may need to add additional modules to the list.

---

Scenario 7: Verify Multiple Invocations Return Independent Lists

Details:
  TestName: multipleInvocationsReturnIndependentLists
  Description: This test verifies that each invocation of the method returns a new, independent list instance, ensuring no shared state between calls.

Execution:
  Arrange: No special setup required.
  Act: Invoke JacksonUtils.instantiateAvailableModules() twice and store both results.
  Assert: Verify that the two returned lists are not the same object reference (using assertNotSame) but contain the same number of modules.

Validation:
  The assertion confirms that the method creates a new list on each invocation, preventing unintended side effects if one caller modifies the returned list.

---

Scenario 8: Verify Modules Are Properly Instantiated Objects

Details:
  TestName: modulesAreProperlyInstantiatedObjects
  Description: This test verifies that each module in the returned list is a properly instantiated object (not null) and is an instance of com.fasterxml.jackson.databind.Module.

Execution:
  Arrange: No special setup required.
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: Iterate through the returned list and verify each element is not null and is an instance of Module.

Validation:
  The assertion confirms that BeanUtils.instantiateClass successfully creates valid module instances. This is important to ensure the modules can be registered with an ObjectMapper.

---

Scenario 9: Verify Method Handles ClassNotFoundException Gracefully

Details:
  TestName: methodHandlesClassNotFoundExceptionGracefully
  Description: This test verifies that when a module class is not found, the method continues processing other modules without throwing an exception.

Execution:
  Arrange: No special setup required (the method internally handles ClassNotFoundException).
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that no exception is thrown and a list is returned successfully.

Validation:
  The assertion confirms that the method's exception handling works correctly, allowing partial module loading when not all dependencies are available. This is crucial for applications that may not have all optional Jackson modules.

---

Scenario 10: Verify Returned List Size Matches Available Modules

Details:
  TestName: returnedListSizeMatchesAvailableModules
  Description: This test verifies that the size of the returned list corresponds to the number of Jackson modules actually available in the classpath.

Execution:
  Arrange: No special setup required.
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the list size is greater than or equal to 3 (assuming standard modules are available) and check the exact count based on Kotlin presence.

Validation:
  The assertion confirms that all available modules are discovered and added to the list. The expected count depends on whether Kotlin is present in the runtime environment.

---

Scenario 11: Verify KotlinModule Is Conditionally Included Based On Kotlin Presence

Details:
  TestName: kotlinModuleConditionallyIncludedBasedOnKotlinPresence
  Description: This test verifies that KotlinModule is only added to the list when Kotlin is detected as present in the runtime environment.

Execution:
  Arrange: Check KotlinDetector.isKotlinPresent() to determine expected behavior.
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: If Kotlin is present and KotlinModule is available, verify it's in the list. If Kotlin is not present, verify KotlinModule is not in the list.

Validation:
  The assertion confirms that the conditional logic for Kotlin module loading works correctly. This prevents unnecessary class loading attempts when Kotlin is not being used.

---

Scenario 12: Verify Each Module Has Unique Module Name

Details:
  TestName: eachModuleHasUniqueModuleName
  Description: This test verifies that each module in the returned list has a unique module name, ensuring no duplicate modules are added.

Execution:
  Arrange: No special setup required.
  Act: Invoke JacksonUtils.instantiateAvailableModules() method and collect module names using getModuleName() method.
  Assert: Verify that all module names in the list are unique by comparing the list size with a Set of module names.

Validation:
  The assertion confirms that no duplicate modules are instantiated, which could cause issues when registering modules with an ObjectMapper.

*/

// ********RoostGPT********

package org.springframework.ai.util;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import com.fasterxml.jackson.databind.Module;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.core.KotlinDetector;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.BeanUtils;

class JacksonUtilsInstantiateAvailableModulesTest {

	@Test
	@Tag("valid")
	void allAvailableModulesInstantiatedWhenDependenciesPresent() {
		// Act
		List<Module> modules = JacksonUtils.instantiateAvailableModules();
		// Assert
		assertNotNull(modules);
		assertTrue(modules.size() >= 3,
				"Expected at least 3 modules (Jdk8Module, JavaTimeModule, ParameterNamesModule)");

		boolean hasJdk8Module = modules.stream().anyMatch(m -> m.getClass().getName().contains("Jdk8Module"));
		boolean hasJavaTimeModule = modules.stream().anyMatch(m -> m.getClass().getName().contains("JavaTimeModule"));
		boolean hasParameterNamesModule = modules.stream()
			.anyMatch(m -> m.getClass().getName().contains("ParameterNamesModule"));

		assertTrue(hasJdk8Module, "Jdk8Module should be present");
		assertTrue(hasJavaTimeModule, "JavaTimeModule should be present");
		assertTrue(hasParameterNamesModule, "ParameterNamesModule should be present");
	}

	@Test
	@Tag("valid")
	void returnedListIsNeverNull() {
		// Act
		List<Module> modules = JacksonUtils.instantiateAvailableModules();
		// Assert
		assertNotNull(modules, "Returned list should never be null");
	}

	@Test
	@Tag("valid")
	void jdk8ModuleIncludedWhenAvailable() {
		// Act
		List<Module> modules = JacksonUtils.instantiateAvailableModules();
		// Assert
		boolean hasJdk8Module = modules.stream()
			.anyMatch(m -> m.getClass().getName().equals("com.fasterxml.jackson.datatype.jdk8.Jdk8Module"));

		assertTrue(hasJdk8Module, "Jdk8Module should be included when available");
	}

	@Test
	@Tag("valid")
	void javaTimeModuleIncludedWhenAvailable() {
		// Act
		List<Module> modules = JacksonUtils.instantiateAvailableModules();
		// Assert
		boolean hasJavaTimeModule = modules.stream()
			.anyMatch(m -> m.getClass().getName().equals("com.fasterxml.jackson.datatype.jsr310.JavaTimeModule"));

		assertTrue(hasJavaTimeModule, "JavaTimeModule should be included when available");
	}

	@Test
	@Tag("valid")
	void parameterNamesModuleIncludedWhenAvailable() {
		// Act
		List<Module> modules = JacksonUtils.instantiateAvailableModules();
		// Assert
		boolean hasParameterNamesModule = modules.stream()
			.anyMatch(
					m -> m.getClass().getName().equals("com.fasterxml.jackson.module.paramnames.ParameterNamesModule"));

		assertTrue(hasParameterNamesModule, "ParameterNamesModule should be included when available");
	}

	@Test
	@Tag("valid")
	void returnedListIsArrayListInstance() {
		// Act
		List<Module> modules = JacksonUtils.instantiateAvailableModules();
		// Assert
		assertTrue(modules instanceof ArrayList, "Returned list should be an ArrayList instance");
	}

	@Test
	@Tag("valid")
	void multipleInvocationsReturnIndependentLists() {
		// Act
		List<Module> modules1 = JacksonUtils.instantiateAvailableModules();
		List<Module> modules2 = JacksonUtils.instantiateAvailableModules();
		// Assert
		assertNotSame(modules1, modules2, "Each invocation should return a new list instance");
		assertEquals(modules1.size(), modules2.size(), "Both lists should contain the same number of modules");
	}

	@Test
	@Tag("valid")
	void modulesAreProperlyInstantiatedObjects() {
		// Act
		List<Module> modules = JacksonUtils.instantiateAvailableModules();
		// Assert
		assertFalse(modules.isEmpty(), "Modules list should not be empty");
		for (Module module : modules) {
			assertNotNull(module, "Each module should not be null");
			assertTrue(module instanceof Module, "Each element should be an instance of Module");
		}
	}

	@Test
	@Tag("valid")
	void methodHandlesClassNotFoundExceptionGracefully() {
		// Act & Assert
		assertDoesNotThrow(() -> {
			List<Module> modules = JacksonUtils.instantiateAvailableModules();
			assertNotNull(modules);
		}, "Method should handle ClassNotFoundException gracefully without throwing");
	}

	@Test
	@Tag("valid")
	void returnedListSizeMatchesAvailableModules() {
		// Act
		List<Module> modules = JacksonUtils.instantiateAvailableModules();
		// Assert
		assertTrue(modules.size() >= 3, "List should contain at least 3 modules (standard Jackson modules)");

		if (KotlinDetector.isKotlinPresent()) {
			// If Kotlin is present and KotlinModule is available, expect 4 modules
			// Note: KotlinModule might not be in classpath even if Kotlin is present
			assertTrue(modules.size() >= 3, "List should contain at least 3 modules when Kotlin is present");
		}
	}

	@Test
	@Tag("valid")
	void kotlinModuleConditionallyIncludedBasedOnKotlinPresence() {
		// Arrange
		boolean kotlinPresent = KotlinDetector.isKotlinPresent();
		// Act
		List<Module> modules = JacksonUtils.instantiateAvailableModules();
		// Assert
		boolean hasKotlinModule = modules.stream().anyMatch(m -> m.getClass().getName().contains("KotlinModule"));
		if (!kotlinPresent) {
			assertFalse(hasKotlinModule, "KotlinModule should not be included when Kotlin is not present");
		}
		// Note: If Kotlin is present, KotlinModule may or may not be in classpath
	}

	@Test
	@Tag("valid")
	void eachModuleHasUniqueModuleName() {
		// Act
		List<Module> modules = JacksonUtils.instantiateAvailableModules();
		// Assert
		Set<String> moduleNames = new HashSet<>();
		for (Module module : modules) {
			String moduleName = module.getModuleName();
			assertNotNull(moduleName, "Module name should not be null");
			moduleNames.add(moduleName);
		}

		assertEquals(modules.size(), moduleNames.size(), "All module names should be unique");
	}

	@Test
	@Tag("boundary")
	void returnedListIsModifiable() {
		// Act
		List<Module> modules = JacksonUtils.instantiateAvailableModules();
		int originalSize = modules.size();
		// Assert - verify list is modifiable (ArrayList should be modifiable)
		assertDoesNotThrow(() -> {
			if (!modules.isEmpty()) {
				Module firstModule = modules.get(0);
				modules.remove(0);
				assertEquals(originalSize - 1, modules.size());
				modules.add(firstModule);
				assertEquals(originalSize, modules.size());
			}
		}, "Returned ArrayList should be modifiable");
	}

	@Test
	@Tag("valid")
	void modulesCanBeRegisteredWithObjectMapper() {
		// Act
		List<Module> modules = JacksonUtils.instantiateAvailableModules();
		// Assert
		for (Module module : modules) {
			assertNotNull(module.getModuleName(), "Each module should have a valid module name");
			assertNotNull(module.version(), "Each module should have a valid version");
		}
	}

	@Test
	@Tag("integration")
	void verifyModuleClassNames() {
		// Act
		List<Module> modules = JacksonUtils.instantiateAvailableModules();
		// Assert
		List<String> expectedClassNames = new ArrayList<>();
		expectedClassNames.add("com.fasterxml.jackson.datatype.jdk8.Jdk8Module");
		expectedClassNames.add("com.fasterxml.jackson.datatype.jsr310.JavaTimeModule");
		expectedClassNames.add("com.fasterxml.jackson.module.paramnames.ParameterNamesModule");
		for (String expectedClassName : expectedClassNames) {
			boolean found = modules.stream().anyMatch(m -> m.getClass().getName().equals(expectedClassName));
			assertTrue(found, "Expected module " + expectedClassName + " to be present");
		}
	}

}