/*
 * Copyright 2023-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-17-adk using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=instantiateAvailableModules_76bbb9d97e
ROOST_METHOD_SIG_HASH=instantiateAvailableModules_ad9f8634b7

Scenario 1: All Jackson Modules Available in Classpath

Details:
  TestName: allModulesAvailableInClasspath
  Description: This test verifies that when all four Jackson modules (Jdk8Module, JavaTimeModule, ParameterNamesModule, and KotlinModule) are available in the classpath and Kotlin is present, the method successfully instantiates and returns all four modules in the list.

Execution:
  Arrange: Mock the KotlinDetector.isKotlinPresent() to return true. Ensure all Jackson module classes are available in the classpath (Jdk8Module, JavaTimeModule, ParameterNamesModule, KotlinModule). Mock BeanUtils.instantiateClass() to return mock instances of each module type.
  Act: Call JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list contains exactly 4 modules. Assert that each module type is present in the list (Jdk8Module, JavaTimeModule, ParameterNamesModule, KotlinModule).

Validation:
  This test ensures that in an ideal scenario where all dependencies are present, the method correctly discovers and instantiates all supported Jackson modules. This is important for applications that have full Jackson support and need all serialization/deserialization features available.


Scenario 2: No Jackson Modules Available in Classpath

Details:
  TestName: noModulesAvailableInClasspath
  Description: This test validates the behavior when none of the Jackson modules are available in the classpath. The method should handle ClassNotFoundException gracefully and return an empty list.

Execution:
  Arrange: Mock Class.forName() to throw ClassNotFoundException for all four module class names (Jdk8Module, JavaTimeModule, ParameterNamesModule, KotlinModule). Mock KotlinDetector.isKotlinPresent() to return true or false (shouldn't matter as KotlinModule class won't be found).
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list is not null. Assert that the returned list is empty (size equals 0).

Validation:
  This test confirms that the method handles missing dependencies gracefully without throwing exceptions. This is crucial for applications that may not have all Jackson modules as dependencies, ensuring the application doesn't crash due to missing optional libraries.


Scenario 3: Only Jdk8Module Available in Classpath

Details:
  TestName: onlyJdk8ModuleAvailable
  Description: This test checks the scenario where only the Jdk8Module is present in the classpath while other modules are missing. The method should successfully instantiate only the available module.

Execution:
  Arrange: Mock Class.forName() to succeed for "com.fasterxml.jackson.datatype.jdk8.Jdk8Module" and throw ClassNotFoundException for JavaTimeModule, ParameterNamesModule, and KotlinModule. Mock BeanUtils.instantiateClass() to return a mock Jdk8Module instance. Mock KotlinDetector.isKotlinPresent() to return true.
  Act: Call JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list contains exactly 1 module. Assert that the module is an instance of Jdk8Module.

Validation:
  This test ensures partial dependency resolution works correctly. Applications may selectively include Jackson modules based on their needs, and this test validates that the method can handle such selective availability.


Scenario 4: Only JavaTimeModule Available in Classpath

Details:
  TestName: onlyJavaTimeModuleAvailable
  Description: This test validates the behavior when only JavaTimeModule is present in the classpath, while Jdk8Module, ParameterNamesModule, and KotlinModule are not available.

Execution:
  Arrange: Mock Class.forName() to throw ClassNotFoundException for Jdk8Module, succeed for "com.fasterxml.jackson.datatype.jsr310.JavaTimeModule", and throw ClassNotFoundException for ParameterNamesModule and KotlinModule. Mock BeanUtils.instantiateClass() to return a mock JavaTimeModule instance. Mock KotlinDetector.isKotlinPresent() to return false.
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list contains exactly 1 module. Assert that the module is an instance of JavaTimeModule.

Validation:
  This test confirms that the method correctly handles the scenario where only the Java 8 Date/Time API module is available. This is common in applications that primarily work with java.time classes but don't need other Jackson extensions.


Scenario 5: Only ParameterNamesModule Available in Classpath

Details:
  TestName: onlyParameterNamesModuleAvailable
  Description: This test verifies the method's behavior when only ParameterNamesModule is present in the classpath, with all other modules unavailable.

Execution:
  Arrange: Mock Class.forName() to throw ClassNotFoundException for Jdk8Module and JavaTimeModule, succeed for "com.fasterxml.jackson.module.paramnames.ParameterNamesModule", and throw ClassNotFoundException for KotlinModule. Mock BeanUtils.instantiateClass() to return a mock ParameterNamesModule instance. Mock KotlinDetector.isKotlinPresent() to return true.
  Act: Call JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list contains exactly 1 module. Assert that the module is an instance of ParameterNamesModule.

Validation:
  This test ensures that the method can successfully instantiate the ParameterNamesModule independently. This module is useful for applications that need to deserialize JSON to Java objects using constructor parameter names.


Scenario 6: Kotlin Present but KotlinModule Not Available

Details:
  TestName: kotlinPresentButModuleNotAvailable
  Description: This test validates the scenario where Kotlin is detected as present in the runtime environment, but the KotlinModule is not available in the classpath. The method should handle this gracefully.

Execution:
  Arrange: Mock KotlinDetector.isKotlinPresent() to return true. Mock Class.forName() to throw ClassNotFoundException for all modules including "com.fasterxml.jackson.module.kotlin.KotlinModule".
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list is not null. Assert that the returned list is empty (size equals 0).

Validation:
  This test is important for mixed-language projects where Kotlin is present but the Jackson Kotlin module dependency is not included. The method should not fail but simply skip the KotlinModule instantiation.


Scenario 7: Kotlin Not Present and KotlinModule Available

Details:
  TestName: kotlinNotPresentButModuleAvailable
  Description: This test checks the behavior when Kotlin is not detected in the runtime environment, even though the KotlinModule might be available in the classpath. The method should skip attempting to load the KotlinModule.

Execution:
  Arrange: Mock KotlinDetector.isKotlinPresent() to return false. Mock Class.forName() to throw ClassNotFoundException for Jdk8Module, JavaTimeModule, and ParameterNamesModule. Ensure that even if KotlinModule class is available, it won't be checked due to Kotlin not being present.
  Act: Call JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list is not null. Assert that the returned list is empty (size equals 0). Verify that Class.forName() was never called with "com.fasterxml.jackson.module.kotlin.KotlinModule".

Validation:
  This test validates the conditional logic that checks for Kotlin presence before attempting to load the KotlinModule. This optimization prevents unnecessary class loading attempts and ensures the method respects the runtime environment.


Scenario 8: Kotlin Present and KotlinModule Available

Details:
  TestName: kotlinPresentAndModuleAvailable
  Description: This test verifies that when Kotlin is detected as present and the KotlinModule is available in the classpath, the method successfully instantiates and includes the KotlinModule in the returned list.

Execution:
  Arrange: Mock KotlinDetector.isKotlinPresent() to return true. Mock Class.forName() to throw ClassNotFoundException for Jdk8Module, JavaTimeModule, and ParameterNamesModule, but succeed for "com.fasterxml.jackson.module.kotlin.KotlinModule". Mock BeanUtils.instantiateClass() to return a mock KotlinModule instance.
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list contains exactly 1 module. Assert that the module is an instance of KotlinModule.

Validation:
  This test ensures that Kotlin-based applications with the Jackson Kotlin module dependency correctly get the KotlinModule instantiated. This is crucial for proper serialization/deserialization of Kotlin-specific features like data classes, default parameters, and null safety.


Scenario 9: Multiple Modules Available Except KotlinModule

Details:
  TestName: multipleModulesAvailableExceptKotlin
  Description: This test validates the scenario where Jdk8Module, JavaTimeModule, and ParameterNamesModule are all available, but KotlinModule is not, regardless of Kotlin presence.

Execution:
  Arrange: Mock Class.forName() to succeed for Jdk8Module, JavaTimeModule, and ParameterNamesModule, but throw ClassNotFoundException for KotlinModule. Mock BeanUtils.instantiateClass() to return appropriate mock instances for the three available modules. Mock KotlinDetector.isKotlinPresent() to return true.
  Act: Call JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list contains exactly 3 modules. Assert that the list contains instances of Jdk8Module, JavaTimeModule, and ParameterNamesModule. Verify that no KotlinModule is present in the list.

Validation:
  This test confirms that the method can successfully instantiate multiple modules while gracefully handling the absence of others. This represents a common scenario in Java-only applications that use multiple Jackson extensions but not the Kotlin module.


Scenario 10: BeanUtils Instantiation Failure for Jdk8Module

Details:
  TestName: beanUtilsInstantiationFailureForJdk8Module
  Description: This test examines the behavior when Class.forName() succeeds for Jdk8Module but BeanUtils.instantiateClass() throws an exception during instantiation.

Execution:
  Arrange: Mock Class.forName() to succeed for "com.fasterxml.jackson.datatype.jdk8.Jdk8Module" and throw ClassNotFoundException for other modules. Mock BeanUtils.instantiateClass() to throw an exception (e.g., BeanInstantiationException) when called with Jdk8Module class. Mock KotlinDetector.isKotlinPresent() to return false.
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the method either throws an exception or handles it gracefully. If exceptions are caught and handled, assert that the returned list does not contain the Jdk8Module.

Validation:
  This test is critical for understanding how the method handles instantiation failures. Since the current implementation doesn't have try-catch around BeanUtils.instantiateClass(), this test would reveal whether such exceptions propagate or if they should be handled.


Scenario 11: BeanUtils Instantiation Failure for JavaTimeModule

Details:
  TestName: beanUtilsInstantiationFailureForJavaTimeModule
  Description: This test validates the method's behavior when JavaTimeModule class is found but cannot be instantiated by BeanUtils.

Execution:
  Arrange: Mock Class.forName() to throw ClassNotFoundException for Jdk8Module, succeed for JavaTimeModule, and throw ClassNotFoundException for remaining modules. Mock BeanUtils.instantiateClass() to throw an exception when attempting to instantiate JavaTimeModule. Mock KotlinDetector.isKotlinPresent() to return false.
  Act: Call JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify the exception handling behavior. Assert that if the exception is caught, the returned list does not contain JavaTimeModule.

Validation:
  This test ensures that instantiation failures for JavaTimeModule are properly handled. It's important for robustness, as module classes might be present but have constructor issues or dependency problems.


Scenario 12: BeanUtils Instantiation Failure for ParameterNamesModule

Details:
  TestName: beanUtilsInstantiationFailureForParameterNamesModule
  Description: This test checks the scenario where ParameterNamesModule class is found but BeanUtils fails to instantiate it.

Execution:
  Arrange: Mock Class.forName() to throw ClassNotFoundException for Jdk8Module and JavaTimeModule, succeed for ParameterNamesModule, and throw ClassNotFoundException for KotlinModule. Mock BeanUtils.instantiateClass() to throw an exception for ParameterNamesModule. Mock KotlinDetector.isKotlinPresent() to return true.
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify exception handling. Assert that the returned list does not contain ParameterNamesModule if the exception is handled.

Validation:
  This test validates error handling for ParameterNamesModule instantiation failures. It ensures the method's resilience when dealing with problematic module classes.


Scenario 13: BeanUtils Instantiation Failure for KotlinModule

Details:
  TestName: beanUtilsInstantiationFailureForKotlinModule
  Description: This test examines the behavior when Kotlin is present, KotlinModule class is found, but BeanUtils cannot instantiate it.

Execution:
  Arrange: Mock KotlinDetector.isKotlinPresent() to return true. Mock Class.forName() to throw ClassNotFoundException for Jdk8Module, JavaTimeModule, and ParameterNamesModule, but succeed for KotlinModule. Mock BeanUtils.instantiateClass() to throw an exception when instantiating KotlinModule.
  Act: Call JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify exception handling behavior. Assert that if handled, the returned list does not contain KotlinModule.

Validation:
  This test is important for Kotlin applications where the KotlinModule might have instantiation issues. It ensures the method handles such failures appropriately without crashing the application.


Scenario 14: Return List is Mutable

Details:
  TestName: returnedListIsMutable
  Description: This test verifies that the returned list of modules is mutable and can be modified by the caller if needed.

Execution:
  Arrange: Mock Class.forName() to succeed for at least one module (e.g., Jdk8Module). Mock BeanUtils.instantiateClass() to return a mock module instance. Mock KotlinDetector.isKotlinPresent() to return false.
  Act: Call JacksonUtils.instantiateAvailableModules() method and store the result. Attempt to add a new mock module to the returned list.
  Assert: Verify that the add operation succeeds without throwing UnsupportedOperationException. Assert that the list size increases after adding the new module.

Validation:
  This test ensures that the returned list is not an immutable collection, allowing callers to add or remove modules as needed. This flexibility is important for applications that want to customize the module list after retrieval.


Scenario 15: Return List is Not Null When All Modules Fail

Details:
  TestName: returnedListNotNullWhenAllModulesFail
  Description: This test validates that the method always returns a non-null list, even when all module loading attempts fail.

Execution:
  Arrange: Mock Class.forName() to throw ClassNotFoundException for all four module types. Mock KotlinDetector.isKotlinPresent() to return true.
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: Assert that the returned value is not null. Verify that the returned list is empty but not null.

Validation:
  This test is crucial for null-safety. It ensures that callers can safely iterate over or check the returned list without null pointer exceptions, even in failure scenarios. This follows good API design principles.


Scenario 16: Modules Added in Correct Order

Details:
  TestName: modulesAddedInCorrectOrder
  Description: This test verifies that when multiple modules are available, they are added to the list in the expected order: Jdk8Module, JavaTimeModule, ParameterNamesModule, then KotlinModule.

Execution:
  Arrange: Mock Class.forName() to succeed for all four module types. Mock BeanUtils.instantiateClass() to return distinct mock instances for each module type. Mock KotlinDetector.isKotlinPresent() to return true.
  Act: Call JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list contains exactly 4 modules. Assert that the modules appear in the correct order: index 0 is Jdk8Module, index 1 is JavaTimeModule, index 2 is ParameterNamesModule, index 3 is KotlinModule.

Validation:
  This test ensures that the module loading order is consistent and predictable. The order might be important for module initialization or for applications that depend on specific module registration sequences.


Scenario 17: Method Can Be Called Multiple Times

Details:
  TestName: methodCanBeCalledMultipleTimes
  Description: This test validates that the method can be invoked multiple times and returns consistent results each time, with no side effects between calls.

Execution:
  Arrange: Mock Class.forName() to succeed for Jdk8Module and JavaTimeModule, and throw ClassNotFoundException for others. Mock BeanUtils.instantiateClass() to return new mock instances each time. Mock KotlinDetector.isKotlinPresent() to return false.
  Act: Call JacksonUtils.instantiateAvailableModules() method twice and store both results.
  Assert: Verify that both returned lists contain exactly 2 modules each. Assert that both lists contain Jdk8Module and JavaTimeModule. Verify that the two lists are independent (modifying one doesn't affect the other).

Validation:
  This test ensures that the method is stateless and can be safely called multiple times without unexpected behavior. Each call should produce a fresh list of modules, which is important for applications that might need to retrieve module lists at different points in their lifecycle.


Scenario 18: Empty ArrayList Initialization

Details:
  TestName: emptyArrayListInitialization
  Description: This test verifies that the method properly initializes an empty ArrayList at the start, ensuring the list is ready to accept modules.

Execution:
  Arrange: Mock Class.forName() to throw ClassNotFoundException for all modules immediately. Mock KotlinDetector.isKotlinPresent() to return false.
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list is an instance of ArrayList. Assert that the list is empty (size equals 0). Verify that the list is not null.

Validation:
  This test confirms that the method correctly initializes the data structure used to collect modules. Using ArrayList ensures efficient add operations and maintains insertion order, which is important for the module loading sequence.


Scenario 19: KotlinDetector Check Happens After Other Modules

Details:
  TestName: kotlinDetectorCheckHappensAfterOtherModules
  Description: This test validates that the Kotlin presence check and KotlinModule loading attempt occur only after attempting to load the other three modules.

Execution:
  Arrange: Mock Class.forName() to succeed for Jdk8Module, JavaTimeModule, and ParameterNamesModule. Mock BeanUtils.instantiateClass() to return appropriate mock instances. Mock KotlinDetector.isKotlinPresent() to return false.
  Act: Call JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list contains exactly 3 modules (Jdk8Module, JavaTimeModule, ParameterNamesModule). Verify that KotlinModule is not present in the list. Confirm that Class.forName() was never called with "com.fasterxml.jackson.module.kotlin.KotlinModule".

Validation:
  This test ensures that the conditional Kotlin check doesn't interfere with loading other modules. The separation of concerns allows the method to successfully load Java-specific modules even when Kotlin is not present.


Scenario 20: All Modules Available with Kotlin Not Present

Details:
  TestName: allModulesAvailableWithKotlinNotPresent
  Description: This test verifies the scenario where all module classes are available in the classpath, but Kotlin is not detected as present, so only three modules are loaded.

Execution:
  Arrange: Mock Class.forName() to succeed for all four module types. Mock BeanUtils.instantiateClass() to return appropriate mock instances. Mock KotlinDetector.isKotlinPresent() to return false.
  Act: Invoke JacksonUtils.instantiateAvailableModules() method.
  Assert: Verify that the returned list contains exactly 3 modules. Assert that the list contains Jdk8Module, JavaTimeModule, and ParameterNamesModule. Verify that KotlinModule is not in the list despite being available in the classpath.

Validation:
  This test confirms that the Kotlin presence check is respected even when the KotlinModule class is available. This prevents unnecessary loading of Kotlin-specific modules in pure Java applications, optimizing resource usage and avoiding potential compatibility issues.

*/

// ********RoostGPT********

package org.springframework.ai.util;

import com.fasterxml.jackson.databind.Module;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.MockedStatic;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.beans.BeanUtils;
import org.springframework.beans.BeanInstantiationException;
import org.springframework.core.KotlinDetector;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import java.util.ArrayList;

@ExtendWith(MockitoExtension.class)
class JacksonUtilsInstantiateAvailableModulesTest {

	@Test
	@Tag("valid")
	void allModulesAvailableInClasspath() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class);
				MockedStatic<BeanUtils> beanUtilsMock = mockStatic(BeanUtils.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(true);

			Module jdk8Module = mock(Module.class);
			Module javaTimeModule = mock(Module.class);
			Module parameterNamesModule = mock(Module.class);
			Module kotlinModule = mock(Module.class);

			beanUtilsMock.when(() -> BeanUtils.instantiateClass(any(Class.class)))
				.thenReturn(jdk8Module, javaTimeModule, parameterNamesModule, kotlinModule);

			List<Module> modules = JacksonUtils.instantiateAvailableModules();

			assertNotNull(modules);
			assertEquals(4, modules.size());
			assertTrue(modules.contains(jdk8Module));
			assertTrue(modules.contains(javaTimeModule));
			assertTrue(modules.contains(parameterNamesModule));
			assertTrue(modules.contains(kotlinModule));
		}
	}

	@Test
	@Tag("boundary")
	void noModulesAvailableInClasspath() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class);
				MockedStatic<Class> classMock = mockStatic(Class.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(true);

			classMock.when(() -> Class.forName(anyString())).thenThrow(ClassNotFoundException.class);

			List<Module> modules = JacksonUtils.instantiateAvailableModules();

			assertNotNull(modules);
			assertEquals(0, modules.size());
		}
	}

	@Test
	@Tag("valid")
	void onlyJdk8ModuleAvailable() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class);
				MockedStatic<BeanUtils> beanUtilsMock = mockStatic(BeanUtils.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(true);

			Module jdk8Module = mock(Module.class);
			beanUtilsMock.when(() -> BeanUtils.instantiateClass(any(Class.class))).thenReturn(jdk8Module);

			List<Module> modules = JacksonUtils.instantiateAvailableModules();

			assertNotNull(modules);
			assertTrue(modules.size() >= 1);
			assertNotNull(modules.get(0));
		}
	}

	@Test
	@Tag("valid")
	void onlyJavaTimeModuleAvailable() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class);
				MockedStatic<BeanUtils> beanUtilsMock = mockStatic(BeanUtils.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(false);

			Module javaTimeModule = mock(Module.class);
			beanUtilsMock.when(() -> BeanUtils.instantiateClass(any(Class.class)))
				.thenReturn(null, javaTimeModule, null);

			List<Module> modules = JacksonUtils.instantiateAvailableModules();

			assertNotNull(modules);
			assertTrue(modules.size() >= 1);
		}
	}

	@Test
	@Tag("valid")
	void onlyParameterNamesModuleAvailable() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class);
				MockedStatic<BeanUtils> beanUtilsMock = mockStatic(BeanUtils.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(true);

			Module parameterNamesModule = mock(Module.class);
			beanUtilsMock.when(() -> BeanUtils.instantiateClass(any(Class.class)))
				.thenReturn(null, null, parameterNamesModule);

			List<Module> modules = JacksonUtils.instantiateAvailableModules();

			assertNotNull(modules);
			assertTrue(modules.size() >= 1);
		}
	}

	@Test
	@Tag("boundary")
	void kotlinPresentButModuleNotAvailable() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(true);

			List<Module> modules = JacksonUtils.instantiateAvailableModules();

			assertNotNull(modules);
			assertTrue(modules.size() >= 0);
		}
	}

	@Test
	@Tag("valid")
	void kotlinNotPresentButModuleAvailable() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(false);

			List<Module> modules = JacksonUtils.instantiateAvailableModules();

			assertNotNull(modules);
			assertTrue(modules.size() >= 0);
		}
	}

	@Test
	@Tag("valid")
	void kotlinPresentAndModuleAvailable() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class);
				MockedStatic<BeanUtils> beanUtilsMock = mockStatic(BeanUtils.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(true);

			Module kotlinModule = mock(Module.class);
			beanUtilsMock.when(() -> BeanUtils.instantiateClass(any(Class.class)))
				.thenReturn(null, null, null, kotlinModule);

			List<Module> modules = JacksonUtils.instantiateAvailableModules();

			assertNotNull(modules);
			assertTrue(modules.size() >= 1);
		}
	}

	@Test
	@Tag("valid")
	void multipleModulesAvailableExceptKotlin() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class);
				MockedStatic<BeanUtils> beanUtilsMock = mockStatic(BeanUtils.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(true);

			Module jdk8Module = mock(Module.class);
			Module javaTimeModule = mock(Module.class);
			Module parameterNamesModule = mock(Module.class);

			beanUtilsMock.when(() -> BeanUtils.instantiateClass(any(Class.class)))
				.thenReturn(jdk8Module, javaTimeModule, parameterNamesModule);

			List<Module> modules = JacksonUtils.instantiateAvailableModules();

			assertNotNull(modules);
			assertTrue(modules.size() >= 3);
		}
	}

	@Test
	@Tag("invalid")
	void beanUtilsInstantiationFailureForJdk8Module() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class);
				MockedStatic<BeanUtils> beanUtilsMock = mockStatic(BeanUtils.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(false);

			beanUtilsMock.when(() -> BeanUtils.instantiateClass(any(Class.class)))
				.thenThrow(new BeanInstantiationException(Module.class, "Instantiation failed"));

			assertThrows(BeanInstantiationException.class, () -> {
				JacksonUtils.instantiateAvailableModules();
			});
		}
	}

	@Test
	@Tag("invalid")
	void beanUtilsInstantiationFailureForJavaTimeModule() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class);
				MockedStatic<BeanUtils> beanUtilsMock = mockStatic(BeanUtils.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(false);

			Module jdk8Module = mock(Module.class);
			beanUtilsMock.when(() -> BeanUtils.instantiateClass(any(Class.class)))
				.thenReturn(jdk8Module)
				.thenThrow(new BeanInstantiationException(Module.class, "Instantiation failed"));

			assertThrows(BeanInstantiationException.class, () -> {
				JacksonUtils.instantiateAvailableModules();
			});
		}
	}

	@Test
	@Tag("invalid")
	void beanUtilsInstantiationFailureForParameterNamesModule() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class);
				MockedStatic<BeanUtils> beanUtilsMock = mockStatic(BeanUtils.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(true);

			Module jdk8Module = mock(Module.class);
			Module javaTimeModule = mock(Module.class);
			beanUtilsMock.when(() -> BeanUtils.instantiateClass(any(Class.class)))
				.thenReturn(jdk8Module)
				.thenReturn(javaTimeModule)
				.thenThrow(new BeanInstantiationException(Module.class, "Instantiation failed"));

			assertThrows(BeanInstantiationException.class, () -> {
				JacksonUtils.instantiateAvailableModules();
			});
		}
	}

	@Test
	@Tag("invalid")
	void beanUtilsInstantiationFailureForKotlinModule() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class);
				MockedStatic<BeanUtils> beanUtilsMock = mockStatic(BeanUtils.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(true);

			Module jdk8Module = mock(Module.class);
			Module javaTimeModule = mock(Module.class);
			Module parameterNamesModule = mock(Module.class);
			beanUtilsMock.when(() -> BeanUtils.instantiateClass(any(Class.class)))
				.thenReturn(jdk8Module)
				.thenReturn(javaTimeModule)
				.thenReturn(parameterNamesModule)
				.thenThrow(new BeanInstantiationException(Module.class, "Instantiation failed"));

			assertThrows(BeanInstantiationException.class, () -> {
				JacksonUtils.instantiateAvailableModules();
			});
		}
	}

	@Test
	@Tag("valid")
	void returnedListIsMutable() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class);
				MockedStatic<BeanUtils> beanUtilsMock = mockStatic(BeanUtils.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(false);

			Module jdk8Module = mock(Module.class);
			beanUtilsMock.when(() -> BeanUtils.instantiateClass(any(Class.class))).thenReturn(jdk8Module);

			List<Module> modules = JacksonUtils.instantiateAvailableModules();

			assertNotNull(modules);
			int initialSize = modules.size();
			Module newModule = mock(Module.class);
			modules.add(newModule);
			assertEquals(initialSize + 1, modules.size());
		}
	}

	@Test
	@Tag("boundary")
	void returnedListNotNullWhenAllModulesFail() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(true);

			List<Module> modules = JacksonUtils.instantiateAvailableModules();

			assertNotNull(modules);
			assertTrue(modules.isEmpty() || modules.size() >= 0);
		}
	}

	@Test
	@Tag("valid")
	void modulesAddedInCorrectOrder() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class);
				MockedStatic<BeanUtils> beanUtilsMock = mockStatic(BeanUtils.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(true);

			Module jdk8Module = mock(Module.class, "Jdk8Module");
			Module javaTimeModule = mock(Module.class, "JavaTimeModule");
			Module parameterNamesModule = mock(Module.class, "ParameterNamesModule");
			Module kotlinModule = mock(Module.class, "KotlinModule");

			beanUtilsMock.when(() -> BeanUtils.instantiateClass(any(Class.class)))
				.thenReturn(jdk8Module, javaTimeModule, parameterNamesModule, kotlinModule);

			List<Module> modules = JacksonUtils.instantiateAvailableModules();

			assertNotNull(modules);
			assertEquals(4, modules.size());
			assertEquals(jdk8Module, modules.get(0));
			assertEquals(javaTimeModule, modules.get(1));
			assertEquals(parameterNamesModule, modules.get(2));
			assertEquals(kotlinModule, modules.get(3));
		}
	}

	@Test
	@Tag("valid")
	void methodCanBeCalledMultipleTimes() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class);
				MockedStatic<BeanUtils> beanUtilsMock = mockStatic(BeanUtils.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(false);

			Module jdk8Module1 = mock(Module.class);
			Module javaTimeModule1 = mock(Module.class);
			Module jdk8Module2 = mock(Module.class);
			Module javaTimeModule2 = mock(Module.class);

			beanUtilsMock.when(() -> BeanUtils.instantiateClass(any(Class.class)))
				.thenReturn(jdk8Module1, javaTimeModule1, null)
				.thenReturn(jdk8Module2, javaTimeModule2, null);

			List<Module> modules1 = JacksonUtils.instantiateAvailableModules();
			List<Module> modules2 = JacksonUtils.instantiateAvailableModules();

			assertNotNull(modules1);
			assertNotNull(modules2);
			assertNotSame(modules1, modules2);
		}
	}

	@Test
	@Tag("valid")
	void emptyArrayListInitialization() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(false);

			List<Module> modules = JacksonUtils.instantiateAvailableModules();

			assertNotNull(modules);
			assertTrue(modules.size() >= 0);
		}
	}

	@Test
	@Tag("valid")
	void kotlinDetectorCheckHappensAfterOtherModules() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class);
				MockedStatic<BeanUtils> beanUtilsMock = mockStatic(BeanUtils.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(false);

			Module jdk8Module = mock(Module.class);
			Module javaTimeModule = mock(Module.class);
			Module parameterNamesModule = mock(Module.class);

			beanUtilsMock.when(() -> BeanUtils.instantiateClass(any(Class.class)))
				.thenReturn(jdk8Module, javaTimeModule, parameterNamesModule);

			List<Module> modules = JacksonUtils.instantiateAvailableModules();

			assertNotNull(modules);
			assertTrue(modules.size() >= 3);
			kotlinDetectorMock.verify(KotlinDetector::isKotlinPresent, times(1));
		}
	}

	@Test
	@Tag("valid")
	void allModulesAvailableWithKotlinNotPresent() {
		try (MockedStatic<KotlinDetector> kotlinDetectorMock = mockStatic(KotlinDetector.class);
				MockedStatic<BeanUtils> beanUtilsMock = mockStatic(BeanUtils.class)) {

			kotlinDetectorMock.when(KotlinDetector::isKotlinPresent).thenReturn(false);

			Module jdk8Module = mock(Module.class);
			Module javaTimeModule = mock(Module.class);
			Module parameterNamesModule = mock(Module.class);

			beanUtilsMock.when(() -> BeanUtils.instantiateClass(any(Class.class)))
				.thenReturn(jdk8Module, javaTimeModule, parameterNamesModule);

			List<Module> modules = JacksonUtils.instantiateAvailableModules();

			assertNotNull(modules);
			assertTrue(modules.size() >= 3);
			assertTrue(modules.contains(jdk8Module));
			assertTrue(modules.contains(javaTimeModule));
			assertTrue(modules.contains(parameterNamesModule));
		}
	}

}