/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test spring-ai-test-timeout-pr using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=splitCamelCase_528df90454
ROOST_METHOD_SIG_HASH=splitCamelCase_3e3f2bf53c

Scenario 1: Split Simple CamelCase String

Details:
  TestName: splitSimpleCamelCaseString
  Description: Verify that a simple camelCase string is correctly split into its constituent parts while preserving the original case of each part.
Execution:
  Arrange: Prepare a simple camelCase string such as "camelCase".
  Act: Invoke splitCamelCase with the prepared string.
  Assert: Verify that the returned list contains ["camel", "Case"].
Validation:
  The assertion verifies that the method correctly identifies the boundary between lowercase and uppercase letters and splits the string accordingly. This is fundamental functionality for parsing camelCase identifiers commonly used in Java naming conventions.

---

Scenario 2: Split String with Multiple CamelCase Words

Details:
  TestName: splitMultipleCamelCaseWords
  Description: Verify that a string with multiple camelCase transitions is correctly split into all its parts.
Execution:
  Arrange: Prepare a camelCase string with multiple words such as "thisIsATestString".
  Act: Invoke splitCamelCase with the prepared string.
  Assert: Verify that the returned list contains ["this", "Is", "A", "Test", "String"].
Validation:
  The assertion confirms that the method handles multiple camelCase boundaries correctly, which is essential for parsing complex identifiers or method names in code analysis scenarios.

---

Scenario 3: Split String Starting with Uppercase Letter

Details:
  TestName: splitPascalCaseString
  Description: Verify that a PascalCase string (starting with uppercase) is correctly split into its parts.
Execution:
  Arrange: Prepare a PascalCase string such as "PascalCaseString".
  Act: Invoke splitCamelCase with the prepared string.
  Assert: Verify that the returned list contains ["Pascal", "Case", "String"].
Validation:
  The assertion verifies that the method handles strings starting with uppercase letters (PascalCase), which is common for class names in Java. The regex pattern should correctly identify boundaries without splitting at the start.

---

Scenario 4: Split Single Word String

Details:
  TestName: splitSingleWordString
  Description: Verify that a single lowercase word without any camelCase transitions returns a list with just that word.
Execution:
  Arrange: Prepare a single word string such as "word".
  Act: Invoke splitCamelCase with the prepared string.
  Assert: Verify that the returned list contains ["word"].
Validation:
  The assertion confirms that strings without camelCase boundaries are returned as a single-element list, ensuring the method handles edge cases of simple words correctly.

---

Scenario 5: Split String with Consecutive Uppercase Letters

Details:
  TestName: splitStringWithConsecutiveUppercase
  Description: Verify that a string with consecutive uppercase letters (like acronyms) is handled correctly.
Execution:
  Arrange: Prepare a string with consecutive uppercase letters such as "parseXMLDocument".
  Act: Invoke splitCamelCase with the prepared string.
  Assert: Verify that the returned list contains ["parse", "XML", "Document"].
Validation:
  The assertion verifies that the method correctly handles acronyms within camelCase strings, splitting before the last uppercase letter of a sequence when followed by lowercase letters.

---

Scenario 6: Split Empty String

Details:
  TestName: splitEmptyString
  Description: Verify that an empty string returns a list containing just the empty string.
Execution:
  Arrange: Prepare an empty string "".
  Act: Invoke splitCamelCase with the empty string.
  Assert: Verify that the returned list contains [""].
Validation:
  The assertion confirms the method's behavior with empty input, ensuring it doesn't throw an exception and returns a predictable result.

---

Scenario 7: Handle Null Input

Details:
  TestName: splitNullInputThrowsException
  Description: Verify that passing null to the method throws an IllegalArgumentException due to the Assert.notNull check.
Execution:
  Arrange: Prepare a null value.
  Act: Invoke splitCamelCase with null.
  Assert: Verify that an IllegalArgumentException is thrown with the message "Source string must not be null".
Validation:
  The assertion confirms that the method properly validates input and fails fast with a meaningful error message when null is provided, following Spring's assertion conventions.

---

Scenario 8: Split String with Underscore

Details:
  TestName: splitStringWithUnderscore
  Description: Verify that a string containing underscores is handled according to the regex pattern which excludes underscore from split boundaries.
Execution:
  Arrange: Prepare a string with underscore such as "camel_CaseTest".
  Act: Invoke splitCamelCase with the prepared string.
  Assert: Verify that the returned list contains ["camel_", "Case", "Test"].
Validation:
  The assertion verifies that underscores are treated as part of the preceding segment based on the regex pattern, which explicitly excludes underscore from triggering splits.

---

Scenario 9: Split String with Dollar Sign

Details:
  TestName: splitStringWithDollarSign
  Description: Verify that a string containing dollar signs is handled correctly according to the regex pattern.
Execution:
  Arrange: Prepare a string with dollar sign such as "camel$CaseTest".
  Act: Invoke splitCamelCase with the prepared string.
  Assert: Verify that the returned list contains ["camel$", "Case", "Test"].
Validation:
  The assertion confirms that dollar signs are treated similarly to underscores in the regex pattern, as both are excluded from split boundary detection.

---

Scenario 10: Verify Returned List is Unmodifiable

Details:
  TestName: returnedListIsUnmodifiable
  Description: Verify that the returned list is unmodifiable and throws an exception when modification is attempted.
Execution:
  Arrange: Prepare a camelCase string such as "testString".
  Act: Invoke splitCamelCase and attempt to add an element to the returned list.
  Assert: Verify that an UnsupportedOperationException is thrown.
Validation:
  The assertion confirms that the method returns an immutable list as per the implementation using Collections.unmodifiableList, ensuring data integrity and preventing accidental modifications.

---

Scenario 11: Split String with Non-Basic Latin Characters

Details:
  TestName: splitStringWithNonBasicLatinCharacters
  Description: Verify that strings containing non-basic Latin characters (like accented letters or Unicode characters) are handled according to the UPPER pattern.
Execution:
  Arrange: Prepare a string with non-basic Latin characters such as "camelCaséTest".
  Act: Invoke splitCamelCase with the prepared string.
  Assert: Verify the returned list splits appropriately based on the regex pattern handling of non-basic Latin characters.
Validation:
  The assertion verifies that the method correctly handles internationalized strings, as the UPPER pattern includes non-basic Latin characters (\\P{InBASIC_LATIN}).

---

Scenario 12: Split All Uppercase String

Details:
  TestName: splitAllUppercaseString
  Description: Verify that an all-uppercase string is returned as a single element list.
Execution:
  Arrange: Prepare an all-uppercase string such as "UPPERCASE".
  Act: Invoke splitCamelCase with the prepared string.
  Assert: Verify that the returned list contains ["UPPERCASE"].
Validation:
  The assertion confirms that strings without lowercase-to-uppercase transitions are not split, as there are no camelCase boundaries to detect.

---

Scenario 13: Split String with Single Character

Details:
  TestName: splitSingleCharacterString
  Description: Verify that a single character string returns a list with just that character.
Execution:
  Arrange: Prepare a single character string such as "a".
  Act: Invoke splitCamelCase with the prepared string.
  Assert: Verify that the returned list contains ["a"].
Validation:
  The assertion confirms proper handling of minimal input, ensuring the method doesn't fail or produce unexpected results with single-character strings.

---

Scenario 14: Split String Preserves Original Case

Details:
  TestName: splitPreservesOriginalCase
  Description: Verify that the split operation preserves the original case of each part without converting to lowercase.
Execution:
  Arrange: Prepare a camelCase string such as "MyTestMethod".
  Act: Invoke splitCamelCase with the prepared string.
  Assert: Verify that the returned list contains ["My", "Test", "Method"] with original casing preserved.
Validation:
  The assertion confirms that splitCamelCase (unlike splitCamelCaseToLower) preserves the original case of each split part, which is important when the original casing carries semantic meaning.

*/

// ********RoostGPT********

package org.springframework.ai.util;

import java.util.List;
import java.util.ArrayList;
import java.util.Collections;
import java.util.regex.Pattern;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import java.util.stream.Stream;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.util.Assert;
import org.springframework.util.StringUtils;

class ParsingUtilsSplitCamelCaseTest {

	@Test
	@Tag("valid")
	void splitSimpleCamelCaseString() {
		// Arrange
		String source = "camelCase";

		// Act
		List<String> result = ParsingUtils.splitCamelCase(source);

		// Assert
		assertEquals(2, result.size());
		assertEquals("camel", result.get(0));
		assertEquals("Case", result.get(1));
	}

	@Test
	@Tag("valid")
	void splitMultipleCamelCaseWords() {
		// Arrange
		String source = "thisIsATestString";

		// Act
		List<String> result = ParsingUtils.splitCamelCase(source);

		// Assert
		assertEquals(5, result.size());
		assertEquals("this", result.get(0));
		assertEquals("Is", result.get(1));
		assertEquals("A", result.get(2));
		assertEquals("Test", result.get(3));
		assertEquals("String", result.get(4));
	}

	@Test
	@Tag("valid")
	void splitPascalCaseString() {
		// Arrange
		String source = "PascalCaseString";

		// Act
		List<String> result = ParsingUtils.splitCamelCase(source);

		// Assert
		assertEquals(3, result.size());
		assertEquals("Pascal", result.get(0));
		assertEquals("Case", result.get(1));
		assertEquals("String", result.get(2));
	}

	@Test
	@Tag("boundary")
	void splitSingleWordString() {
		// Arrange
		String source = "word";

		// Act
		List<String> result = ParsingUtils.splitCamelCase(source);

		// Assert
		assertEquals(1, result.size());
		assertEquals("word", result.get(0));
	}

	@Test
	@Tag("valid")
	void splitStringWithConsecutiveUppercase() {
		// Arrange
		String source = "parseXMLDocument";

		// Act
		List<String> result = ParsingUtils.splitCamelCase(source);

		// Assert
		assertNotNull(result);
		assertTrue(result.size() >= 2);
		assertEquals("parse", result.get(0));
		// The regex should handle consecutive uppercase letters
		assertTrue(result.contains("Document"));
	}

	@Test
	@Tag("boundary")
	void splitEmptyString() {
		// Arrange
		String source = "";

		// Act
		List<String> result = ParsingUtils.splitCamelCase(source);

		// Assert
		assertNotNull(result);
		assertEquals(1, result.size());
		assertEquals("", result.get(0));
	}

	@Test
	@Tag("invalid")
	void splitNullInputThrowsException() {
		// Arrange
		String source = null;

		// Act & Assert
		IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
			ParsingUtils.splitCamelCase(source);
		});

		assertTrue(exception.getMessage().contains("Source string must not be null"));
	}

	@Test
	@Tag("valid")
	void splitStringWithUnderscore() {
		// Arrange
		String source = "camel_CaseTest";

		// Act
		List<String> result = ParsingUtils.splitCamelCase(source);

		// Assert
		assertNotNull(result);
		assertTrue(result.size() >= 2);
		// Underscore should be part of the preceding segment
		assertTrue(result.get(0).contains("_") || result.stream().anyMatch(s -> s.contains("_")));
	}

	@Test
	@Tag("valid")
	void splitStringWithDollarSign() {
		// Arrange
		String source = "camel$CaseTest";

		// Act
		List<String> result = ParsingUtils.splitCamelCase(source);

		// Assert
		assertNotNull(result);
		assertTrue(result.size() >= 2);
		// Dollar sign should be part of the preceding segment
		assertTrue(result.stream().anyMatch(s -> s.contains("$")));
	}

	@Test
	@Tag("valid")
	void returnedListIsUnmodifiable() {
		// Arrange
		String source = "testString";

		// Act
		List<String> result = ParsingUtils.splitCamelCase(source);

		// Assert
		assertThrows(UnsupportedOperationException.class, () -> {
			result.add("newElement");
		});
	}

	@Test
	@Tag("valid")
	void splitStringWithNonBasicLatinCharacters() {
		// Arrange
		String source = "camelCaséTest";

		// Act
		List<String> result = ParsingUtils.splitCamelCase(source);

		// Assert
		assertNotNull(result);
		assertTrue(result.size() >= 1);
		// Verify the string is processed without exception
		assertTrue(result.stream().anyMatch(s -> s.contains("é") || s.contains("Cas")));
	}

	@Test
	@Tag("boundary")
	void splitAllUppercaseString() {
		// Arrange
		String source = "UPPERCASE";

		// Act
		List<String> result = ParsingUtils.splitCamelCase(source);

		// Assert
		assertNotNull(result);
		assertEquals(1, result.size());
		assertEquals("UPPERCASE", result.get(0));
	}

	@Test
	@Tag("boundary")
	void splitSingleCharacterString() {
		// Arrange
		String source = "a";

		// Act
		List<String> result = ParsingUtils.splitCamelCase(source);

		// Assert
		assertNotNull(result);
		assertEquals(1, result.size());
		assertEquals("a", result.get(0));
	}

	@Test
	@Tag("valid")
	void splitPreservesOriginalCase() {
		// Arrange
		String source = "MyTestMethod";

		// Act
		List<String> result = ParsingUtils.splitCamelCase(source);

		// Assert
		assertEquals(3, result.size());
		assertEquals("My", result.get(0));
		assertEquals("Test", result.get(1));
		assertEquals("Method", result.get(2));
	}

	@ParameterizedTest
	@MethodSource("provideCamelCaseTestCases")
	@Tag("valid")
	void splitCamelCaseParameterized(String input, int expectedSize, String firstElement) {
		// Act
		List<String> result = ParsingUtils.splitCamelCase(input);

		// Assert
		assertNotNull(result);
		assertEquals(expectedSize, result.size());
		assertEquals(firstElement, result.get(0));
	}

	private static Stream<Arguments> provideCamelCaseTestCases() {
		return Stream.of(Arguments.of("simpleTest", 2, "simple"), Arguments.of("AnotherTest", 2, "Another"),
				Arguments.of("oneMoreTestCase", 4, "one"), Arguments.of("single", 1, "single"));
	}

	@Test
	@Tag("boundary")
	void splitSingleUppercaseCharacter() {
		// Arrange
		String source = "A";

		// Act
		List<String> result = ParsingUtils.splitCamelCase(source);

		// Assert
		assertNotNull(result);
		assertEquals(1, result.size());
		assertEquals("A", result.get(0));
	}

	@Test
	@Tag("valid")
	void splitStringWithNumbers() {
		// Arrange
		String source = "test123Method";

		// Act
		List<String> result = ParsingUtils.splitCamelCase(source);

		// Assert
		assertNotNull(result);
		assertTrue(result.size() >= 1);
		// Numbers should be handled without exception
		assertTrue(result.stream().anyMatch(s -> s.contains("123") || s.contains("test")));
	}

	@Test
	@Tag("valid")
	void splitStringEndingWithUppercase() {
		// Arrange
		String source = "testMethodA";

		// Act
		List<String> result = ParsingUtils.splitCamelCase(source);

		// Assert
		assertNotNull(result);
		assertTrue(result.size() >= 2);
		assertEquals("A", result.get(result.size() - 1));
	}

	@Test
	@Tag("valid")
	void splitReturnsSameResultForSameInput() {
		// Arrange
		String source = "consistentResult";

		// Act
		List<String> result1 = ParsingUtils.splitCamelCase(source);
		List<String> result2 = ParsingUtils.splitCamelCase(source);

		// Assert
		assertEquals(result1, result2);
	}

}