/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-8-java using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=splitCamelCaseToLower_4dee15ee62
ROOST_METHOD_SIG_HASH=splitCamelCaseToLower_36d5637cf8

Scenario 1: Split Simple CamelCase String to Lowercase

Details:
  TestName: splitSimpleCamelCaseStringToLowercase
  Description: Verify that a simple camelCase string is correctly split into separate lowercase words. This tests the basic functionality of the method with a standard camelCase input.
Execution:
  Arrange: Prepare a simple camelCase string such as "camelCase".
  Act: Invoke splitCamelCaseToLower with the prepared string.
  Assert: Verify that the returned list contains ["camel", "case"].
Validation:
  The assertion verifies that the method correctly identifies the uppercase letter as a split point and converts all parts to lowercase. This is fundamental functionality for parsing camelCase identifiers into readable words.

---

Scenario 2: Split Multiple Word CamelCase String

Details:
  TestName: splitMultipleWordCamelCaseString
  Description: Verify that a camelCase string with multiple words is correctly split into all individual lowercase components.
Execution:
  Arrange: Prepare a multi-word camelCase string such as "thisIsATestString".
  Act: Invoke splitCamelCaseToLower with the prepared string.
  Assert: Verify that the returned list contains ["this", "is", "a", "test", "string"].
Validation:
  The assertion confirms that the method handles multiple consecutive camelCase transitions correctly, splitting at each uppercase letter boundary and converting to lowercase.

---

Scenario 3: Handle Single Lowercase Word

Details:
  TestName: handleSingleLowercaseWord
  Description: Verify that a single lowercase word without any camelCase transitions is returned as a single-element list.
Execution:
  Arrange: Prepare a single lowercase word such as "word".
  Act: Invoke splitCamelCaseToLower with the prepared string.
  Assert: Verify that the returned list contains ["word"].
Validation:
  The assertion ensures that strings without camelCase patterns are handled gracefully, returning the original string in lowercase as a single element.

---

Scenario 4: Handle Single Uppercase Word

Details:
  TestName: handleSingleUppercaseWord
  Description: Verify that a single uppercase word is returned as a single-element list in lowercase.
Execution:
  Arrange: Prepare a single uppercase word such as "WORD".
  Act: Invoke splitCamelCaseToLower with the prepared string.
  Assert: Verify that the returned list contains ["word"].
Validation:
  The assertion confirms that all-uppercase strings are converted to lowercase without unnecessary splitting.

---

Scenario 5: Handle PascalCase String

Details:
  TestName: handlePascalCaseString
  Description: Verify that a PascalCase string (starting with uppercase) is correctly split into lowercase words.
Execution:
  Arrange: Prepare a PascalCase string such as "PascalCaseString".
  Act: Invoke splitCamelCaseToLower with the prepared string.
  Assert: Verify that the returned list contains ["pascal", "case", "string"].
Validation:
  The assertion verifies that the method handles PascalCase (upper camelCase) correctly, treating the initial uppercase letter as part of the first word.

---

Scenario 6: Handle Consecutive Uppercase Letters (Acronym)

Details:
  TestName: handleConsecutiveUppercaseLettersAcronym
  Description: Verify that consecutive uppercase letters (like acronyms) are handled correctly according to the camelCase splitting rules.
Execution:
  Arrange: Prepare a string with an acronym such as "parseXMLDocument".
  Act: Invoke splitCamelCaseToLower with the prepared string.
  Assert: Verify that the returned list correctly splits the acronym portion.
Validation:
  The assertion confirms proper handling of acronyms within camelCase strings, which is important for parsing technical identifiers.

---

Scenario 7: Handle Empty String

Details:
  TestName: handleEmptyString
  Description: Verify that an empty string is handled correctly and returns an appropriate result.
Execution:
  Arrange: Prepare an empty string "".
  Act: Invoke splitCamelCaseToLower with the empty string.
  Assert: Verify that the returned list contains a single empty string element [""].
Validation:
  The assertion ensures that empty strings don't cause errors and are processed consistently.

---

Scenario 8: Handle Null Input Throws Exception

Details:
  TestName: handleNullInputThrowsException
  Description: Verify that passing null as input throws an IllegalArgumentException as specified by the Assert.notNull check.
Execution:
  Arrange: Prepare a null value.
  Act: Invoke splitCamelCaseToLower with null.
  Assert: Verify that an IllegalArgumentException is thrown with the message "Source string must not be null".
Validation:
  The assertion confirms that the method properly validates input and fails fast with a meaningful error message when given null input.

---

Scenario 9: Handle String with Underscore

Details:
  TestName: handleStringWithUnderscore
  Description: Verify that strings containing underscores are handled according to the regex pattern which treats underscore as a special character.
Execution:
  Arrange: Prepare a string with underscore such as "camel_Case".
  Act: Invoke splitCamelCaseToLower with the prepared string.
  Assert: Verify the returned list based on the regex behavior with underscores.
Validation:
  The assertion confirms that underscores in the input are handled according to the defined pattern, which excludes underscore from triggering splits.

---

Scenario 10: Handle String with Dollar Sign

Details:
  TestName: handleStringWithDollarSign
  Description: Verify that strings containing dollar signs are handled according to the regex pattern which treats dollar sign as a special character.
Execution:
  Arrange: Prepare a string with dollar sign such as "camel$Case".
  Act: Invoke splitCamelCaseToLower with the prepared string.
  Assert: Verify the returned list based on the regex behavior with dollar signs.
Validation:
  The assertion confirms that dollar signs in the input are handled according to the defined pattern.

---

Scenario 11: Verify Returned List Is Unmodifiable

Details:
  TestName: verifyReturnedListIsUnmodifiable
  Description: Verify that the returned list is unmodifiable and throws an exception when modification is attempted.
Execution:
  Arrange: Prepare a valid camelCase string such as "testString".
  Act: Invoke splitCamelCaseToLower and attempt to add an element to the returned list.
  Assert: Verify that an UnsupportedOperationException is thrown when trying to modify the list.
Validation:
  The assertion confirms that the method returns an immutable list as specified by Collections.unmodifiableList, ensuring data integrity.

---

Scenario 12: Handle Non-Basic Latin Characters

Details:
  TestName: handleNonBasicLatinCharacters
  Description: Verify that strings containing non-basic Latin characters (like accented characters or other Unicode) are handled according to the UPPER pattern which includes non-basic Latin.
Execution:
  Arrange: Prepare a string with non-basic Latin characters such as "caféMañana".
  Act: Invoke splitCamelCaseToLower with the prepared string.
  Assert: Verify the returned list handles non-basic Latin characters appropriately.
Validation:
  The assertion confirms that the regex pattern correctly handles international characters as defined by the UPPER constant.

---

Scenario 13: Handle Single Character String

Details:
  TestName: handleSingleCharacterString
  Description: Verify that a single character string is returned as a single-element list in lowercase.
Execution:
  Arrange: Prepare a single character string such as "A".
  Act: Invoke splitCamelCaseToLower with the prepared string.
  Assert: Verify that the returned list contains ["a"].
Validation:
  The assertion ensures that edge case of single character input is handled correctly.

---

Scenario 14: Handle String Starting with Lowercase Followed by Uppercase

Details:
  TestName: handleStringStartingWithLowercaseFollowedByUppercase
  Description: Verify correct splitting when a lowercase letter is immediately followed by an uppercase letter at the start.
Execution:
  Arrange: Prepare a string such as "iPhone".
  Act: Invoke splitCamelCaseToLower with the prepared string.
  Assert: Verify that the returned list correctly splits at the uppercase boundary.
Validation:
  The assertion confirms proper handling of product-name style camelCase patterns.

---

Scenario 15: Handle All Uppercase Acronym at End

Details:
  TestName: handleAllUppercaseAcronymAtEnd
  Description: Verify that a string ending with consecutive uppercase letters is handled correctly.
Execution:
  Arrange: Prepare a string such as "parseHTML".
  Act: Invoke splitCamelCaseToLower with the prepared string.
  Assert: Verify the returned list handles the trailing acronym appropriately.
Validation:
  The assertion confirms that trailing acronyms are processed according to the camelCase splitting rules.

*/

// ********RoostGPT********

package org.springframework.ai.util;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.regex.Pattern;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.util.Assert;
import org.springframework.util.StringUtils;

class ParsingUtilsSplitCamelCaseToLowerTest {

	@Test
	@Tag("valid")
	void splitSimpleCamelCaseStringToLowercase() {
		// Arrange
		String source = "camelCase";

		// Act
		List<String> result = ParsingUtils.splitCamelCaseToLower(source);

		// Assert
		assertNotNull(result);
		assertEquals(2, result.size());
		assertEquals("camel", result.get(0));
		assertEquals("case", result.get(1));
	}

	@Test
	@Tag("valid")
	void splitMultipleWordCamelCaseString() {
		// Arrange
		String source = "thisIsATestString";

		// Act
		List<String> result = ParsingUtils.splitCamelCaseToLower(source);

		// Assert
		assertNotNull(result);
		assertEquals(5, result.size());
		assertEquals("this", result.get(0));
		assertEquals("is", result.get(1));
		assertEquals("a", result.get(2));
		assertEquals("test", result.get(3));
		assertEquals("string", result.get(4));
	}

	@Test
	@Tag("boundary")
	void handleSingleLowercaseWord() {
		// Arrange
		String source = "word";

		// Act
		List<String> result = ParsingUtils.splitCamelCaseToLower(source);

		// Assert
		assertNotNull(result);
		assertEquals(1, result.size());
		assertEquals("word", result.get(0));
	}

	@Test
	@Tag("boundary")
	void handleSingleUppercaseWord() {
		// Arrange
		String source = "WORD";

		// Act
		List<String> result = ParsingUtils.splitCamelCaseToLower(source);

		// Assert
		assertNotNull(result);
		assertEquals(1, result.size());
		assertEquals("word", result.get(0));
	}

	@Test
	@Tag("valid")
	void handlePascalCaseString() {
		// Arrange
		String source = "PascalCaseString";

		// Act
		List<String> result = ParsingUtils.splitCamelCaseToLower(source);

		// Assert
		assertNotNull(result);
		assertEquals(3, result.size());
		assertEquals("pascal", result.get(0));
		assertEquals("case", result.get(1));
		assertEquals("string", result.get(2));
	}

	@Test
	@Tag("valid")
	void handleConsecutiveUppercaseLettersAcronym() {
		// Arrange
		String source = "parseXMLDocument";

		// Act
		List<String> result = ParsingUtils.splitCamelCaseToLower(source);

		// Assert
		assertNotNull(result);
		assertTrue(result.size() >= 2);
		assertEquals("parse", result.get(0));
	}

	@Test
	@Tag("boundary")
	void handleEmptyString() {
		// Arrange
		String source = "";

		// Act
		List<String> result = ParsingUtils.splitCamelCaseToLower(source);

		// Assert
		assertNotNull(result);
		assertEquals(1, result.size());
		assertEquals("", result.get(0));
	}

	@Test
	@Tag("invalid")
	void handleNullInputThrowsException() {
		// Arrange
		String source = null;

		// Act & Assert
		IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
			ParsingUtils.splitCamelCaseToLower(source);
		});

		assertTrue(exception.getMessage().contains("Source string must not be null"));
	}

	@Test
	@Tag("valid")
	void handleStringWithUnderscore() {
		// Arrange
		String source = "camel_Case";

		// Act
		List<String> result = ParsingUtils.splitCamelCaseToLower(source);

		// Assert
		assertNotNull(result);
		assertFalse(result.isEmpty());
	}

	@Test
	@Tag("valid")
	void handleStringWithDollarSign() {
		// Arrange
		String source = "camel$Case";

		// Act
		List<String> result = ParsingUtils.splitCamelCaseToLower(source);

		// Assert
		assertNotNull(result);
		assertFalse(result.isEmpty());
	}

	@Test
	@Tag("valid")
	void verifyReturnedListIsUnmodifiable() {
		// Arrange
		String source = "testString";

		// Act
		List<String> result = ParsingUtils.splitCamelCaseToLower(source);

		// Assert
		assertNotNull(result);
		assertThrows(UnsupportedOperationException.class, () -> {
			result.add("newElement");
		});
	}

	@Test
	@Tag("valid")
	void handleNonBasicLatinCharacters() {
		// Arrange
		String source = "caféMañana";

		// Act
		List<String> result = ParsingUtils.splitCamelCaseToLower(source);

		// Assert
		assertNotNull(result);
		assertFalse(result.isEmpty());
	}

	@Test
	@Tag("boundary")
	void handleSingleCharacterString() {
		// Arrange
		String source = "A";

		// Act
		List<String> result = ParsingUtils.splitCamelCaseToLower(source);

		// Assert
		assertNotNull(result);
		assertEquals(1, result.size());
		assertEquals("a", result.get(0));
	}

	@Test
	@Tag("valid")
	void handleStringStartingWithLowercaseFollowedByUppercase() {
		// Arrange
		String source = "iPhone";

		// Act
		List<String> result = ParsingUtils.splitCamelCaseToLower(source);

		// Assert
		assertNotNull(result);
		assertTrue(result.size() >= 1);
		assertTrue(result.get(0).equals("i") || result.get(0).equals("iphone"));
	}

	@Test
	@Tag("valid")
	void handleAllUppercaseAcronymAtEnd() {
		// Arrange
		String source = "parseHTML";

		// Act
		List<String> result = ParsingUtils.splitCamelCaseToLower(source);

		// Assert
		assertNotNull(result);
		assertTrue(result.size() >= 1);
		assertEquals("parse", result.get(0));
	}

	@Test
	@Tag("boundary")
	void handleSingleLowercaseCharacter() {
		// Arrange
		String source = "a";

		// Act
		List<String> result = ParsingUtils.splitCamelCaseToLower(source);

		// Assert
		assertNotNull(result);
		assertEquals(1, result.size());
		assertEquals("a", result.get(0));
	}

	@Test
	@Tag("valid")
	void handleMixedCaseWithNumbers() {
		// Arrange
		String source = "test123Value";

		// Act
		List<String> result = ParsingUtils.splitCamelCaseToLower(source);

		// Assert
		assertNotNull(result);
		assertFalse(result.isEmpty());
	}

	@Test
	@Tag("valid")
	void handleAllLowercaseString() {
		// Arrange
		String source = "alllowercase";

		// Act
		List<String> result = ParsingUtils.splitCamelCaseToLower(source);

		// Assert
		assertNotNull(result);
		assertEquals(1, result.size());
		assertEquals("alllowercase", result.get(0));
	}

	@Test
	@Tag("valid")
	void verifyAllElementsAreLowercase() {
		// Arrange
		String source = "ThisIsATest";

		// Act
		List<String> result = ParsingUtils.splitCamelCaseToLower(source);

		// Assert
		assertNotNull(result);
		for (String element : result) {
			assertEquals(element.toLowerCase(), element);
		}
	}

}