/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test spring-ai-test-timeout-pr using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=reConcatenateCamelCase_f66e996fbf
ROOST_METHOD_SIG_HASH=reConcatenateCamelCase_c02294312c

Scenario 1: Basic Camel Case String with Hyphen Delimiter

Details:
  TestName: reConcatenateCamelCaseWithHyphenDelimiter
  Description: Verify that a standard camel case string is correctly split and recombined with a hyphen delimiter, converting all parts to lowercase.
Execution:
  Arrange: Prepare a camel case string "firstName" and delimiter "-".
  Act: Invoke reConcatenateCamelCase("firstName", "-").
  Assert: Verify the result equals "first-name".
Validation:
  The assertion confirms that the method correctly identifies camel case boundaries, converts parts to lowercase, and joins them with the specified delimiter. This is essential for converting Java naming conventions to other formats like kebab-case for URLs or configuration keys.

---

Scenario 2: Multiple Camel Case Words with Underscore Delimiter

Details:
  TestName: reConcatenateCamelCaseWithUnderscoreDelimiter
  Description: Verify that a camel case string with multiple words is correctly processed and joined with an underscore delimiter.
Execution:
  Arrange: Prepare a camel case string "myVariableName" and delimiter "_".
  Act: Invoke reConcatenateCamelCase("myVariableName", "_").
  Assert: Verify the result equals "my_variable_name".
Validation:
  The assertion validates that multiple camel case boundaries are detected and the resulting parts are properly joined with underscores. This is commonly used for converting to snake_case format.

---

Scenario 3: Single Word Without Camel Case

Details:
  TestName: reConcatenateSingleWordWithoutCamelCase
  Description: Verify that a single lowercase word without camel case boundaries is returned as-is with no delimiter added.
Execution:
  Arrange: Prepare a single word string "name" and delimiter "-".
  Act: Invoke reConcatenateCamelCase("name", "-").
  Assert: Verify the result equals "name".
Validation:
  The assertion confirms that strings without camel case boundaries are handled correctly, returning the original string in lowercase without any delimiters.

---

Scenario 4: Empty String Source

Details:
  TestName: reConcatenateCamelCaseWithEmptySource
  Description: Verify that an empty string source returns an empty string result.
Execution:
  Arrange: Prepare an empty string "" and delimiter "-".
  Act: Invoke reConcatenateCamelCase("", "-").
  Assert: Verify the result equals "".
Validation:
  The assertion ensures that empty input is handled gracefully without errors, returning an empty string as expected.

---

Scenario 5: Null Source String Throws Exception

Details:
  TestName: reConcatenateCamelCaseWithNullSourceThrowsException
  Description: Verify that passing a null source string throws an IllegalArgumentException.
Execution:
  Arrange: Prepare null as source and "-" as delimiter.
  Act: Invoke reConcatenateCamelCase(null, "-").
  Assert: Verify that an IllegalArgumentException is thrown with message "Source string must not be null".
Validation:
  The assertion confirms that the method enforces the non-null constraint on the source parameter, providing clear error messaging for invalid input.

---

Scenario 6: Null Delimiter Throws Exception

Details:
  TestName: reConcatenateCamelCaseWithNullDelimiterThrowsException
  Description: Verify that passing a null delimiter throws an IllegalArgumentException.
Execution:
  Arrange: Prepare "camelCase" as source and null as delimiter.
  Act: Invoke reConcatenateCamelCase("camelCase", null).
  Assert: Verify that an IllegalArgumentException is thrown with message "Delimiter must not be null".
Validation:
  The assertion confirms that the method enforces the non-null constraint on the delimiter parameter, ensuring proper error handling.

---

Scenario 7: Consecutive Uppercase Letters (Acronym)

Details:
  TestName: reConcatenateCamelCaseWithAcronym
  Description: Verify that consecutive uppercase letters (acronyms) are handled correctly in camel case splitting.
Execution:
  Arrange: Prepare a string "parseXMLDocument" and delimiter "-".
  Act: Invoke reConcatenateCamelCase("parseXMLDocument", "-").
  Assert: Verify the result handles the XML acronym appropriately.
Validation:
  The assertion validates the regex pattern's behavior with consecutive uppercase letters, which is important for handling acronyms in variable names.

---

Scenario 8: String Starting with Uppercase Letter

Details:
  TestName: reConcatenateCamelCaseStartingWithUppercase
  Description: Verify that a Pascal case string (starting with uppercase) is correctly processed.
Execution:
  Arrange: Prepare a string "FirstName" and delimiter "_".
  Act: Invoke reConcatenateCamelCase("FirstName", "_").
  Assert: Verify the result equals "first_name".
Validation:
  The assertion confirms that strings starting with uppercase letters are handled correctly, converting to lowercase and joining with the delimiter.

---

Scenario 9: Empty Delimiter

Details:
  TestName: reConcatenateCamelCaseWithEmptyDelimiter
  Description: Verify that using an empty string as delimiter concatenates parts without separation.
Execution:
  Arrange: Prepare a string "camelCase" and delimiter "".
  Act: Invoke reConcatenateCamelCase("camelCase", "").
  Assert: Verify the result equals "camelcase".
Validation:
  The assertion confirms that an empty delimiter results in all parts being joined together without any separator, effectively just lowercasing the entire string.

---

Scenario 10: Multi-Character Delimiter

Details:
  TestName: reConcatenateCamelCaseWithMultiCharacterDelimiter
  Description: Verify that a multi-character delimiter is correctly used to join the parts.
Execution:
  Arrange: Prepare a string "myTestMethod" and delimiter " -> ".
  Act: Invoke reConcatenateCamelCase("myTestMethod", " -> ").
  Assert: Verify the result equals "my -> test -> method".
Validation:
  The assertion confirms that delimiters of any length are supported, allowing flexible formatting options.

---

Scenario 11: String with Numbers

Details:
  TestName: reConcatenateCamelCaseWithNumbers
  Description: Verify that camel case strings containing numbers are processed correctly.
Execution:
  Arrange: Prepare a string "test123Value" and delimiter "-".
  Act: Invoke reConcatenateCamelCase("test123Value", "-").
  Assert: Verify the result handles numeric characters appropriately.
Validation:
  The assertion validates that numbers within the string do not interfere with camel case detection and the string is properly split and rejoined.

---

Scenario 12: Non-Basic Latin Characters

Details:
  TestName: reConcatenateCamelCaseWithNonBasicLatinCharacters
  Description: Verify that the method handles non-basic Latin characters according to the UPPER regex pattern.
Execution:
  Arrange: Prepare a string containing non-basic Latin characters and delimiter "-".
  Act: Invoke reConcatenateCamelCase with the prepared string.
  Assert: Verify the result handles non-basic Latin characters as uppercase boundaries.
Validation:
  The assertion confirms that the regex pattern correctly identifies non-basic Latin characters as potential split points, as defined in the UPPER constant.

---

Scenario 13: All Uppercase String

Details:
  TestName: reConcatenateCamelCaseWithAllUppercase
  Description: Verify that an all-uppercase string is processed correctly.
Execution:
  Arrange: Prepare a string "CONSTANT" and delimiter "_".
  Act: Invoke reConcatenateCamelCase("CONSTANT", "_").
  Assert: Verify the result equals "constant".
Validation:
  The assertion confirms that all-uppercase strings are converted to lowercase without unnecessary splitting.

---

Scenario 14: All Lowercase String

Details:
  TestName: reConcatenateCamelCaseWithAllLowercase
  Description: Verify that an all-lowercase string is returned unchanged except for the delimiter not being applied.
Execution:
  Arrange: Prepare a string "lowercase" and delimiter "-".
  Act: Invoke reConcatenateCamelCase("lowercase", "-").
  Assert: Verify the result equals "lowercase".
Validation:
  The assertion confirms that strings without any uppercase letters are returned as-is since there are no camel case boundaries to split on.

---

Scenario 15: Single Character String

Details:
  TestName: reConcatenateCamelCaseWithSingleCharacter
  Description: Verify that a single character string is handled correctly.
Execution:
  Arrange: Prepare a string "A" and delimiter "-".
  Act: Invoke reConcatenateCamelCase("A", "-").
  Assert: Verify the result equals "a".
Validation:
  The assertion confirms that single character inputs are processed correctly, converting to lowercase without any delimiter application.

*/

// ********RoostGPT********

package org.springframework.ai.util;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.regex.Pattern;
import org.springframework.util.Assert;
import org.springframework.util.StringUtils;

class ParsingUtilsReConcatenateCamelCaseTest {

	@Test
	@Tag("valid")
	void reConcatenateCamelCaseWithHyphenDelimiter() {
		// Arrange
		String source = "firstName";
		String delimiter = "-";
		// Act
		String result = ParsingUtils.reConcatenateCamelCase(source, delimiter);
		// Assert
		assertEquals("first-name", result);
	}

	@Test
	@Tag("valid")
	void reConcatenateCamelCaseWithUnderscoreDelimiter() {
		// Arrange
		String source = "myVariableName";
		String delimiter = "_";
		// Act
		String result = ParsingUtils.reConcatenateCamelCase(source, delimiter);
		// Assert
		assertEquals("my_variable_name", result);
	}

	@Test
	@Tag("boundary")
	void reConcatenateSingleWordWithoutCamelCase() {
		// Arrange
		String source = "name";
		String delimiter = "-";
		// Act
		String result = ParsingUtils.reConcatenateCamelCase(source, delimiter);
		// Assert
		assertEquals("name", result);
	}

	@Test
	@Tag("boundary")
	void reConcatenateCamelCaseWithEmptySource() {
		// Arrange
		String source = "";
		String delimiter = "-";
		// Act
		String result = ParsingUtils.reConcatenateCamelCase(source, delimiter);
		// Assert
		assertEquals("", result);
	}

	@Test
	@Tag("invalid")
	void reConcatenateCamelCaseWithNullSourceThrowsException() {
		// Arrange
		String source = null;
		String delimiter = "-";
		// Act & Assert
		IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
			ParsingUtils.reConcatenateCamelCase(source, delimiter);
		});
		assertTrue(exception.getMessage().contains("Source string must not be null"));
	}

	@Test
	@Tag("invalid")
	void reConcatenateCamelCaseWithNullDelimiterThrowsException() {
		// Arrange
		String source = "camelCase";
		String delimiter = null;
		// Act & Assert
		IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
			ParsingUtils.reConcatenateCamelCase(source, delimiter);
		});
		assertTrue(exception.getMessage().contains("Delimiter must not be null"));
	}

	@Test
	@Tag("valid")
	void reConcatenateCamelCaseWithAcronym() {
		// Arrange
		String source = "parseXMLDocument";
		String delimiter = "-";
		// Act
		String result = ParsingUtils.reConcatenateCamelCase(source, delimiter);
		// Assert
		assertNotNull(result);
		assertTrue(result.contains("parse"));
		assertTrue(result.contains("document"));
	}

	@Test
	@Tag("valid")
	void reConcatenateCamelCaseStartingWithUppercase() {
		// Arrange
		String source = "FirstName";
		String delimiter = "_";
		// Act
		String result = ParsingUtils.reConcatenateCamelCase(source, delimiter);
		// Assert
		assertEquals("first_name", result);
	}

	@Test
	@Tag("boundary")
	void reConcatenateCamelCaseWithEmptyDelimiter() {
		// Arrange
		String source = "camelCase";
		String delimiter = "";
		// Act
		String result = ParsingUtils.reConcatenateCamelCase(source, delimiter);
		// Assert
		assertEquals("camelcase", result);
	}

	@Test
	@Tag("valid")
	void reConcatenateCamelCaseWithMultiCharacterDelimiter() {
		// Arrange
		String source = "myTestMethod";
		String delimiter = " -> ";
		// Act
		String result = ParsingUtils.reConcatenateCamelCase(source, delimiter);
		// Assert
		assertEquals("my -> test -> method", result);
	}

	@Test
	@Tag("valid")
	void reConcatenateCamelCaseWithNumbers() {
		// Arrange
		String source = "test123Value";
		String delimiter = "-";
		// Act
		String result = ParsingUtils.reConcatenateCamelCase(source, delimiter);
		// Assert
		assertNotNull(result);
		assertTrue(result.toLowerCase().equals(result));
		assertTrue(result.contains("value"));
	}

	@Test
	@Tag("valid")
	void reConcatenateCamelCaseWithNonBasicLatinCharacters() {
		// Arrange
		String source = "testÜberValue";
		String delimiter = "-";
		// Act
		String result = ParsingUtils.reConcatenateCamelCase(source, delimiter);
		// Assert
		assertNotNull(result);
		assertTrue(result.toLowerCase().equals(result));
	}

	@Test
	@Tag("boundary")
	void reConcatenateCamelCaseWithAllUppercase() {
		// Arrange
		String source = "CONSTANT";
		String delimiter = "_";
		// Act
		String result = ParsingUtils.reConcatenateCamelCase(source, delimiter);
		// Assert
		assertEquals("constant", result);
	}

	@Test
	@Tag("boundary")
	void reConcatenateCamelCaseWithAllLowercase() {
		// Arrange
		String source = "lowercase";
		String delimiter = "-";
		// Act
		String result = ParsingUtils.reConcatenateCamelCase(source, delimiter);
		// Assert
		assertEquals("lowercase", result);
	}

	@Test
	@Tag("boundary")
	void reConcatenateCamelCaseWithSingleCharacter() {
		// Arrange
		String source = "A";
		String delimiter = "-";
		// Act
		String result = ParsingUtils.reConcatenateCamelCase(source, delimiter);
		// Assert
		assertEquals("a", result);
	}

}