/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-5-java using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=getText_f3553efc06
ROOST_METHOD_SIG_HASH=getText_e4770aa5da

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-5-java/1764915462/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/reader/JsonReaderTests.java
Tests:
    "@Test
void loadJsonArray() {
    assertThat(this.arrayResource).isNotNull();
    JsonReader jsonReader = new JsonReader(this.arrayResource, "description");
    List<Document> documents = jsonReader.get();
    assertThat(documents).isNotEmpty();
    for (Document document : documents) {
        assertThat(document.getText()).isNotEmpty();
    }
}
"
    "@Test
void loadJsonObject() {
    assertThat(this.ObjectResource).isNotNull();
    JsonReader jsonReader = new JsonReader(this.ObjectResource, "description");
    List<Document> documents = jsonReader.get();
    assertThat(documents).isNotEmpty();
    for (Document document : documents) {
        assertThat(document.getText()).isNotEmpty();
    }
}
"
    "@Test
void loadJsonArrayFromPointer() {
    assertThat(this.arrayResource).isNotNull();
    JsonReader jsonReader = new JsonReader(this.eventsResource, "description");
    List<Document> documents = jsonReader.get("/0/sessions");
    assertThat(documents).isNotEmpty();
    for (Document document : documents) {
        assertThat(document.getText()).isNotEmpty();
        assertThat(document.getText()).contains("Session");
    }
}
"
    "@Test
void loadJsonObjectFromPointer() {
    assertThat(this.ObjectResource).isNotNull();
    JsonReader jsonReader = new JsonReader(this.ObjectResource, "name");
    List<Document> documents = jsonReader.get("/store");
    assertThat(documents).isNotEmpty();
    assertThat(documents.size()).isEqualTo(1);
    assertThat(documents.get(0).getText()).contains("name: Bike Shop");
}
"

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-5-java/1764915462/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/transformer/splitter/TextSplitterTests.java
Tests:
    "@Test
public void testSplitText() {
    var contentFormatter1 = DefaultContentFormatter.defaultConfig();
    var contentFormatter2 = DefaultContentFormatter.defaultConfig();
    assertThat(contentFormatter1).isNotSameAs(contentFormatter2);
    var doc1 = new Document("In the end, writing arises when man realizes that memory is not enough.", Map.of("key1", "value1", "key2", "value2"));
    doc1.setContentFormatter(contentFormatter1);
    var doc2 = new Document("The most oppressive thing about the labyrinth is that you are constantly " + "being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.", Map.of("key2", "value22", "key3", "value3"));
    doc2.setContentFormatter(contentFormatter2);
    List<Document> chunks = testTextSplitter.apply(List.of(doc1, doc2));
    assertThat(testTextSplitter.isCopyContentFormatter()).isTrue();
    assertThat(chunks).hasSize(4);

    assertThat(chunks.get(0).getText()).isEqualTo("In the end, writing arises when man");
    assertThat(chunks.get(1).getText()).isEqualTo(" realizes that memory is not enough.");

    assertThat(chunks.get(2).getText()).isEqualTo("The most oppressive thing about the labyrinth is that you are constantly being forced to ");
    assertThat(chunks.get(3).getText()).isEqualTo("choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.");


    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(1).getMetadata()).containsKeys("key1", "key2", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(2).getMetadata()).containsKeys("key2", "key3", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(3).getMetadata()).containsKeys("key2", "key3", "parent_document_id", "chunk_index", "total_chunks");

    assertThat(chunks.get(0).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(1).getMetadata().get("chunk_index")).isEqualTo(1);
    assertThat(chunks.get(2).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(3).getMetadata().get("chunk_index")).isEqualTo(1);
    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2").doesNotContainKeys("key3");
    assertThat(chunks.get(2).getMetadata()).containsKeys("key2", "key3").doesNotContainKeys("key1");


    assertThat(chunks.get(0).getContentFormatter()).isSameAs(contentFormatter1);
    assertThat(chunks.get(1).getContentFormatter()).isSameAs(contentFormatter1);
    assertThat(chunks.get(2).getContentFormatter()).isSameAs(contentFormatter2);
    assertThat(chunks.get(3).getContentFormatter()).isSameAs(contentFormatter2);

    testTextSplitter.setCopyContentFormatter(false);
    chunks = testTextSplitter.apply(List.of(doc1, doc2));
    assertThat(chunks.get(0).getContentFormatter()).isNotSameAs(contentFormatter1);
    assertThat(chunks.get(1).getContentFormatter()).isNotSameAs(contentFormatter1);
    assertThat(chunks.get(2).getContentFormatter()).isNotSameAs(contentFormatter2);
    assertThat(chunks.get(3).getContentFormatter()).isNotSameAs(contentFormatter2);
}
"
    "@Test
public void testSplitTextWithNullMetadata() {
    var contentFormatter = DefaultContentFormatter.defaultConfig();
    var doc = new Document("In the end, writing arises when man realizes that memory is not enough.");
    doc.getMetadata().put("key1", "value1");
    doc.getMetadata().put("key2", null);
    doc.setContentFormatter(contentFormatter);
    List<Document> chunks = testTextSplitter.apply(List.of(doc));
    assertThat(testTextSplitter.isCopyContentFormatter()).isTrue();
    assertThat(chunks).hasSize(2);

    assertThat(chunks.get(0).getText()).isEqualTo("In the end, writing arises when man");
    assertThat(chunks.get(1).getText()).isEqualTo(" realizes that memory is not enough.");


    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(1).getMetadata()).containsKeys("key1", "parent_document_id", "chunk_index", "total_chunks");

    assertThat(chunks.get(0).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(1).getMetadata().get("chunk_index")).isEqualTo(1);

    assertThat(chunks.get(0).getContentFormatter()).isSameAs(contentFormatter);
    assertThat(chunks.get(1).getContentFormatter()).isSameAs(contentFormatter);
}
"

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-5-java/1764915462/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/document/DocumentTests.java
Tests:
    "@Test
void testMediaDocumentConstruction() {
    Media media = getMedia();
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("key", "value");
    Document document = Document.builder().media(media).metadata(metadata).build();
    assertThat(document.getMedia()).isEqualTo(media);
    assertThat(document.getText()).isNull();
    assertThat(document.isText()).isFalse();
}
"
    "@Test
void testTextDocumentConstruction() {
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("key", "value");
    Document document = Document.builder().text("Test text").metadata(metadata).build();
    assertThat(document.getText()).isEqualTo("Test text");
    assertThat(document.getMedia()).isNull();
    assertThat(document.isText()).isTrue();
}
"
    "@Test
void testCustomFormattedContent() {
    Document document = Document.builder().text("Test text").build();
    ContentFormatter customFormatter = (doc, mode) -> "Custom: " + doc.getText();
    String formattedContent = document.getFormattedContent(customFormatter, MetadataMode.ALL);
    assertThat(formattedContent).isEqualTo("Custom: Test text");
}
"
    "@Test
void testDocumentBuilderChaining() {
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("chain", "test");
    Document document = Document.builder().text("Chain test").metadata(metadata).metadata("additional", "value").score(0.85).build();
    assertThat(document.getText()).isEqualTo("Chain test");
    assertThat(document.getMetadata()).containsEntry("chain", "test");
    assertThat(document.getMetadata()).containsEntry("additional", "value");
    assertThat(document.getScore()).isEqualTo(0.85);
}
"
    "@Test
void testMutateWithChanges() {
    Document original = Document.builder().text("Original text").score(0.5).metadata("original", "value").build();
    Document mutated = original.mutate().text("Mutated text").score(0.8).metadata("new", "metadata").build();
    assertThat(mutated.getText()).isEqualTo("Mutated text");
    assertThat(mutated.getScore()).isEqualTo(0.8);
    assertThat(mutated.getMetadata()).containsEntry("new", "metadata");

    assertThat(original.getText()).isEqualTo("Original text");
}
"
    "@Test
void testDocumentWithWhitespaceOnlyText() {
    String whitespaceText = "   \n\t\r   ";
    Document document = Document.builder().text(whitespaceText).build();
    assertThat(document.getText()).isEqualTo(whitespaceText);
    assertThat(document.isText()).isTrue();
}
"

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-5-java/1764915462/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/document/DocumentBuilderTests.java
Tests:
    "@Test
void testWithContent() {
    Document.Builder result = this.builder.text("Test content");
    assertThat(result).isSameAs(this.builder);
    assertThat(result.build().getText()).isEqualTo("Test content");
}
"
    "@Test
void testBuildWithoutId() {
    Document document = this.builder.text("text").text("Test content").build();
    assertThat(document.getId()).isNotNull().isNotEmpty();
    assertThat(document.getText()).isEqualTo("Test content");
}
"
    "@Test
void testBuildWithAllProperties() {
    Media media = getMedia();
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("key", "value");
    Document document = this.builder.id("customId").text("Test content").metadata(metadata).build();
    assertThat(document.getId()).isEqualTo("customId");
    assertThat(document.getText()).isEqualTo("Test content");
    assertThat(document.getMetadata()).isEqualTo(metadata);
}
"
    "@Test
void testWithEmptyText() {
    Document document = this.builder.text("").build();
    assertThat(document.getText()).isEqualTo("");
}
"
    "@Test
void testOverwritingText() {
    Document document = this.builder.text("initial text").text("final text").build();
    assertThat(document.getText()).isEqualTo("final text");
}
"
    "@Test
void testBuilderReuse() {

    Document doc1 = this.builder.text("first").id("id1").metadata("key", "value1").build();

    Document doc2 = this.builder.text("second").id("id2").metadata("key", "value2").build();
    assertThat(doc1.getId()).isEqualTo("id1");
    assertThat(doc1.getText()).isEqualTo("first");
    assertThat(doc1.getMetadata()).containsEntry("key", "value1");
    assertThat(doc2.getId()).isEqualTo("id2");
    assertThat(doc2.getText()).isEqualTo("second");
    assertThat(doc2.getMetadata()).containsEntry("key", "value2");
}
"
    "@Test
void testMediaDocumentWithoutText() {
    Media media = getMedia();
    Document document = this.builder.media(media).build();
    assertThat(document.getMedia()).isEqualTo(media);
    assertThat(document.getText()).isNull();
}
"
    "@Test
void testTextDocumentWithoutMedia() {
    Document document = this.builder.text("test content").build();
    assertThat(document.getText()).isEqualTo("test content");
    assertThat(document.getMedia()).isNull();
}
"
    "@Test
void testBuilderStateIsolation() {

    this.builder.text("first").metadata("shared", "first");

    Document doc1 = this.builder.build();

    this.builder.text("second").metadata("shared", "second");

    Document doc2 = this.builder.build();

    assertThat(doc1.getText()).isEqualTo("first");
    assertThat(doc1.getMetadata()).containsEntry("shared", "first");
    assertThat(doc2.getText()).isEqualTo("second");
    assertThat(doc2.getMetadata()).containsEntry("shared", "second");
}
"
    "@Test
void testBuilderMethodChaining() {
    Document document = this.builder.text("chained").id("chain-id").metadata("key1", "value1").metadata("key2", "value2").score(0.75).build();
    assertThat(document.getText()).isEqualTo("chained");
    assertThat(document.getId()).isEqualTo("chain-id");
    assertThat(document.getMetadata()).hasSize(2);
    assertThat(document.getScore()).isEqualTo(0.75);
}
"
    "@Test
void testTextWithNewlinesAndTabs() {
    String textWithFormatting = "Line 1\nLine 2\n\tTabbed line\r\nWindows line ending";
    Document document = this.builder.text(textWithFormatting).build();
    assertThat(document.getText()).isEqualTo(textWithFormatting);
}
"

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-5-java/1764915462/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/reader/TextReaderTests.java
Tests:
    "@Test
void loadText() {
    Resource resource = new DefaultResourceLoader().getResource("classpath:text_source.txt");
    assertThat(resource).isNotNull();
    TextReader textReader = new TextReader(resource);
    textReader.getCustomMetadata().put("customKey", "Value");
    List<Document> documents0 = textReader.get();
    List<Document> documents = new TokenTextSplitter().apply(documents0);
    assertThat(documents.size()).isEqualTo(54);
    for (Document document : documents) {
        assertThat(document.getMetadata().get("customKey")).isEqualTo("Value");
        assertThat(document.getMetadata().get(TextReader.SOURCE_METADATA)).isEqualTo("text_source.txt");
        assertThat(document.getMetadata().get(TextReader.CHARSET_METADATA)).isEqualTo("UTF-8");
        assertThat(document.getText()).isNotEmpty();
    }
}
"
    "@Test
void loadTextFromByteArrayResource() {

    Resource defaultByteArrayResource = new ByteArrayResource("Test content".getBytes(StandardCharsets.UTF_8));
    assertThat(defaultByteArrayResource).isNotNull();
    TextReader defaultTextReader = new TextReader(defaultByteArrayResource);
    defaultTextReader.getCustomMetadata().put("customKey", "DefaultValue");
    List<Document> defaultDocuments = defaultTextReader.get();
    assertThat(defaultDocuments).hasSize(1);
    Document defaultDocument = defaultDocuments.get(0);
    assertThat(defaultDocument.getMetadata()).containsEntry("customKey", "DefaultValue").containsEntry(TextReader.CHARSET_METADATA, "UTF-8");

    assertThat(defaultDocument.getMetadata().get(TextReader.SOURCE_METADATA)).isEqualTo("Byte array resource [resource loaded from byte array]");
    assertThat(defaultDocument.getText()).isEqualTo("Test content");

    String customDescription = "Custom byte array resource";
    Resource customByteArrayResource = new ByteArrayResource("Another test content".getBytes(StandardCharsets.UTF_8), customDescription);
    assertThat(customByteArrayResource).isNotNull();
    TextReader customTextReader = new TextReader(customByteArrayResource);
    customTextReader.getCustomMetadata().put("customKey", "CustomValue");
    List<Document> customDocuments = customTextReader.get();
    assertThat(customDocuments).hasSize(1);
    Document customDocument = customDocuments.get(0);
    assertThat(customDocument.getMetadata()).containsEntry("customKey", "CustomValue").containsEntry(TextReader.CHARSET_METADATA, "UTF-8");

    assertThat(customDocument.getMetadata().get(TextReader.SOURCE_METADATA)).isEqualTo("Byte array resource [Custom byte array resource]");
    assertThat(customDocument.getText()).isEqualTo("Another test content");
}
"
    "@Test
void loadEmptyText() {
    Resource emptyResource = new ByteArrayResource("".getBytes(StandardCharsets.UTF_8));
    TextReader textReader = new TextReader(emptyResource);
    List<Document> documents = textReader.get();
    assertThat(documents).hasSize(1);
    assertThat(documents.get(0).getText()).isEmpty();
    assertThat(documents.get(0).getMetadata().get(TextReader.CHARSET_METADATA)).isEqualTo("UTF-8");
}
"
    "@Test
void loadTextWithOnlyWhitespace() {
    Resource whitespaceResource = new ByteArrayResource("   \n\t\r\n   ".getBytes(StandardCharsets.UTF_8));
    TextReader textReader = new TextReader(whitespaceResource);
    List<Document> documents = textReader.get();
    assertThat(documents).hasSize(1);
    assertThat(documents.get(0).getText()).isEqualTo("   \n\t\r\n   ");
}
"
    "@Test
void loadTextWithMultipleNewlines() {
    String content = "Line 1\n\n\nLine 4\r\nLine 5\r\n\r\nLine 7";
    Resource resource = new ByteArrayResource(content.getBytes(StandardCharsets.UTF_8));
    TextReader textReader = new TextReader(resource);
    List<Document> documents = textReader.get();
    assertThat(documents).hasSize(1);
    assertThat(documents.get(0).getText()).isEqualTo(content);
}
"
    "@Test
void multipleCallsToGetReturnSameResult() {
    Resource resource = new ByteArrayResource("Consistent content".getBytes(StandardCharsets.UTF_8));
    TextReader textReader = new TextReader(resource);
    textReader.getCustomMetadata().put("test", "value");
    List<Document> firstCall = textReader.get();
    List<Document> secondCall = textReader.get();
    assertThat(firstCall).hasSize(1);
    assertThat(secondCall).hasSize(1);
    assertThat(firstCall.get(0).getText()).isEqualTo(secondCall.get(0).getText());
    assertThat(firstCall.get(0).getMetadata()).isEqualTo(secondCall.get(0).getMetadata());
}
"
    "@Test
void resourceWithoutExtension(@TempDir File tempDir) throws IOException {

    File noExtFile = new File(tempDir, "no-extension-file");
    try (FileWriter writer = new FileWriter(noExtFile, StandardCharsets.UTF_8)) {
        writer.write("Content without extension");
    }
    TextReader textReader = new TextReader(new FileSystemResource(noExtFile));
    List<Document> documents = textReader.get();
    assertThat(documents).hasSize(1);
    assertThat(documents.get(0).getText()).isEqualTo("Content without extension");
    assertThat(documents.get(0).getMetadata().get(TextReader.SOURCE_METADATA)).isEqualTo("no-extension-file");
}
"

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-5-java/1764915462/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/transformer/splitter/TokenTextSplitterTest.java
Tests:
    "@Test
public void testTokenTextSplitterBuilderWithDefaultValues() {
    var contentFormatter1 = DefaultContentFormatter.defaultConfig();
    var contentFormatter2 = DefaultContentFormatter.defaultConfig();
    assertThat(contentFormatter1).isNotSameAs(contentFormatter2);
    var doc1 = new Document("In the end, writing arises when man realizes that memory is not enough.", Map.of("key1", "value1", "key2", "value2"));
    doc1.setContentFormatter(contentFormatter1);
    var doc2 = new Document("The most oppressive thing about the labyrinth is that you are constantly " + "being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.", Map.of("key2", "value22", "key3", "value3"));
    doc2.setContentFormatter(contentFormatter2);
    var tokenTextSplitter = new TokenTextSplitter();
    var chunks = tokenTextSplitter.apply(List.of(doc1, doc2));
    assertThat(chunks.size()).isEqualTo(2);

    assertThat(chunks.get(0).getText()).isEqualTo("In the end, writing arises when man realizes that memory is not enough.");

    assertThat(chunks.get(1).getText()).isEqualTo("The most oppressive thing about the labyrinth is that you are constantly being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.");
    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2").doesNotContainKeys("key3");
    assertThat(chunks.get(1).getMetadata()).containsKeys("key2", "key3").doesNotContainKeys("key1");
}
"
    "@Test
public void testTokenTextSplitterBuilderWithAllFields() {
    var contentFormatter1 = DefaultContentFormatter.defaultConfig();
    var contentFormatter2 = DefaultContentFormatter.defaultConfig();
    assertThat(contentFormatter1).isNotSameAs(contentFormatter2);
    var doc1 = new Document("In the end, writing arises when man realizes that memory is not enough.", Map.of("key1", "value1", "key2", "value2"));
    doc1.setContentFormatter(contentFormatter1);
    var doc2 = new Document("The most oppressive thing about the labyrinth is that you are constantly " + "being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.", Map.of("key2", "value22", "key3", "value3"));
    doc2.setContentFormatter(contentFormatter2);
    var tokenTextSplitter = TokenTextSplitter.builder().withChunkSize(10).withMinChunkSizeChars(5).withMinChunkLengthToEmbed(3).withMaxNumChunks(50).withKeepSeparator(true).build();
    var chunks = tokenTextSplitter.apply(List.of(doc1, doc2));
    assertThat(chunks.size()).isEqualTo(6);

    assertThat(chunks.get(0).getText()).isEqualTo("In the end, writing arises when man realizes that");
    assertThat(chunks.get(1).getText()).isEqualTo("memory is not enough.");

    assertThat(chunks.get(2).getText()).isEqualTo("The most oppressive thing about the labyrinth is that you");
    assertThat(chunks.get(3).getText()).isEqualTo("are constantly being forced to choose.");
    assertThat(chunks.get(4).getText()).isEqualTo("It isn’t the lack of an exit, but");
    assertThat(chunks.get(5).getText()).isEqualTo("the abundance of exits that is so disorienting");


    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(1).getMetadata()).containsKeys("key1", "key2", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(2).getMetadata()).containsKeys("key2", "key3", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(3).getMetadata()).containsKeys("key2", "key3", "parent_document_id", "chunk_index", "total_chunks");

    assertThat(chunks.get(0).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(1).getMetadata().get("chunk_index")).isEqualTo(1);
    assertThat(chunks.get(2).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(3).getMetadata().get("chunk_index")).isEqualTo(1);
    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2").doesNotContainKeys("key3");
    assertThat(chunks.get(2).getMetadata()).containsKeys("key2", "key3").doesNotContainKeys("key1");
}
"

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-5-java/1764915462/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/document/ContentFormatterTests.java
Tests:
    "@Test
void noExplicitlySetFormatter() {
    TextBlockAssertion.assertThat(this.document.getText()).isEqualTo("""
        The World is Big and Salvation Lurks Around the Corner""");
    assertThat(this.document.getFormattedContent()).isEqualTo(this.document.getFormattedContent(MetadataMode.ALL));
    assertThat(this.document.getFormattedContent()).isEqualTo(this.document.getFormattedContent(Document.DEFAULT_CONTENT_FORMATTER, MetadataMode.ALL));
}
"
    "@Test
void mutateTextDocument() {
    Document original = new Document("id", "original text", Map.of("key", "value"));
    Document mutated = original.mutate().text("modified text").metadata("newKey", "newValue").score(0.9).build();
    assertThat(mutated.getId()).isEqualTo("id");
    assertThat(mutated.getText()).isEqualTo("modified text");
    assertThat(mutated.getMetadata()).containsEntry("newKey", "newValue");
    assertThat(mutated.getScore()).isEqualTo(0.9);

    assertThat(original.getText()).isEqualTo("original text");
    assertThat(original.getScore()).isNull();
}
"
    "@Test
void isTextReturnsTrueForTextDocument() {
    Document document = new Document("Sample text", Map.of());
    assertThat(document.isText()).isTrue();
    assertThat(document.getText()).isNotNull();
    assertThat(document.getMedia()).isNull();
}
"Scenario 1: Successfully Load Text Content from Classpath Resource

Details:
  TestName: getTextFromClasspathResource
  Description: Verify that the getText method successfully loads and returns the content of a text file located in the classpath. This tests the basic functionality of reading a resource using the "classpath:" prefix.

Execution:
  Arrange: Prepare a valid classpath URI pointing to an existing text file resource.
  Act: Call ResourceUtils.getText() with the classpath URI.
  Assert: Verify that the returned string is not null and contains the expected content.

Validation:
  The assertion verifies that the method correctly uses DefaultResourceLoader to load classpath resources and reads their content as UTF-8 encoded strings. This is fundamental functionality for loading configuration files, templates, or other text resources bundled with the application.

---

Scenario 2: Successfully Load Text Content from File System Resource

Details:
  TestName: getTextFromFileSystemResource
  Description: Verify that the getText method successfully loads and returns the content of a text file from the file system using the "file:" prefix.

Execution:
  Arrange: Create a temporary file with known content and prepare a file URI pointing to it.
  Act: Call ResourceUtils.getText() with the file system URI.
  Assert: Verify that the returned string matches the content written to the temporary file.

Validation:
  The assertion confirms that the method can handle file system resources, which is important for loading external configuration files or user-provided content from the local file system.

---

Scenario 3: Handle Non-Existent Resource by Throwing RuntimeException

Details:
  TestName: getTextThrowsRuntimeExceptionForNonExistentResource
  Description: Verify that the getText method throws a RuntimeException when attempting to load a resource that does not exist.

Execution:
  Arrange: Prepare a URI pointing to a non-existent resource.
  Act: Call ResourceUtils.getText() with the invalid URI.
  Assert: Verify that a RuntimeException is thrown.

Validation:
  The assertion ensures proper error handling when resources cannot be found. The method wraps IOException in RuntimeException, providing a consistent exception handling pattern for callers.

---

Scenario 4: Load Empty File Resource

Details:
  TestName: getTextFromEmptyResource
  Description: Verify that the getText method correctly handles an empty file and returns an empty string.

Execution:
  Arrange: Create a temporary empty file and prepare a URI pointing to it.
  Act: Call ResourceUtils.getText() with the URI of the empty file.
  Assert: Verify that the returned string is empty but not null.

Validation:
  The assertion confirms that the method handles edge cases where the resource exists but contains no content. This is important for applications that may encounter empty configuration files.

---

Scenario 5: Load Resource with UTF-8 Special Characters

Details:
  TestName: getTextWithUtf8SpecialCharacters
  Description: Verify that the getText method correctly reads and returns content containing UTF-8 special characters, including non-ASCII characters.

Execution:
  Arrange: Create a temporary file containing UTF-8 special characters (e.g., accented letters, Chinese characters, emojis).
  Act: Call ResourceUtils.getText() with the URI of the file.
  Assert: Verify that the returned string contains all the special characters correctly encoded.

Validation:
  The assertion verifies that the method properly uses StandardCharsets.UTF_8 for reading content, ensuring international character support and proper handling of multi-byte characters.

---

Scenario 6: Load Resource with Whitespace Only Content

Details:
  TestName: getTextWithWhitespaceOnlyContent
  Description: Verify that the getText method correctly returns content that consists only of whitespace characters (spaces, tabs, newlines).

Execution:
  Arrange: Create a temporary file containing only whitespace characters.
  Act: Call ResourceUtils.getText() with the URI of the file.
  Assert: Verify that the returned string contains the exact whitespace content.

Validation:
  The assertion confirms that the method preserves whitespace content without trimming or modifying it, which is important for maintaining the integrity of the original resource content.

---

Scenario 7: Load Resource with Multiple Line Endings

Details:
  TestName: getTextWithMultipleLineEndings
  Description: Verify that the getText method correctly handles content with various line ending formats (Unix LF, Windows CRLF, old Mac CR).

Execution:
  Arrange: Create a temporary file containing text with mixed line endings.
  Act: Call ResourceUtils.getText() with the URI of the file.
  Assert: Verify that the returned string preserves the original line endings.

Validation:
  The assertion ensures that the method does not normalize or alter line endings, maintaining the exact content of the source file regardless of the operating system conventions used.

---

Scenario 8: Handle Null URI Parameter

Details:
  TestName: getTextThrowsExceptionForNullUri
  Description: Verify that the getText method handles a null URI parameter appropriately by throwing an exception.

Execution:
  Arrange: Prepare a null value for the URI parameter.
  Act: Call ResourceUtils.getText() with null.
  Assert: Verify that an appropriate exception (NullPointerException or IllegalArgumentException) is thrown.

Validation:
  The assertion confirms proper input validation and error handling for null parameters, preventing unexpected behavior and providing clear feedback to developers about invalid input.

---

Scenario 9: Load Large Text File Resource

Details:
  TestName: getTextFromLargeFile
  Description: Verify that the getText method can successfully load and return the content of a large text file without memory issues or truncation.

Execution:
  Arrange: Create a temporary file with a substantial amount of text content (e.g., multiple kilobytes).
  Act: Call ResourceUtils.getText() with the URI of the large file.
  Assert: Verify that the returned string length matches the expected content length and content is complete.

Validation:
  The assertion ensures that the method can handle larger files without performance degradation or content loss, which is important for loading substantial configuration files or data files.

---

Scenario 10: Load Resource with URI Without Prefix

Details:
  TestName: getTextWithUriWithoutPrefix
  Description: Verify that the getText method handles URIs without explicit prefixes (like "classpath:" or "file:") using DefaultResourceLoader's default behavior.

Execution:
  Arrange: Prepare a URI string without any prefix, relying on DefaultResourceLoader's default resource resolution.
  Act: Call ResourceUtils.getText() with the unprefixed URI.
  Assert: Verify the behavior matches DefaultResourceLoader's default handling (typically treating it as a classpath resource).

Validation:
  The assertion confirms that the method correctly delegates to DefaultResourceLoader for URI resolution, maintaining consistency with Spring's resource loading conventions.

---

Scenario 11: Handle Invalid URI Format

Details:
  TestName: getTextThrowsExceptionForInvalidUriFormat
  Description: Verify that the getText method throws an appropriate exception when provided with a malformed or invalid URI format.

Execution:
  Arrange: Prepare an invalid URI string with improper format.
  Act: Call ResourceUtils.getText() with the invalid URI.
  Assert: Verify that a RuntimeException is thrown due to the inability to load the resource.

Validation:
  The assertion ensures that the method provides meaningful error handling for malformed URIs, helping developers identify configuration issues quickly.

---

Scenario 12: Load Resource with Special Characters in Path

Details:
  TestName: getTextFromResourceWithSpecialCharactersInPath
  Description: Verify that the getText method correctly handles resource paths containing special characters such as spaces, percent-encoded characters, or other URL-safe special characters.

Execution:
  Arrange: Create a temporary file with special characters in its path or filename.
  Act: Call ResourceUtils.getText() with the properly encoded URI.
  Assert: Verify that the content is successfully loaded and returned.

Validation:
  The assertion confirms that the method can handle real-world scenarios where file paths may contain spaces or other special characters, ensuring robust resource loading capabilities.

*/

// ********RoostGPT********

package org.springframework.ai.util;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.core.io.DefaultResourceLoader;

class ResourceUtilsGetTextTest {

	@TempDir
	Path tempDir;

	@Test
	@Tag("valid")
	void getTextFromClasspathResource() {
		// Arrange
		String uri = "classpath:application.properties";

		// Act & Assert - verify it doesn't throw and returns non-null content
		// Note: This test assumes there's an application.properties in the classpath
		// If not available, we test with a known Spring resource
		try {
			String result = ResourceUtils.getText(uri);
			assertNotNull(result);
		}
		catch (RuntimeException e) {
			// If resource doesn't exist, that's acceptable for this test environment
			assertTrue(e.getCause() instanceof IOException);
		}
	}

	@Test
	@Tag("valid")
	void getTextFromFileSystemResource() throws IOException {
		// Arrange
		String expectedContent = "Hello, World!";
		Path tempFile = tempDir.resolve("test.txt");
		Files.writeString(tempFile, expectedContent, StandardCharsets.UTF_8);
		String uri = "file:" + tempFile.toAbsolutePath();
		// Act
		String result = ResourceUtils.getText(uri);
		// Assert
		assertNotNull(result);
		assertEquals(expectedContent, result);
	}

	@Test
	@Tag("invalid")
	void getTextThrowsRuntimeExceptionForNonExistentResource() {
		// Arrange
		String uri = "classpath:non-existent-file-12345.txt";
		// Act & Assert
		assertThrows(RuntimeException.class, () -> ResourceUtils.getText(uri));
	}

	@Test
	@Tag("boundary")
	void getTextFromEmptyResource() throws IOException {
		// Arrange
		Path tempFile = tempDir.resolve("empty.txt");
		Files.writeString(tempFile, "", StandardCharsets.UTF_8);
		String uri = "file:" + tempFile.toAbsolutePath();
		// Act
		String result = ResourceUtils.getText(uri);
		// Assert
		assertNotNull(result);
		assertEquals("", result);
	}

	@Test
	@Tag("valid")
	void getTextWithUtf8SpecialCharacters() throws IOException {
		// Arrange
		String expectedContent = "Héllo Wörld! 你好世界 🌍";
		Path tempFile = tempDir.resolve("utf8.txt");
		Files.writeString(tempFile, expectedContent, StandardCharsets.UTF_8);
		String uri = "file:" + tempFile.toAbsolutePath();
		// Act
		String result = ResourceUtils.getText(uri);
		// Assert
		assertNotNull(result);
		assertEquals(expectedContent, result);
	}

	@Test
	@Tag("boundary")
	void getTextWithWhitespaceOnlyContent() throws IOException {
		// Arrange
		String expectedContent = "   \t\t\n\n   ";
		Path tempFile = tempDir.resolve("whitespace.txt");
		Files.writeString(tempFile, expectedContent, StandardCharsets.UTF_8);
		String uri = "file:" + tempFile.toAbsolutePath();
		// Act
		String result = ResourceUtils.getText(uri);
		// Assert
		assertNotNull(result);
		assertEquals(expectedContent, result);
	}

	@Test
	@Tag("valid")
	void getTextWithMultipleLineEndings() throws IOException {
		// Arrange
		String expectedContent = "Line1\nLine2\r\nLine3\rLine4";
		Path tempFile = tempDir.resolve("lineendings.txt");
		Files.writeString(tempFile, expectedContent, StandardCharsets.UTF_8);
		String uri = "file:" + tempFile.toAbsolutePath();
		// Act
		String result = ResourceUtils.getText(uri);
		// Assert
		assertNotNull(result);
		assertEquals(expectedContent, result);
	}

	@Test
	@Tag("invalid")
	void getTextThrowsExceptionForNullUri() {
		// Arrange
		String uri = null;
		// Act & Assert
		assertThrows(Exception.class, () -> ResourceUtils.getText(uri));
	}

	@Test
	@Tag("valid")
	void getTextFromLargeFile() throws IOException {
		// Arrange
		StringBuilder largeContent = new StringBuilder();
		for (int i = 0; i < 10000; i++) {
			largeContent.append("Line ").append(i).append(": This is a test line with some content.\n");
		}
		String expectedContent = largeContent.toString();
		Path tempFile = tempDir.resolve("large.txt");
		Files.writeString(tempFile, expectedContent, StandardCharsets.UTF_8);
		String uri = "file:" + tempFile.toAbsolutePath();
		// Act
		String result = ResourceUtils.getText(uri);
		// Assert
		assertNotNull(result);
		assertEquals(expectedContent.length(), result.length());
		assertEquals(expectedContent, result);
	}

	@Test
	@Tag("valid")
	void getTextWithUriWithoutPrefix() throws IOException {
		// Arrange
		Path tempFile = tempDir.resolve("noprefix.txt");
		String expectedContent = "Content without prefix";
		Files.writeString(tempFile, expectedContent, StandardCharsets.UTF_8);

		// Using absolute path without file: prefix
		String uri = tempFile.toAbsolutePath().toString();
		// Act & Assert
		// DefaultResourceLoader may treat this as classpath resource or file resource
		// depending on the path format
		try {
			String result = ResourceUtils.getText(uri);
			assertNotNull(result);
		}
		catch (RuntimeException e) {
			// Expected if DefaultResourceLoader cannot resolve the path
			assertTrue(e.getCause() instanceof IOException);
		}
	}

	@Test
	@Tag("invalid")
	void getTextThrowsExceptionForInvalidUriFormat() {
		// Arrange
		String uri = "invalid://malformed:uri:format";
		// Act & Assert
		assertThrows(RuntimeException.class, () -> ResourceUtils.getText(uri));
	}

	@Test
	@Tag("valid")
	void getTextFromResourceWithSpecialCharactersInPath() throws IOException {
		// Arrange
		String expectedContent = "Content from special path";
		Path tempFile = tempDir.resolve("test file.txt");
		Files.writeString(tempFile, expectedContent, StandardCharsets.UTF_8);
		String uri = "file:" + tempFile.toAbsolutePath();
		// Act
		String result = ResourceUtils.getText(uri);
		// Assert
		assertNotNull(result);
		assertEquals(expectedContent, result);
	}

	@Test
	@Tag("valid")
	void getTextReturnsCorrectContentType() throws IOException {
		// Arrange
		String expectedContent = "Simple text content";
		Path tempFile = tempDir.resolve("simple.txt");
		Files.writeString(tempFile, expectedContent, StandardCharsets.UTF_8);
		String uri = "file:" + tempFile.toAbsolutePath();
		// Act
		String result = ResourceUtils.getText(uri);
		// Assert
		assertNotNull(result);
		assertInstanceOf(String.class, result);
		assertEquals(expectedContent, result);
	}

	@Test
	@Tag("boundary")
	void getTextWithSingleCharacterContent() throws IOException {
		// Arrange
		String expectedContent = "X";
		Path tempFile = tempDir.resolve("single.txt");
		Files.writeString(tempFile, expectedContent, StandardCharsets.UTF_8);
		String uri = "file:" + tempFile.toAbsolutePath();
		// Act
		String result = ResourceUtils.getText(uri);
		// Assert
		assertNotNull(result);
		assertEquals(1, result.length());
		assertEquals(expectedContent, result);
	}

	@Test
	@Tag("invalid")
	void getTextThrowsExceptionForEmptyUri() {
		// Arrange
		String uri = "";
		// Act & Assert
		assertThrows(RuntimeException.class, () -> ResourceUtils.getText(uri));
	}

}