/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test spring-ai-test-timeout-pr using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=format_90ba7d716c
ROOST_METHOD_SIG_HASH=format_e979e93e1c

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/spring-ai-test-timeout-pr/1e559eba-5752-4feb-88f7-63ae643c0140/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/document/ContentFormatterTests.java
Tests:
    "@Test
void defaultConfigTextFormatter() {
    DefaultContentFormatter defaultConfigFormatter = DefaultContentFormatter.defaultConfig();
    TextBlockAssertion.assertThat(this.document.getFormattedContent(defaultConfigFormatter, MetadataMode.ALL)).isEqualTo("""
        llmKey2: value4
        embedKey1: value1
        embedKey2: value2
        embedKey3: value3

        The World is Big and Salvation Lurks Around the Corner""");
    assertThat(this.document.getFormattedContent(defaultConfigFormatter, MetadataMode.ALL)).isEqualTo(this.document.getFormattedContent());
    assertThat(this.document.getFormattedContent(defaultConfigFormatter, MetadataMode.ALL)).isEqualTo(defaultConfigFormatter.format(this.document, MetadataMode.ALL));
}
"
    "@Test
void setCustomContentFormatter() {
    Document document = new Document("Sample text", Map.of());
    ContentFormatter customFormatter = mock(ContentFormatter.class);
    when(customFormatter.format(document, MetadataMode.ALL)).thenReturn("Custom formatted content");
    document.setContentFormatter(customFormatter);
    assertThat(document.getContentFormatter()).isEqualTo(customFormatter);
    assertThat(document.getFormattedContent()).isEqualTo("Custom formatted content");
}
"Scenario 1: Format Document with MetadataMode.ALL and Multiple Metadata Entries

Details:
  TestName: formatDocumentWithAllMetadataModeAndMultipleEntries
  Description: Verify that the format method correctly formats a document when MetadataMode.ALL is used, including all metadata entries in the output with default templates.

Execution:
  Arrange: Create a DefaultContentFormatter using default configuration. Create a Document with text content and multiple metadata entries (e.g., "key1": "value1", "key2": "value2").
  Act: Call the format method with the document and MetadataMode.ALL.
  Assert: Verify that the returned string contains all metadata entries formatted as "key: value" separated by the default separator (system line separator), followed by two newlines and the document text.

Validation:
  The assertion verifies that when MetadataMode.ALL is specified, all metadata entries are included in the formatted output. This is important for scenarios where complete document information needs to be preserved for downstream processing.

---

Scenario 2: Format Document with MetadataMode.NONE

Details:
  TestName: formatDocumentWithNoneMetadataMode
  Description: Verify that the format method excludes all metadata when MetadataMode.NONE is specified, returning only the document content.

Execution:
  Arrange: Create a DefaultContentFormatter using default configuration. Create a Document with text content and metadata entries.
  Act: Call the format method with the document and MetadataMode.NONE.
  Assert: Verify that the returned string contains only the document text with empty metadata section (resulting in "\n\n" followed by content).

Validation:
  The assertion confirms that MetadataMode.NONE properly filters out all metadata. This is essential when only the raw content is needed without any metadata overhead.

---

Scenario 3: Format Document with MetadataMode.INFERENCE and Excluded Keys

Details:
  TestName: formatDocumentWithInferenceModeExcludingSpecificKeys
  Description: Verify that the format method correctly excludes specified inference metadata keys when MetadataMode.INFERENCE is used.

Execution:
  Arrange: Create a DefaultContentFormatter with excludedInferenceMetadataKeys containing "excludedKey". Create a Document with metadata including "excludedKey": "excludedValue" and "includedKey": "includedValue".
  Act: Call the format method with the document and MetadataMode.INFERENCE.
  Assert: Verify that the returned string contains only "includedKey: includedValue" and not the excluded key.

Validation:
  The assertion validates that inference-specific metadata filtering works correctly. This is crucial for controlling what metadata is passed to inference models.

---

Scenario 4: Format Document with MetadataMode.EMBED and Excluded Keys

Details:
  TestName: formatDocumentWithEmbedModeExcludingSpecificKeys
  Description: Verify that the format method correctly excludes specified embed metadata keys when MetadataMode.EMBED is used.

Execution:
  Arrange: Create a DefaultContentFormatter with excludedEmbedMetadataKeys containing "embedExcludedKey". Create a Document with metadata including "embedExcludedKey": "value1" and "embedIncludedKey": "value2".
  Act: Call the format method with the document and MetadataMode.EMBED.
  Assert: Verify that the returned string contains only "embedIncludedKey: value2" and not the excluded key.

Validation:
  The assertion confirms that embed-specific metadata filtering functions properly. This ensures that embedding operations receive only relevant metadata.

---

Scenario 5: Format Document with Empty Metadata

Details:
  TestName: formatDocumentWithEmptyMetadata
  Description: Verify that the format method handles documents with no metadata entries gracefully.

Execution:
  Arrange: Create a DefaultContentFormatter using default configuration. Create a Document with text content and an empty metadata map.
  Act: Call the format method with the document and MetadataMode.ALL.
  Assert: Verify that the returned string contains the document text with an empty metadata section.

Validation:
  The assertion ensures the formatter handles edge cases where no metadata exists. This prevents null pointer exceptions and ensures consistent output format.

---

Scenario 6: Format Document with Custom Metadata Template

Details:
  TestName: formatDocumentWithCustomMetadataTemplate
  Description: Verify that the format method uses a custom metadata template when configured.

Execution:
  Arrange: Create a DefaultContentFormatter with a custom metadataTemplate like "[{key}] = {value}". Create a Document with metadata entry "testKey": "testValue".
  Act: Call the format method with the document and MetadataMode.ALL.
  Assert: Verify that the metadata in the output is formatted as "[testKey] = testValue".

Validation:
  The assertion confirms that custom metadata templates are properly applied. This allows flexibility in how metadata is presented in different contexts.

---

Scenario 7: Format Document with Custom Metadata Separator

Details:
  TestName: formatDocumentWithCustomMetadataSeparator
  Description: Verify that the format method uses a custom metadata separator between multiple metadata entries.

Execution:
  Arrange: Create a DefaultContentFormatter with a custom metadataSeparator like " | ". Create a Document with multiple metadata entries.
  Act: Call the format method with the document and MetadataMode.ALL.
  Assert: Verify that metadata entries are separated by " | " in the output.

Validation:
  The assertion validates that custom separators work correctly for formatting multiple metadata entries. This is useful for different output format requirements.

---

Scenario 8: Format Document with Custom Text Template

Details:
  TestName: formatDocumentWithCustomTextTemplate
  Description: Verify that the format method uses a custom text template for the overall document format.

Execution:
  Arrange: Create a DefaultContentFormatter with a custom textTemplate like "Content: {content} | Metadata: {metadata_string}". Create a Document with text and metadata.
  Act: Call the format method with the document and MetadataMode.ALL.
  Assert: Verify that the output follows the custom template structure with content and metadata in specified positions.

Validation:
  The assertion confirms that the overall document structure can be customized. This enables different output formats for various use cases.

---

Scenario 9: Format Document with Metadata Containing Special Characters

Details:
  TestName: formatDocumentWithMetadataContainingSpecialCharacters
  Description: Verify that the format method correctly handles metadata values containing special characters.

Execution:
  Arrange: Create a DefaultContentFormatter using default configuration. Create a Document with metadata containing special characters like "key": "value with {braces} and newlines\n".
  Act: Call the format method with the document and MetadataMode.ALL.
  Assert: Verify that the special characters are preserved in the output without causing formatting issues.

Validation:
  The assertion ensures that special characters in metadata don't interfere with template replacement. This is important for handling real-world data with varied content.

---

Scenario 10: Format Document with Numeric Metadata Values

Details:
  TestName: formatDocumentWithNumericMetadataValues
  Description: Verify that the format method correctly converts numeric metadata values to strings.

Execution:
  Arrange: Create a DefaultContentFormatter using default configuration. Create a Document with metadata containing numeric values like "count": 42, "price": 19.99.
  Act: Call the format method with the document and MetadataMode.ALL.
  Assert: Verify that numeric values are properly converted to their string representations in the output.

Validation:
  The assertion confirms that the toString() method is correctly called on metadata values. This ensures proper handling of non-string metadata types.

---

Scenario 11: Format Document with Single Metadata Entry

Details:
  TestName: formatDocumentWithSingleMetadataEntry
  Description: Verify that the format method correctly handles a document with exactly one metadata entry.

Execution:
  Arrange: Create a DefaultContentFormatter using default configuration. Create a Document with text and a single metadata entry "singleKey": "singleValue".
  Act: Call the format method with the document and MetadataMode.ALL.
  Assert: Verify that the output contains the single metadata entry without any separator issues.

Validation:
  The assertion validates that single metadata entries are handled correctly without trailing separators. This is an edge case that ensures clean output.

---

Scenario 12: Format Document with All Metadata Keys Excluded in Inference Mode

Details:
  TestName: formatDocumentWithAllKeysExcludedInInferenceMode
  Description: Verify that the format method returns empty metadata section when all keys are excluded in INFERENCE mode.

Execution:
  Arrange: Create a DefaultContentFormatter with excludedInferenceMetadataKeys containing all metadata keys. Create a Document with those metadata entries.
  Act: Call the format method with the document and MetadataMode.INFERENCE.
  Assert: Verify that the output contains only the document text with empty metadata section.

Validation:
  The assertion confirms that complete exclusion of metadata keys results in empty metadata output. This tests the boundary condition of the filtering logic.

---

Scenario 13: Format Document with Overlapping Excluded Keys Between Modes

Details:
  TestName: formatDocumentWithDifferentExclusionsForInferenceAndEmbed
  Description: Verify that different metadata modes use their respective exclusion lists independently.

Execution:
  Arrange: Create a DefaultContentFormatter with excludedInferenceMetadataKeys containing "inferenceOnly" and excludedEmbedMetadataKeys containing "embedOnly". Create a Document with metadata including both keys plus a common key.
  Act: Call the format method twice - once with MetadataMode.INFERENCE and once with MetadataMode.EMBED.
  Assert: Verify that INFERENCE mode excludes only "inferenceOnly" and EMBED mode excludes only "embedOnly".

Validation:
  The assertion validates that each metadata mode maintains its own exclusion list. This is critical for proper separation of concerns between inference and embedding operations.

---

Scenario 14: Format Document with Null Metadata Value

Details:
  TestName: formatDocumentWithNullMetadataValue
  Description: Verify the behavior of the format method when a metadata entry has a null value.

Execution:
  Arrange: Create a DefaultContentFormatter using default configuration. Create a Document with metadata containing a null value entry.
  Act: Call the format method with the document and MetadataMode.ALL.
  Assert: Verify the behavior - either the null is converted to "null" string or handled appropriately.

Validation:
  The assertion tests how null values in metadata are handled during the toString() conversion. This is important for robustness against unexpected data.

---

Scenario 15: Format Document Preserves Original Document Text

Details:
  TestName: formatDocumentPreservesOriginalText
  Description: Verify that the format method preserves the exact document text content without modification.

Execution:
  Arrange: Create a DefaultContentFormatter using default configuration. Create a Document with specific text content including whitespace, newlines, and special formatting.
  Act: Call the format method with the document and MetadataMode.NONE.
  Assert: Verify that the document text portion of the output exactly matches the original text.

Validation:
  The assertion ensures that document content integrity is maintained during formatting. This is essential for preserving the semantic meaning of the original content.

*/

// ********RoostGPT********

package org.springframework.ai.document;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.util.Assert;

class DefaultContentFormatterFormatTest {

	private DefaultContentFormatter defaultFormatter;

	@BeforeEach
	void setUp() {
		defaultFormatter = DefaultContentFormatter.defaultConfig();
	}

	@Test
	@Tag("valid")
	void formatDocumentWithAllMetadataModeAndMultipleEntries() {
		// Arrange
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("key1", "value1");
		metadata.put("key2", "value2");
		Document document = new Document("Test content", metadata);
		// Act
		String result = defaultFormatter.format(document, MetadataMode.ALL);
		// Assert
		assertNotNull(result);
		assertTrue(result.contains("key1: value1") || result.contains("key2: value2"));
		assertTrue(result.contains("Test content"));
		assertTrue(result.contains("\n\n"));
	}

	@Test
	@Tag("valid")
	void formatDocumentWithNoneMetadataMode() {
		// Arrange
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("key1", "value1");
		metadata.put("key2", "value2");
		Document document = new Document("Test content", metadata);
		// Act
		String result = defaultFormatter.format(document, MetadataMode.NONE);
		// Assert
		assertNotNull(result);
		assertFalse(result.contains("key1"));
		assertFalse(result.contains("key2"));
		assertTrue(result.contains("Test content"));
	}

	@Test
	@Tag("valid")
	void formatDocumentWithInferenceModeExcludingSpecificKeys() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys("excludedKey")
			.build();
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("excludedKey", "excludedValue");
		metadata.put("includedKey", "includedValue");
		Document document = new Document("Test content", metadata);
		// Act
		String result = formatter.format(document, MetadataMode.INFERENCE);
		// Assert
		assertNotNull(result);
		assertTrue(result.contains("includedKey: includedValue"));
		assertFalse(result.contains("excludedKey"));
		assertFalse(result.contains("excludedValue"));
	}

	@Test
	@Tag("valid")
	void formatDocumentWithEmbedModeExcludingSpecificKeys() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedEmbedMetadataKeys("embedExcludedKey")
			.build();
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("embedExcludedKey", "value1");
		metadata.put("embedIncludedKey", "value2");
		Document document = new Document("Test content", metadata);
		// Act
		String result = formatter.format(document, MetadataMode.EMBED);
		// Assert
		assertNotNull(result);
		assertTrue(result.contains("embedIncludedKey: value2"));
		assertFalse(result.contains("embedExcludedKey"));
	}

	@Test
	@Tag("boundary")
	void formatDocumentWithEmptyMetadata() {
		// Arrange
		Map<String, Object> metadata = new HashMap<>();
		Document document = new Document("Test content", metadata);
		// Act
		String result = defaultFormatter.format(document, MetadataMode.ALL);
		// Assert
		assertNotNull(result);
		assertTrue(result.contains("Test content"));
	}

	@Test
	@Tag("valid")
	void formatDocumentWithCustomMetadataTemplate() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataTemplate("[{key}] = {value}")
			.build();
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("testKey", "testValue");
		Document document = new Document("Test content", metadata);
		// Act
		String result = formatter.format(document, MetadataMode.ALL);
		// Assert
		assertNotNull(result);
		assertTrue(result.contains("[testKey] = testValue"));
	}

	@Test
	@Tag("valid")
	void formatDocumentWithCustomMetadataSeparator() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.builder().withMetadataSeparator(" | ").build();
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("key1", "value1");
		metadata.put("key2", "value2");
		Document document = new Document("Test content", metadata);
		// Act
		String result = formatter.format(document, MetadataMode.ALL);
		// Assert
		assertNotNull(result);
		assertTrue(result.contains(" | ") || metadata.size() == 1);
	}

	@Test
	@Tag("valid")
	void formatDocumentWithCustomTextTemplate() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withTextTemplate("Content: {content} | Metadata: {metadata_string}")
			.build();
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("key1", "value1");
		Document document = new Document("Test content", metadata);
		// Act
		String result = formatter.format(document, MetadataMode.ALL);
		// Assert
		assertNotNull(result);
		assertTrue(result.startsWith("Content: Test content"));
		assertTrue(result.contains("Metadata:"));
	}

	@Test
	@Tag("valid")
	void formatDocumentWithMetadataContainingSpecialCharacters() {
		// Arrange
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("key", "value with {braces} and special chars");
		Document document = new Document("Test content", metadata);
		// Act
		String result = defaultFormatter.format(document, MetadataMode.ALL);
		// Assert
		assertNotNull(result);
		assertTrue(result.contains("value with {braces} and special chars"));
	}

	@Test
	@Tag("valid")
	void formatDocumentWithNumericMetadataValues() {
		// Arrange
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("count", 42);
		metadata.put("price", 19.99);
		Document document = new Document("Test content", metadata);
		// Act
		String result = defaultFormatter.format(document, MetadataMode.ALL);
		// Assert
		assertNotNull(result);
		assertTrue(result.contains("42") || result.contains("19.99"));
	}

	@Test
	@Tag("boundary")
	void formatDocumentWithSingleMetadataEntry() {
		// Arrange
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("singleKey", "singleValue");
		Document document = new Document("Test content", metadata);
		// Act
		String result = defaultFormatter.format(document, MetadataMode.ALL);
		// Assert
		assertNotNull(result);
		assertTrue(result.contains("singleKey: singleValue"));
		assertTrue(result.contains("Test content"));
	}

	@Test
	@Tag("boundary")
	void formatDocumentWithAllKeysExcludedInInferenceMode() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys("key1", "key2")
			.build();
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("key1", "value1");
		metadata.put("key2", "value2");
		Document document = new Document("Test content", metadata);
		// Act
		String result = formatter.format(document, MetadataMode.INFERENCE);
		// Assert
		assertNotNull(result);
		assertFalse(result.contains("key1"));
		assertFalse(result.contains("key2"));
		assertTrue(result.contains("Test content"));
	}

	@Test
	@Tag("valid")
	void formatDocumentWithDifferentExclusionsForInferenceAndEmbed() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys("inferenceOnly")
			.withExcludedEmbedMetadataKeys("embedOnly")
			.build();
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("inferenceOnly", "inferenceValue");
		metadata.put("embedOnly", "embedValue");
		metadata.put("commonKey", "commonValue");
		Document document = new Document("Test content", metadata);
		// Act
		String inferenceResult = formatter.format(document, MetadataMode.INFERENCE);
		String embedResult = formatter.format(document, MetadataMode.EMBED);
		// Assert
		assertNotNull(inferenceResult);
		assertNotNull(embedResult);
		// INFERENCE mode should exclude "inferenceOnly" but include "embedOnly"
		assertFalse(inferenceResult.contains("inferenceOnly"));
		assertTrue(inferenceResult.contains("embedOnly: embedValue"));
		assertTrue(inferenceResult.contains("commonKey: commonValue"));
		// EMBED mode should exclude "embedOnly" but include "inferenceOnly"
		assertFalse(embedResult.contains("embedOnly"));
		assertTrue(embedResult.contains("inferenceOnly: inferenceValue"));
		assertTrue(embedResult.contains("commonKey: commonValue"));
	}

	@Test
	@Tag("boundary")
	void formatDocumentWithNullMetadataValue() {
		// Arrange
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("nullKey", null);
		metadata.put("validKey", "validValue");
		Document document = new Document("Test content", metadata);
		// Act & Assert
		// This may throw NullPointerException or handle null gracefully
		try {
			String result = defaultFormatter.format(document, MetadataMode.ALL);
			assertNotNull(result);
			assertTrue(result.contains("Test content"));
		}
		catch (NullPointerException e) {
			// Expected behavior if null values are not handled
			assertNotNull(e);
		}
	}

	@Test
	@Tag("valid")
	void formatDocumentPreservesOriginalText() {
		// Arrange
		String originalText = "  Text with   whitespace\nand newlines\t\tand tabs  ";
		Map<String, Object> metadata = new HashMap<>();
		Document document = new Document(originalText, metadata);
		// Act
		String result = defaultFormatter.format(document, MetadataMode.NONE);
		// Assert
		assertNotNull(result);
		assertTrue(result.contains(originalText));
	}

	@Test
	@Tag("valid")
	void formatDocumentWithBuilderFromExistingFormatter() {
		// Arrange
		DefaultContentFormatter originalFormatter = DefaultContentFormatter.builder()
			.withMetadataTemplate("[{key}]={value}")
			.withMetadataSeparator(";")
			.withExcludedInferenceMetadataKeys("excluded1")
			.build();
		DefaultContentFormatter copiedFormatter = DefaultContentFormatter.builder().from(originalFormatter).build();
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("testKey", "testValue");
		Document document = new Document("Test content", metadata);
		// Act
		String originalResult = originalFormatter.format(document, MetadataMode.ALL);
		String copiedResult = copiedFormatter.format(document, MetadataMode.ALL);
		// Assert
		assertEquals(originalResult, copiedResult);
	}

	@Test
	@Tag("valid")
	void formatDocumentVerifyGetterMethods() {
		// Arrange
		String customMetadataTemplate = "[{key}]={value}";
		String customSeparator = " | ";
		String customTextTemplate = "META: {metadata_string} CONTENT: {content}";
		List<String> inferenceKeys = Arrays.asList("inf1", "inf2");
		List<String> embedKeys = Arrays.asList("emb1", "emb2");
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataTemplate(customMetadataTemplate)
			.withMetadataSeparator(customSeparator)
			.withTextTemplate(customTextTemplate)
			.withExcludedInferenceMetadataKeys(inferenceKeys)
			.withExcludedEmbedMetadataKeys(embedKeys)
			.build();
		// Assert
		assertEquals(customMetadataTemplate, formatter.getMetadataTemplate());
		assertEquals(customSeparator, formatter.getMetadataSeparator());
		assertEquals(customTextTemplate, formatter.getTextTemplate());
		assertEquals(inferenceKeys, formatter.getExcludedInferenceMetadataKeys());
		assertEquals(embedKeys, formatter.getExcludedEmbedMetadataKeys());
	}

	@Test
	@Tag("valid")
	void formatDocumentWithDefaultConfigVerifyDefaults() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.defaultConfig();
		// Assert
		assertNotNull(formatter);
		assertEquals("{key}: {value}", formatter.getMetadataTemplate());
		assertEquals(System.lineSeparator(), formatter.getMetadataSeparator());
		assertTrue(formatter.getTextTemplate().contains("{metadata_string}"));
		assertTrue(formatter.getTextTemplate().contains("{content}"));
	}

	@Test
	@Tag("boundary")
	void formatDocumentWithLongTextContent() {
		// Arrange
		StringBuilder longText = new StringBuilder();
		for (int i = 0; i < 1000; i++) {
			longText.append("This is a long text content. ");
		}
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("key", "value");
		Document document = new Document(longText.toString(), metadata);
		// Act
		String result = defaultFormatter.format(document, MetadataMode.ALL);
		// Assert
		assertNotNull(result);
		assertTrue(result.contains(longText.toString()));
	}

	@Test
	@Tag("valid")
	void formatDocumentWithBooleanMetadataValue() {
		// Arrange
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("isActive", true);
		metadata.put("isDeleted", false);
		Document document = new Document("Test content", metadata);
		// Act
		String result = defaultFormatter.format(document, MetadataMode.ALL);
		// Assert
		assertNotNull(result);
		assertTrue(result.contains("true") || result.contains("false"));
	}

	@Test
	@Tag("invalid")
	void formatDocumentBuilderWithEmptyMetadataTemplate() {
		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> {
			DefaultContentFormatter.builder().withMetadataTemplate("").build();
		});
	}

	@Test
	@Tag("invalid")
	void formatDocumentBuilderWithNullMetadataSeparator() {
		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> {
			DefaultContentFormatter.builder().withMetadataSeparator(null).build();
		});
	}

	@Test
	@Tag("invalid")
	void formatDocumentBuilderWithEmptyTextTemplate() {
		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> {
			DefaultContentFormatter.builder().withTextTemplate("").build();
		});
	}

}