/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test spring-ai-test-timeout-pr using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=getMetadataSeparator_79a2ecbb47
ROOST_METHOD_SIG_HASH=getMetadataSeparator_ea23f0ab20

Scenario 1: Verify Default Metadata Separator Returns System Line Separator

Details:
  TestName: getMetadataSeparatorReturnsDefaultSystemLineSeparator
  Description: This test verifies that when a DefaultContentFormatter is created using the default configuration (via defaultConfig() or builder().build()), the getMetadataSeparator() method returns the system's default line separator (System.lineSeparator()).

Execution:
  Arrange: Create a DefaultContentFormatter instance using the defaultConfig() static method.
  Act: Invoke the getMetadataSeparator() method on the formatter instance.
  Assert: Assert that the returned value equals System.lineSeparator().

Validation:
  The assertion verifies that the default metadata separator is correctly initialized to the system's line separator. This is significant because it ensures cross-platform compatibility, where different operating systems use different line separators (e.g., "\n" on Unix/Linux, "\r\n" on Windows).

---

Scenario 2: Verify Custom Metadata Separator Is Returned When Set Via Builder

Details:
  TestName: getMetadataSeparatorReturnsCustomSeparatorWhenConfigured
  Description: This test verifies that when a custom metadata separator is configured using the builder's withMetadataSeparator() method, the getMetadataSeparator() method returns the custom separator value.

Execution:
  Arrange: Create a DefaultContentFormatter instance using the builder pattern with a custom metadata separator (e.g., " | ").
  Act: Invoke the getMetadataSeparator() method on the formatter instance.
  Assert: Assert that the returned value equals the custom separator " | ".

Validation:
  The assertion confirms that the builder correctly sets and the getter correctly retrieves a custom metadata separator. This is important for scenarios where users need specific formatting between metadata fields, such as using pipes, commas, or other delimiters.

---

Scenario 3: Verify Empty String Metadata Separator Is Allowed

Details:
  TestName: getMetadataSeparatorReturnsEmptyStringWhenConfigured
  Description: This test verifies that an empty string can be set as the metadata separator and is correctly returned by getMetadataSeparator(). The withMetadataSeparator() method uses Assert.notNull() which allows empty strings.

Execution:
  Arrange: Create a DefaultContentFormatter instance using the builder pattern with an empty string as the metadata separator.
  Act: Invoke the getMetadataSeparator() method on the formatter instance.
  Assert: Assert that the returned value equals an empty string "".

Validation:
  The assertion verifies that empty strings are valid metadata separators. This is useful when users want metadata fields to be concatenated without any separator between them.

---

Scenario 4: Verify Metadata Separator With Special Characters

Details:
  TestName: getMetadataSeparatorReturnsSpecialCharacterSeparator
  Description: This test verifies that special characters (such as newlines, tabs, or Unicode characters) can be used as metadata separators and are correctly returned.

Execution:
  Arrange: Create a DefaultContentFormatter instance using the builder pattern with a special character separator (e.g., "\n---\n").
  Act: Invoke the getMetadataSeparator() method on the formatter instance.
  Assert: Assert that the returned value equals "\n---\n".

Validation:
  The assertion confirms that special characters and multi-character separators are properly stored and retrieved. This is important for creating visually distinct separations between metadata entries in formatted output.

---

Scenario 5: Verify Metadata Separator Preserved When Using Builder From Method

Details:
  TestName: getMetadataSeparatorPreservedWhenCopiedFromExistingFormatter
  Description: This test verifies that when creating a new formatter using the builder's from() method to copy settings from an existing formatter, the metadata separator is correctly preserved.

Execution:
  Arrange: Create an initial DefaultContentFormatter with a custom metadata separator (e.g., ";;"). Then create a second formatter using builder().from(firstFormatter).build().
  Act: Invoke the getMetadataSeparator() method on the second formatter instance.
  Assert: Assert that the returned value equals ";;".

Validation:
  The assertion verifies that the from() method correctly copies the metadata separator from an existing formatter. This is crucial for scenarios where users want to create variations of existing formatters while preserving certain settings.

---

Scenario 6: Verify Metadata Separator With Whitespace Only

Details:
  TestName: getMetadataSeparatorReturnsWhitespaceSeparator
  Description: This test verifies that whitespace-only strings (such as spaces or tabs) can be used as metadata separators and are correctly returned.

Execution:
  Arrange: Create a DefaultContentFormatter instance using the builder pattern with a whitespace separator (e.g., "   " - three spaces).
  Act: Invoke the getMetadataSeparator() method on the formatter instance.
  Assert: Assert that the returned value equals "   ".

Validation:
  The assertion confirms that whitespace-only separators are valid and correctly stored. This allows for flexible formatting where metadata fields are separated by specific amounts of whitespace.

---

Scenario 7: Verify Metadata Separator Consistency Across Multiple Calls

Details:
  TestName: getMetadataSeparatorReturnsConsistentValueOnMultipleCalls
  Description: This test verifies that calling getMetadataSeparator() multiple times on the same formatter instance returns the same value consistently, confirming immutability.

Execution:
  Arrange: Create a DefaultContentFormatter instance with a custom metadata separator.
  Act: Invoke the getMetadataSeparator() method multiple times (e.g., three times) and store each result.
  Assert: Assert that all returned values are equal to each other and to the expected separator value.

Validation:
  The assertion verifies the immutability and consistency of the formatter's metadata separator field. This is important for ensuring thread-safety and predictable behavior when the formatter is used across multiple operations.

---

Scenario 8: Verify Metadata Separator With Unicode Characters

Details:
  TestName: getMetadataSeparatorReturnsUnicodeSeparator
  Description: This test verifies that Unicode characters can be used as metadata separators and are correctly returned by getMetadataSeparator().

Execution:
  Arrange: Create a DefaultContentFormatter instance using the builder pattern with a Unicode separator (e.g., "→" or "•").
  Act: Invoke the getMetadataSeparator() method on the formatter instance.
  Assert: Assert that the returned value equals the Unicode separator.

Validation:
  The assertion confirms that Unicode characters are properly handled as metadata separators. This is important for internationalization and for creating visually appealing formatted output with special symbols.

*/

// ********RoostGPT********

package org.springframework.ai.document;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.*;
import org.springframework.util.Assert;

class DefaultContentFormatterGetMetadataSeparatorTest {

	@Test
	@Tag("valid")
	@DisplayName("Verify Default Metadata Separator Returns System Line Separator")
	void getMetadataSeparatorReturnsDefaultSystemLineSeparator() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.defaultConfig();
		// Act
		String metadataSeparator = formatter.getMetadataSeparator();
		// Assert
		assertNotNull(metadataSeparator);
		assertEquals(System.lineSeparator(), metadataSeparator);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Custom Metadata Separator Is Returned When Set Via Builder")
	void getMetadataSeparatorReturnsCustomSeparatorWhenConfigured() {
		// Arrange
		String customSeparator = " | ";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataSeparator(customSeparator)
			.build();
		// Act
		String metadataSeparator = formatter.getMetadataSeparator();
		// Assert
		assertNotNull(metadataSeparator);
		assertEquals(customSeparator, metadataSeparator);
	}

	@Test
	@Tag("boundary")
	@DisplayName("Verify Empty String Metadata Separator Is Allowed")
	void getMetadataSeparatorReturnsEmptyStringWhenConfigured() {
		// Arrange
		String emptySeparator = "";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataSeparator(emptySeparator)
			.build();
		// Act
		String metadataSeparator = formatter.getMetadataSeparator();
		// Assert
		assertNotNull(metadataSeparator);
		assertEquals(emptySeparator, metadataSeparator);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Metadata Separator With Special Characters")
	void getMetadataSeparatorReturnsSpecialCharacterSeparator() {
		// Arrange
		String specialSeparator = "\n---\n";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataSeparator(specialSeparator)
			.build();
		// Act
		String metadataSeparator = formatter.getMetadataSeparator();
		// Assert
		assertNotNull(metadataSeparator);
		assertEquals(specialSeparator, metadataSeparator);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Metadata Separator Preserved When Using Builder From Method")
	void getMetadataSeparatorPreservedWhenCopiedFromExistingFormatter() {
		// Arrange
		String customSeparator = ";;";
		DefaultContentFormatter firstFormatter = DefaultContentFormatter.builder()
			.withMetadataSeparator(customSeparator)
			.build();

		DefaultContentFormatter secondFormatter = DefaultContentFormatter.builder().from(firstFormatter).build();
		// Act
		String metadataSeparator = secondFormatter.getMetadataSeparator();
		// Assert
		assertNotNull(metadataSeparator);
		assertEquals(customSeparator, metadataSeparator);
	}

	@Test
	@Tag("boundary")
	@DisplayName("Verify Metadata Separator With Whitespace Only")
	void getMetadataSeparatorReturnsWhitespaceSeparator() {
		// Arrange
		String whitespaceSeparator = "   ";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataSeparator(whitespaceSeparator)
			.build();
		// Act
		String metadataSeparator = formatter.getMetadataSeparator();
		// Assert
		assertNotNull(metadataSeparator);
		assertEquals(whitespaceSeparator, metadataSeparator);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Metadata Separator Consistency Across Multiple Calls")
	void getMetadataSeparatorReturnsConsistentValueOnMultipleCalls() {
		// Arrange
		String customSeparator = ", ";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataSeparator(customSeparator)
			.build();
		// Act
		String firstCall = formatter.getMetadataSeparator();
		String secondCall = formatter.getMetadataSeparator();
		String thirdCall = formatter.getMetadataSeparator();
		// Assert
		assertNotNull(firstCall);
		assertNotNull(secondCall);
		assertNotNull(thirdCall);
		assertEquals(customSeparator, firstCall);
		assertEquals(customSeparator, secondCall);
		assertEquals(customSeparator, thirdCall);
		assertEquals(firstCall, secondCall);
		assertEquals(secondCall, thirdCall);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Metadata Separator With Unicode Characters")
	void getMetadataSeparatorReturnsUnicodeSeparator() {
		// Arrange
		String unicodeSeparator = "→";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataSeparator(unicodeSeparator)
			.build();
		// Act
		String metadataSeparator = formatter.getMetadataSeparator();
		// Assert
		assertNotNull(metadataSeparator);
		assertEquals(unicodeSeparator, metadataSeparator);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Metadata Separator With Bullet Unicode Character")
	void getMetadataSeparatorReturnsBulletUnicodeSeparator() {
		// Arrange
		String bulletSeparator = "•";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataSeparator(bulletSeparator)
			.build();
		// Act
		String metadataSeparator = formatter.getMetadataSeparator();
		// Assert
		assertNotNull(metadataSeparator);
		assertEquals(bulletSeparator, metadataSeparator);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Metadata Separator With Tab Character")
	void getMetadataSeparatorReturnsTabSeparator() {
		// Arrange
		String tabSeparator = "\t";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataSeparator(tabSeparator)
			.build();
		// Act
		String metadataSeparator = formatter.getMetadataSeparator();
		// Assert
		assertNotNull(metadataSeparator);
		assertEquals(tabSeparator, metadataSeparator);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Metadata Separator With Comma Separator")
	void getMetadataSeparatorReturnsCommaSeparator() {
		// Arrange
		String commaSeparator = ", ";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataSeparator(commaSeparator)
			.build();
		// Act
		String metadataSeparator = formatter.getMetadataSeparator();
		// Assert
		assertNotNull(metadataSeparator);
		assertEquals(commaSeparator, metadataSeparator);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Metadata Separator With Newline Character")
	void getMetadataSeparatorReturnsNewlineSeparator() {
		// Arrange
		String newlineSeparator = "\n";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataSeparator(newlineSeparator)
			.build();
		// Act
		String metadataSeparator = formatter.getMetadataSeparator();
		// Assert
		assertNotNull(metadataSeparator);
		assertEquals(newlineSeparator, metadataSeparator);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Metadata Separator With Carriage Return And Newline")
	void getMetadataSeparatorReturnsCarriageReturnNewlineSeparator() {
		// Arrange
		String crlfSeparator = "\r\n";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataSeparator(crlfSeparator)
			.build();
		// Act
		String metadataSeparator = formatter.getMetadataSeparator();
		// Assert
		assertNotNull(metadataSeparator);
		assertEquals(crlfSeparator, metadataSeparator);
	}

}