/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test spring-ai-test-timeout-pr using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=builder_2187989d2f
ROOST_METHOD_SIG_HASH=builder_80041265ae

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/spring-ai-test-timeout-pr/1e559eba-5752-4feb-88f7-63ae643c0140/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/transformer/splitter/TokenTextSplitterTest.java
Tests:
    "@Test
public void testTokenTextSplitterBuilderWithAllFields() {
    var contentFormatter1 = DefaultContentFormatter.defaultConfig();
    var contentFormatter2 = DefaultContentFormatter.defaultConfig();
    assertThat(contentFormatter1).isNotSameAs(contentFormatter2);
    var doc1 = new Document("In the end, writing arises when man realizes that memory is not enough.", Map.of("key1", "value1", "key2", "value2"));
    doc1.setContentFormatter(contentFormatter1);
    var doc2 = new Document("The most oppressive thing about the labyrinth is that you are constantly " + "being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.", Map.of("key2", "value22", "key3", "value3"));
    doc2.setContentFormatter(contentFormatter2);
    var tokenTextSplitter = TokenTextSplitter.builder().withChunkSize(10).withMinChunkSizeChars(5).withMinChunkLengthToEmbed(3).withMaxNumChunks(50).withKeepSeparator(true).build();
    var chunks = tokenTextSplitter.apply(List.of(doc1, doc2));
    assertThat(chunks.size()).isEqualTo(6);

    assertThat(chunks.get(0).getText()).isEqualTo("In the end, writing arises when man realizes that");
    assertThat(chunks.get(1).getText()).isEqualTo("memory is not enough.");

    assertThat(chunks.get(2).getText()).isEqualTo("The most oppressive thing about the labyrinth is that you");
    assertThat(chunks.get(3).getText()).isEqualTo("are constantly being forced to choose.");
    assertThat(chunks.get(4).getText()).isEqualTo("It isn’t the lack of an exit, but");
    assertThat(chunks.get(5).getText()).isEqualTo("the abundance of exits that is so disorienting");


    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(1).getMetadata()).containsKeys("key1", "key2", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(2).getMetadata()).containsKeys("key2", "key3", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(3).getMetadata()).containsKeys("key2", "key3", "parent_document_id", "chunk_index", "total_chunks");

    assertThat(chunks.get(0).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(1).getMetadata().get("chunk_index")).isEqualTo(1);
    assertThat(chunks.get(2).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(3).getMetadata().get("chunk_index")).isEqualTo(1);
    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2").doesNotContainKeys("key3");
    assertThat(chunks.get(2).getMetadata()).containsKeys("key2", "key3").doesNotContainKeys("key1");
}
"

File Path: /var/tmp/Roost/RoostGPT/spring-ai-test-timeout-pr/1e559eba-5752-4feb-88f7-63ae643c0140/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/document/ContentFormatterTests.java
Tests:
    "@Test
void shouldThrowWhenNeitherTextNorMediaAreSet() {
    assertThatThrownBy(() -> Document.builder().id("test-id").metadata("key", "value").build()).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("exactly one of text or media must be specified");
}
"
    "@Test
void builderWithCustomIdGenerator() {
    IdGenerator mockGenerator = mock(IdGenerator.class);
    when(mockGenerator.generateId("test text", Map.of("key", "value"))).thenReturn("generated-id");
    Document document = Document.builder().idGenerator(mockGenerator).text("test text").metadata("key", "value").build();
    assertThat(document.getId()).isEqualTo("generated-id");
}
"
    "@Test
void builderShouldThrowWhenIdGeneratorIsNull() {
    assertThatThrownBy(() -> Document.builder().idGenerator(null)).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("idGenerator cannot be null");
}
"
    "@Test
void builderShouldThrowWhenMetadataKeyIsNull() {
    assertThatThrownBy(() -> Document.builder().metadata(null, "value")).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("metadata key cannot be null");
}
"
    "@Test
void builderShouldThrowWhenMetadataValueIsNull() {
    assertThatThrownBy(() -> Document.builder().metadata("key", null)).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("metadata value cannot be null");
}
"
    "@Test
void scoreHandling() {
    Document document = Document.builder().text("test").score(0.85).build();
    assertThat(document.getScore()).isEqualTo(0.85);
    Document documentWithoutScore = new Document("test");
    assertThat(documentWithoutScore.getScore()).isNull();
}
"
    "@Test
void builderWithMetadataMap() {
    Map<String, Object> metadata = Map.of("key1", "value1", "key2", 1);
    Document document = Document.builder().text("test").metadata(metadata).build();
    assertThat(document.getMetadata()).containsExactlyInAnyOrderEntriesOf(metadata);
}
"

File Path: /var/tmp/Roost/RoostGPT/spring-ai-test-timeout-pr/1e559eba-5752-4feb-88f7-63ae643c0140/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/util/JacksonUtilsTests.java
Tests:
    "@Test
void usesCorrectClassLoader() throws JsonProcessingException, ClassNotFoundException {
    ClassLoader previousLoader = Thread.currentThread().getContextClassLoader();
    try {

        Thread.currentThread().setContextClassLoader(getClass().getClassLoader().getParent());

        var jsonMapper = JsonMapper.builder().addModules(JacksonUtils.instantiateAvailableModules()).build();
        Class<?> clazz = getClass().getClassLoader().loadClass(getClass().getName() + "$Cell");
        var output = jsonMapper.readValue("{\"name\":\"Amoeba\",\"lifespan\":\"PT42S\"}", clazz);
        assertThat(output).isEqualTo(new Cell("Amoeba", Duration.of(42L, ChronoUnit.SECONDS)));
    } finally {
        Thread.currentThread().setContextClassLoader(previousLoader);
    }
}
"

File Path: /var/tmp/Roost/RoostGPT/spring-ai-test-timeout-pr/1e559eba-5752-4feb-88f7-63ae643c0140/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/document/DocumentTests.java
Tests:
    "@Test
void testScore() {
    Double score = 0.95;
    Document document = Document.builder().text("Test content").score(score).build();
    assertThat(document.getScore()).isEqualTo(score);
}
"
    "@Test
void testNullScore() {
    Document document = Document.builder().text("Test content").score(null).build();
    assertThat(document.getScore()).isNull();
}
"
    "@Test
void testMutate() {
    Media media = getMedia();
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("key", "value");
    Double score = 0.95;
    Document original = Document.builder().id("customId").text("Test content").media(null).metadata(metadata).score(score).build();
    Document mutated = original.mutate().build();
    assertThat(mutated).isNotSameAs(original).usingRecursiveComparison().isEqualTo(original);
}
"
    "@Test
void testEquals() {
    Media media = getMedia();
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("key", "value");
    Double score = 0.95;
    Document doc1 = Document.builder().id("customId").text("Test text").metadata(metadata).score(score).build();
    Document doc2 = Document.builder().id("customId").text("Test text").metadata(metadata).score(score).build();
    Document differentDoc = Document.builder().id("differentId").text("Different content").metadata(metadata).score(score).build();
    assertThat(doc1).isEqualTo(doc2).isNotEqualTo(differentDoc).isNotEqualTo(null).isNotEqualTo(new Object());
    assertThat(doc1.hashCode()).isEqualTo(doc2.hashCode());
}
"
    "@Test
void testEmptyDocument() {
    assertThrows(IllegalArgumentException.class, () -> Document.builder().build());
}
"
    "@Test
void testToString() {
    Media media = getMedia();
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("key", "value");
    Double score = 0.95;
    Document document = Document.builder().id("customId").text("Test content").media(null).metadata(metadata).score(score).build();
    String toString = document.toString();
    assertThat(toString).contains("id='customId'").contains("text='Test content'").contains("metadata=" + metadata).contains("score=" + score);
}
"
    "@Test
void testMediaDocumentConstruction() {
    Media media = getMedia();
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("key", "value");
    Document document = Document.builder().media(media).metadata(metadata).build();
    assertThat(document.getMedia()).isEqualTo(media);
    assertThat(document.getText()).isNull();
    assertThat(document.isText()).isFalse();
}
"
    "@Test
void testTextDocumentConstruction() {
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("key", "value");
    Document document = Document.builder().text("Test text").metadata(metadata).build();
    assertThat(document.getText()).isEqualTo("Test text");
    assertThat(document.getMedia()).isNull();
    assertThat(document.isText()).isTrue();
}
"
    "@Test
void testBothTextAndMediaThrowsException() {
    Media media = getMedia();
    assertThrows(IllegalArgumentException.class, () -> Document.builder().text("Test text").media(media).build());
}
"
    "@Test
void testCustomIdGenerator() {
    IdGenerator customGenerator = contents -> "custom-" + contents[0];
    Document document = Document.builder().text("test").idGenerator(customGenerator).build();
    assertThat(document.getId()).isEqualTo("custom-test");
}
"
    "@Test
void testMetadataValidation() {
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("nullKey", null);
    assertThrows(IllegalArgumentException.class, () -> Document.builder().text("test").metadata(metadata).build());
}
"
    "@Test
void testFormattedContent() {
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("key", "value");
    Document document = Document.builder().text("Test text").metadata(metadata).build();
    String formattedContent = document.getFormattedContent(MetadataMode.ALL);
    assertThat(formattedContent).contains("Test text");
    assertThat(formattedContent).contains("key");
    assertThat(formattedContent).contains("value");
}
"
    "@Test
void testCustomFormattedContent() {
    Document document = Document.builder().text("Test text").build();
    ContentFormatter customFormatter = (doc, mode) -> "Custom: " + doc.getText();
    String formattedContent = document.getFormattedContent(customFormatter, MetadataMode.ALL);
    assertThat(formattedContent).isEqualTo("Custom: Test text");
}
"
    "@Test
void testNullIdThrowsException() {
    assertThrows(IllegalArgumentException.class, () -> Document.builder().id(null).text("test").build());
}
"
    "@Test
void testEmptyIdThrowsException() {
    assertThrows(IllegalArgumentException.class, () -> Document.builder().id("").text("test").build());
}
"
    "@Test
void testMetadataKeyValueAddition() {
    Document document = Document.builder().text("test").metadata("key1", "value1").metadata("key2", "value2").build();
    assertThat(document.getMetadata()).containsEntry("key1", "value1").containsEntry("key2", "value2");
}
"
    "@Test
private static Media getMedia() {
    return Media.builder().mimeType(MimeTypeUtils.IMAGE_JPEG).data(URI.create("http:
}
"
    "@Test
void testMetadataModeNone() {
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("secret", "hidden");
    Document document = Document.builder().text("Visible content").metadata(metadata).build();
    String formattedContent = document.getFormattedContent(MetadataMode.NONE);
    assertThat(formattedContent).contains("Visible content");
    assertThat(formattedContent).doesNotContain("secret");
    assertThat(formattedContent).doesNotContain("hidden");
}
"
    "@Test
void testMetadataModeEmbed() {
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("embedKey", "embedValue");
    metadata.put("filterKey", "filterValue");
    Document document = Document.builder().text("Test content").metadata(metadata).build();
    String formattedContent = document.getFormattedContent(MetadataMode.EMBED);


    assertThat(formattedContent).contains("Test content");
}
"
    "@Test
void testDocumentBuilderChaining() {
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("chain", "test");
    Document document = Document.builder().text("Chain test").metadata(metadata).metadata("additional", "value").score(0.85).build();
    assertThat(document.getText()).isEqualTo("Chain test");
    assertThat(document.getMetadata()).containsEntry("chain", "test");
    assertThat(document.getMetadata()).containsEntry("additional", "value");
    assertThat(document.getScore()).isEqualTo(0.85);
}
"
    "@Test
void testDocumentWithScoreGreaterThanOne() {
    Document document = Document.builder().text("High score test").score(1.5).build();
    assertThat(document.getScore()).isEqualTo(1.5);
}
"
    "@Test
void testMutateWithChanges() {
    Document original = Document.builder().text("Original text").score(0.5).metadata("original", "value").build();
    Document mutated = original.mutate().text("Mutated text").score(0.8).metadata("new", "metadata").build();
    assertThat(mutated.getText()).isEqualTo("Mutated text");
    assertThat(mutated.getScore()).isEqualTo(0.8);
    assertThat(mutated.getMetadata()).containsEntry("new", "metadata");

    assertThat(original.getText()).isEqualTo("Original text");
}
"
    "@Test
void testDocumentEqualityWithDifferentScores() {
    Document doc1 = Document.builder().id("sameId").text("Same text").score(0.5).build();
    Document doc2 = Document.builder().id("sameId").text("Same text").score(0.8).build();

    assertThat(doc1).isNotEqualTo(doc2);
}
"
    "@Test
void testDocumentWithComplexMetadata() {
    Map<String, Object> nestedMap = new HashMap<>();
    nestedMap.put("nested", "value");
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("string", "value");
    metadata.put("number", 1);
    metadata.put("boolean", true);
    metadata.put("map", nestedMap);
    Document document = Document.builder().text("Complex metadata test").metadata(metadata).build();
    assertThat(document.getMetadata()).containsEntry("string", "value");
    assertThat(document.getMetadata()).containsEntry("number", 1);
    assertThat(document.getMetadata()).containsEntry("boolean", true);
    assertThat(document.getMetadata()).containsEntry("map", nestedMap);
}
"
    "@Test
void testMetadataImmutability() {
    Map<String, Object> originalMetadata = new HashMap<>();
    originalMetadata.put("key", "value");
    Document document = Document.builder().text("Immutability test").metadata(originalMetadata).build();

    originalMetadata.put("key", "modified");
    originalMetadata.put("newKey", "newValue");

    assertThat(document.getMetadata()).containsEntry("key", "value");
    assertThat(document.getMetadata()).doesNotContainKey("newKey");
}
"
    "@Test
void testDocumentWithEmptyMetadata() {
    Document document = Document.builder().text("Empty metadata test").metadata(new HashMap<>()).build();
    assertThat(document.getMetadata()).isEmpty();
}
"
    "@Test
void testMetadataWithNullValueInMap() {
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("validKey", "validValue");
    metadata.put("nullKey", null);
    assertThrows(IllegalArgumentException.class, () -> Document.builder().text("test").metadata(metadata).build());
}
"
    "@Test
void testDocumentWithWhitespaceOnlyText() {
    String whitespaceText = "   \n\t\r   ";
    Document document = Document.builder().text(whitespaceText).build();
    assertThat(document.getText()).isEqualTo(whitespaceText);
    assertThat(document.isText()).isTrue();
}
"
    "@Test
void testDocumentHashCodeConsistency() {
    Document document = Document.builder().text("Hash test").metadata("key", "value").score(0.1).build();
    int hashCode1 = document.hashCode();
    int hashCode2 = document.hashCode();
    assertThat(hashCode1).isEqualTo(hashCode2);
}
"

File Path: /var/tmp/Roost/RoostGPT/spring-ai-test-timeout-pr/1e559eba-5752-4feb-88f7-63ae643c0140/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/transformer/splitter/TextSplitterTests.java
Tests:
    "@Test
public void testScorePreservation() {

    Double originalScore = 0.95;
    var doc = Document.builder().text("This is a test document that will be split into multiple chunks.").metadata(Map.of("source", "test.txt")).score(originalScore).build();

    List<Document> chunks = testTextSplitter.apply(List.of(doc));

    assertThat(chunks).hasSize(2);
    assertThat(chunks.get(0).getScore()).isEqualTo(originalScore);
    assertThat(chunks.get(1).getScore()).isEqualTo(originalScore);
}
"
    "@Test
public void testEnhancedMetadataWithMultipleDocuments() {

    var doc1 = Document.builder().text("First document with score and metadata.").metadata(Map.of("type", "article", "priority", "high")).score(0.8).build();
    var doc2 = Document.builder().text("Second document with different score.").metadata(Map.of("type", "report", "priority", "medium")).score(0.6).build();
    String originalId1 = doc1.getId();
    String originalId2 = doc2.getId();

    List<Document> chunks = testTextSplitter.apply(List.of(doc1, doc2));

    assertThat(chunks).hasSize(4);

    for (int i = 0; i < 2; i++) {
        Document chunk = chunks.get(i);
        assertThat(chunk.getScore()).isEqualTo(0.8);
        assertThat(chunk.getMetadata().get("parent_document_id")).isEqualTo(originalId1);
        assertThat(chunk.getMetadata().get("chunk_index")).isEqualTo(i);
        assertThat(chunk.getMetadata().get("total_chunks")).isEqualTo(2);
        assertThat(chunk.getMetadata().get("type")).isEqualTo("article");
        assertThat(chunk.getMetadata().get("priority")).isEqualTo("high");
    }

    for (int i = 2; i < 4; i++) {
        Document chunk = chunks.get(i);
        assertThat(chunk.getScore()).isEqualTo(0.6);
        assertThat(chunk.getMetadata().get("parent_document_id")).isEqualTo(originalId2);
        assertThat(chunk.getMetadata().get("chunk_index")).isEqualTo(i - 2);
        assertThat(chunk.getMetadata().get("total_chunks")).isEqualTo(2);
        assertThat(chunk.getMetadata().get("type")).isEqualTo("report");
        assertThat(chunk.getMetadata().get("priority")).isEqualTo("medium");
    }
}
"

File Path: /var/tmp/Roost/RoostGPT/spring-ai-test-timeout-pr/1e559eba-5752-4feb-88f7-63ae643c0140/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/observation/AiOperationMetadataTests.java
Tests:
    "@Test
void whenMandatoryMetadataThenReturn() {
    var operationMetadata = AiOperationMetadata.builder().operationType("chat").provider("doofenshmirtz").build();
    assertThat(operationMetadata).isNotNull();
}
"
    "@Test
void whenOperationTypeIsNullThenThrow() {
    assertThatThrownBy(() -> AiOperationMetadata.builder().provider("doofenshmirtz").build()).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("operationType cannot be null or empty");
}
"
    "@Test
void whenOperationTypeIsEmptyThenThrow() {
    assertThatThrownBy(() -> AiOperationMetadata.builder().operationType("").provider("doofenshmirtz").build()).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("operationType cannot be null or empty");
}
"
    "@Test
void whenProviderIsNullThenThrow() {
    assertThatThrownBy(() -> AiOperationMetadata.builder().operationType("chat").build()).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("provider cannot be null or empty");
}
"
    "@Test
void whenProviderIsEmptyThenThrow() {
    assertThatThrownBy(() -> AiOperationMetadata.builder().operationType("chat").provider("").build()).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("provider cannot be null or empty");
}
"
    "@Test
void whenOperationTypeIsBlankThenThrow() {
    assertThatThrownBy(() -> AiOperationMetadata.builder().operationType("   ").provider("doofenshmirtz").build()).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("operationType cannot be null or empty");
}
"
    "@Test
void whenProviderIsBlankThenThrow() {
    assertThatThrownBy(() -> AiOperationMetadata.builder().operationType("chat").provider("   ").build()).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("provider cannot be null or empty");
}
"
    "@Test
void whenBuiltWithValidValuesThenFieldsAreAccessible() {
    var operationMetadata = AiOperationMetadata.builder().operationType("chat").provider("openai").build();
    assertThat(operationMetadata.operationType()).isEqualTo("chat");
    assertThat(operationMetadata.provider()).isEqualTo("openai");
}
"

File Path: /var/tmp/Roost/RoostGPT/spring-ai-test-timeout-pr/1e559eba-5752-4feb-88f7-63ae643c0140/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/writer/FileDocumentWriterTest.java
Tests:
    "@Test
void setUp() {
    this.testFileName = this.tempDir.resolve("file-document-test-output.txt").toString();
    this.testDocuments = List.of(Document.builder().text("Document one introduces the core functionality of Spring AI.").metadata("page_number", "1").metadata("end_page_number", "2").metadata("source", "intro.pdf").metadata("title", "Spring AI Overview").metadata("author", "QA Team").build(), Document.builder().text("Document two illustrates multi-line handling and line breaks.\nEnsure preservation of formatting.").metadata("page_number", "3").metadata("end_page_number", "4").metadata("source", "formatting.pdf").build(), Document.builder().text("Document three checks metadata inclusion and output formatting behavior.").metadata("page_number", "5").metadata("end_page_number", "6").metadata("version", "v1.2").build());
}
"

File Path: /var/tmp/Roost/RoostGPT/spring-ai-test-timeout-pr/1e559eba-5752-4feb-88f7-63ae643c0140/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/document/DocumentBuilderTests.java
Tests:
    "@Test
private static Media getMedia() {
    return Media.builder().data(URI.create("http:
}
"
    "@Test
void setUp() {
    this.builder = Document.builder();
}
"
    "@Test
void testWithMediaSingle() {
    Media media = Media.builder().mimeType(MimeTypeUtils.IMAGE_JPEG).data(URI.create("http:
    Document.Builder result = this.builder.media(media);
    assertThat(result).isSameAs(this.builder);
    assertThat(result.build().getMedia()).isEqualTo(media);
}
"Scenario 1: Verify builder() returns a new Builder instance

Details:
  TestName: builderReturnsNewBuilderInstance
  Description: Verify that the static builder() method returns a non-null Builder instance that can be used to construct a DefaultContentFormatter.
Execution:
  Arrange: No setup required.
  Act: Call DefaultContentFormatter.builder() to obtain a Builder instance.
  Assert: Verify that the returned Builder is not null.
Validation:
  The assertion confirms that the builder() method successfully creates and returns a Builder object. This is fundamental for the builder pattern implementation, ensuring clients can start constructing DefaultContentFormatter instances.

Scenario 2: Verify builder() returns a new instance on each call

Details:
  TestName: builderReturnsDistinctInstancesOnEachCall
  Description: Verify that each call to builder() returns a different Builder instance, ensuring no shared state between builder instances.
Execution:
  Arrange: No setup required.
  Act: Call DefaultContentFormatter.builder() twice to obtain two Builder instances.
  Assert: Verify that the two Builder instances are not the same object reference.
Validation:
  This test ensures that the builder pattern is correctly implemented with each call creating a fresh Builder instance. This prevents unintended side effects from shared builder state across different construction operations.

Scenario 3: Verify builder can create DefaultContentFormatter with default configuration

Details:
  TestName: builderCreatesDefaultContentFormatterWithDefaultValues
  Description: Verify that a Builder obtained from builder() can successfully create a DefaultContentFormatter with default configuration values.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Call build() on the Builder to create a DefaultContentFormatter.
  Assert: Verify that the resulting DefaultContentFormatter is not null and has expected default values for metadataTemplate, metadataSeparator, and textTemplate.
Validation:
  This test confirms that the builder pattern works end-to-end, creating a properly configured DefaultContentFormatter with default values when no customizations are applied.

Scenario 4: Verify builder allows method chaining for configuration

Details:
  TestName: builderSupportsMethodChainingForConfiguration
  Description: Verify that the Builder returned by builder() supports fluent method chaining for setting various configuration options.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Chain multiple configuration methods (withMetadataTemplate, withMetadataSeparator, withTextTemplate) and call build().
  Assert: Verify that the resulting DefaultContentFormatter has the configured values.
Validation:
  This test validates the fluent API design of the Builder, ensuring that configuration methods return the Builder instance for chaining, which improves code readability and usability.

Scenario 5: Verify builder creates independent DefaultContentFormatter instances

Details:
  TestName: builderCreatesIndependentFormatterInstances
  Description: Verify that multiple DefaultContentFormatter instances created from separate builders are independent and do not share state.
Execution:
  Arrange: Create two separate Builder instances using DefaultContentFormatter.builder().
  Act: Configure each builder differently and build two DefaultContentFormatter instances.
  Assert: Verify that the two formatters have different configurations and are not the same instance.
Validation:
  This test ensures that the builder pattern correctly isolates configuration between different formatter instances, preventing unintended state sharing.

Scenario 6: Verify builder with custom metadata template

Details:
  TestName: builderWithCustomMetadataTemplate
  Description: Verify that a Builder can be configured with a custom metadata template and the resulting formatter uses it.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Call withMetadataTemplate with a custom template string and build the formatter.
  Assert: Verify that getMetadataTemplate() returns the custom template.
Validation:
  This test confirms that the builder correctly applies custom metadata template configuration, which is essential for customizing how metadata is formatted in documents.

Scenario 7: Verify builder with custom metadata separator

Details:
  TestName: builderWithCustomMetadataSeparator
  Description: Verify that a Builder can be configured with a custom metadata separator and the resulting formatter uses it.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Call withMetadataSeparator with a custom separator string and build the formatter.
  Assert: Verify that getMetadataSeparator() returns the custom separator.
Validation:
  This test confirms that the builder correctly applies custom metadata separator configuration, allowing flexibility in how metadata entries are separated.

Scenario 8: Verify builder with custom text template

Details:
  TestName: builderWithCustomTextTemplate
  Description: Verify that a Builder can be configured with a custom text template and the resulting formatter uses it.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Call withTextTemplate with a custom template string and build the formatter.
  Assert: Verify that getTextTemplate() returns the custom template.
Validation:
  This test confirms that the builder correctly applies custom text template configuration, enabling customization of the overall document format.

Scenario 9: Verify builder with excluded inference metadata keys as list

Details:
  TestName: builderWithExcludedInferenceMetadataKeysAsList
  Description: Verify that a Builder can be configured with a list of excluded inference metadata keys.
Execution:
  Arrange: Obtain a Builder instance and create a list of metadata keys to exclude.
  Act: Call withExcludedInferenceMetadataKeys with the list and build the formatter.
  Assert: Verify that getExcludedInferenceMetadataKeys() returns the configured keys.
Validation:
  This test ensures that inference metadata exclusion can be configured via a list, which is important for controlling what metadata appears during inference operations.

Scenario 10: Verify builder with excluded inference metadata keys as varargs

Details:
  TestName: builderWithExcludedInferenceMetadataKeysAsVarargs
  Description: Verify that a Builder can be configured with excluded inference metadata keys using varargs.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Call withExcludedInferenceMetadataKeys with multiple string arguments and build the formatter.
  Assert: Verify that getExcludedInferenceMetadataKeys() contains all the specified keys.
Validation:
  This test confirms the convenience varargs method works correctly for excluding inference metadata keys.

Scenario 11: Verify builder with excluded embed metadata keys as list

Details:
  TestName: builderWithExcludedEmbedMetadataKeysAsList
  Description: Verify that a Builder can be configured with a list of excluded embed metadata keys.
Execution:
  Arrange: Obtain a Builder instance and create a list of metadata keys to exclude.
  Act: Call withExcludedEmbedMetadataKeys with the list and build the formatter.
  Assert: Verify that getExcludedEmbedMetadataKeys() returns the configured keys.
Validation:
  This test ensures that embed metadata exclusion can be configured via a list, controlling what metadata appears during embedding operations.

Scenario 12: Verify builder with excluded embed metadata keys as varargs

Details:
  TestName: builderWithExcludedEmbedMetadataKeysAsVarargs
  Description: Verify that a Builder can be configured with excluded embed metadata keys using varargs.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Call withExcludedEmbedMetadataKeys with multiple string arguments and build the formatter.
  Assert: Verify that getExcludedEmbedMetadataKeys() contains all the specified keys.
Validation:
  This test confirms the convenience varargs method works correctly for excluding embed metadata keys.

Scenario 13: Verify builder from existing formatter copies configuration

Details:
  TestName: builderFromExistingFormatterCopiesConfiguration
  Description: Verify that a Builder can be initialized from an existing DefaultContentFormatter and copies all its configuration.
Execution:
  Arrange: Create a DefaultContentFormatter with custom configuration using builder().
  Act: Create a new Builder using builder() and call from() with the existing formatter, then build.
  Assert: Verify that the new formatter has the same configuration as the original.
Validation:
  This test ensures the from() method correctly copies all configuration from an existing formatter, enabling easy creation of modified copies.

Scenario 14: Verify builder throws exception for empty metadata template

Details:
  TestName: builderThrowsExceptionForEmptyMetadataTemplate
  Description: Verify that the Builder throws an IllegalArgumentException when withMetadataTemplate is called with an empty string.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Call withMetadataTemplate with an empty string.
  Assert: Verify that an IllegalArgumentException is thrown with appropriate message.
Validation:
  This test ensures proper validation of the metadata template, preventing invalid configurations that would cause issues during formatting.

Scenario 15: Verify builder throws exception for null metadata separator

Details:
  TestName: builderThrowsExceptionForNullMetadataSeparator
  Description: Verify that the Builder throws an IllegalArgumentException when withMetadataSeparator is called with null.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Call withMetadataSeparator with null.
  Assert: Verify that an IllegalArgumentException is thrown.
Validation:
  This test ensures proper null validation for the metadata separator configuration.

Scenario 16: Verify builder throws exception for empty text template

Details:
  TestName: builderThrowsExceptionForEmptyTextTemplate
  Description: Verify that the Builder throws an IllegalArgumentException when withTextTemplate is called with an empty string.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Call withTextTemplate with an empty string.
  Assert: Verify that an IllegalArgumentException is thrown with appropriate message.
Validation:
  This test ensures proper validation of the text template, preventing invalid configurations.

Scenario 17: Verify builder throws exception for null excluded inference metadata keys list

Details:
  TestName: builderThrowsExceptionForNullExcludedInferenceMetadataKeysList
  Description: Verify that the Builder throws an IllegalArgumentException when withExcludedInferenceMetadataKeys is called with a null list.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Call withExcludedInferenceMetadataKeys with null list.
  Assert: Verify that an IllegalArgumentException is thrown.
Validation:
  This test ensures proper null validation for excluded inference metadata keys configuration.

Scenario 18: Verify builder throws exception for null excluded embed metadata keys list

Details:
  TestName: builderThrowsExceptionForNullExcludedEmbedMetadataKeysList
  Description: Verify that the Builder throws an IllegalArgumentException when withExcludedEmbedMetadataKeys is called with a null list.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Call withExcludedEmbedMetadataKeys with null list.
  Assert: Verify that an IllegalArgumentException is thrown.
Validation:
  This test ensures proper null validation for excluded embed metadata keys configuration.

Scenario 19: Verify builder allows empty metadata separator

Details:
  TestName: builderAllowsEmptyMetadataSeparator
  Description: Verify that the Builder accepts an empty string as a valid metadata separator.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Call withMetadataSeparator with an empty string and build the formatter.
  Assert: Verify that getMetadataSeparator() returns an empty string.
Validation:
  This test confirms that empty string is a valid separator value, which may be useful when no separation is desired between metadata entries.

Scenario 20: Verify builder accumulates excluded inference metadata keys from multiple calls

Details:
  TestName: builderAccumulatesExcludedInferenceMetadataKeysFromMultipleCalls
  Description: Verify that multiple calls to withExcludedInferenceMetadataKeys with varargs accumulate the keys.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Call withExcludedInferenceMetadataKeys multiple times with different keys and build.
  Assert: Verify that getExcludedInferenceMetadataKeys() contains all keys from all calls.
Validation:
  This test ensures that the varargs method adds to the existing list rather than replacing it, allowing incremental configuration.

Scenario 21: Verify builder accumulates excluded embed metadata keys from multiple calls

Details:
  TestName: builderAccumulatesExcludedEmbedMetadataKeysFromMultipleCalls
  Description: Verify that multiple calls to withExcludedEmbedMetadataKeys with varargs accumulate the keys.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Call withExcludedEmbedMetadataKeys multiple times with different keys and build.
  Assert: Verify that getExcludedEmbedMetadataKeys() contains all keys from all calls.
Validation:
  This test ensures that the varargs method adds to the existing list rather than replacing it.

Scenario 22: Verify builder returns immutable excluded inference metadata keys list

Details:
  TestName: builderReturnsImmutableExcludedInferenceMetadataKeysList
  Description: Verify that the list returned by getExcludedInferenceMetadataKeys() is immutable.
Execution:
  Arrange: Create a DefaultContentFormatter with excluded inference metadata keys.
  Act: Attempt to modify the list returned by getExcludedInferenceMetadataKeys().
  Assert: Verify that an UnsupportedOperationException is thrown.
Validation:
  This test ensures that the formatter's internal state cannot be modified after construction, maintaining immutability.

Scenario 23: Verify builder returns immutable excluded embed metadata keys list

Details:
  TestName: builderReturnsImmutableExcludedEmbedMetadataKeysList
  Description: Verify that the list returned by getExcludedEmbedMetadataKeys() is immutable.
Execution:
  Arrange: Create a DefaultContentFormatter with excluded embed metadata keys.
  Act: Attempt to modify the list returned by getExcludedEmbedMetadataKeys().
  Assert: Verify that an UnsupportedOperationException is thrown.
Validation:
  This test ensures that the formatter's internal state cannot be modified after construction.

Scenario 24: Verify builder with all configuration options set

Details:
  TestName: builderWithAllConfigurationOptionsSet
  Description: Verify that a Builder can be configured with all available options and produces a correctly configured formatter.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Configure all options (metadataTemplate, metadataSeparator, textTemplate, excludedInferenceMetadataKeys, excludedEmbedMetadataKeys) and build.
  Assert: Verify that all getter methods return the configured values.
Validation:
  This comprehensive test ensures that all configuration options work together correctly when fully specified.

*/

// ********RoostGPT********

package org.springframework.ai.document;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.util.Assert;

class DefaultContentFormatterBuilderTest {

	@Test
	@Tag("valid")
	void builderReturnsNewBuilderInstance() {
		// Arrange - No setup required

		// Act
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Assert
		assertNotNull(builder);
	}

	@Test
	@Tag("valid")
	void builderReturnsDistinctInstancesOnEachCall() {
		// Arrange - No setup required

		// Act
		DefaultContentFormatter.Builder builder1 = DefaultContentFormatter.builder();
		DefaultContentFormatter.Builder builder2 = DefaultContentFormatter.builder();

		// Assert
		assertNotSame(builder1, builder2);
	}

	@Test
	@Tag("valid")
	void builderCreatesDefaultContentFormatterWithDefaultValues() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act
		DefaultContentFormatter formatter = builder.build();

		// Assert
		assertNotNull(formatter);
		assertNotNull(formatter.getMetadataTemplate());
		assertNotNull(formatter.getMetadataSeparator());
		assertNotNull(formatter.getTextTemplate());
		assertEquals("{key}: {value}", formatter.getMetadataTemplate());
		assertEquals(System.lineSeparator(), formatter.getMetadataSeparator());
		assertEquals("{metadata_string}\n\n{content}", formatter.getTextTemplate());
	}

	@Test
	@Tag("valid")
	void builderSupportsMethodChainingForConfiguration() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();
		String customMetadataTemplate = "Key={key}, Value={value}";
		String customMetadataSeparator = " | ";
		String customTextTemplate = "Content: {content} - Metadata: {metadata_string}";

		// Act
		DefaultContentFormatter formatter = builder.withMetadataTemplate(customMetadataTemplate)
			.withMetadataSeparator(customMetadataSeparator)
			.withTextTemplate(customTextTemplate)
			.build();

		// Assert
		assertEquals(customMetadataTemplate, formatter.getMetadataTemplate());
		assertEquals(customMetadataSeparator, formatter.getMetadataSeparator());
		assertEquals(customTextTemplate, formatter.getTextTemplate());
	}

	@Test
	@Tag("valid")
	void builderCreatesIndependentFormatterInstances() {
		// Arrange
		DefaultContentFormatter.Builder builder1 = DefaultContentFormatter.builder();
		DefaultContentFormatter.Builder builder2 = DefaultContentFormatter.builder();

		// Act
		DefaultContentFormatter formatter1 = builder1.withMetadataTemplate("Template1: {key}={value}").build();
		DefaultContentFormatter formatter2 = builder2.withMetadataTemplate("Template2: {key}-{value}").build();

		// Assert
		assertNotSame(formatter1, formatter2);
		assertNotEquals(formatter1.getMetadataTemplate(), formatter2.getMetadataTemplate());
	}

	@Test
	@Tag("valid")
	void builderWithCustomMetadataTemplate() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();
		String customTemplate = "CustomKey={key}, CustomValue={value}";

		// Act
		DefaultContentFormatter formatter = builder.withMetadataTemplate(customTemplate).build();

		// Assert
		assertEquals(customTemplate, formatter.getMetadataTemplate());
	}

	@Test
	@Tag("valid")
	void builderWithCustomMetadataSeparator() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();
		String customSeparator = " || ";

		// Act
		DefaultContentFormatter formatter = builder.withMetadataSeparator(customSeparator).build();

		// Assert
		assertEquals(customSeparator, formatter.getMetadataSeparator());
	}

	@Test
	@Tag("valid")
	void builderWithCustomTextTemplate() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();
		String customTextTemplate = "Document: {content}\nMeta: {metadata_string}";

		// Act
		DefaultContentFormatter formatter = builder.withTextTemplate(customTextTemplate).build();

		// Assert
		assertEquals(customTextTemplate, formatter.getTextTemplate());
	}

	@Test
	@Tag("valid")
	void builderWithExcludedInferenceMetadataKeysAsList() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();
		List<String> excludedKeys = Arrays.asList("key1", "key2", "key3");

		// Act
		DefaultContentFormatter formatter = builder.withExcludedInferenceMetadataKeys(excludedKeys).build();

		// Assert
		assertEquals(excludedKeys, formatter.getExcludedInferenceMetadataKeys());
	}

	@Test
	@Tag("valid")
	void builderWithExcludedInferenceMetadataKeysAsVarargs() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act
		DefaultContentFormatter formatter = builder.withExcludedInferenceMetadataKeys("keyA", "keyB", "keyC").build();

		// Assert
		List<String> excludedKeys = formatter.getExcludedInferenceMetadataKeys();
		assertTrue(excludedKeys.contains("keyA"));
		assertTrue(excludedKeys.contains("keyB"));
		assertTrue(excludedKeys.contains("keyC"));
	}

	@Test
	@Tag("valid")
	void builderWithExcludedEmbedMetadataKeysAsList() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();
		List<String> excludedKeys = Arrays.asList("embedKey1", "embedKey2");

		// Act
		DefaultContentFormatter formatter = builder.withExcludedEmbedMetadataKeys(excludedKeys).build();

		// Assert
		assertEquals(excludedKeys, formatter.getExcludedEmbedMetadataKeys());
	}

	@Test
	@Tag("valid")
	void builderWithExcludedEmbedMetadataKeysAsVarargs() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act
		DefaultContentFormatter formatter = builder.withExcludedEmbedMetadataKeys("embedA", "embedB").build();

		// Assert
		List<String> excludedKeys = formatter.getExcludedEmbedMetadataKeys();
		assertTrue(excludedKeys.contains("embedA"));
		assertTrue(excludedKeys.contains("embedB"));
	}

	@Test
	@Tag("valid")
	void builderFromExistingFormatterCopiesConfiguration() {
		// Arrange
		String customMetadataTemplate = "Custom: {key}={value}";
		String customMetadataSeparator = " ; ";
		String customTextTemplate = "Text: {content} | Meta: {metadata_string}";
		List<String> inferenceKeys = Arrays.asList("inf1", "inf2");
		List<String> embedKeys = Arrays.asList("emb1", "emb2");

		DefaultContentFormatter originalFormatter = DefaultContentFormatter.builder()
			.withMetadataTemplate(customMetadataTemplate)
			.withMetadataSeparator(customMetadataSeparator)
			.withTextTemplate(customTextTemplate)
			.withExcludedInferenceMetadataKeys(inferenceKeys)
			.withExcludedEmbedMetadataKeys(embedKeys)
			.build();

		// Act
		DefaultContentFormatter copiedFormatter = DefaultContentFormatter.builder().from(originalFormatter).build();

		// Assert
		assertEquals(originalFormatter.getMetadataTemplate(), copiedFormatter.getMetadataTemplate());
		assertEquals(originalFormatter.getMetadataSeparator(), copiedFormatter.getMetadataSeparator());
		assertEquals(originalFormatter.getTextTemplate(), copiedFormatter.getTextTemplate());
		assertEquals(originalFormatter.getExcludedInferenceMetadataKeys(),
				copiedFormatter.getExcludedInferenceMetadataKeys());
		assertEquals(originalFormatter.getExcludedEmbedMetadataKeys(), copiedFormatter.getExcludedEmbedMetadataKeys());
	}

	@Test
	@Tag("invalid")
	void builderThrowsExceptionForEmptyMetadataTemplate() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> {
			builder.withMetadataTemplate("");
		});
	}

	@Test
	@Tag("invalid")
	void builderThrowsExceptionForNullMetadataSeparator() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> {
			builder.withMetadataSeparator(null);
		});
	}

	@Test
	@Tag("invalid")
	void builderThrowsExceptionForEmptyTextTemplate() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> {
			builder.withTextTemplate("");
		});
	}

	@Test
	@Tag("invalid")
	void builderThrowsExceptionForNullExcludedInferenceMetadataKeysList() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> {
			builder.withExcludedInferenceMetadataKeys((List<String>) null);
		});
	}

	@Test
	@Tag("invalid")
	void builderThrowsExceptionForNullExcludedEmbedMetadataKeysList() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> {
			builder.withExcludedEmbedMetadataKeys((List<String>) null);
		});
	}

	@Test
	@Tag("boundary")
	void builderAllowsEmptyMetadataSeparator() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act
		DefaultContentFormatter formatter = builder.withMetadataSeparator("").build();

		// Assert
		assertEquals("", formatter.getMetadataSeparator());
	}

	@Test
	@Tag("valid")
	void builderAccumulatesExcludedInferenceMetadataKeysFromMultipleCalls() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act
		DefaultContentFormatter formatter = builder.withExcludedInferenceMetadataKeys("key1", "key2")
			.withExcludedInferenceMetadataKeys("key3", "key4")
			.build();

		// Assert
		List<String> excludedKeys = formatter.getExcludedInferenceMetadataKeys();
		assertTrue(excludedKeys.contains("key1"));
		assertTrue(excludedKeys.contains("key2"));
		assertTrue(excludedKeys.contains("key3"));
		assertTrue(excludedKeys.contains("key4"));
	}

	@Test
	@Tag("valid")
	void builderAccumulatesExcludedEmbedMetadataKeysFromMultipleCalls() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act
		DefaultContentFormatter formatter = builder.withExcludedEmbedMetadataKeys("embedKey1", "embedKey2")
			.withExcludedEmbedMetadataKeys("embedKey3")
			.build();

		// Assert
		List<String> excludedKeys = formatter.getExcludedEmbedMetadataKeys();
		assertTrue(excludedKeys.contains("embedKey1"));
		assertTrue(excludedKeys.contains("embedKey2"));
		assertTrue(excludedKeys.contains("embedKey3"));
	}

	@Test
	@Tag("valid")
	void builderReturnsImmutableExcludedInferenceMetadataKeysList() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys("key1", "key2")
			.build();

		// Act & Assert
		List<String> excludedKeys = formatter.getExcludedInferenceMetadataKeys();
		assertThrows(UnsupportedOperationException.class, () -> {
			excludedKeys.add("newKey");
		});
	}

	@Test
	@Tag("valid")
	void builderReturnsImmutableExcludedEmbedMetadataKeysList() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedEmbedMetadataKeys("embedKey1")
			.build();

		// Act & Assert
		List<String> excludedKeys = formatter.getExcludedEmbedMetadataKeys();
		assertThrows(UnsupportedOperationException.class, () -> {
			excludedKeys.add("newEmbedKey");
		});
	}

	@Test
	@Tag("integration")
	void builderWithAllConfigurationOptionsSet() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();
		String customMetadataTemplate = "META[{key}]={value}";
		String customMetadataSeparator = " | ";
		String customTextTemplate = "CONTENT:{content}\nMETADATA:{metadata_string}";
		List<String> inferenceKeys = Arrays.asList("inferenceKey1", "inferenceKey2");
		List<String> embedKeys = Arrays.asList("embedKey1", "embedKey2", "embedKey3");

		// Act
		DefaultContentFormatter formatter = builder.withMetadataTemplate(customMetadataTemplate)
			.withMetadataSeparator(customMetadataSeparator)
			.withTextTemplate(customTextTemplate)
			.withExcludedInferenceMetadataKeys(inferenceKeys)
			.withExcludedEmbedMetadataKeys(embedKeys)
			.build();

		// Assert
		assertEquals(customMetadataTemplate, formatter.getMetadataTemplate());
		assertEquals(customMetadataSeparator, formatter.getMetadataSeparator());
		assertEquals(customTextTemplate, formatter.getTextTemplate());
		assertEquals(inferenceKeys, formatter.getExcludedInferenceMetadataKeys());
		assertEquals(embedKeys, formatter.getExcludedEmbedMetadataKeys());
	}

}