/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test spring-ai-test-timeout-pr using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=getTextTemplate_29241066d9
ROOST_METHOD_SIG_HASH=getTextTemplate_a49df0ad9f

Scenario 1: Verify getTextTemplate returns default text template when using default configuration

Details:
  TestName: getTextTemplateReturnsDefaultTemplateWhenUsingDefaultConfig
  Description: This test verifies that when a DefaultContentFormatter is created using the default configuration (via defaultConfig() method), the getTextTemplate() method returns the expected default text template which contains both metadata_string and content placeholders.

Execution:
  Arrange: Create a DefaultContentFormatter instance using the defaultConfig() static method.
  Act: Invoke the getTextTemplate() method on the formatter instance.
  Assert: Verify that the returned string equals the expected default template format "{metadata_string}\n\n{content}".

Validation:
  The assertion confirms that the default text template is correctly initialized with the expected format containing both placeholders. This is significant because the default template defines how document content and metadata are combined for output, which is essential for proper document formatting in the application.

---

Scenario 2: Verify getTextTemplate returns custom text template when configured via builder

Details:
  TestName: getTextTemplateReturnsCustomTemplateWhenConfiguredViaBuilder
  Description: This test verifies that when a custom text template is provided through the builder's withTextTemplate() method, the getTextTemplate() method returns that custom template.

Execution:
  Arrange: Create a DefaultContentFormatter instance using the builder pattern with a custom text template such as "Custom: {content} - {metadata_string}".
  Act: Invoke the getTextTemplate() method on the formatter instance.
  Assert: Verify that the returned string equals the custom template "Custom: {content} - {metadata_string}".

Validation:
  The assertion confirms that custom text templates are properly stored and retrieved. This is important for applications that need to customize how document content is formatted, allowing flexibility in output presentation.

---

Scenario 3: Verify getTextTemplate returns template with only content placeholder

Details:
  TestName: getTextTemplateReturnsTemplateWithOnlyContentPlaceholder
  Description: This test verifies that the getTextTemplate() method correctly returns a text template that contains only the content placeholder without the metadata_string placeholder.

Execution:
  Arrange: Create a DefaultContentFormatter instance using the builder with a text template containing only "{content}".
  Act: Invoke the getTextTemplate() method on the formatter instance.
  Assert: Verify that the returned string equals "{content}".

Validation:
  The assertion confirms that templates without metadata placeholders are supported. This is useful when users want to format documents without including any metadata information in the output.

---

Scenario 4: Verify getTextTemplate returns template with only metadata placeholder

Details:
  TestName: getTextTemplateReturnsTemplateWithOnlyMetadataPlaceholder
  Description: This test verifies that the getTextTemplate() method correctly returns a text template that contains only the metadata_string placeholder without the content placeholder.

Execution:
  Arrange: Create a DefaultContentFormatter instance using the builder with a text template containing only "{metadata_string}".
  Act: Invoke the getTextTemplate() method on the formatter instance.
  Assert: Verify that the returned string equals "{metadata_string}".

Validation:
  The assertion confirms that templates without content placeholders are supported. This scenario covers edge cases where only metadata needs to be displayed.

---

Scenario 5: Verify getTextTemplate returns template with special characters

Details:
  TestName: getTextTemplateReturnsTemplateWithSpecialCharacters
  Description: This test verifies that the getTextTemplate() method correctly returns a text template containing special characters such as newlines, tabs, and unicode characters.

Execution:
  Arrange: Create a DefaultContentFormatter instance using the builder with a text template containing special characters like "Header:\t{metadata_string}\n---\n{content}\n===".
  Act: Invoke the getTextTemplate() method on the formatter instance.
  Assert: Verify that the returned string equals "Header:\t{metadata_string}\n---\n{content}\n===".

Validation:
  The assertion confirms that special characters in templates are preserved correctly. This is important for maintaining formatting integrity when templates include whitespace characters or other special formatting.

---

Scenario 6: Verify getTextTemplate returns empty string when configured with empty template

Details:
  TestName: getTextTemplateReturnsEmptyStringWhenConfiguredWithEmptyTemplate
  Description: This test verifies the behavior when attempting to configure an empty text template. Based on the builder's validation using Assert.hasText, this should throw an exception.

Execution:
  Arrange: Attempt to create a DefaultContentFormatter instance using the builder with an empty string "" as the text template.
  Act: Invoke the withTextTemplate("") method on the builder.
  Assert: Verify that an IllegalArgumentException is thrown with an appropriate message.

Validation:
  The assertion confirms that the builder properly validates input and prevents empty text templates. This is important for ensuring that the formatter always has a valid template to work with.

---

Scenario 7: Verify getTextTemplate returns same value on multiple invocations

Details:
  TestName: getTextTemplateReturnsSameValueOnMultipleInvocations
  Description: This test verifies that calling getTextTemplate() multiple times on the same formatter instance returns the same value consistently, confirming the immutability of the text template.

Execution:
  Arrange: Create a DefaultContentFormatter instance with a specific text template.
  Act: Invoke the getTextTemplate() method multiple times (e.g., three times) on the same formatter instance.
  Assert: Verify that all returned values are equal to each other and to the expected template.

Validation:
  The assertion confirms that the text template is immutable and consistent across multiple calls. This is important for thread safety and predictable behavior in concurrent environments.

---

Scenario 8: Verify getTextTemplate after using builder from() method

Details:
  TestName: getTextTemplateReturnsCorrectValueAfterUsingBuilderFromMethod
  Description: This test verifies that when creating a new formatter using the builder's from() method to copy settings from an existing formatter, the getTextTemplate() returns the same text template as the source formatter.

Execution:
  Arrange: Create an initial DefaultContentFormatter with a custom text template. Then create a second formatter using builder().from(firstFormatter).build().
  Act: Invoke getTextTemplate() on both formatter instances.
  Assert: Verify that both formatters return the same text template value.

Validation:
  The assertion confirms that the from() method correctly copies the text template from the source formatter. This is important for creating modified copies of formatters while preserving certain settings.

---

Scenario 9: Verify getTextTemplate with template containing multiple placeholder occurrences

Details:
  TestName: getTextTemplateReturnsTemplateWithMultiplePlaceholderOccurrences
  Description: This test verifies that the getTextTemplate() method correctly returns a text template that contains multiple occurrences of the same placeholder.

Execution:
  Arrange: Create a DefaultContentFormatter instance using the builder with a text template like "{content} - {metadata_string} - {content}".
  Act: Invoke the getTextTemplate() method on the formatter instance.
  Assert: Verify that the returned string equals "{content} - {metadata_string} - {content}".

Validation:
  The assertion confirms that templates with repeated placeholders are stored and retrieved correctly. This tests an edge case where users might want to repeat content in their output format.

---

Scenario 10: Verify getTextTemplate with very long template string

Details:
  TestName: getTextTemplateReturnsVeryLongTemplateString
  Description: This test verifies that the getTextTemplate() method correctly handles and returns a very long text template string without truncation or modification.

Execution:
  Arrange: Create a DefaultContentFormatter instance using the builder with a very long text template (e.g., 1000+ characters including placeholders and filler text).
  Act: Invoke the getTextTemplate() method on the formatter instance.
  Assert: Verify that the returned string equals the exact long template that was configured.

Validation:
  The assertion confirms that there are no length limitations on the text template and that long strings are handled correctly. This is important for applications that may require complex or verbose template formats.

*/

// ********RoostGPT********

package org.springframework.ai.document;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.util.Assert;

class DefaultContentFormatterGetTextTemplateTest {

	private static final String TEMPLATE_CONTENT_PLACEHOLDER = "{content}";

	private static final String TEMPLATE_METADATA_STRING_PLACEHOLDER = "{metadata_string}";

	private static final String DEFAULT_TEXT_TEMPLATE = String.format("%s\n\n%s", TEMPLATE_METADATA_STRING_PLACEHOLDER,
			TEMPLATE_CONTENT_PLACEHOLDER);

	@Test
	@Tag("valid")
	@DisplayName("Verify getTextTemplate returns default text template when using default configuration")
	void getTextTemplateReturnsDefaultTemplateWhenUsingDefaultConfig() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.defaultConfig();
		// Act
		String result = formatter.getTextTemplate();
		// Assert
		assertEquals(DEFAULT_TEXT_TEMPLATE, result);
		assertTrue(result.contains(TEMPLATE_METADATA_STRING_PLACEHOLDER));
		assertTrue(result.contains(TEMPLATE_CONTENT_PLACEHOLDER));
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify getTextTemplate returns custom text template when configured via builder")
	void getTextTemplateReturnsCustomTemplateWhenConfiguredViaBuilder() {
		// Arrange
		String customTemplate = "Custom: {content} - {metadata_string}";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder().withTextTemplate(customTemplate).build();
		// Act
		String result = formatter.getTextTemplate();
		// Assert
		assertEquals(customTemplate, result);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify getTextTemplate returns template with only content placeholder")
	void getTextTemplateReturnsTemplateWithOnlyContentPlaceholder() {
		// Arrange
		String templateWithOnlyContent = "{content}";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withTextTemplate(templateWithOnlyContent)
			.build();
		// Act
		String result = formatter.getTextTemplate();
		// Assert
		assertEquals(templateWithOnlyContent, result);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify getTextTemplate returns template with only metadata placeholder")
	void getTextTemplateReturnsTemplateWithOnlyMetadataPlaceholder() {
		// Arrange
		String templateWithOnlyMetadata = "{metadata_string}";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withTextTemplate(templateWithOnlyMetadata)
			.build();
		// Act
		String result = formatter.getTextTemplate();
		// Assert
		assertEquals(templateWithOnlyMetadata, result);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify getTextTemplate returns template with special characters")
	void getTextTemplateReturnsTemplateWithSpecialCharacters() {
		// Arrange
		String templateWithSpecialChars = "Header:\t{metadata_string}\n---\n{content}\n===";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withTextTemplate(templateWithSpecialChars)
			.build();
		// Act
		String result = formatter.getTextTemplate();
		// Assert
		assertEquals(templateWithSpecialChars, result);
		assertTrue(result.contains("\t"));
		assertTrue(result.contains("\n"));
	}

	@Test
	@Tag("invalid")
	@DisplayName("Verify getTextTemplate throws exception when configured with empty template")
	void getTextTemplateThrowsExceptionWhenConfiguredWithEmptyTemplate() {
		// Arrange & Act & Assert
		assertThrows(IllegalArgumentException.class, () -> {
			DefaultContentFormatter.builder().withTextTemplate("").build();
		});
	}

	@Test
	@Tag("invalid")
	@DisplayName("Verify getTextTemplate throws exception when configured with null template")
	void getTextTemplateThrowsExceptionWhenConfiguredWithNullTemplate() {
		// Arrange & Act & Assert
		assertThrows(IllegalArgumentException.class, () -> {
			DefaultContentFormatter.builder().withTextTemplate(null).build();
		});
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify getTextTemplate returns same value on multiple invocations")
	void getTextTemplateReturnsSameValueOnMultipleInvocations() {
		// Arrange
		String customTemplate = "Test: {content} | {metadata_string}";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder().withTextTemplate(customTemplate).build();
		// Act
		String result1 = formatter.getTextTemplate();
		String result2 = formatter.getTextTemplate();
		String result3 = formatter.getTextTemplate();
		// Assert
		assertEquals(customTemplate, result1);
		assertEquals(result1, result2);
		assertEquals(result2, result3);
		assertSame(result1, result2);
		assertSame(result2, result3);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify getTextTemplate returns correct value after using builder from() method")
	void getTextTemplateReturnsCorrectValueAfterUsingBuilderFromMethod() {
		// Arrange
		String customTemplate = "Original: {metadata_string} - {content}";
		DefaultContentFormatter originalFormatter = DefaultContentFormatter.builder()
			.withTextTemplate(customTemplate)
			.build();
		DefaultContentFormatter copiedFormatter = DefaultContentFormatter.builder().from(originalFormatter).build();
		// Act
		String originalResult = originalFormatter.getTextTemplate();
		String copiedResult = copiedFormatter.getTextTemplate();
		// Assert
		assertEquals(customTemplate, originalResult);
		assertEquals(originalResult, copiedResult);
	}

	@Test
	@Tag("boundary")
	@DisplayName("Verify getTextTemplate returns template with multiple placeholder occurrences")
	void getTextTemplateReturnsTemplateWithMultiplePlaceholderOccurrences() {
		// Arrange
		String templateWithMultiplePlaceholders = "{content} - {metadata_string} - {content}";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withTextTemplate(templateWithMultiplePlaceholders)
			.build();
		// Act
		String result = formatter.getTextTemplate();
		// Assert
		assertEquals(templateWithMultiplePlaceholders, result);
		// Verify multiple occurrences of {content}
		int contentCount = result.split("\\{content\\}", -1).length - 1;
		assertEquals(2, contentCount);
	}

	@Test
	@Tag("boundary")
	@DisplayName("Verify getTextTemplate returns very long template string")
	void getTextTemplateReturnsVeryLongTemplateString() {
		// Arrange
		StringBuilder longTemplateBuilder = new StringBuilder();
		longTemplateBuilder.append("Header: {metadata_string}\n");
		for (int i = 0; i < 100; i++) {
			longTemplateBuilder.append("Line ").append(i).append(": Some filler text here. ");
		}
		longTemplateBuilder.append("\nContent: {content}\n");
		for (int i = 0; i < 100; i++) {
			longTemplateBuilder.append("Footer line ").append(i).append(": More filler text. ");
		}
		String longTemplate = longTemplateBuilder.toString();
		DefaultContentFormatter formatter = DefaultContentFormatter.builder().withTextTemplate(longTemplate).build();
		// Act
		String result = formatter.getTextTemplate();
		// Assert
		assertEquals(longTemplate, result);
		assertEquals(longTemplate.length(), result.length());
		assertTrue(result.length() > 1000);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify getTextTemplate returns template with unicode characters")
	void getTextTemplateReturnsTemplateWithUnicodeCharacters() {
		// Arrange
		String templateWithUnicode = "文档: {content} | 元数据: {metadata_string} | émoji: 🎉";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withTextTemplate(templateWithUnicode)
			.build();
		// Act
		String result = formatter.getTextTemplate();
		// Assert
		assertEquals(templateWithUnicode, result);
		assertTrue(result.contains("文档"));
		assertTrue(result.contains("🎉"));
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify getTextTemplate returns template without any placeholders")
	void getTextTemplateReturnsTemplateWithoutAnyPlaceholders() {
		// Arrange
		String templateWithoutPlaceholders = "Static text without any placeholders";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withTextTemplate(templateWithoutPlaceholders)
			.build();
		// Act
		String result = formatter.getTextTemplate();
		// Assert
		assertEquals(templateWithoutPlaceholders, result);
		assertFalse(result.contains("{content}"));
		assertFalse(result.contains("{metadata_string}"));
	}

	@Test
	@Tag("boundary")
	@DisplayName("Verify getTextTemplate returns template with whitespace only content")
	void getTextTemplateReturnsTemplateWithWhitespaceContent() {
		// Arrange
		String templateWithWhitespace = "   {content}   {metadata_string}   ";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withTextTemplate(templateWithWhitespace)
			.build();
		// Act
		String result = formatter.getTextTemplate();
		// Assert
		assertEquals(templateWithWhitespace, result);
		assertTrue(result.startsWith("   "));
		assertTrue(result.endsWith("   "));
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify getTextTemplate is not null for default config")
	void getTextTemplateIsNotNullForDefaultConfig() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.defaultConfig();
		// Act
		String result = formatter.getTextTemplate();
		// Assert
		assertNotNull(result);
		assertFalse(result.isEmpty());
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify getTextTemplate after modifying copied formatter via from() method")
	void getTextTemplateAfterModifyingCopiedFormatterViaFromMethod() {
		// Arrange
		String originalTemplate = "Original: {content}";
		String modifiedTemplate = "Modified: {metadata_string} - {content}";

		DefaultContentFormatter originalFormatter = DefaultContentFormatter.builder()
			.withTextTemplate(originalTemplate)
			.build();
		DefaultContentFormatter modifiedFormatter = DefaultContentFormatter.builder()
			.from(originalFormatter)
			.withTextTemplate(modifiedTemplate)
			.build();
		// Act
		String originalResult = originalFormatter.getTextTemplate();
		String modifiedResult = modifiedFormatter.getTextTemplate();
		// Assert
		assertEquals(originalTemplate, originalResult);
		assertEquals(modifiedTemplate, modifiedResult);
		assertNotEquals(originalResult, modifiedResult);
	}

	@Test
	@Tag("invalid")
	@DisplayName("Verify getTextTemplate throws exception when configured with blank template")
	void getTextTemplateThrowsExceptionWhenConfiguredWithBlankTemplate() {
		// Arrange & Act & Assert
		assertThrows(IllegalArgumentException.class, () -> {
			DefaultContentFormatter.builder().withTextTemplate("   ").build();
		});
	}

}