/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-8-java using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=builder_2187989d2f
ROOST_METHOD_SIG_HASH=builder_80041265ae

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-8-java/1765436562/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/document/ContentFormatterTests.java
Tests:
    "@Test
void shouldThrowWhenNeitherTextNorMediaAreSet() {
    assertThatThrownBy(() -> Document.builder().id("test-id").metadata("key", "value").build()).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("exactly one of text or media must be specified");
}
"
    "@Test
void builderWithCustomIdGenerator() {
    IdGenerator mockGenerator = mock(IdGenerator.class);
    when(mockGenerator.generateId("test text", Map.of("key", "value"))).thenReturn("generated-id");
    Document document = Document.builder().idGenerator(mockGenerator).text("test text").metadata("key", "value").build();
    assertThat(document.getId()).isEqualTo("generated-id");
}
"
    "@Test
void builderShouldThrowWhenIdGeneratorIsNull() {
    assertThatThrownBy(() -> Document.builder().idGenerator(null)).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("idGenerator cannot be null");
}
"
    "@Test
void builderShouldThrowWhenMetadataKeyIsNull() {
    assertThatThrownBy(() -> Document.builder().metadata(null, "value")).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("metadata key cannot be null");
}
"
    "@Test
void builderShouldThrowWhenMetadataValueIsNull() {
    assertThatThrownBy(() -> Document.builder().metadata("key", null)).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("metadata value cannot be null");
}
"
    "@Test
void scoreHandling() {
    Document document = Document.builder().text("test").score(0.85).build();
    assertThat(document.getScore()).isEqualTo(0.85);
    Document documentWithoutScore = new Document("test");
    assertThat(documentWithoutScore.getScore()).isNull();
}
"
    "@Test
void builderWithMetadataMap() {
    Map<String, Object> metadata = Map.of("key1", "value1", "key2", 1);
    Document document = Document.builder().text("test").metadata(metadata).build();
    assertThat(document.getMetadata()).containsExactlyInAnyOrderEntriesOf(metadata);
}
"

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-8-java/1765436562/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/transformer/splitter/TokenTextSplitterTest.java
Tests:
    "@Test
public void testTokenTextSplitterBuilderWithAllFields() {
    var contentFormatter1 = DefaultContentFormatter.defaultConfig();
    var contentFormatter2 = DefaultContentFormatter.defaultConfig();
    assertThat(contentFormatter1).isNotSameAs(contentFormatter2);
    var doc1 = new Document("In the end, writing arises when man realizes that memory is not enough.", Map.of("key1", "value1", "key2", "value2"));
    doc1.setContentFormatter(contentFormatter1);
    var doc2 = new Document("The most oppressive thing about the labyrinth is that you are constantly " + "being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.", Map.of("key2", "value22", "key3", "value3"));
    doc2.setContentFormatter(contentFormatter2);
    var tokenTextSplitter = TokenTextSplitter.builder().withChunkSize(10).withMinChunkSizeChars(5).withMinChunkLengthToEmbed(3).withMaxNumChunks(50).withKeepSeparator(true).build();
    var chunks = tokenTextSplitter.apply(List.of(doc1, doc2));
    assertThat(chunks.size()).isEqualTo(6);

    assertThat(chunks.get(0).getText()).isEqualTo("In the end, writing arises when man realizes that");
    assertThat(chunks.get(1).getText()).isEqualTo("memory is not enough.");

    assertThat(chunks.get(2).getText()).isEqualTo("The most oppressive thing about the labyrinth is that you");
    assertThat(chunks.get(3).getText()).isEqualTo("are constantly being forced to choose.");
    assertThat(chunks.get(4).getText()).isEqualTo("It isn’t the lack of an exit, but");
    assertThat(chunks.get(5).getText()).isEqualTo("the abundance of exits that is so disorienting");


    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(1).getMetadata()).containsKeys("key1", "key2", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(2).getMetadata()).containsKeys("key2", "key3", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(3).getMetadata()).containsKeys("key2", "key3", "parent_document_id", "chunk_index", "total_chunks");

    assertThat(chunks.get(0).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(1).getMetadata().get("chunk_index")).isEqualTo(1);
    assertThat(chunks.get(2).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(3).getMetadata().get("chunk_index")).isEqualTo(1);
    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2").doesNotContainKeys("key3");
    assertThat(chunks.get(2).getMetadata()).containsKeys("key2", "key3").doesNotContainKeys("key1");
}
"

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-8-java/1765436562/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/document/DocumentTests.java
Tests:
    "@Test
void testScore() {
    Double score = 0.95;
    Document document = Document.builder().text("Test content").score(score).build();
    assertThat(document.getScore()).isEqualTo(score);
}
"
    "@Test
void testNullScore() {
    Document document = Document.builder().text("Test content").score(null).build();
    assertThat(document.getScore()).isNull();
}
"
    "@Test
void testMutate() {
    Media media = getMedia();
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("key", "value");
    Double score = 0.95;
    Document original = Document.builder().id("customId").text("Test content").media(null).metadata(metadata).score(score).build();
    Document mutated = original.mutate().build();
    assertThat(mutated).isNotSameAs(original).usingRecursiveComparison().isEqualTo(original);
}
"
    "@Test
void testEquals() {
    Media media = getMedia();
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("key", "value");
    Double score = 0.95;
    Document doc1 = Document.builder().id("customId").text("Test text").metadata(metadata).score(score).build();
    Document doc2 = Document.builder().id("customId").text("Test text").metadata(metadata).score(score).build();
    Document differentDoc = Document.builder().id("differentId").text("Different content").metadata(metadata).score(score).build();
    assertThat(doc1).isEqualTo(doc2).isNotEqualTo(differentDoc).isNotEqualTo(null).isNotEqualTo(new Object());
    assertThat(doc1.hashCode()).isEqualTo(doc2.hashCode());
}
"
    "@Test
void testEmptyDocument() {
    assertThrows(IllegalArgumentException.class, () -> Document.builder().build());
}
"
    "@Test
void testToString() {
    Media media = getMedia();
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("key", "value");
    Double score = 0.95;
    Document document = Document.builder().id("customId").text("Test content").media(null).metadata(metadata).score(score).build();
    String toString = document.toString();
    assertThat(toString).contains("id='customId'").contains("text='Test content'").contains("metadata=" + metadata).contains("score=" + score);
}
"
    "@Test
void testMediaDocumentConstruction() {
    Media media = getMedia();
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("key", "value");
    Document document = Document.builder().media(media).metadata(metadata).build();
    assertThat(document.getMedia()).isEqualTo(media);
    assertThat(document.getText()).isNull();
    assertThat(document.isText()).isFalse();
}
"
    "@Test
void testTextDocumentConstruction() {
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("key", "value");
    Document document = Document.builder().text("Test text").metadata(metadata).build();
    assertThat(document.getText()).isEqualTo("Test text");
    assertThat(document.getMedia()).isNull();
    assertThat(document.isText()).isTrue();
}
"
    "@Test
void testBothTextAndMediaThrowsException() {
    Media media = getMedia();
    assertThrows(IllegalArgumentException.class, () -> Document.builder().text("Test text").media(media).build());
}
"
    "@Test
void testCustomIdGenerator() {
    IdGenerator customGenerator = contents -> "custom-" + contents[0];
    Document document = Document.builder().text("test").idGenerator(customGenerator).build();
    assertThat(document.getId()).isEqualTo("custom-test");
}
"
    "@Test
void testMetadataValidation() {
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("nullKey", null);
    assertThrows(IllegalArgumentException.class, () -> Document.builder().text("test").metadata(metadata).build());
}
"
    "@Test
void testFormattedContent() {
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("key", "value");
    Document document = Document.builder().text("Test text").metadata(metadata).build();
    String formattedContent = document.getFormattedContent(MetadataMode.ALL);
    assertThat(formattedContent).contains("Test text");
    assertThat(formattedContent).contains("key");
    assertThat(formattedContent).contains("value");
}
"
    "@Test
void testCustomFormattedContent() {
    Document document = Document.builder().text("Test text").build();
    ContentFormatter customFormatter = (doc, mode) -> "Custom: " + doc.getText();
    String formattedContent = document.getFormattedContent(customFormatter, MetadataMode.ALL);
    assertThat(formattedContent).isEqualTo("Custom: Test text");
}
"
    "@Test
void testNullIdThrowsException() {
    assertThrows(IllegalArgumentException.class, () -> Document.builder().id(null).text("test").build());
}
"
    "@Test
void testEmptyIdThrowsException() {
    assertThrows(IllegalArgumentException.class, () -> Document.builder().id("").text("test").build());
}
"
    "@Test
void testMetadataKeyValueAddition() {
    Document document = Document.builder().text("test").metadata("key1", "value1").metadata("key2", "value2").build();
    assertThat(document.getMetadata()).containsEntry("key1", "value1").containsEntry("key2", "value2");
}
"
    "@Test
private static Media getMedia() {
    return Media.builder().mimeType(MimeTypeUtils.IMAGE_JPEG).data(URI.create("http:
}
"
    "@Test
void testMetadataModeNone() {
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("secret", "hidden");
    Document document = Document.builder().text("Visible content").metadata(metadata).build();
    String formattedContent = document.getFormattedContent(MetadataMode.NONE);
    assertThat(formattedContent).contains("Visible content");
    assertThat(formattedContent).doesNotContain("secret");
    assertThat(formattedContent).doesNotContain("hidden");
}
"
    "@Test
void testMetadataModeEmbed() {
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("embedKey", "embedValue");
    metadata.put("filterKey", "filterValue");
    Document document = Document.builder().text("Test content").metadata(metadata).build();
    String formattedContent = document.getFormattedContent(MetadataMode.EMBED);


    assertThat(formattedContent).contains("Test content");
}
"
    "@Test
void testDocumentBuilderChaining() {
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("chain", "test");
    Document document = Document.builder().text("Chain test").metadata(metadata).metadata("additional", "value").score(0.85).build();
    assertThat(document.getText()).isEqualTo("Chain test");
    assertThat(document.getMetadata()).containsEntry("chain", "test");
    assertThat(document.getMetadata()).containsEntry("additional", "value");
    assertThat(document.getScore()).isEqualTo(0.85);
}
"
    "@Test
void testDocumentWithScoreGreaterThanOne() {
    Document document = Document.builder().text("High score test").score(1.5).build();
    assertThat(document.getScore()).isEqualTo(1.5);
}
"
    "@Test
void testMutateWithChanges() {
    Document original = Document.builder().text("Original text").score(0.5).metadata("original", "value").build();
    Document mutated = original.mutate().text("Mutated text").score(0.8).metadata("new", "metadata").build();
    assertThat(mutated.getText()).isEqualTo("Mutated text");
    assertThat(mutated.getScore()).isEqualTo(0.8);
    assertThat(mutated.getMetadata()).containsEntry("new", "metadata");

    assertThat(original.getText()).isEqualTo("Original text");
}
"
    "@Test
void testDocumentEqualityWithDifferentScores() {
    Document doc1 = Document.builder().id("sameId").text("Same text").score(0.5).build();
    Document doc2 = Document.builder().id("sameId").text("Same text").score(0.8).build();

    assertThat(doc1).isNotEqualTo(doc2);
}
"
    "@Test
void testDocumentWithComplexMetadata() {
    Map<String, Object> nestedMap = new HashMap<>();
    nestedMap.put("nested", "value");
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("string", "value");
    metadata.put("number", 1);
    metadata.put("boolean", true);
    metadata.put("map", nestedMap);
    Document document = Document.builder().text("Complex metadata test").metadata(metadata).build();
    assertThat(document.getMetadata()).containsEntry("string", "value");
    assertThat(document.getMetadata()).containsEntry("number", 1);
    assertThat(document.getMetadata()).containsEntry("boolean", true);
    assertThat(document.getMetadata()).containsEntry("map", nestedMap);
}
"
    "@Test
void testMetadataImmutability() {
    Map<String, Object> originalMetadata = new HashMap<>();
    originalMetadata.put("key", "value");
    Document document = Document.builder().text("Immutability test").metadata(originalMetadata).build();

    originalMetadata.put("key", "modified");
    originalMetadata.put("newKey", "newValue");

    assertThat(document.getMetadata()).containsEntry("key", "value");
    assertThat(document.getMetadata()).doesNotContainKey("newKey");
}
"
    "@Test
void testDocumentWithEmptyMetadata() {
    Document document = Document.builder().text("Empty metadata test").metadata(new HashMap<>()).build();
    assertThat(document.getMetadata()).isEmpty();
}
"
    "@Test
void testMetadataWithNullValueInMap() {
    Map<String, Object> metadata = new HashMap<>();
    metadata.put("validKey", "validValue");
    metadata.put("nullKey", null);
    assertThrows(IllegalArgumentException.class, () -> Document.builder().text("test").metadata(metadata).build());
}
"
    "@Test
void testDocumentWithWhitespaceOnlyText() {
    String whitespaceText = "   \n\t\r   ";
    Document document = Document.builder().text(whitespaceText).build();
    assertThat(document.getText()).isEqualTo(whitespaceText);
    assertThat(document.isText()).isTrue();
}
"
    "@Test
void testDocumentHashCodeConsistency() {
    Document document = Document.builder().text("Hash test").metadata("key", "value").score(0.1).build();
    int hashCode1 = document.hashCode();
    int hashCode2 = document.hashCode();
    assertThat(hashCode1).isEqualTo(hashCode2);
}
"

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-8-java/1765436562/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/util/JacksonUtilsTests.java
Tests:
    "@Test
void usesCorrectClassLoader() throws JsonProcessingException, ClassNotFoundException {
    ClassLoader previousLoader = Thread.currentThread().getContextClassLoader();
    try {

        Thread.currentThread().setContextClassLoader(getClass().getClassLoader().getParent());

        var jsonMapper = JsonMapper.builder().addModules(JacksonUtils.instantiateAvailableModules()).build();
        Class<?> clazz = getClass().getClassLoader().loadClass(getClass().getName() + "$Cell");
        var output = jsonMapper.readValue("{\"name\":\"Amoeba\",\"lifespan\":\"PT42S\"}", clazz);
        assertThat(output).isEqualTo(new Cell("Amoeba", Duration.of(42L, ChronoUnit.SECONDS)));
    } finally {
        Thread.currentThread().setContextClassLoader(previousLoader);
    }
}
"

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-8-java/1765436562/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/transformer/splitter/TextSplitterTests.java
Tests:
    "@Test
public void testScorePreservation() {

    Double originalScore = 0.95;
    var doc = Document.builder().text("This is a test document that will be split into multiple chunks.").metadata(Map.of("source", "test.txt")).score(originalScore).build();

    List<Document> chunks = testTextSplitter.apply(List.of(doc));

    assertThat(chunks).hasSize(2);
    assertThat(chunks.get(0).getScore()).isEqualTo(originalScore);
    assertThat(chunks.get(1).getScore()).isEqualTo(originalScore);
}
"
    "@Test
public void testEnhancedMetadataWithMultipleDocuments() {

    var doc1 = Document.builder().text("First document with score and metadata.").metadata(Map.of("type", "article", "priority", "high")).score(0.8).build();
    var doc2 = Document.builder().text("Second document with different score.").metadata(Map.of("type", "report", "priority", "medium")).score(0.6).build();
    String originalId1 = doc1.getId();
    String originalId2 = doc2.getId();

    List<Document> chunks = testTextSplitter.apply(List.of(doc1, doc2));

    assertThat(chunks).hasSize(4);

    for (int i = 0; i < 2; i++) {
        Document chunk = chunks.get(i);
        assertThat(chunk.getScore()).isEqualTo(0.8);
        assertThat(chunk.getMetadata().get("parent_document_id")).isEqualTo(originalId1);
        assertThat(chunk.getMetadata().get("chunk_index")).isEqualTo(i);
        assertThat(chunk.getMetadata().get("total_chunks")).isEqualTo(2);
        assertThat(chunk.getMetadata().get("type")).isEqualTo("article");
        assertThat(chunk.getMetadata().get("priority")).isEqualTo("high");
    }

    for (int i = 2; i < 4; i++) {
        Document chunk = chunks.get(i);
        assertThat(chunk.getScore()).isEqualTo(0.6);
        assertThat(chunk.getMetadata().get("parent_document_id")).isEqualTo(originalId2);
        assertThat(chunk.getMetadata().get("chunk_index")).isEqualTo(i - 2);
        assertThat(chunk.getMetadata().get("total_chunks")).isEqualTo(2);
        assertThat(chunk.getMetadata().get("type")).isEqualTo("report");
        assertThat(chunk.getMetadata().get("priority")).isEqualTo("medium");
    }
}
"

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-8-java/1765436562/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/observation/AiOperationMetadataTests.java
Tests:
    "@Test
void whenMandatoryMetadataThenReturn() {
    var operationMetadata = AiOperationMetadata.builder().operationType("chat").provider("doofenshmirtz").build();
    assertThat(operationMetadata).isNotNull();
}
"
    "@Test
void whenOperationTypeIsNullThenThrow() {
    assertThatThrownBy(() -> AiOperationMetadata.builder().provider("doofenshmirtz").build()).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("operationType cannot be null or empty");
}
"
    "@Test
void whenOperationTypeIsEmptyThenThrow() {
    assertThatThrownBy(() -> AiOperationMetadata.builder().operationType("").provider("doofenshmirtz").build()).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("operationType cannot be null or empty");
}
"
    "@Test
void whenProviderIsNullThenThrow() {
    assertThatThrownBy(() -> AiOperationMetadata.builder().operationType("chat").build()).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("provider cannot be null or empty");
}
"
    "@Test
void whenProviderIsEmptyThenThrow() {
    assertThatThrownBy(() -> AiOperationMetadata.builder().operationType("chat").provider("").build()).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("provider cannot be null or empty");
}
"
    "@Test
void whenOperationTypeIsBlankThenThrow() {
    assertThatThrownBy(() -> AiOperationMetadata.builder().operationType("   ").provider("doofenshmirtz").build()).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("operationType cannot be null or empty");
}
"
    "@Test
void whenProviderIsBlankThenThrow() {
    assertThatThrownBy(() -> AiOperationMetadata.builder().operationType("chat").provider("   ").build()).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("provider cannot be null or empty");
}
"
    "@Test
void whenBuiltWithValidValuesThenFieldsAreAccessible() {
    var operationMetadata = AiOperationMetadata.builder().operationType("chat").provider("openai").build();
    assertThat(operationMetadata.operationType()).isEqualTo("chat");
    assertThat(operationMetadata.provider()).isEqualTo("openai");
}
"

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-8-java/1765436562/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/writer/FileDocumentWriterTest.java
Tests:
    "@Test
void setUp() {
    this.testFileName = this.tempDir.resolve("file-document-test-output.txt").toString();
    this.testDocuments = List.of(Document.builder().text("Document one introduces the core functionality of Spring AI.").metadata("page_number", "1").metadata("end_page_number", "2").metadata("source", "intro.pdf").metadata("title", "Spring AI Overview").metadata("author", "QA Team").build(), Document.builder().text("Document two illustrates multi-line handling and line breaks.\nEnsure preservation of formatting.").metadata("page_number", "3").metadata("end_page_number", "4").metadata("source", "formatting.pdf").build(), Document.builder().text("Document three checks metadata inclusion and output formatting behavior.").metadata("page_number", "5").metadata("end_page_number", "6").metadata("version", "v1.2").build());
}
"

File Path: /var/tmp/Roost/RoostGPT/zbio-dec-8-java/1765436562/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/document/DocumentBuilderTests.java
Tests:
    "@Test
private static Media getMedia() {
    return Media.builder().data(URI.create("http:
}
"
    "@Test
void setUp() {
    this.builder = Document.builder();
}
"
    "@Test
void testWithMediaSingle() {
    Media media = Media.builder().mimeType(MimeTypeUtils.IMAGE_JPEG).data(URI.create("http:
    Document.Builder result = this.builder.media(media);
    assertThat(result).isSameAs(this.builder);
    assertThat(result.build().getMedia()).isEqualTo(media);
}
"Scenario 1: Verify builder() returns a new Builder instance

Details:
  TestName: builderReturnsNewBuilderInstance
  Description: Verify that the static builder() method returns a non-null Builder instance that can be used to construct a DefaultContentFormatter.
Execution:
  Arrange: No setup required.
  Act: Call DefaultContentFormatter.builder() to obtain a Builder instance.
  Assert: Verify that the returned Builder instance is not null.
Validation:
  The assertion confirms that the builder() method successfully creates and returns a Builder object. This is fundamental for the builder pattern implementation, ensuring clients can start constructing DefaultContentFormatter instances.

Scenario 2: Verify builder() returns distinct Builder instances on each call

Details:
  TestName: builderReturnsDistinctInstancesOnEachCall
  Description: Verify that each call to builder() returns a new, distinct Builder instance rather than reusing the same instance.
Execution:
  Arrange: No setup required.
  Act: Call DefaultContentFormatter.builder() twice to obtain two Builder instances.
  Assert: Verify that the two Builder instances are not the same object reference.
Validation:
  This test ensures thread safety and proper isolation between builder instances. Each caller should receive their own Builder to configure independently without affecting other builders.

Scenario 3: Verify Builder can build DefaultContentFormatter with default values

Details:
  TestName: builderBuildsDefaultContentFormatterWithDefaultValues
  Description: Verify that a Builder obtained from builder() can successfully build a DefaultContentFormatter with default configuration values.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Call build() on the Builder to create a DefaultContentFormatter.
  Assert: Verify that the resulting DefaultContentFormatter is not null and has default values for metadataTemplate, metadataSeparator, and textTemplate.
Validation:
  This validates the complete builder workflow from obtaining a builder to creating a configured instance. The default values should match the static constants defined in the class.

Scenario 4: Verify Builder returned by builder() allows method chaining

Details:
  TestName: builderAllowsMethodChaining
  Description: Verify that the Builder returned by builder() supports fluent method chaining for configuration.
Execution:
  Arrange: No setup required.
  Act: Call DefaultContentFormatter.builder() and chain multiple configuration methods like withMetadataTemplate(), withMetadataSeparator(), and withTextTemplate().
  Assert: Verify that each chained method returns the same Builder instance and the final build() produces a properly configured DefaultContentFormatter.
Validation:
  Method chaining is a key feature of the builder pattern. This test ensures that the Builder supports fluent API design, making it easier and more readable to configure DefaultContentFormatter instances.

Scenario 5: Verify Builder from builder() can configure excludedInferenceMetadataKeys

Details:
  TestName: builderCanConfigureExcludedInferenceMetadataKeys
  Description: Verify that the Builder obtained from builder() can be configured with excluded inference metadata keys.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Configure the Builder with excluded inference metadata keys using withExcludedInferenceMetadataKeys() and build the formatter.
  Assert: Verify that the built DefaultContentFormatter contains the configured excluded inference metadata keys.
Validation:
  This test ensures that the Builder properly handles the configuration of excluded inference metadata keys, which is important for filtering metadata during inference operations.

Scenario 6: Verify Builder from builder() can configure excludedEmbedMetadataKeys

Details:
  TestName: builderCanConfigureExcludedEmbedMetadataKeys
  Description: Verify that the Builder obtained from builder() can be configured with excluded embed metadata keys.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Configure the Builder with excluded embed metadata keys using withExcludedEmbedMetadataKeys() and build the formatter.
  Assert: Verify that the built DefaultContentFormatter contains the configured excluded embed metadata keys.
Validation:
  This test ensures that the Builder properly handles the configuration of excluded embed metadata keys, which is important for filtering metadata during embedding operations.

Scenario 7: Verify Builder from builder() can configure custom metadataTemplate

Details:
  TestName: builderCanConfigureCustomMetadataTemplate
  Description: Verify that the Builder obtained from builder() can be configured with a custom metadata template.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Configure the Builder with a custom metadata template using withMetadataTemplate() and build the formatter.
  Assert: Verify that the built DefaultContentFormatter has the custom metadata template.
Validation:
  This test ensures that users can customize how metadata key-value pairs are formatted in the output, allowing flexibility in document formatting.

Scenario 8: Verify Builder from builder() can configure custom metadataSeparator

Details:
  TestName: builderCanConfigureCustomMetadataSeparator
  Description: Verify that the Builder obtained from builder() can be configured with a custom metadata separator.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Configure the Builder with a custom metadata separator using withMetadataSeparator() and build the formatter.
  Assert: Verify that the built DefaultContentFormatter has the custom metadata separator.
Validation:
  This test ensures that users can customize the separator used between metadata entries, providing flexibility in how metadata is presented.

Scenario 9: Verify Builder from builder() can configure custom textTemplate

Details:
  TestName: builderCanConfigureCustomTextTemplate
  Description: Verify that the Builder obtained from builder() can be configured with a custom text template.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Configure the Builder with a custom text template using withTextTemplate() and build the formatter.
  Assert: Verify that the built DefaultContentFormatter has the custom text template.
Validation:
  This test ensures that users can customize the overall document text template, controlling how content and metadata are combined in the final output.

Scenario 10: Verify Builder from builder() can use from() to copy configuration

Details:
  TestName: builderCanCopyConfigurationFromExistingFormatter
  Description: Verify that the Builder obtained from builder() can copy configuration from an existing DefaultContentFormatter using the from() method.
Execution:
  Arrange: Create a DefaultContentFormatter with custom configuration. Obtain a new Builder instance using DefaultContentFormatter.builder().
  Act: Use the from() method to copy the configuration from the existing formatter and build a new formatter.
  Assert: Verify that the new formatter has the same configuration as the original.
Validation:
  This test ensures that the from() method properly copies all configuration from an existing formatter, enabling easy creation of modified copies.

Scenario 11: Verify builder() is a static method accessible without instance

Details:
  TestName: builderIsStaticMethodAccessibleWithoutInstance
  Description: Verify that builder() is a static factory method that can be called directly on the class without needing an instance.
Execution:
  Arrange: No setup required.
  Act: Call DefaultContentFormatter.builder() directly on the class.
  Assert: Verify that the method executes successfully and returns a Builder.
Validation:
  This confirms the static nature of the builder() method, which is essential for the factory pattern implementation where instances are created through the builder rather than constructors.

Scenario 12: Verify multiple Builders can be used independently

Details:
  TestName: multipleBuilderInstancesWorkIndependently
  Description: Verify that multiple Builder instances obtained from builder() can be configured independently without affecting each other.
Execution:
  Arrange: Obtain two Builder instances using DefaultContentFormatter.builder().
  Act: Configure each Builder with different settings and build both formatters.
  Assert: Verify that each resulting DefaultContentFormatter has its own distinct configuration.
Validation:
  This test ensures proper isolation between Builder instances, which is critical for concurrent usage and preventing configuration leakage between different builder operations.

Scenario 13: Verify Builder from builder() with varargs excludedInferenceMetadataKeys

Details:
  TestName: builderCanConfigureExcludedInferenceMetadataKeysWithVarargs
  Description: Verify that the Builder can be configured with excluded inference metadata keys using the varargs overload.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Configure the Builder with excluded inference metadata keys using withExcludedInferenceMetadataKeys(String... keys) and build the formatter.
  Assert: Verify that the built DefaultContentFormatter contains all the specified excluded inference metadata keys.
Validation:
  This test ensures that the varargs method for configuring excluded inference metadata keys works correctly, providing a convenient API for specifying multiple keys.

Scenario 14: Verify Builder from builder() with varargs excludedEmbedMetadataKeys

Details:
  TestName: builderCanConfigureExcludedEmbedMetadataKeysWithVarargs
  Description: Verify that the Builder can be configured with excluded embed metadata keys using the varargs overload.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Configure the Builder with excluded embed metadata keys using withExcludedEmbedMetadataKeys(String... keys) and build the formatter.
  Assert: Verify that the built DefaultContentFormatter contains all the specified excluded embed metadata keys.
Validation:
  This test ensures that the varargs method for configuring excluded embed metadata keys works correctly, providing a convenient API for specifying multiple keys.

Scenario 15: Verify Builder produces formatter that implements ContentFormatter interface

Details:
  TestName: builderProducesFormatterImplementingContentFormatterInterface
  Description: Verify that the DefaultContentFormatter built from the Builder properly implements the ContentFormatter interface.
Execution:
  Arrange: Obtain a Builder instance using DefaultContentFormatter.builder().
  Act: Build a DefaultContentFormatter and verify it is an instance of ContentFormatter.
  Assert: Verify that the built object is an instance of ContentFormatter interface.
Validation:
  This test confirms that the built DefaultContentFormatter properly implements the ContentFormatter interface, ensuring it can be used wherever ContentFormatter is expected.

*/

// ********RoostGPT********

package org.springframework.ai.document;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.util.Assert;

class DefaultContentFormatterBuilderTest {

	@Test
	@Tag("valid")
	@DisplayName("Verify builder() returns a new Builder instance")
	void builderReturnsNewBuilderInstance() {
		// Arrange - No setup required

		// Act
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Assert
		assertNotNull(builder, "Builder instance should not be null");
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify builder() returns distinct Builder instances on each call")
	void builderReturnsDistinctInstancesOnEachCall() {
		// Arrange - No setup required

		// Act
		DefaultContentFormatter.Builder builder1 = DefaultContentFormatter.builder();
		DefaultContentFormatter.Builder builder2 = DefaultContentFormatter.builder();

		// Assert
		assertNotSame(builder1, builder2, "Each call to builder() should return a distinct instance");
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Builder can build DefaultContentFormatter with default values")
	void builderBuildsDefaultContentFormatterWithDefaultValues() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act
		DefaultContentFormatter formatter = builder.build();

		// Assert
		assertNotNull(formatter, "Built formatter should not be null");
		assertNotNull(formatter.getMetadataTemplate(), "Metadata template should not be null");
		assertNotNull(formatter.getMetadataSeparator(), "Metadata separator should not be null");
		assertNotNull(formatter.getTextTemplate(), "Text template should not be null");
		assertEquals("{key}: {value}", formatter.getMetadataTemplate(), "Default metadata template should match");
		assertEquals(System.lineSeparator(), formatter.getMetadataSeparator(),
				"Default metadata separator should be system line separator");
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Builder returned by builder() allows method chaining")
	void builderAllowsMethodChaining() {
		// Arrange
		String customMetadataTemplate = "{key}={value}";
		String customMetadataSeparator = ", ";
		String customTextTemplate = "{content} - {metadata_string}";

		// Act
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataTemplate(customMetadataTemplate)
			.withMetadataSeparator(customMetadataSeparator)
			.withTextTemplate(customTextTemplate)
			.build();

		// Assert
		assertNotNull(formatter, "Built formatter should not be null");
		assertEquals(customMetadataTemplate, formatter.getMetadataTemplate());
		assertEquals(customMetadataSeparator, formatter.getMetadataSeparator());
		assertEquals(customTextTemplate, formatter.getTextTemplate());
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Builder from builder() can configure excludedInferenceMetadataKeys")
	void builderCanConfigureExcludedInferenceMetadataKeys() {
		// Arrange
		List<String> excludedKeys = Arrays.asList("key1", "key2", "key3");

		// Act
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys(excludedKeys)
			.build();

		// Assert
		assertNotNull(formatter.getExcludedInferenceMetadataKeys());
		assertEquals(excludedKeys.size(), formatter.getExcludedInferenceMetadataKeys().size());
		assertTrue(formatter.getExcludedInferenceMetadataKeys().containsAll(excludedKeys));
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Builder from builder() can configure excludedEmbedMetadataKeys")
	void builderCanConfigureExcludedEmbedMetadataKeys() {
		// Arrange
		List<String> excludedKeys = Arrays.asList("embedKey1", "embedKey2");

		// Act
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedEmbedMetadataKeys(excludedKeys)
			.build();

		// Assert
		assertNotNull(formatter.getExcludedEmbedMetadataKeys());
		assertEquals(excludedKeys.size(), formatter.getExcludedEmbedMetadataKeys().size());
		assertTrue(formatter.getExcludedEmbedMetadataKeys().containsAll(excludedKeys));
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Builder from builder() can configure custom metadataTemplate")
	void builderCanConfigureCustomMetadataTemplate() {
		// Arrange
		String customTemplate = "[{key}] -> {value}";

		// Act
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataTemplate(customTemplate)
			.build();

		// Assert
		assertEquals(customTemplate, formatter.getMetadataTemplate());
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Builder from builder() can configure custom metadataSeparator")
	void builderCanConfigureCustomMetadataSeparator() {
		// Arrange
		String customSeparator = " | ";

		// Act
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataSeparator(customSeparator)
			.build();

		// Assert
		assertEquals(customSeparator, formatter.getMetadataSeparator());
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Builder from builder() can configure custom textTemplate")
	void builderCanConfigureCustomTextTemplate() {
		// Arrange
		String customTextTemplate = "Content: {content}\nMetadata: {metadata_string}";

		// Act
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withTextTemplate(customTextTemplate)
			.build();

		// Assert
		assertEquals(customTextTemplate, formatter.getTextTemplate());
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Builder from builder() can use from() to copy configuration")
	void builderCanCopyConfigurationFromExistingFormatter() {
		// Arrange
		String customMetadataTemplate = "{key}={value}";
		String customMetadataSeparator = ";";
		String customTextTemplate = "{metadata_string}\n{content}";
		List<String> excludedInferenceKeys = Arrays.asList("inferKey1");
		List<String> excludedEmbedKeys = Arrays.asList("embedKey1");

		DefaultContentFormatter originalFormatter = DefaultContentFormatter.builder()
			.withMetadataTemplate(customMetadataTemplate)
			.withMetadataSeparator(customMetadataSeparator)
			.withTextTemplate(customTextTemplate)
			.withExcludedInferenceMetadataKeys(excludedInferenceKeys)
			.withExcludedEmbedMetadataKeys(excludedEmbedKeys)
			.build();

		// Act
		DefaultContentFormatter copiedFormatter = DefaultContentFormatter.builder().from(originalFormatter).build();

		// Assert
		assertEquals(originalFormatter.getMetadataTemplate(), copiedFormatter.getMetadataTemplate());
		assertEquals(originalFormatter.getMetadataSeparator(), copiedFormatter.getMetadataSeparator());
		assertEquals(originalFormatter.getTextTemplate(), copiedFormatter.getTextTemplate());
		assertEquals(originalFormatter.getExcludedInferenceMetadataKeys(),
				copiedFormatter.getExcludedInferenceMetadataKeys());
		assertEquals(originalFormatter.getExcludedEmbedMetadataKeys(), copiedFormatter.getExcludedEmbedMetadataKeys());
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify builder() is a static method accessible without instance")
	void builderIsStaticMethodAccessibleWithoutInstance() {
		// Arrange - No setup required

		// Act
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Assert
		assertNotNull(builder, "Static builder() method should be accessible and return a Builder");
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify multiple Builders can be used independently")
	void multipleBuilderInstancesWorkIndependently() {
		// Arrange
		DefaultContentFormatter.Builder builder1 = DefaultContentFormatter.builder();
		DefaultContentFormatter.Builder builder2 = DefaultContentFormatter.builder();

		String template1 = "{key}:{value}";
		String template2 = "{key}={value}";

		// Act
		DefaultContentFormatter formatter1 = builder1.withMetadataTemplate(template1).build();

		DefaultContentFormatter formatter2 = builder2.withMetadataTemplate(template2).build();

		// Assert
		assertEquals(template1, formatter1.getMetadataTemplate());
		assertEquals(template2, formatter2.getMetadataTemplate());
		assertNotEquals(formatter1.getMetadataTemplate(), formatter2.getMetadataTemplate());
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Builder can configure excludedInferenceMetadataKeys with varargs")
	void builderCanConfigureExcludedInferenceMetadataKeysWithVarargs() {
		// Arrange - No setup required

		// Act
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys("key1", "key2", "key3")
			.build();

		// Assert
		assertNotNull(formatter.getExcludedInferenceMetadataKeys());
		assertTrue(formatter.getExcludedInferenceMetadataKeys().contains("key1"));
		assertTrue(formatter.getExcludedInferenceMetadataKeys().contains("key2"));
		assertTrue(formatter.getExcludedInferenceMetadataKeys().contains("key3"));
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Builder can configure excludedEmbedMetadataKeys with varargs")
	void builderCanConfigureExcludedEmbedMetadataKeysWithVarargs() {
		// Arrange - No setup required

		// Act
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedEmbedMetadataKeys("embedKey1", "embedKey2")
			.build();

		// Assert
		assertNotNull(formatter.getExcludedEmbedMetadataKeys());
		assertTrue(formatter.getExcludedEmbedMetadataKeys().contains("embedKey1"));
		assertTrue(formatter.getExcludedEmbedMetadataKeys().contains("embedKey2"));
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Builder produces formatter implementing ContentFormatter interface")
	void builderProducesFormatterImplementingContentFormatterInterface() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act
		DefaultContentFormatter formatter = builder.build();

		// Assert
		assertTrue(formatter instanceof ContentFormatter,
				"Built formatter should implement ContentFormatter interface");
	}

	@Test
	@Tag("invalid")
	@DisplayName("Verify Builder throws exception for empty metadataTemplate")
	void builderThrowsExceptionForEmptyMetadataTemplate() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> {
			builder.withMetadataTemplate("");
		});
	}

	@Test
	@Tag("invalid")
	@DisplayName("Verify Builder throws exception for null metadataTemplate")
	void builderThrowsExceptionForNullMetadataTemplate() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> {
			builder.withMetadataTemplate(null);
		});
	}

	@Test
	@Tag("invalid")
	@DisplayName("Verify Builder throws exception for null metadataSeparator")
	void builderThrowsExceptionForNullMetadataSeparator() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> {
			builder.withMetadataSeparator(null);
		});
	}

	@Test
	@Tag("invalid")
	@DisplayName("Verify Builder throws exception for empty textTemplate")
	void builderThrowsExceptionForEmptyTextTemplate() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> {
			builder.withTextTemplate("");
		});
	}

	@Test
	@Tag("invalid")
	@DisplayName("Verify Builder throws exception for null excludedInferenceMetadataKeys list")
	void builderThrowsExceptionForNullExcludedInferenceMetadataKeysList() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> {
			builder.withExcludedInferenceMetadataKeys((List<String>) null);
		});
	}

	@Test
	@Tag("invalid")
	@DisplayName("Verify Builder throws exception for null excludedEmbedMetadataKeys list")
	void builderThrowsExceptionForNullExcludedEmbedMetadataKeysList() {
		// Arrange
		DefaultContentFormatter.Builder builder = DefaultContentFormatter.builder();

		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> {
			builder.withExcludedEmbedMetadataKeys((List<String>) null);
		});
	}

	@Test
	@Tag("boundary")
	@DisplayName("Verify Builder allows empty metadataSeparator")
	void builderAllowsEmptyMetadataSeparator() {
		// Arrange
		String emptySeparator = "";

		// Act
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataSeparator(emptySeparator)
			.build();

		// Assert
		assertEquals(emptySeparator, formatter.getMetadataSeparator());
	}

	@Test
	@Tag("boundary")
	@DisplayName("Verify Builder with empty excluded keys lists")
	void builderWithEmptyExcludedKeysLists() {
		// Arrange
		List<String> emptyList = new ArrayList<>();

		// Act
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys(emptyList)
			.withExcludedEmbedMetadataKeys(emptyList)
			.build();

		// Assert
		assertTrue(formatter.getExcludedInferenceMetadataKeys().isEmpty());
		assertTrue(formatter.getExcludedEmbedMetadataKeys().isEmpty());
	}

	@Test
	@Tag("integration")
	@DisplayName("Verify built formatter can format Document correctly")
	void builtFormatterCanFormatDocumentCorrectly() {
		// Arrange
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("author", "John Doe");
		metadata.put("date", "2024-01-01");

		Document document = new Document("Test content", metadata);

		DefaultContentFormatter formatter = DefaultContentFormatter.builder().build();

		// Act
		String formattedContent = formatter.format(document, MetadataMode.ALL);

		// Assert
		assertNotNull(formattedContent);
		assertTrue(formattedContent.contains("Test content"));
		assertTrue(formattedContent.contains("author"));
		assertTrue(formattedContent.contains("John Doe"));
	}

	@Test
	@Tag("integration")
	@DisplayName("Verify built formatter respects excluded inference metadata keys")
	void builtFormatterRespectsExcludedInferenceMetadataKeys() {
		// Arrange
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("author", "John Doe");
		metadata.put("secret", "hidden");

		Document document = new Document("Test content", metadata);

		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys("secret")
			.build();

		// Act
		String formattedContent = formatter.format(document, MetadataMode.INFERENCE);

		// Assert
		assertNotNull(formattedContent);
		assertTrue(formattedContent.contains("author"));
		assertFalse(formattedContent.contains("secret"));
	}

	@Test
	@Tag("integration")
	@DisplayName("Verify built formatter respects excluded embed metadata keys")
	void builtFormatterRespectsExcludedEmbedMetadataKeys() {
		// Arrange
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("author", "John Doe");
		metadata.put("embedSecret", "hidden");

		Document document = new Document("Test content", metadata);

		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedEmbedMetadataKeys("embedSecret")
			.build();

		// Act
		String formattedContent = formatter.format(document, MetadataMode.EMBED);

		// Assert
		assertNotNull(formattedContent);
		assertTrue(formattedContent.contains("author"));
		assertFalse(formattedContent.contains("embedSecret"));
	}

}