/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test spring-ai-test-timeout-pr using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=defaultConfig_254de96ad0
ROOST_METHOD_SIG_HASH=defaultConfig_93a2ea067a

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/spring-ai-test-timeout-pr/1e559eba-5752-4feb-88f7-63ae643c0140/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/transformer/splitter/TokenTextSplitterTest.java
Tests:
    "@Test
public void testTokenTextSplitterBuilderWithDefaultValues() {
    var contentFormatter1 = DefaultContentFormatter.defaultConfig();
    var contentFormatter2 = DefaultContentFormatter.defaultConfig();
    assertThat(contentFormatter1).isNotSameAs(contentFormatter2);
    var doc1 = new Document("In the end, writing arises when man realizes that memory is not enough.", Map.of("key1", "value1", "key2", "value2"));
    doc1.setContentFormatter(contentFormatter1);
    var doc2 = new Document("The most oppressive thing about the labyrinth is that you are constantly " + "being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.", Map.of("key2", "value22", "key3", "value3"));
    doc2.setContentFormatter(contentFormatter2);
    var tokenTextSplitter = new TokenTextSplitter();
    var chunks = tokenTextSplitter.apply(List.of(doc1, doc2));
    assertThat(chunks.size()).isEqualTo(2);

    assertThat(chunks.get(0).getText()).isEqualTo("In the end, writing arises when man realizes that memory is not enough.");

    assertThat(chunks.get(1).getText()).isEqualTo("The most oppressive thing about the labyrinth is that you are constantly being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.");
    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2").doesNotContainKeys("key3");
    assertThat(chunks.get(1).getMetadata()).containsKeys("key2", "key3").doesNotContainKeys("key1");
}
"
    "@Test
public void testTokenTextSplitterBuilderWithAllFields() {
    var contentFormatter1 = DefaultContentFormatter.defaultConfig();
    var contentFormatter2 = DefaultContentFormatter.defaultConfig();
    assertThat(contentFormatter1).isNotSameAs(contentFormatter2);
    var doc1 = new Document("In the end, writing arises when man realizes that memory is not enough.", Map.of("key1", "value1", "key2", "value2"));
    doc1.setContentFormatter(contentFormatter1);
    var doc2 = new Document("The most oppressive thing about the labyrinth is that you are constantly " + "being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.", Map.of("key2", "value22", "key3", "value3"));
    doc2.setContentFormatter(contentFormatter2);
    var tokenTextSplitter = TokenTextSplitter.builder().withChunkSize(10).withMinChunkSizeChars(5).withMinChunkLengthToEmbed(3).withMaxNumChunks(50).withKeepSeparator(true).build();
    var chunks = tokenTextSplitter.apply(List.of(doc1, doc2));
    assertThat(chunks.size()).isEqualTo(6);

    assertThat(chunks.get(0).getText()).isEqualTo("In the end, writing arises when man realizes that");
    assertThat(chunks.get(1).getText()).isEqualTo("memory is not enough.");

    assertThat(chunks.get(2).getText()).isEqualTo("The most oppressive thing about the labyrinth is that you");
    assertThat(chunks.get(3).getText()).isEqualTo("are constantly being forced to choose.");
    assertThat(chunks.get(4).getText()).isEqualTo("It isn’t the lack of an exit, but");
    assertThat(chunks.get(5).getText()).isEqualTo("the abundance of exits that is so disorienting");


    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(1).getMetadata()).containsKeys("key1", "key2", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(2).getMetadata()).containsKeys("key2", "key3", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(3).getMetadata()).containsKeys("key2", "key3", "parent_document_id", "chunk_index", "total_chunks");

    assertThat(chunks.get(0).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(1).getMetadata().get("chunk_index")).isEqualTo(1);
    assertThat(chunks.get(2).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(3).getMetadata().get("chunk_index")).isEqualTo(1);
    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2").doesNotContainKeys("key3");
    assertThat(chunks.get(2).getMetadata()).containsKeys("key2", "key3").doesNotContainKeys("key1");
}
"

File Path: /var/tmp/Roost/RoostGPT/spring-ai-test-timeout-pr/1e559eba-5752-4feb-88f7-63ae643c0140/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/document/ContentFormatterTests.java
Tests:
    "@Test
void defaultConfigTextFormatter() {
    DefaultContentFormatter defaultConfigFormatter = DefaultContentFormatter.defaultConfig();
    TextBlockAssertion.assertThat(this.document.getFormattedContent(defaultConfigFormatter, MetadataMode.ALL)).isEqualTo("""
        llmKey2: value4
        embedKey1: value1
        embedKey2: value2
        embedKey3: value3

        The World is Big and Salvation Lurks Around the Corner""");
    assertThat(this.document.getFormattedContent(defaultConfigFormatter, MetadataMode.ALL)).isEqualTo(this.document.getFormattedContent());
    assertThat(this.document.getFormattedContent(defaultConfigFormatter, MetadataMode.ALL)).isEqualTo(defaultConfigFormatter.format(this.document, MetadataMode.ALL));
}
"

File Path: /var/tmp/Roost/RoostGPT/spring-ai-test-timeout-pr/1e559eba-5752-4feb-88f7-63ae643c0140/source/spring-ai/spring-ai-commons/src/test/java/org/springframework/ai/transformer/splitter/TextSplitterTests.java
Tests:
    "@Test
public void testSplitText() {
    var contentFormatter1 = DefaultContentFormatter.defaultConfig();
    var contentFormatter2 = DefaultContentFormatter.defaultConfig();
    assertThat(contentFormatter1).isNotSameAs(contentFormatter2);
    var doc1 = new Document("In the end, writing arises when man realizes that memory is not enough.", Map.of("key1", "value1", "key2", "value2"));
    doc1.setContentFormatter(contentFormatter1);
    var doc2 = new Document("The most oppressive thing about the labyrinth is that you are constantly " + "being forced to choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.", Map.of("key2", "value22", "key3", "value3"));
    doc2.setContentFormatter(contentFormatter2);
    List<Document> chunks = testTextSplitter.apply(List.of(doc1, doc2));
    assertThat(testTextSplitter.isCopyContentFormatter()).isTrue();
    assertThat(chunks).hasSize(4);

    assertThat(chunks.get(0).getText()).isEqualTo("In the end, writing arises when man");
    assertThat(chunks.get(1).getText()).isEqualTo(" realizes that memory is not enough.");

    assertThat(chunks.get(2).getText()).isEqualTo("The most oppressive thing about the labyrinth is that you are constantly being forced to ");
    assertThat(chunks.get(3).getText()).isEqualTo("choose. It isn’t the lack of an exit, but the abundance of exits that is so disorienting.");


    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(1).getMetadata()).containsKeys("key1", "key2", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(2).getMetadata()).containsKeys("key2", "key3", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(3).getMetadata()).containsKeys("key2", "key3", "parent_document_id", "chunk_index", "total_chunks");

    assertThat(chunks.get(0).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(1).getMetadata().get("chunk_index")).isEqualTo(1);
    assertThat(chunks.get(2).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(3).getMetadata().get("chunk_index")).isEqualTo(1);
    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "key2").doesNotContainKeys("key3");
    assertThat(chunks.get(2).getMetadata()).containsKeys("key2", "key3").doesNotContainKeys("key1");


    assertThat(chunks.get(0).getContentFormatter()).isSameAs(contentFormatter1);
    assertThat(chunks.get(1).getContentFormatter()).isSameAs(contentFormatter1);
    assertThat(chunks.get(2).getContentFormatter()).isSameAs(contentFormatter2);
    assertThat(chunks.get(3).getContentFormatter()).isSameAs(contentFormatter2);

    testTextSplitter.setCopyContentFormatter(false);
    chunks = testTextSplitter.apply(List.of(doc1, doc2));
    assertThat(chunks.get(0).getContentFormatter()).isNotSameAs(contentFormatter1);
    assertThat(chunks.get(1).getContentFormatter()).isNotSameAs(contentFormatter1);
    assertThat(chunks.get(2).getContentFormatter()).isNotSameAs(contentFormatter2);
    assertThat(chunks.get(3).getContentFormatter()).isNotSameAs(contentFormatter2);
}
"
    "@Test
public void testSplitTextWithNullMetadata() {
    var contentFormatter = DefaultContentFormatter.defaultConfig();
    var doc = new Document("In the end, writing arises when man realizes that memory is not enough.");
    doc.getMetadata().put("key1", "value1");
    doc.getMetadata().put("key2", null);
    doc.setContentFormatter(contentFormatter);
    List<Document> chunks = testTextSplitter.apply(List.of(doc));
    assertThat(testTextSplitter.isCopyContentFormatter()).isTrue();
    assertThat(chunks).hasSize(2);

    assertThat(chunks.get(0).getText()).isEqualTo("In the end, writing arises when man");
    assertThat(chunks.get(1).getText()).isEqualTo(" realizes that memory is not enough.");


    assertThat(chunks.get(0).getMetadata()).containsKeys("key1", "parent_document_id", "chunk_index", "total_chunks");
    assertThat(chunks.get(1).getMetadata()).containsKeys("key1", "parent_document_id", "chunk_index", "total_chunks");

    assertThat(chunks.get(0).getMetadata().get("chunk_index")).isEqualTo(0);
    assertThat(chunks.get(1).getMetadata().get("chunk_index")).isEqualTo(1);

    assertThat(chunks.get(0).getContentFormatter()).isSameAs(contentFormatter);
    assertThat(chunks.get(1).getContentFormatter()).isSameAs(contentFormatter);
}
"Scenario 1: Verify defaultConfig Returns Non-Null Instance

Details:
  TestName: defaultConfigReturnsNonNullInstance
  Description: This test verifies that the defaultConfig() method returns a non-null DefaultContentFormatter instance. The method should always create and return a valid formatter object.
Execution:
  Arrange: No setup required as this is a static factory method with no dependencies.
  Act: Call DefaultContentFormatter.defaultConfig() to obtain a formatter instance.
  Assert: Verify that the returned instance is not null using assertNotNull.
Validation:
  The assertion confirms that the factory method successfully creates an object. This is fundamental to ensure the method fulfills its contract of providing a default configuration instance that can be used immediately.

---

Scenario 2: Verify defaultConfig Returns New Instance Each Call

Details:
  TestName: defaultConfigReturnsNewInstanceEachCall
  Description: This test ensures that each call to defaultConfig() returns a new, distinct instance of DefaultContentFormatter rather than a singleton or cached instance.
Execution:
  Arrange: No setup required.
  Act: Call DefaultContentFormatter.defaultConfig() twice to obtain two formatter instances.
  Assert: Verify that the two instances are not the same object reference using assertNotSame.
Validation:
  This validates that the method creates fresh instances, which is important for scenarios where different documents may need independent formatter configurations without affecting each other.

---

Scenario 3: Verify defaultConfig Returns Instance With Default Metadata Template

Details:
  TestName: defaultConfigHasDefaultMetadataTemplate
  Description: This test verifies that the DefaultContentFormatter returned by defaultConfig() has the expected default metadata template format "{key}: {value}".
Execution:
  Arrange: No setup required.
  Act: Call DefaultContentFormatter.defaultConfig() and retrieve the metadataTemplate using getMetadataTemplate().
  Assert: Verify that the metadata template equals "{key}: {value}".
Validation:
  This confirms that the default configuration uses the standard metadata template format, which is essential for consistent document formatting across the application.

---

Scenario 4: Verify defaultConfig Returns Instance With Default Metadata Separator

Details:
  TestName: defaultConfigHasDefaultMetadataSeparator
  Description: This test verifies that the DefaultContentFormatter returned by defaultConfig() uses System.lineSeparator() as the default metadata separator.
Execution:
  Arrange: No setup required.
  Act: Call DefaultContentFormatter.defaultConfig() and retrieve the metadataSeparator using getMetadataSeparator().
  Assert: Verify that the metadata separator equals System.lineSeparator().
Validation:
  This ensures that metadata entries are separated by the system's line separator, providing platform-appropriate formatting for document content.

---

Scenario 5: Verify defaultConfig Returns Instance With Default Text Template

Details:
  TestName: defaultConfigHasDefaultTextTemplate
  Description: This test verifies that the DefaultContentFormatter returned by defaultConfig() has the expected default text template format "{metadata_string}\n\n{content}".
Execution:
  Arrange: No setup required.
  Act: Call DefaultContentFormatter.defaultConfig() and retrieve the textTemplate using getTextTemplate().
  Assert: Verify that the text template equals "{metadata_string}\n\n{content}".
Validation:
  This confirms that the default text template places metadata before content with proper spacing, which is the expected standard format for document representation.

---

Scenario 6: Verify defaultConfig Returns Instance With Empty Excluded Inference Metadata Keys

Details:
  TestName: defaultConfigHasEmptyExcludedInferenceMetadataKeys
  Description: This test verifies that the DefaultContentFormatter returned by defaultConfig() has an empty list of excluded inference metadata keys by default.
Execution:
  Arrange: No setup required.
  Act: Call DefaultContentFormatter.defaultConfig() and retrieve the excludedInferenceMetadataKeys using getExcludedInferenceMetadataKeys().
  Assert: Verify that the list is empty using assertTrue with isEmpty().
Validation:
  This ensures that by default, no metadata keys are excluded from inference processing, allowing all metadata to be included unless explicitly configured otherwise.

---

Scenario 7: Verify defaultConfig Returns Instance With Empty Excluded Embed Metadata Keys

Details:
  TestName: defaultConfigHasEmptyExcludedEmbedMetadataKeys
  Description: This test verifies that the DefaultContentFormatter returned by defaultConfig() has an empty list of excluded embed metadata keys by default.
Execution:
  Arrange: No setup required.
  Act: Call DefaultContentFormatter.defaultConfig() and retrieve the excludedEmbedMetadataKeys using getExcludedEmbedMetadataKeys().
  Assert: Verify that the list is empty using assertTrue with isEmpty().
Validation:
  This ensures that by default, no metadata keys are excluded from embedding processing, allowing all metadata to be included in embeddings unless explicitly configured otherwise.

---

Scenario 8: Verify defaultConfig Instance Implements ContentFormatter Interface

Details:
  TestName: defaultConfigImplementsContentFormatterInterface
  Description: This test verifies that the instance returned by defaultConfig() is an implementation of the ContentFormatter interface.
Execution:
  Arrange: No setup required.
  Act: Call DefaultContentFormatter.defaultConfig() to obtain a formatter instance.
  Assert: Verify that the instance is of type ContentFormatter using assertInstanceOf or assertTrue with instanceof check.
Validation:
  This confirms that the returned object adheres to the ContentFormatter contract, ensuring it can be used polymorphically wherever ContentFormatter is expected.

---

Scenario 9: Verify defaultConfig Excluded Inference Metadata Keys List Is Unmodifiable

Details:
  TestName: defaultConfigExcludedInferenceMetadataKeysIsUnmodifiable
  Description: This test verifies that the list of excluded inference metadata keys returned by the default configuration is unmodifiable to prevent external modification.
Execution:
  Arrange: Call DefaultContentFormatter.defaultConfig() to obtain a formatter instance.
  Act: Attempt to add an element to the excludedInferenceMetadataKeys list obtained via getExcludedInferenceMetadataKeys().
  Assert: Verify that an UnsupportedOperationException is thrown when attempting to modify the list.
Validation:
  This ensures immutability of the configuration, preventing accidental or malicious modification of the formatter's state after creation.

---

Scenario 10: Verify defaultConfig Excluded Embed Metadata Keys List Is Unmodifiable

Details:
  TestName: defaultConfigExcludedEmbedMetadataKeysIsUnmodifiable
  Description: This test verifies that the list of excluded embed metadata keys returned by the default configuration is unmodifiable to prevent external modification.
Execution:
  Arrange: Call DefaultContentFormatter.defaultConfig() to obtain a formatter instance.
  Act: Attempt to add an element to the excludedEmbedMetadataKeys list obtained via getExcludedEmbedMetadataKeys().
  Assert: Verify that an UnsupportedOperationException is thrown when attempting to modify the list.
Validation:
  This ensures immutability of the configuration, preventing accidental or malicious modification of the formatter's state after creation.

---

Scenario 11: Verify defaultConfig Can Be Used As Base For Builder Customization

Details:
  TestName: defaultConfigCanBeUsedAsBaseForBuilderCustomization
  Description: This test verifies that a default configuration can be used as a starting point for creating customized configurations using the Builder's from() method.
Execution:
  Arrange: Call DefaultContentFormatter.defaultConfig() to obtain a base formatter instance.
  Act: Create a new formatter using DefaultContentFormatter.builder().from(baseFormatter).withMetadataSeparator(", ").build().
  Assert: Verify that the new formatter has the custom separator ", " while retaining other default values.
Validation:
  This confirms that the default configuration can serve as a template for creating variations, supporting the builder pattern's flexibility while maintaining sensible defaults.

---

Scenario 12: Verify Multiple defaultConfig Instances Have Identical Default Values

Details:
  TestName: multipleDefaultConfigInstancesHaveIdenticalDefaultValues
  Description: This test verifies that multiple instances created via defaultConfig() have identical default configuration values, ensuring consistency.
Execution:
  Arrange: No setup required.
  Act: Call DefaultContentFormatter.defaultConfig() twice to obtain two formatter instances.
  Assert: Verify that both instances have equal metadataTemplate, metadataSeparator, textTemplate, excludedInferenceMetadataKeys, and excludedEmbedMetadataKeys values.
Validation:
  This ensures that the factory method produces consistent configurations, which is critical for predictable behavior across the application when using default settings.

*/

// ********RoostGPT********

package org.springframework.ai.document;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.util.Assert;

class DefaultContentFormatterDefaultConfigTest {

	@Test
	@Tag("valid")
	void defaultConfigReturnsNonNullInstance() {
		// Arrange - No setup required
		// Act
		DefaultContentFormatter formatter = DefaultContentFormatter.defaultConfig();
		// Assert
		assertNotNull(formatter, "defaultConfig() should return a non-null instance");
	}

	@Test
	@Tag("valid")
	void defaultConfigReturnsNewInstanceEachCall() {
		// Arrange - No setup required
		// Act
		DefaultContentFormatter formatter1 = DefaultContentFormatter.defaultConfig();
		DefaultContentFormatter formatter2 = DefaultContentFormatter.defaultConfig();
		// Assert
		assertNotSame(formatter1, formatter2, "Each call to defaultConfig() should return a new instance");
	}

	@Test
	@Tag("valid")
	void defaultConfigHasDefaultMetadataTemplate() {
		// Arrange - No setup required
		// Act
		DefaultContentFormatter formatter = DefaultContentFormatter.defaultConfig();
		String metadataTemplate = formatter.getMetadataTemplate();
		// Assert
		assertEquals("{key}: {value}", metadataTemplate, "Default metadata template should be '{key}: {value}'");
	}

	@Test
	@Tag("valid")
	void defaultConfigHasDefaultMetadataSeparator() {
		// Arrange - No setup required
		// Act
		DefaultContentFormatter formatter = DefaultContentFormatter.defaultConfig();
		String metadataSeparator = formatter.getMetadataSeparator();
		// Assert
		assertEquals(System.lineSeparator(), metadataSeparator,
				"Default metadata separator should be System.lineSeparator()");
	}

	@Test
	@Tag("valid")
	void defaultConfigHasDefaultTextTemplate() {
		// Arrange - No setup required
		// Act
		DefaultContentFormatter formatter = DefaultContentFormatter.defaultConfig();
		String textTemplate = formatter.getTextTemplate();
		// Assert
		assertEquals("{metadata_string}\n\n{content}", textTemplate,
				"Default text template should be '{metadata_string}\\n\\n{content}'");
	}

	@Test
	@Tag("valid")
	void defaultConfigHasEmptyExcludedInferenceMetadataKeys() {
		// Arrange - No setup required
		// Act
		DefaultContentFormatter formatter = DefaultContentFormatter.defaultConfig();
		List<String> excludedInferenceMetadataKeys = formatter.getExcludedInferenceMetadataKeys();
		// Assert
		assertNotNull(excludedInferenceMetadataKeys, "Excluded inference metadata keys list should not be null");
		assertTrue(excludedInferenceMetadataKeys.isEmpty(), "Default excluded inference metadata keys should be empty");
	}

	@Test
	@Tag("valid")
	void defaultConfigHasEmptyExcludedEmbedMetadataKeys() {
		// Arrange - No setup required
		// Act
		DefaultContentFormatter formatter = DefaultContentFormatter.defaultConfig();
		List<String> excludedEmbedMetadataKeys = formatter.getExcludedEmbedMetadataKeys();
		// Assert
		assertNotNull(excludedEmbedMetadataKeys, "Excluded embed metadata keys list should not be null");
		assertTrue(excludedEmbedMetadataKeys.isEmpty(), "Default excluded embed metadata keys should be empty");
	}

	@Test
	@Tag("valid")
	void defaultConfigImplementsContentFormatterInterface() {
		// Arrange - No setup required
		// Act
		DefaultContentFormatter formatter = DefaultContentFormatter.defaultConfig();
		// Assert
		assertInstanceOf(ContentFormatter.class, formatter,
				"DefaultContentFormatter should implement ContentFormatter interface");
	}

	@Test
	@Tag("boundary")
	void defaultConfigExcludedInferenceMetadataKeysIsUnmodifiable() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.defaultConfig();
		List<String> excludedInferenceMetadataKeys = formatter.getExcludedInferenceMetadataKeys();
		// Act & Assert
		assertThrows(UnsupportedOperationException.class, () -> {
			excludedInferenceMetadataKeys.add("testKey");
		}, "Excluded inference metadata keys list should be unmodifiable");
	}

	@Test
	@Tag("boundary")
	void defaultConfigExcludedEmbedMetadataKeysIsUnmodifiable() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.defaultConfig();
		List<String> excludedEmbedMetadataKeys = formatter.getExcludedEmbedMetadataKeys();
		// Act & Assert
		assertThrows(UnsupportedOperationException.class, () -> {
			excludedEmbedMetadataKeys.add("testKey");
		}, "Excluded embed metadata keys list should be unmodifiable");
	}

	@Test
	@Tag("integration")
	void defaultConfigCanBeUsedAsBaseForBuilderCustomization() {
		// Arrange
		DefaultContentFormatter baseFormatter = DefaultContentFormatter.defaultConfig();
		String customSeparator = ", ";
		// Act
		DefaultContentFormatter customFormatter = DefaultContentFormatter.builder()
			.from(baseFormatter)
			.withMetadataSeparator(customSeparator)
			.build();
		// Assert
		assertEquals(customSeparator, customFormatter.getMetadataSeparator(), "Custom separator should be applied");
		assertEquals(baseFormatter.getMetadataTemplate(), customFormatter.getMetadataTemplate(),
				"Metadata template should be retained from base");
		assertEquals(baseFormatter.getTextTemplate(), customFormatter.getTextTemplate(),
				"Text template should be retained from base");
		assertEquals(baseFormatter.getExcludedInferenceMetadataKeys(),
				customFormatter.getExcludedInferenceMetadataKeys(),
				"Excluded inference metadata keys should be retained from base");
		assertEquals(baseFormatter.getExcludedEmbedMetadataKeys(), customFormatter.getExcludedEmbedMetadataKeys(),
				"Excluded embed metadata keys should be retained from base");
	}

	@Test
	@Tag("valid")
	void multipleDefaultConfigInstancesHaveIdenticalDefaultValues() {
		// Arrange - No setup required
		// Act
		DefaultContentFormatter formatter1 = DefaultContentFormatter.defaultConfig();
		DefaultContentFormatter formatter2 = DefaultContentFormatter.defaultConfig();
		// Assert
		assertEquals(formatter1.getMetadataTemplate(), formatter2.getMetadataTemplate(),
				"Metadata templates should be identical");
		assertEquals(formatter1.getMetadataSeparator(), formatter2.getMetadataSeparator(),
				"Metadata separators should be identical");
		assertEquals(formatter1.getTextTemplate(), formatter2.getTextTemplate(), "Text templates should be identical");
		assertEquals(formatter1.getExcludedInferenceMetadataKeys(), formatter2.getExcludedInferenceMetadataKeys(),
				"Excluded inference metadata keys should be identical");
		assertEquals(formatter1.getExcludedEmbedMetadataKeys(), formatter2.getExcludedEmbedMetadataKeys(),
				"Excluded embed metadata keys should be identical");
	}

}