/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test spring-ai-test-timeout-pr using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=getMetadataTemplate_b99aec5a71
ROOST_METHOD_SIG_HASH=getMetadataTemplate_2904c8ef73

Scenario 1: Verify Default Metadata Template Is Returned When Using Default Configuration

Details:
  TestName: getMetadataTemplateReturnsDefaultValueWhenUsingDefaultConfig
  Description: This test verifies that when a DefaultContentFormatter is created using the default configuration (via defaultConfig() method), the getMetadataTemplate() method returns the default metadata template which is "{key}: {value}".

Execution:
  Arrange: Create a DefaultContentFormatter instance using the defaultConfig() static method.
  Act: Invoke the getMetadataTemplate() method on the formatter instance.
  Assert: Verify that the returned string equals "{key}: {value}".

Validation:
  The assertion confirms that the default metadata template follows the expected format with key and value placeholders. This is significant because it ensures that when no custom template is provided, the formatter uses a sensible default that formats metadata as "key: value" pairs.

---

Scenario 2: Verify Custom Metadata Template Is Returned When Set Via Builder

Details:
  TestName: getMetadataTemplateReturnsCustomValueWhenSetViaBuilder
  Description: This test verifies that when a custom metadata template is configured using the Builder's withMetadataTemplate() method, the getMetadataTemplate() method returns that custom template.

Execution:
  Arrange: Create a DefaultContentFormatter instance using the builder pattern with a custom metadata template such as "{key}={value}".
  Act: Invoke the getMetadataTemplate() method on the formatter instance.
  Assert: Verify that the returned string equals the custom template "{key}={value}".

Validation:
  The assertion confirms that the builder correctly sets the custom metadata template and that getMetadataTemplate() returns the configured value. This is important for users who need different formatting styles for their metadata.

---

Scenario 3: Verify Metadata Template With Complex Custom Format

Details:
  TestName: getMetadataTemplateReturnsComplexCustomFormat
  Description: This test verifies that the getMetadataTemplate() method correctly returns a more complex custom metadata template that includes additional characters and formatting.

Execution:
  Arrange: Create a DefaultContentFormatter instance using the builder with a complex template such as "[{key}] -> '{value}'".
  Act: Invoke the getMetadataTemplate() method on the formatter instance.
  Assert: Verify that the returned string equals "[{key}] -> '{value}'".

Validation:
  The assertion confirms that complex metadata templates with special characters and formatting are preserved correctly. This validates that the formatter can handle various formatting requirements for different use cases.

---

Scenario 4: Verify Metadata Template Preservation When Using Builder From Method

Details:
  TestName: getMetadataTemplateIsPreservedWhenCopyingFromExistingFormatter
  Description: This test verifies that when creating a new formatter by copying from an existing one using the Builder's from() method, the metadata template is correctly preserved.

Execution:
  Arrange: Create an initial DefaultContentFormatter with a custom metadata template. Then create a second formatter using Builder.from() method with the first formatter.
  Act: Invoke the getMetadataTemplate() method on the second formatter instance.
  Assert: Verify that the returned string equals the custom template from the original formatter.

Validation:
  The assertion confirms that the from() method correctly copies the metadata template from an existing formatter. This is crucial for scenarios where users want to create variations of existing formatters while preserving certain configurations.

---

Scenario 5: Verify Metadata Template With Only Key Placeholder

Details:
  TestName: getMetadataTemplateReturnsTemplateWithOnlyKeyPlaceholder
  Description: This test verifies that a metadata template containing only the key placeholder (without value placeholder) is correctly stored and returned.

Execution:
  Arrange: Create a DefaultContentFormatter instance using the builder with a template containing only "{key}".
  Act: Invoke the getMetadataTemplate() method on the formatter instance.
  Assert: Verify that the returned string equals "{key}".

Validation:
  The assertion confirms that templates with partial placeholders are accepted and returned correctly. This tests edge cases where users might want unconventional metadata formatting.

---

Scenario 6: Verify Metadata Template With Only Value Placeholder

Details:
  TestName: getMetadataTemplateReturnsTemplateWithOnlyValuePlaceholder
  Description: This test verifies that a metadata template containing only the value placeholder (without key placeholder) is correctly stored and returned.

Execution:
  Arrange: Create a DefaultContentFormatter instance using the builder with a template containing only "{value}".
  Act: Invoke the getMetadataTemplate() method on the formatter instance.
  Assert: Verify that the returned string equals "{value}".

Validation:
  The assertion confirms that templates with only value placeholders are handled correctly. This validates flexibility in template configuration.

---

Scenario 7: Verify Metadata Template With Unicode Characters

Details:
  TestName: getMetadataTemplateReturnsTemplateWithUnicodeCharacters
  Description: This test verifies that a metadata template containing Unicode characters is correctly stored and returned by getMetadataTemplate().

Execution:
  Arrange: Create a DefaultContentFormatter instance using the builder with a template containing Unicode characters such as "键:{key} → 值:{value}".
  Act: Invoke the getMetadataTemplate() method on the formatter instance.
  Assert: Verify that the returned string equals "键:{key} → 值:{value}".

Validation:
  The assertion confirms that Unicode characters in metadata templates are preserved correctly. This is important for internationalization support.

---

Scenario 8: Verify Metadata Template With Whitespace Characters

Details:
  TestName: getMetadataTemplateReturnsTemplateWithWhitespaceCharacters
  Description: This test verifies that a metadata template containing various whitespace characters (tabs, newlines, spaces) is correctly stored and returned.

Execution:
  Arrange: Create a DefaultContentFormatter instance using the builder with a template containing whitespace such as "{key}\t:\t{value}\n".
  Act: Invoke the getMetadataTemplate() method on the formatter instance.
  Assert: Verify that the returned string equals "{key}\t:\t{value}\n".

Validation:
  The assertion confirms that whitespace characters in templates are preserved. This is important for formatting requirements that need specific spacing or line breaks.

---

Scenario 9: Verify Metadata Template Remains Unchanged After Multiple Calls

Details:
  TestName: getMetadataTemplateReturnsConsistentValueOnMultipleCalls
  Description: This test verifies that calling getMetadataTemplate() multiple times on the same formatter instance returns the same value consistently.

Execution:
  Arrange: Create a DefaultContentFormatter instance with a custom metadata template.
  Act: Invoke the getMetadataTemplate() method multiple times (at least 3 times) on the same formatter instance.
  Assert: Verify that all returned values are equal to each other and to the expected template.

Validation:
  The assertion confirms the immutability and consistency of the metadata template field. This is important for ensuring thread safety and predictable behavior in concurrent environments.

---

Scenario 10: Verify Metadata Template With Empty Placeholders Text

Details:
  TestName: getMetadataTemplateReturnsTemplateWithMinimalContent
  Description: This test verifies that a metadata template with minimal content (just the placeholders without any separator) is correctly returned.

Execution:
  Arrange: Create a DefaultContentFormatter instance using the builder with a minimal template "{key}{value}".
  Act: Invoke the getMetadataTemplate() method on the formatter instance.
  Assert: Verify that the returned string equals "{key}{value}".

Validation:
  The assertion confirms that minimal templates without separators between placeholders are handled correctly. This tests the boundary case of template formatting.

*/

// ********RoostGPT********

package org.springframework.ai.document;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.*;
import org.springframework.util.Assert;

class DefaultContentFormatterGetMetadataTemplateTest {

	@Test
	@Tag("valid")
	@DisplayName("Verify Default Metadata Template Is Returned When Using Default Configuration")
	void getMetadataTemplateReturnsDefaultValueWhenUsingDefaultConfig() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.defaultConfig();
		// Act
		String metadataTemplate = formatter.getMetadataTemplate();
		// Assert
		assertNotNull(metadataTemplate);
		assertEquals("{key}: {value}", metadataTemplate);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Custom Metadata Template Is Returned When Set Via Builder")
	void getMetadataTemplateReturnsCustomValueWhenSetViaBuilder() {
		// Arrange
		String customTemplate = "{key}={value}";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataTemplate(customTemplate)
			.build();
		// Act
		String metadataTemplate = formatter.getMetadataTemplate();
		// Assert
		assertNotNull(metadataTemplate);
		assertEquals(customTemplate, metadataTemplate);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Metadata Template With Complex Custom Format")
	void getMetadataTemplateReturnsComplexCustomFormat() {
		// Arrange
		String complexTemplate = "[{key}] -> '{value}'";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataTemplate(complexTemplate)
			.build();
		// Act
		String metadataTemplate = formatter.getMetadataTemplate();
		// Assert
		assertNotNull(metadataTemplate);
		assertEquals(complexTemplate, metadataTemplate);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Metadata Template Preservation When Using Builder From Method")
	void getMetadataTemplateIsPreservedWhenCopyingFromExistingFormatter() {
		// Arrange
		String customTemplate = "Custom: {key} => {value}";
		DefaultContentFormatter originalFormatter = DefaultContentFormatter.builder()
			.withMetadataTemplate(customTemplate)
			.build();
		DefaultContentFormatter copiedFormatter = DefaultContentFormatter.builder().from(originalFormatter).build();
		// Act
		String metadataTemplate = copiedFormatter.getMetadataTemplate();
		// Assert
		assertNotNull(metadataTemplate);
		assertEquals(customTemplate, metadataTemplate);
		assertEquals(originalFormatter.getMetadataTemplate(), metadataTemplate);
	}

	@Test
	@Tag("boundary")
	@DisplayName("Verify Metadata Template With Only Key Placeholder")
	void getMetadataTemplateReturnsTemplateWithOnlyKeyPlaceholder() {
		// Arrange
		String keyOnlyTemplate = "{key}";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataTemplate(keyOnlyTemplate)
			.build();
		// Act
		String metadataTemplate = formatter.getMetadataTemplate();
		// Assert
		assertNotNull(metadataTemplate);
		assertEquals(keyOnlyTemplate, metadataTemplate);
	}

	@Test
	@Tag("boundary")
	@DisplayName("Verify Metadata Template With Only Value Placeholder")
	void getMetadataTemplateReturnsTemplateWithOnlyValuePlaceholder() {
		// Arrange
		String valueOnlyTemplate = "{value}";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataTemplate(valueOnlyTemplate)
			.build();
		// Act
		String metadataTemplate = formatter.getMetadataTemplate();
		// Assert
		assertNotNull(metadataTemplate);
		assertEquals(valueOnlyTemplate, metadataTemplate);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Metadata Template With Unicode Characters")
	void getMetadataTemplateReturnsTemplateWithUnicodeCharacters() {
		// Arrange
		String unicodeTemplate = "键:{key} → 值:{value}";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataTemplate(unicodeTemplate)
			.build();
		// Act
		String metadataTemplate = formatter.getMetadataTemplate();
		// Assert
		assertNotNull(metadataTemplate);
		assertEquals(unicodeTemplate, metadataTemplate);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Metadata Template With Whitespace Characters")
	void getMetadataTemplateReturnsTemplateWithWhitespaceCharacters() {
		// Arrange
		String whitespaceTemplate = "{key}\t:\t{value}\n";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataTemplate(whitespaceTemplate)
			.build();
		// Act
		String metadataTemplate = formatter.getMetadataTemplate();
		// Assert
		assertNotNull(metadataTemplate);
		assertEquals(whitespaceTemplate, metadataTemplate);
	}

	@Test
	@Tag("valid")
	@DisplayName("Verify Metadata Template Remains Unchanged After Multiple Calls")
	void getMetadataTemplateReturnsConsistentValueOnMultipleCalls() {
		// Arrange
		String customTemplate = "Metadata: {key} - {value}";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataTemplate(customTemplate)
			.build();
		// Act
		String firstCall = formatter.getMetadataTemplate();
		String secondCall = formatter.getMetadataTemplate();
		String thirdCall = formatter.getMetadataTemplate();
		// Assert
		assertNotNull(firstCall);
		assertNotNull(secondCall);
		assertNotNull(thirdCall);
		assertEquals(customTemplate, firstCall);
		assertEquals(firstCall, secondCall);
		assertEquals(secondCall, thirdCall);
	}

	@Test
	@Tag("boundary")
	@DisplayName("Verify Metadata Template With Minimal Content")
	void getMetadataTemplateReturnsTemplateWithMinimalContent() {
		// Arrange
		String minimalTemplate = "{key}{value}";
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withMetadataTemplate(minimalTemplate)
			.build();
		// Act
		String metadataTemplate = formatter.getMetadataTemplate();
		// Assert
		assertNotNull(metadataTemplate);
		assertEquals(minimalTemplate, metadataTemplate);
	}

}