/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test spring-ai-test-timeout-pr using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=getExcludedInferenceMetadataKeys_50327b3aa2
ROOST_METHOD_SIG_HASH=getExcludedInferenceMetadataKeys_236829454a

Scenario 1: Verify that getExcludedInferenceMetadataKeys returns an empty list when no keys are configured

Details:
  TestName: getExcludedInferenceMetadataKeysReturnsEmptyListWhenNoKeysConfigured
  Description: This test verifies that when a DefaultContentFormatter is created using the default configuration (without specifying any excluded inference metadata keys), the getExcludedInferenceMetadataKeys method returns an empty list.
Execution:
  Arrange: Create a DefaultContentFormatter instance using the defaultConfig() static method.
  Act: Call the getExcludedInferenceMetadataKeys() method on the formatter instance.
  Assert: Verify that the returned list is empty using assertTrue with isEmpty().
Validation:
  The assertion confirms that the default configuration does not include any excluded inference metadata keys. This is important because it ensures that by default, all metadata keys are available for inference operations unless explicitly excluded.

---

Scenario 2: Verify that getExcludedInferenceMetadataKeys returns the configured keys when keys are specified

Details:
  TestName: getExcludedInferenceMetadataKeysReturnsConfiguredKeys
  Description: This test verifies that when a DefaultContentFormatter is built with specific excluded inference metadata keys, the getExcludedInferenceMetadataKeys method returns those exact keys.
Execution:
  Arrange: Create a DefaultContentFormatter using the builder pattern with withExcludedInferenceMetadataKeys specifying keys like "key1", "key2", "key3".
  Act: Call the getExcludedInferenceMetadataKeys() method on the formatter instance.
  Assert: Verify that the returned list contains exactly the configured keys and has the expected size of 3.
Validation:
  The assertion confirms that the builder correctly stores and the getter correctly retrieves the excluded inference metadata keys. This is critical for ensuring that metadata filtering works as expected during inference operations.

---

Scenario 3: Verify that getExcludedInferenceMetadataKeys returns an unmodifiable list

Details:
  TestName: getExcludedInferenceMetadataKeysReturnsUnmodifiableList
  Description: This test verifies that the list returned by getExcludedInferenceMetadataKeys is unmodifiable, meaning any attempt to modify it will throw an UnsupportedOperationException.
Execution:
  Arrange: Create a DefaultContentFormatter using the builder with at least one excluded inference metadata key.
  Act: Call getExcludedInferenceMetadataKeys() and attempt to add a new element to the returned list.
  Assert: Verify that an UnsupportedOperationException is thrown when attempting to modify the list.
Validation:
  The assertion confirms that the returned list is immutable, which is important for maintaining the integrity of the formatter's configuration. This prevents accidental or malicious modifications to the excluded keys after the formatter is created.

---

Scenario 4: Verify that getExcludedInferenceMetadataKeys returns a list with single key when one key is configured

Details:
  TestName: getExcludedInferenceMetadataKeysReturnsSingleKey
  Description: This test verifies that when only one excluded inference metadata key is configured, the getExcludedInferenceMetadataKeys method returns a list containing exactly that one key.
Execution:
  Arrange: Create a DefaultContentFormatter using the builder with withExcludedInferenceMetadataKeys specifying a single key "singleKey".
  Act: Call the getExcludedInferenceMetadataKeys() method on the formatter instance.
  Assert: Verify that the returned list has size 1 and contains "singleKey".
Validation:
  The assertion confirms that the method correctly handles the case of a single excluded key. This is a boundary condition test ensuring proper behavior with minimal configuration.

---

Scenario 5: Verify that getExcludedInferenceMetadataKeys preserves the order of configured keys

Details:
  TestName: getExcludedInferenceMetadataKeysPreservesKeyOrder
  Description: This test verifies that the list returned by getExcludedInferenceMetadataKeys maintains the same order as the keys were configured in the builder.
Execution:
  Arrange: Create a DefaultContentFormatter using the builder with withExcludedInferenceMetadataKeys specifying keys in a specific order: "alpha", "beta", "gamma".
  Act: Call the getExcludedInferenceMetadataKeys() method on the formatter instance.
  Assert: Verify that the returned list contains keys in the exact order: index 0 is "alpha", index 1 is "beta", index 2 is "gamma".
Validation:
  The assertion confirms that the order of keys is preserved, which may be important for consistent behavior and debugging. This ensures predictable iteration over excluded keys.

---

Scenario 6: Verify that getExcludedInferenceMetadataKeys works correctly when configured via List parameter

Details:
  TestName: getExcludedInferenceMetadataKeysWorksWithListParameter
  Description: This test verifies that when excluded inference metadata keys are configured using a List parameter in the builder, the getExcludedInferenceMetadataKeys method returns the correct keys.
Execution:
  Arrange: Create an ArrayList containing keys "listKey1" and "listKey2", then create a DefaultContentFormatter using the builder with withExcludedInferenceMetadataKeys(List) method.
  Act: Call the getExcludedInferenceMetadataKeys() method on the formatter instance.
  Assert: Verify that the returned list contains both "listKey1" and "listKey2" and has size 2.
Validation:
  The assertion confirms that the builder correctly accepts and stores keys provided as a List. This tests an alternative configuration method and ensures flexibility in how keys can be specified.

---

Scenario 7: Verify that getExcludedInferenceMetadataKeys returns independent copy from builder modifications

Details:
  TestName: getExcludedInferenceMetadataKeysReturnsIndependentList
  Description: This test verifies that the list returned by getExcludedInferenceMetadataKeys is independent of the original list used during construction, ensuring encapsulation.
Execution:
  Arrange: Create a mutable ArrayList with keys, use it to build a DefaultContentFormatter, then modify the original ArrayList by adding more keys.
  Act: Call the getExcludedInferenceMetadataKeys() method on the formatter instance.
  Assert: Verify that the returned list only contains the original keys and not the keys added after construction.
Validation:
  The assertion confirms proper encapsulation - modifications to the source list after formatter creation do not affect the formatter's internal state. This is crucial for maintaining immutability and thread safety.

---

Scenario 8: Verify that getExcludedInferenceMetadataKeys works correctly after using from() builder method

Details:
  TestName: getExcludedInferenceMetadataKeysWorksAfterFromMethod
  Description: This test verifies that when a DefaultContentFormatter is created by copying from another formatter using the from() builder method, the getExcludedInferenceMetadataKeys returns the same keys as the source formatter.
Execution:
  Arrange: Create a source DefaultContentFormatter with specific excluded inference metadata keys, then create a new formatter using builder().from(sourceFormatter).build().
  Act: Call getExcludedInferenceMetadataKeys() on both the source and the copied formatter.
  Assert: Verify that both lists contain the same keys and have the same size.
Validation:
  The assertion confirms that the from() method correctly copies the excluded inference metadata keys configuration. This is important for scenarios where formatters need to be cloned or modified based on existing configurations.

---

Scenario 9: Verify that getExcludedInferenceMetadataKeys handles duplicate keys in configuration

Details:
  TestName: getExcludedInferenceMetadataKeysHandlesDuplicateKeys
  Description: This test verifies the behavior of getExcludedInferenceMetadataKeys when duplicate keys are provided during configuration using the varargs method multiple times.
Execution:
  Arrange: Create a DefaultContentFormatter using the builder, calling withExcludedInferenceMetadataKeys("key1", "key2") followed by another call withExcludedInferenceMetadataKeys("key2", "key3").
  Act: Call the getExcludedInferenceMetadataKeys() method on the formatter instance.
  Assert: Verify that the returned list contains all added keys including duplicates (size should be 4 with "key2" appearing twice).
Validation:
  The assertion documents the actual behavior when duplicate keys are added. Understanding this behavior is important for users who may inadvertently add duplicate keys and need to know whether deduplication occurs.

---

Scenario 10: Verify that getExcludedInferenceMetadataKeys returns list that cannot be cleared

Details:
  TestName: getExcludedInferenceMetadataKeysCannotBeCleared
  Description: This test verifies that attempting to clear the list returned by getExcludedInferenceMetadataKeys throws an UnsupportedOperationException.
Execution:
  Arrange: Create a DefaultContentFormatter with excluded inference metadata keys configured.
  Act: Call getExcludedInferenceMetadataKeys() and attempt to call clear() on the returned list.
  Assert: Verify that an UnsupportedOperationException is thrown.
Validation:
  The assertion confirms that the clear operation is not permitted on the returned list, reinforcing the immutability guarantee. This protects the formatter's configuration from being inadvertently emptied.

*/

// ********RoostGPT********

package org.springframework.ai.document;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import org.springframework.util.Assert;

class DefaultContentFormatterGetExcludedInferenceMetadataKeysTest {

	@Test
	@Tag("valid")
	void getExcludedInferenceMetadataKeysReturnsEmptyListWhenNoKeysConfigured() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.defaultConfig();
		// Act
		List<String> result = formatter.getExcludedInferenceMetadataKeys();
		// Assert
		assertTrue(result.isEmpty());
	}

	@Test
	@Tag("valid")
	void getExcludedInferenceMetadataKeysReturnsConfiguredKeys() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys("key1", "key2", "key3")
			.build();
		// Act
		List<String> result = formatter.getExcludedInferenceMetadataKeys();
		// Assert
		assertEquals(3, result.size());
		assertTrue(result.contains("key1"));
		assertTrue(result.contains("key2"));
		assertTrue(result.contains("key3"));
	}

	@Test
	@Tag("valid")
	void getExcludedInferenceMetadataKeysReturnsUnmodifiableList() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys("key1")
			.build();
		// Act
		List<String> result = formatter.getExcludedInferenceMetadataKeys();
		// Assert
		assertThrows(UnsupportedOperationException.class, () -> result.add("newKey"));
	}

	@Test
	@Tag("boundary")
	void getExcludedInferenceMetadataKeysReturnsSingleKey() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys("singleKey")
			.build();
		// Act
		List<String> result = formatter.getExcludedInferenceMetadataKeys();
		// Assert
		assertEquals(1, result.size());
		assertTrue(result.contains("singleKey"));
	}

	@Test
	@Tag("valid")
	void getExcludedInferenceMetadataKeysPreservesKeyOrder() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys("alpha", "beta", "gamma")
			.build();
		// Act
		List<String> result = formatter.getExcludedInferenceMetadataKeys();
		// Assert
		assertEquals("alpha", result.get(0));
		assertEquals("beta", result.get(1));
		assertEquals("gamma", result.get(2));
	}

	@Test
	@Tag("valid")
	void getExcludedInferenceMetadataKeysWorksWithListParameter() {
		// Arrange
		List<String> keysList = new ArrayList<>();
		keysList.add("listKey1");
		keysList.add("listKey2");

		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys(keysList)
			.build();
		// Act
		List<String> result = formatter.getExcludedInferenceMetadataKeys();
		// Assert
		assertEquals(2, result.size());
		assertTrue(result.contains("listKey1"));
		assertTrue(result.contains("listKey2"));
	}

	@Test
	@Tag("valid")
	void getExcludedInferenceMetadataKeysReturnsIndependentList() {
		// Arrange
		List<String> originalList = new ArrayList<>();
		originalList.add("originalKey1");
		originalList.add("originalKey2");

		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys(originalList)
			.build();

		// Modify original list after construction
		originalList.add("addedAfterConstruction");
		// Act
		List<String> result = formatter.getExcludedInferenceMetadataKeys();
		// Assert
		assertEquals(2, result.size());
		assertTrue(result.contains("originalKey1"));
		assertTrue(result.contains("originalKey2"));
		assertFalse(result.contains("addedAfterConstruction"));
	}

	@Test
	@Tag("integration")
	void getExcludedInferenceMetadataKeysWorksAfterFromMethod() {
		// Arrange
		DefaultContentFormatter sourceFormatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys("sourceKey1", "sourceKey2")
			.build();

		DefaultContentFormatter copiedFormatter = DefaultContentFormatter.builder().from(sourceFormatter).build();
		// Act
		List<String> sourceResult = sourceFormatter.getExcludedInferenceMetadataKeys();
		List<String> copiedResult = copiedFormatter.getExcludedInferenceMetadataKeys();
		// Assert
		assertEquals(sourceResult.size(), copiedResult.size());
		assertTrue(copiedResult.containsAll(sourceResult));
		assertTrue(sourceResult.containsAll(copiedResult));
	}

	@Test
	@Tag("boundary")
	void getExcludedInferenceMetadataKeysHandlesDuplicateKeys() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys("key1", "key2")
			.withExcludedInferenceMetadataKeys("key2", "key3")
			.build();
		// Act
		List<String> result = formatter.getExcludedInferenceMetadataKeys();
		// Assert
		assertEquals(4, result.size());
		assertTrue(result.contains("key1"));
		assertTrue(result.contains("key2"));
		assertTrue(result.contains("key3"));
		assertEquals(2, Collections.frequency(result, "key2"));
	}

	@Test
	@Tag("valid")
	void getExcludedInferenceMetadataKeysCannotBeCleared() {
		// Arrange
		DefaultContentFormatter formatter = DefaultContentFormatter.builder()
			.withExcludedInferenceMetadataKeys("key1", "key2")
			.build();
		// Act
		List<String> result = formatter.getExcludedInferenceMetadataKeys();
		// Assert
		assertThrows(UnsupportedOperationException.class, () -> result.clear());
	}

}