/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-spring-ai using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=doNot_82558cd573
ROOST_METHOD_SIG_HASH=doNot_ecb1a8c56c

Scenario 1: Valid NOT Expression with Left Operand

Details:
  TestName: notExpressionWithValidLeftOperand
  Description: This test verifies that the doNot method correctly processes a valid NOT expression by appending "NOT " to the context and converting the left operand. The test ensures that when a NOT expression type is provided, the method successfully builds the expected string representation.
Execution:
  Arrange: Create a mock Expression object with type NOT and a valid left operand (e.g., a Key or another Expression). Initialize a StringBuilder as the context. Set up the Neo4jVectorFilterExpressionConverter instance.
  Act: Invoke the doNot method with the NOT expression and the StringBuilder context.
  Assert: Verify that the context StringBuilder contains "NOT " followed by the converted left operand string representation.
Validation:
  The assertion verifies that the method correctly appends the "NOT " prefix and processes the left operand through the convertOperand method. This is essential for generating proper Neo4j filter expressions that negate conditions. The test ensures the basic functionality of the NOT operator conversion works as expected.

Scenario 2: Invalid Expression Type - Non-NOT Expression

Details:
  TestName: notExpressionWithInvalidExpressionType
  Description: This test validates that the doNot method throws a RuntimeException when provided with an expression type other than NOT. This ensures proper error handling and prevents incorrect filter generation.
Execution:
  Arrange: Create a mock Expression object with a type different from NOT (e.g., AND, OR, EQ, etc.). Initialize a StringBuilder as the context. Set up the Neo4jVectorFilterExpressionConverter instance.
  Act: Invoke the doNot method with the non-NOT expression and the StringBuilder context.
  Assert: Verify that a RuntimeException is thrown with a message indicating "Unsupported expression type %s. Only NOT is supported here" formatted with the actual expression type.
Validation:
  This assertion ensures that the method enforces type safety and only processes NOT expressions. The test is critical for preventing runtime errors and ensuring that the method contract is respected. It validates the defensive programming approach used in the implementation.

Scenario 3: NOT Expression with Key as Left Operand

Details:
  TestName: notExpressionWithKeyOperand
  Description: This test checks that the doNot method correctly handles a NOT expression where the left operand is a Key object. It verifies the integration between doNot and the convertOperand method for Key types.
Execution:
  Arrange: Create a NOT Expression with a Key object as the left operand (e.g., new Key("fieldName")). Initialize a StringBuilder as the context. Set up the Neo4jVectorFilterExpressionConverter instance.
  Act: Invoke the doNot method with the NOT expression containing the Key operand.
  Assert: Verify that the context contains "NOT " followed by the properly formatted key representation (e.g., "NOT node.`metadata.fieldName`").
Validation:
  This test validates that the doNot method works correctly with Key operands, which are common in filter expressions. It ensures that the convertOperand method is properly invoked and that the resulting string follows Neo4j's property access syntax. This is important for real-world usage where NOT operations are applied to field conditions.

Scenario 4: NOT Expression with Nested Expression as Left Operand

Details:
  TestName: notExpressionWithNestedExpression
  Description: This test verifies that the doNot method can handle complex scenarios where the left operand is itself another Expression (e.g., an equality or comparison expression). This tests the recursive nature of expression conversion.
Execution:
  Arrange: Create a NOT Expression with a nested Expression as the left operand (e.g., an EQ expression comparing a Key to a value). Initialize a StringBuilder as the context. Set up the Neo4jVectorFilterExpressionConverter instance.
  Act: Invoke the doNot method with the NOT expression containing the nested expression.
  Assert: Verify that the context contains "NOT " followed by the properly converted nested expression (e.g., "NOT (node.`metadata.field` = value)").
Validation:
  This assertion ensures that the doNot method correctly delegates to convertOperand for complex nested expressions. This is crucial for handling sophisticated filter conditions where NOT is applied to compound expressions. The test validates the method's ability to work within the broader expression conversion framework.

Scenario 5: NOT Expression with Group as Left Operand

Details:
  TestName: notExpressionWithGroupOperand
  Description: This test validates that the doNot method correctly processes a NOT expression where the left operand is a Group containing multiple expressions. This ensures proper handling of grouped conditions.
Execution:
  Arrange: Create a NOT Expression with a Group object as the left operand, where the Group contains multiple sub-expressions. Initialize a StringBuilder as the context. Set up the Neo4jVectorFilterExpressionConverter instance.
  Act: Invoke the doNot method with the NOT expression containing the Group operand.
  Assert: Verify that the context contains "NOT " followed by the properly formatted group with parentheses (e.g., "NOT (expression1 AND expression2)").
Validation:
  This test ensures that the doNot method works correctly with grouped expressions, which is essential for complex filter logic. It validates that the convertOperand method properly handles Group types and that the resulting string maintains proper precedence through parentheses. This is important for generating semantically correct Neo4j queries.

Scenario 6: Empty StringBuilder Context

Details:
  TestName: notExpressionWithEmptyContext
  Description: This test verifies that the doNot method works correctly when the StringBuilder context is empty at the start of the method invocation. This represents the typical initial state.
Execution:
  Arrange: Create a valid NOT Expression with a simple left operand. Initialize an empty StringBuilder as the context. Set up the Neo4jVectorFilterExpressionConverter instance.
  Act: Invoke the doNot method with the NOT expression and empty StringBuilder.
  Assert: Verify that the context starts with "NOT " and contains the converted operand without any preceding content.
Validation:
  This assertion validates that the method correctly initializes the context with the NOT prefix when starting from an empty state. This is the most common use case and ensures that the method doesn't depend on any pre-existing context content. It's fundamental for verifying the method's standalone functionality.

Scenario 7: NOT Expression with Non-Empty StringBuilder Context

Details:
  TestName: notExpressionWithExistingContext
  Description: This test checks that the doNot method correctly appends to an existing StringBuilder context that already contains content. This simulates scenarios where NOT is part of a larger expression chain.
Execution:
  Arrange: Create a valid NOT Expression with a left operand. Initialize a StringBuilder with pre-existing content (e.g., "WHERE "). Set up the Neo4jVectorFilterExpressionConverter instance.
  Act: Invoke the doNot method with the NOT expression and the non-empty StringBuilder.
  Assert: Verify that the context contains the original content followed by "NOT " and the converted operand (e.g., "WHERE NOT node.`metadata.field`").
Validation:
  This test ensures that the doNot method properly appends to existing context without overwriting or corrupting previous content. This is important for building complex filter expressions where NOT is combined with other operators. It validates the method's behavior in a realistic expression-building scenario.

Scenario 8: NOT Expression Type Validation with NULL Expression

Details:
  TestName: notExpressionWithNullExpression
  Description: This test verifies the method's behavior when a null expression is passed, ensuring proper null handling or appropriate exception throwing.
Execution:
  Arrange: Set up a null Expression object. Initialize a StringBuilder as the context. Set up the Neo4jVectorFilterExpressionConverter instance.
  Act: Invoke the doNot method with the null expression and StringBuilder context.
  Assert: Verify that either a NullPointerException or RuntimeException is thrown, or that the method handles null gracefully based on the implementation's null-handling strategy.
Validation:
  This test validates the method's robustness in handling null inputs, which could occur due to programming errors or unexpected data. It ensures that the method fails fast with a clear error rather than producing invalid output. This is important for debugging and maintaining code quality.

Scenario 9: NOT Expression with AND Expression as Left Operand

Details:
  TestName: notExpressionWithAndOperand
  Description: This test specifically validates that the doNot method correctly handles a NOT expression where the left operand is an AND expression combining multiple conditions.
Execution:
  Arrange: Create a NOT Expression with an AND Expression as the left operand (e.g., field1 = value1 AND field2 = value2). Initialize a StringBuilder as the context. Set up the Neo4jVectorFilterExpressionConverter instance.
  Act: Invoke the doNot method with the NOT expression containing the AND expression.
  Assert: Verify that the context contains "NOT " followed by the properly formatted AND expression with all its components.
Validation:
  This assertion ensures that the doNot method correctly handles logical AND operations within NOT expressions, which is common in filter logic (De Morgan's laws). It validates that the method maintains the correct logical structure and that the convertOperand method properly processes complex logical expressions.

Scenario 10: NOT Expression with OR Expression as Left Operand

Details:
  TestName: notExpressionWithOrOperand
  Description: This test validates that the doNot method correctly processes a NOT expression where the left operand is an OR expression combining multiple conditions.
Execution:
  Arrange: Create a NOT Expression with an OR Expression as the left operand (e.g., field1 = value1 OR field2 = value2). Initialize a StringBuilder as the context. Set up the Neo4jVectorFilterExpressionConverter instance.
  Act: Invoke the doNot method with the NOT expression containing the OR expression.
  Assert: Verify that the context contains "NOT " followed by the properly formatted OR expression with all its components.
Validation:
  This test ensures that the doNot method works correctly with logical OR operations, which is essential for comprehensive filter support. It validates the method's ability to handle different logical operators within NOT expressions and ensures proper expression conversion for complex filter scenarios.

Scenario 11: Multiple Expression Types Validation - EQ Type

Details:
  TestName: notExpressionRejectsEqType
  Description: This test verifies that the doNot method throws a RuntimeException when provided with an EQ (equals) expression type instead of NOT, ensuring strict type enforcement.
Execution:
  Arrange: Create an Expression object with type EQ. Initialize a StringBuilder as the context. Set up the Neo4jVectorFilterExpressionConverter instance.
  Act: Invoke the doNot method with the EQ expression.
  Assert: Verify that a RuntimeException is thrown with the message "Unsupported expression type EQ. Only NOT is supported here".
Validation:
  This test validates that the method strictly enforces the NOT expression type requirement and rejects equality expressions. It ensures type safety and prevents misuse of the method, which is designed specifically for NOT operations.

Scenario 12: Multiple Expression Types Validation - IN Type

Details:
  TestName: notExpressionRejectsInType
  Description: This test verifies that the doNot method throws a RuntimeException when provided with an IN expression type, ensuring that only NOT expressions are processed.
Execution:
  Arrange: Create an Expression object with type IN. Initialize a StringBuilder as the context. Set up the Neo4jVectorFilterExpressionConverter instance.
  Act: Invoke the doNot method with the IN expression.
  Assert: Verify that a RuntimeException is thrown with the message "Unsupported expression type IN. Only NOT is supported here".
Validation:
  This assertion ensures that the method rejects IN expressions, which should be handled by different methods in the converter. It validates the separation of concerns in the expression conversion logic and ensures that each method handles only its designated expression types.

Scenario 13: NOT Expression with Comparison Expression (GT) as Left Operand

Details:
  TestName: notExpressionWithGreaterThanOperand
  Description: This test validates that the doNot method correctly handles a NOT expression where the left operand is a greater-than (GT) comparison expression.
Execution:
  Arrange: Create a NOT Expression with a GT Expression as the left operand (e.g., field > value). Initialize a StringBuilder as the context. Set up the Neo4jVectorFilterExpressionConverter instance.
  Act: Invoke the doNot method with the NOT expression containing the GT expression.
  Assert: Verify that the context contains "NOT " followed by the properly formatted greater-than comparison.
Validation:
  This test ensures that the doNot method works correctly with comparison operators, which are fundamental in filter expressions. It validates that the method properly delegates to convertOperand for comparison expressions and maintains the correct logical semantics.

Scenario 14: NOT Expression with Comparison Expression (LT) as Left Operand

Details:
  TestName: notExpressionWithLessThanOperand
  Description: This test verifies that the doNot method correctly processes a NOT expression where the left operand is a less-than (LT) comparison expression.
Execution:
  Arrange: Create a NOT Expression with an LT Expression as the left operand (e.g., field < value). Initialize a StringBuilder as the context. Set up the Neo4jVectorFilterExpressionConverter instance.
  Act: Invoke the doNot method with the NOT expression containing the LT expression.
  Assert: Verify that the context contains "NOT " followed by the properly formatted less-than comparison.
Validation:
  This assertion validates that the doNot method handles less-than comparisons correctly within NOT expressions. It ensures comprehensive support for all comparison operators and validates the method's integration with the broader expression conversion framework.

Scenario 15: StringBuilder Mutation Verification

Details:
  TestName: notExpressionMutatesStringBuilder
  Description: This test verifies that the doNot method actually mutates the provided StringBuilder context rather than creating a new instance, ensuring efficient string building.
Execution:
  Arrange: Create a valid NOT Expression with a left operand. Initialize a StringBuilder as the context and keep a reference to it. Set up the Neo4jVectorFilterExpressionConverter instance.
  Act: Invoke the doNot method with the NOT expression and StringBuilder. Check the same StringBuilder instance after method execution.
  Assert: Verify that the original StringBuilder reference contains the expected content and that no new StringBuilder was created.
Validation:
  This test ensures that the method follows the expected pattern of mutating the provided StringBuilder for performance reasons. It validates that the method doesn't create unnecessary object allocations and properly uses the builder pattern for string construction.

*/

// ********RoostGPT********

package org.springframework.ai.vectorstore.neo4j.filter;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.ai.vectorstore.filter.Filter;
import org.springframework.ai.vectorstore.filter.Filter.Expression;
import org.springframework.ai.vectorstore.filter.Filter.ExpressionType;
import org.springframework.ai.vectorstore.filter.Filter.Group;
import org.springframework.ai.vectorstore.filter.Filter.Key;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.ai.vectorstore.filter.converter.AbstractFilterExpressionConverter;

class Neo4JVectorFilterExpressionConverterDoNotTest {

	private Neo4jVectorFilterExpressionConverter converter;

	private StringBuilder context;

	@BeforeEach
	void setUp() {
		converter = new Neo4jVectorFilterExpressionConverter();
		context = new StringBuilder();
	}

	@Test
	@Tag("valid")
	void notExpressionWithValidLeftOperand() {
		Key key = new Key("fieldName");
		Expression notExpression = new Expression(ExpressionType.NOT, key, null);
		converter.doNot(notExpression, context);
		assertTrue(context.toString().startsWith("NOT "));
		assertTrue(context.toString().contains("node.\"metadata.fieldName\""));
	}

	@Test
	@Tag("invalid")
	void notExpressionWithInvalidExpressionType() {
		Expression andExpression = new Expression(ExpressionType.AND, new Key("field1"), new Key("field2"));
		RuntimeException exception = assertThrows(RuntimeException.class, () -> {
			converter.doNot(andExpression, context);
		});
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("Only NOT is supported here"));
	}

	@Test
	@Tag("valid")
	void notExpressionWithKeyOperand() {
		Key key = new Key("testField");
		Expression notExpression = new Expression(ExpressionType.NOT, key, null);
		converter.doNot(notExpression, context);
		String result = context.toString();
		assertEquals("NOT node.\"metadata.testField\"", result);
	}

	@Test
	@Tag("valid")
	void notExpressionWithNestedExpression() {
		Key key = new Key("field");
		Expression eqExpression = new Expression(ExpressionType.EQ, key, "value");
		Expression notExpression = new Expression(ExpressionType.NOT, eqExpression, null);
		converter.doNot(notExpression, context);
		String result = context.toString();
		assertTrue(result.startsWith("NOT "));
		assertTrue(result.contains("node.\"metadata.field\""));
		assertTrue(result.contains("="));
	}

	@Test
	@Tag("valid")
	void notExpressionWithGroupOperand() {
		Key key1 = new Key("field1");
		Key key2 = new Key("field2");
		Expression expr1 = new Expression(ExpressionType.EQ, key1, "value1");
		Expression expr2 = new Expression(ExpressionType.EQ, key2, "value2");
		Expression andExpression = new Expression(ExpressionType.AND, expr1, expr2);
		Group group = new Group(andExpression);
		Expression notExpression = new Expression(ExpressionType.NOT, group, null);
		converter.doNot(notExpression, context);
		String result = context.toString();
		assertTrue(result.startsWith("NOT "));
		assertTrue(result.contains("("));
		assertTrue(result.contains(")"));
	}

	@Test
	@Tag("boundary")
	void notExpressionWithEmptyContext() {
		Key key = new Key("field");
		Expression notExpression = new Expression(ExpressionType.NOT, key, null);
		StringBuilder emptyContext = new StringBuilder();
		converter.doNot(notExpression, emptyContext);
		String result = emptyContext.toString();
		assertTrue(result.startsWith("NOT "));
		assertFalse(result.startsWith(" NOT "));
	}

	@Test
	@Tag("valid")
	void notExpressionWithExistingContext() {
		Key key = new Key("field");
		Expression notExpression = new Expression(ExpressionType.NOT, key, null);
		StringBuilder existingContext = new StringBuilder("WHERE ");
		converter.doNot(notExpression, existingContext);
		String result = existingContext.toString();
		assertTrue(result.startsWith("WHERE NOT "));
		assertTrue(result.contains("node.\"metadata.field\""));
	}

	@Test
	@Tag("invalid")
	void notExpressionWithNullExpression() {
		assertThrows(NullPointerException.class, () -> {
			converter.doNot(null, context);
		});
	}

	@Test
	@Tag("valid")
	void notExpressionWithAndOperand() {
		Key key1 = new Key("field1");
		Key key2 = new Key("field2");
		Expression expr1 = new Expression(ExpressionType.EQ, key1, "value1");
		Expression expr2 = new Expression(ExpressionType.EQ, key2, "value2");
		Expression andExpression = new Expression(ExpressionType.AND, expr1, expr2);
		Expression notExpression = new Expression(ExpressionType.NOT, andExpression, null);
		converter.doNot(notExpression, context);
		String result = context.toString();
		assertTrue(result.startsWith("NOT "));
		assertTrue(result.contains("AND"));
	}

	@Test
	@Tag("valid")
	void notExpressionWithOrOperand() {
		Key key1 = new Key("field1");
		Key key2 = new Key("field2");
		Expression expr1 = new Expression(ExpressionType.EQ, key1, "value1");
		Expression expr2 = new Expression(ExpressionType.EQ, key2, "value2");
		Expression orExpression = new Expression(ExpressionType.OR, expr1, expr2);
		Expression notExpression = new Expression(ExpressionType.NOT, orExpression, null);
		converter.doNot(notExpression, context);
		String result = context.toString();
		assertTrue(result.startsWith("NOT "));
		assertTrue(result.contains("OR"));
	}

	@Test
	@Tag("invalid")
	void notExpressionRejectsEqType() {
		Key key = new Key("field");
		Expression eqExpression = new Expression(ExpressionType.EQ, key, "value");
		RuntimeException exception = assertThrows(RuntimeException.class, () -> {
			converter.doNot(eqExpression, context);
		});
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("EQ"));
	}

	@Test
	@Tag("invalid")
	void notExpressionRejectsInType() {
		Key key = new Key("field");
		Expression inExpression = new Expression(ExpressionType.IN, key, new Object[] { "value1", "value2" });
		RuntimeException exception = assertThrows(RuntimeException.class, () -> {
			converter.doNot(inExpression, context);
		});
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("IN"));
	}

	@Test
	@Tag("valid")
	void notExpressionWithGreaterThanOperand() {
		Key key = new Key("field");
		Expression gtExpression = new Expression(ExpressionType.GT, key, 100);
		Expression notExpression = new Expression(ExpressionType.NOT, gtExpression, null);
		converter.doNot(notExpression, context);
		String result = context.toString();
		assertTrue(result.startsWith("NOT "));
		assertTrue(result.contains("node.\"metadata.field\""));
		assertTrue(result.contains(">"));
	}

	@Test
	@Tag("valid")
	void notExpressionWithLessThanOperand() {
		Key key = new Key("field");
		Expression ltExpression = new Expression(ExpressionType.LT, key, 50);
		Expression notExpression = new Expression(ExpressionType.NOT, ltExpression, null);
		converter.doNot(notExpression, context);
		String result = context.toString();
		assertTrue(result.startsWith("NOT "));
		assertTrue(result.contains("node.\"metadata.field\""));
		assertTrue(result.contains("<"));
	}

	@Test
	@Tag("valid")
	void notExpressionMutatesStringBuilder() {
		Key key = new Key("field");
		Expression notExpression = new Expression(ExpressionType.NOT, key, null);
		StringBuilder originalContext = new StringBuilder();
		StringBuilder referenceToContext = originalContext;
		converter.doNot(notExpression, originalContext);
		assertSame(originalContext, referenceToContext);
		assertTrue(originalContext.length() > 0);
		assertTrue(originalContext.toString().startsWith("NOT "));
	}

	@Test
	@Tag("invalid")
	void notExpressionRejectsNeType() {
		Key key = new Key("field");
		Expression neExpression = new Expression(ExpressionType.NE, key, "value");
		RuntimeException exception = assertThrows(RuntimeException.class, () -> {
			converter.doNot(neExpression, context);
		});
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("NE"));
	}

	@Test
	@Tag("invalid")
	void notExpressionRejectsLteType() {
		Key key = new Key("field");
		Expression lteExpression = new Expression(ExpressionType.LTE, key, 100);
		RuntimeException exception = assertThrows(RuntimeException.class, () -> {
			converter.doNot(lteExpression, context);
		});
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("LTE"));
	}

	@Test
	@Tag("invalid")
	void notExpressionRejectsGteType() {
		Key key = new Key("field");
		Expression gteExpression = new Expression(ExpressionType.GTE, key, 100);
		RuntimeException exception = assertThrows(RuntimeException.class, () -> {
			converter.doNot(gteExpression, context);
		});
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("GTE"));
	}

	@Test
	@Tag("valid")
	void notExpressionWithComplexNestedStructure() {
		Key key1 = new Key("field1");
		Key key2 = new Key("field2");
		Key key3 = new Key("field3");

		Expression expr1 = new Expression(ExpressionType.EQ, key1, "value1");
		Expression expr2 = new Expression(ExpressionType.GT, key2, 50);
		Expression andExpression = new Expression(ExpressionType.AND, expr1, expr2);
		Expression expr3 = new Expression(ExpressionType.LT, key3, 100);
		Expression orExpression = new Expression(ExpressionType.OR, andExpression, expr3);
		Expression notExpression = new Expression(ExpressionType.NOT, orExpression, null);
		converter.doNot(notExpression, context);
		String result = context.toString();
		assertTrue(result.startsWith("NOT "));
		assertTrue(result.contains("AND"));
		assertTrue(result.contains("OR"));
	}

	@Test
	@Tag("boundary")
	void notExpressionWithKeyContainingSpecialCharacters() {
		Key key = new Key("field_name-123");
		Expression notExpression = new Expression(ExpressionType.NOT, key, null);
		converter.doNot(notExpression, context);
		String result = context.toString();
		assertTrue(result.startsWith("NOT "));
		assertTrue(result.contains("field_name-123"));
	}

	@Test
	@Tag("valid")
	void notExpressionMultipleInvocations() {
		Key key1 = new Key("field1");
		Expression notExpression1 = new Expression(ExpressionType.NOT, key1, null);

		converter.doNot(notExpression1, context);
		int firstLength = context.length();

		Key key2 = new Key("field2");
		Expression notExpression2 = new Expression(ExpressionType.NOT, key2, null);

		converter.doNot(notExpression2, context);

		assertTrue(context.length() > firstLength);
		String result = context.toString();
		assertTrue(result.contains("field1"));
		assertTrue(result.contains("field2"));
	}

}