/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-spring-ai using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=doExpression_7373dbacf8
ROOST_METHOD_SIG_HASH=doExpression_f053663651

Scenario 1: Handle NIN Expression Type Successfully

Details:
  TestName: ninExpressionConvertsToNotInExpression
  Description: This test verifies that when an expression with type NIN (Not In) is provided, the method correctly transforms it into a NOT expression wrapping an IN expression. The NIN operation should be converted to "NOT <left> IN <right>" format.
Execution:
  Arrange: Create an Expression object with ExpressionType.NIN, a left operand (Key), and a right operand (list of values). Create a StringBuilder to capture the output context.
  Act: Invoke the doExpression method with the NIN expression and the StringBuilder context.
  Assert: Verify that the StringBuilder contains the expected "NOT" prefix followed by the IN operation format.
Validation:
  This assertion verifies that NIN expressions are properly transformed into their equivalent NOT IN representation. This is critical because Neo4j uses "NOT <left> IN <right>" syntax rather than a direct "NOT IN" operator. The test ensures the special handling branch for NIN is working correctly.

Scenario 2: Handle EQ Expression Type Successfully

Details:
  TestName: eqExpressionConvertsToEqualsOperator
  Description: This test validates that an equality expression (EQ) is correctly converted to Neo4j's equality operator format with proper operand placement on both sides of the operator.
Execution:
  Arrange: Create an Expression object with ExpressionType.EQ, a left operand (Key), and a right operand (value). Initialize a StringBuilder for the output.
  Act: Call doExpression with the EQ expression and StringBuilder.
  Assert: Verify that the StringBuilder contains the left operand, followed by " = ", followed by the right operand.
Validation:
  This test confirms that standard equality expressions follow the else branch and are formatted as "<left> = <right>". It validates the basic flow for non-NIN expressions and ensures the getOperationSymbol method returns the correct operator for EQ type.

Scenario 3: Handle NE Expression Type Successfully

Details:
  TestName: neExpressionConvertsToNotEqualsOperator
  Description: This test ensures that a not-equals expression (NE) is properly converted to Neo4j's not-equals operator ("<>") with correct operand positioning.
Execution:
  Arrange: Create an Expression with ExpressionType.NE, a left operand (Key), and a right operand (value). Prepare a StringBuilder.
  Act: Invoke doExpression with the NE expression and StringBuilder.
  Assert: Verify the StringBuilder contains "<left> <> <right>" format.
Validation:
  This assertion validates that NE expressions are handled through the standard else branch and formatted correctly with Neo4j's not-equals operator. It ensures the getOperationSymbol method returns " <> " for NE type expressions.

Scenario 4: Handle LT Expression Type Successfully

Details:
  TestName: ltExpressionConvertsToLessThanOperator
  Description: This test verifies that a less-than expression (LT) is correctly converted to the less-than operator with proper operand placement.
Execution:
  Arrange: Create an Expression with ExpressionType.LT, a left operand (Key), and a right operand (numeric value). Initialize a StringBuilder.
  Act: Call doExpression with the LT expression and StringBuilder.
  Assert: Verify the StringBuilder contains "<left> < <right>" format.
Validation:
  This test confirms that comparison expressions like LT are properly handled and formatted with the correct operator symbol. It validates the integration between doExpression and getOperationSymbol for less-than comparisons.

Scenario 5: Handle LTE Expression Type Successfully

Details:
  TestName: lteExpressionConvertsToLessThanOrEqualsOperator
  Description: This test ensures that a less-than-or-equals expression (LTE) is properly converted to the "<=" operator with correct operand positioning.
Execution:
  Arrange: Create an Expression with ExpressionType.LTE, a left operand (Key), and a right operand (numeric value). Prepare a StringBuilder.
  Act: Invoke doExpression with the LTE expression and StringBuilder.
  Assert: Verify the StringBuilder contains "<left> <= <right>" format.
Validation:
  This assertion validates that LTE expressions are correctly formatted with the less-than-or-equals operator. It ensures the method handles inclusive comparison operators properly.

Scenario 6: Handle GT Expression Type Successfully

Details:
  TestName: gtExpressionConvertsToGreaterThanOperator
  Description: This test verifies that a greater-than expression (GT) is correctly converted to the greater-than operator with proper operand placement.
Execution:
  Arrange: Create an Expression with ExpressionType.GT, a left operand (Key), and a right operand (numeric value). Initialize a StringBuilder.
  Act: Call doExpression with the GT expression and StringBuilder.
  Assert: Verify the StringBuilder contains "<left> > <right>" format.
Validation:
  This test confirms that GT expressions follow the standard conversion path and are formatted correctly with the greater-than operator. It validates proper handling of comparison expressions.

Scenario 7: Handle GTE Expression Type Successfully

Details:
  TestName: gteExpressionConvertsToGreaterThanOrEqualsOperator
  Description: This test ensures that a greater-than-or-equals expression (GTE) is properly converted to the ">=" operator with correct operand positioning.
Execution:
  Arrange: Create an Expression with ExpressionType.GTE, a left operand (Key), and a right operand (numeric value). Prepare a StringBuilder.
  Act: Invoke doExpression with the GTE expression and StringBuilder.
  Assert: Verify the StringBuilder contains "<left> >= <right>" format.
Validation:
  This assertion validates that GTE expressions are correctly formatted with the greater-than-or-equals operator. It ensures inclusive comparison operators are handled properly.

Scenario 8: Handle IN Expression Type Successfully

Details:
  TestName: inExpressionConvertsToInOperator
  Description: This test verifies that an IN expression is correctly converted to Neo4j's IN operator format with proper operand placement.
Execution:
  Arrange: Create an Expression with ExpressionType.IN, a left operand (Key), and a right operand (list of values). Initialize a StringBuilder.
  Act: Call doExpression with the IN expression and StringBuilder.
  Assert: Verify the StringBuilder contains "<left> IN <right>" format.
Validation:
  This test confirms that IN expressions are handled through the else branch and formatted correctly. It validates that the method doesn't confuse IN with NIN and processes it as a standard expression.

Scenario 9: Handle AND Expression Type Successfully

Details:
  TestName: andExpressionConvertsToAndOperator
  Description: This test ensures that a logical AND expression is properly converted with the AND operator between operands.
Execution:
  Arrange: Create an Expression with ExpressionType.AND, a left operand (nested Expression), and a right operand (nested Expression). Prepare a StringBuilder.
  Act: Invoke doExpression with the AND expression and StringBuilder.
  Assert: Verify the StringBuilder contains "<left> AND <right>" format.
Validation:
  This assertion validates that logical AND expressions are correctly formatted with the AND operator. It ensures the method properly handles logical operators that combine multiple conditions.

Scenario 10: Handle OR Expression Type Successfully

Details:
  TestName: orExpressionConvertsToOrOperator
  Description: This test verifies that a logical OR expression is correctly converted with the OR operator between operands.
Execution:
  Arrange: Create an Expression with ExpressionType.OR, a left operand (nested Expression), and a right operand (nested Expression). Initialize a StringBuilder.
  Act: Call doExpression with the OR expression and StringBuilder.
  Assert: Verify the StringBuilder contains "<left> OR <right>" format.
Validation:
  This test confirms that logical OR expressions are handled correctly and formatted with the OR operator. It validates proper handling of alternative conditions in filter expressions.

Scenario 11: Handle NIN Expression with Complex Right Operand

Details:
  TestName: ninExpressionWithMultipleValuesConvertsCorrectly
  Description: This test verifies that a NIN expression with multiple values in the right operand is correctly transformed into a NOT IN expression with all values preserved.
Execution:
  Arrange: Create an Expression with ExpressionType.NIN, a left operand (Key), and a right operand containing multiple values in a list. Prepare a StringBuilder.
  Act: Call doExpression with the NIN expression and StringBuilder.
  Assert: Verify the StringBuilder contains "NOT" followed by the left operand, "IN", and all the right operand values.
Validation:
  This assertion ensures that NIN expressions with complex right operands (multiple values) are properly converted. It validates that the transformation to NOT IN preserves all values and maintains the correct structure for Neo4j queries.

Scenario 12: Handle Expression with Null Left Operand

Details:
  TestName: expressionWithNullLeftOperandHandledGracefully
  Description: This test verifies the behavior when an expression has a null left operand, ensuring the method handles this edge case appropriately.
Execution:
  Arrange: Create an Expression with ExpressionType.EQ, a null left operand, and a valid right operand. Initialize a StringBuilder.
  Act: Invoke doExpression with the expression containing null left operand and StringBuilder.
  Assert: Verify that the method either handles the null gracefully or that convertOperand is called with null (behavior depends on convertOperand implementation).
Validation:
  This test validates edge case handling for null operands. It ensures the method doesn't throw unexpected exceptions and delegates null handling to the convertOperand method appropriately.

Scenario 13: Handle Expression with Null Right Operand

Details:
  TestName: expressionWithNullRightOperandHandledGracefully
  Description: This test verifies the behavior when an expression has a null right operand, ensuring proper handling of this edge case.
Execution:
  Arrange: Create an Expression with ExpressionType.EQ, a valid left operand, and a null right operand. Prepare a StringBuilder.
  Act: Call doExpression with the expression containing null right operand and StringBuilder.
  Assert: Verify that the method handles the null right operand appropriately through the convertOperand method.
Validation:
  This assertion validates that null right operands are handled correctly. It ensures the method maintains robustness when dealing with incomplete or malformed expressions.

Scenario 14: Handle NIN Expression Calls doNot Method

Details:
  TestName: ninExpressionInvokesDoNotMethod
  Description: This test verifies that when a NIN expression is processed, the doNot method is invoked with the correctly transformed NOT expression wrapping an IN expression.
Execution:
  Arrange: Create an Expression with ExpressionType.NIN, valid left and right operands. Prepare a StringBuilder. Set up a way to verify doNot method invocation (through behavior verification or output analysis).
  Act: Invoke doExpression with the NIN expression and StringBuilder.
  Assert: Verify that the output matches the expected format produced by doNot method, confirming it was called with the transformed expression.
Validation:
  This test confirms the control flow for NIN expressions, ensuring that the special case handling correctly delegates to the doNot method. It validates the transformation logic that converts NIN into NOT(IN).

Scenario 15: Handle Expression with Empty StringBuilder Context

Details:
  TestName: expressionWithEmptyStringBuilderProducesCorrectOutput
  Description: This test verifies that when an empty StringBuilder is provided as context, the method correctly appends the formatted expression without issues.
Execution:
  Arrange: Create an Expression with ExpressionType.EQ, valid operands, and an empty StringBuilder.
  Act: Call doExpression with the expression and empty StringBuilder.
  Assert: Verify the StringBuilder contains only the formatted expression without any preceding content.
Validation:
  This assertion validates that the method works correctly with a fresh StringBuilder context. It ensures the method doesn't assume any pre-existing content and starts formatting from a clean state.

Scenario 16: Handle Expression with Pre-existing StringBuilder Content

Details:
  TestName: expressionAppendsToExistingStringBuilderContent
  Description: This test verifies that when a StringBuilder already contains content, the method correctly appends the new expression to the existing content.
Execution:
  Arrange: Create an Expression with ExpressionType.EQ and valid operands. Initialize a StringBuilder with some pre-existing content (e.g., "WHERE ").
  Act: Invoke doExpression with the expression and StringBuilder containing existing content.
  Assert: Verify the StringBuilder contains both the original content and the newly appended expression in the correct order.
Validation:
  This test confirms that the method properly appends to existing context rather than replacing it. It validates the method's behavior in scenarios where multiple expressions are being built into a single query string.

Scenario 17: Handle Multiple Sequential Expression Calls

Details:
  TestName: multipleSequentialExpressionsAppendCorrectly
  Description: This test verifies that multiple sequential calls to doExpression with the same StringBuilder correctly append each expression.
Execution:
  Arrange: Create multiple Expression objects with different types (EQ, NE, GT). Initialize a single StringBuilder.
  Act: Call doExpression multiple times with different expressions and the same StringBuilder.
  Assert: Verify the StringBuilder contains all expressions in the order they were added.
Validation:
  This assertion validates that the method can be called multiple times with the same context StringBuilder, which is important for building complex filter expressions. It ensures no state interference between calls.

Scenario 18: Handle NIN Expression with Key as Left Operand

Details:
  TestName: ninExpressionWithKeyLeftOperandTransformsCorrectly
  Description: This test verifies that a NIN expression with a Key object as the left operand is correctly transformed and the Key is properly processed.
Execution:
  Arrange: Create a Key object, create an Expression with ExpressionType.NIN using the Key as left operand and a list as right operand. Prepare a StringBuilder.
  Act: Invoke doExpression with the NIN expression and StringBuilder.
  Assert: Verify the StringBuilder contains the NOT IN format with the Key properly converted.
Validation:
  This test confirms that NIN expressions work correctly with Key operands, which is a common use case for filtering on metadata fields. It validates the integration between the NIN transformation and Key handling.

Scenario 19: Handle Expression with Nested Expression as Left Operand

Details:
  TestName: expressionWithNestedLeftExpressionConvertsCorrectly
  Description: This test verifies that when the left operand is itself an Expression (nested expression), the method correctly processes it through convertOperand.
Execution:
  Arrange: Create a nested Expression as the left operand, create a parent Expression with ExpressionType.AND using the nested expression as left operand. Initialize a StringBuilder.
  Act: Call doExpression with the parent expression and StringBuilder.
  Assert: Verify the StringBuilder contains the properly formatted nested expression structure.
Validation:
  This assertion validates that the method handles complex nested expression structures correctly. It ensures the convertOperand method is properly invoked for nested expressions, maintaining the correct expression hierarchy.

Scenario 20: Handle Expression with Nested Expression as Right Operand

Details:
  TestName: expressionWithNestedRightExpressionConvertsCorrectly
  Description: This test verifies that when the right operand is itself an Expression (nested expression), the method correctly processes it through convertOperand.
Execution:
  Arrange: Create a nested Expression as the right operand, create a parent Expression with ExpressionType.OR using the nested expression as right operand. Prepare a StringBuilder.
  Act: Invoke doExpression with the parent expression and StringBuilder.
  Assert: Verify the StringBuilder contains the properly formatted structure with the nested right expression.
Validation:
  This test confirms that nested expressions on the right side are handled correctly. It validates the method's ability to process complex expression trees where operands can themselves be expressions.

Scenario 21: Verify NIN Creates Correct NOT Expression Structure

Details:
  TestName: ninExpressionCreatesCorrectNotExpressionStructure
  Description: This test verifies that the NIN expression creates a NOT expression with the correct structure: NOT type wrapping an IN expression with the original left and right operands.
Execution:
  Arrange: Create an Expression with ExpressionType.NIN, specific left operand (Key with value "status"), and right operand (list containing "active", "pending"). Prepare a StringBuilder.
  Act: Call doExpression with the NIN expression and StringBuilder.
  Assert: Verify the output structure matches "NOT <left> IN <right>" where left is "status" and right contains the list values.
Validation:
  This assertion validates the exact transformation logic for NIN expressions. It ensures that the new Expression created within the method has the correct type (NOT), and the nested IN expression preserves the original operands correctly.

Scenario 22: Handle EQ Expression with String Value

Details:
  TestName: eqExpressionWithStringValueFormatsCorrectly
  Description: This test verifies that an equality expression with a string value as the right operand is correctly formatted.
Execution:
  Arrange: Create an Expression with ExpressionType.EQ, a Key as left operand, and a string value as right operand. Initialize a StringBuilder.
  Act: Invoke doExpression with the expression and StringBuilder.
  Assert: Verify the StringBuilder contains the left operand, " = ", and the string value properly formatted.
Validation:
  This test confirms that string values are handled correctly in equality expressions. It validates that the convertOperand method is called appropriately for string values and they are formatted correctly in the output.

Scenario 23: Handle EQ Expression with Numeric Value

Details:
  TestName: eqExpressionWithNumericValueFormatsCorrectly
  Description: This test verifies that an equality expression with a numeric value as the right operand is correctly formatted.
Execution:
  Arrange: Create an Expression with ExpressionType.EQ, a Key as left operand, and a numeric value (e.g., Integer or Double) as right operand. Prepare a StringBuilder.
  Act: Call doExpression with the expression and StringBuilder.
  Assert: Verify the StringBuilder contains the left operand, " = ", and the numeric value properly formatted.
Validation:
  This assertion validates that numeric values are handled correctly in expressions. It ensures the method works with different data types and delegates proper formatting to convertOperand.

Scenario 24: Handle EQ Expression with Boolean Value

Details:
  TestName: eqExpressionWithBooleanValueFormatsCorrectly
  Description: This test verifies that an equality expression with a boolean value as the right operand is correctly formatted.
Execution:
  Arrange: Create an Expression with ExpressionType.EQ, a Key as left operand, and a boolean value (true or false) as right operand. Initialize a StringBuilder.
  Act: Invoke doExpression with the expression and StringBuilder.
  Assert: Verify the StringBuilder contains the left operand, " = ", and the boolean value properly formatted.
Validation:
  This test confirms that boolean values are handled correctly in equality expressions. It validates the method's ability to work with different primitive types through the convertOperand delegation.

Scenario 25: Handle IN Expression with Empty List

Details:
  TestName: inExpressionWithEmptyListHandledCorrectly
  Description: This test verifies the behavior when an IN expression has an empty list as the right operand.
Execution:
  Arrange: Create an Expression with ExpressionType.IN, a Key as left operand, and an empty list as right operand. Prepare a StringBuilder.
  Act: Call doExpression with the IN expression and StringBuilder.
  Assert: Verify the StringBuilder contains the IN operator with the empty list properly represented (behavior depends on convertOperand implementation).
Validation:
  This assertion validates edge case handling for IN expressions with empty collections. It ensures the method doesn't fail and produces valid output even when the list of values is empty.

Scenario 26: Handle NIN Expression with Empty List

Details:
  TestName: ninExpressionWithEmptyListHandledCorrectly
  Description: This test verifies the behavior when a NIN expression has an empty list as the right operand.
Execution:
  Arrange: Create an Expression with ExpressionType.NIN, a Key as left operand, and an empty list as right operand. Initialize a StringBuilder.
  Act: Invoke doExpression with the NIN expression and StringBuilder.
  Assert: Verify the StringBuilder contains the NOT IN structure with the empty list properly handled.
Validation:
  This test confirms that NIN expressions with empty lists are transformed correctly into NOT IN format. It validates that the transformation logic works even with edge case operand values.

Scenario 27: Handle IN Expression with Single Value List

Details:
  TestName: inExpressionWithSingleValueListFormatsCorrectly
  Description: This test verifies that an IN expression with a list containing only one value is correctly formatted.
Execution:
  Arrange: Create an Expression with ExpressionType.IN, a Key as left operand, and a list containing a single value as right operand. Prepare a StringBuilder.
  Act: Call doExpression with the IN expression and StringBuilder.
  Assert: Verify the StringBuilder contains the IN operator with the single value properly formatted in list format.
Validation:
  This assertion validates that IN expressions work correctly even with single-value lists. It ensures the method doesn't require multiple values and handles the edge case of a single-element collection.

Scenario 28: Handle Complex Nested NIN Expression

Details:
  TestName: complexNestedNinExpressionTransformsCorrectly
  Description: This test verifies that a NIN expression nested within a larger expression structure is correctly transformed.
Execution:
  Arrange: Create a NIN expression, then create a parent AND expression that includes the NIN expression as one of its operands. Initialize a StringBuilder.
  Act: Invoke doExpression with the parent AND expression and StringBuilder.
  Assert: Verify the StringBuilder contains the AND operator with the NIN expression correctly transformed to NOT IN format.
Validation:
  This test confirms that NIN transformations work correctly within complex nested expression structures. It validates that the special NIN handling doesn't interfere with the processing of parent expressions.

Scenario 29: Verify Operator Symbol Spacing

Details:
  TestName: operatorSymbolsIncludeCorrectSpacing
  Description: This test verifies that all operator symbols returned by getOperationSymbol include proper spacing (leading and trailing spaces).
Execution:
  Arrange: Create expressions with different types (EQ, NE, LT, GT, AND, OR, etc.). Prepare a StringBuilder for each.
  Act: Call doExpression for each expression type and capture the output.
  Assert: Verify that each operator in the StringBuilder has proper spacing (space before and after the operator symbol).
Validation:
  This assertion validates that the formatted output is properly spaced for readability and correct Neo4j syntax. It ensures that operators like " = ", " AND ", " OR " have consistent spacing that matches Neo4j query requirements.

Scenario 30: Handle Expression Type NOT Through Else Branch

Details:
  TestName: notExpressionTypeHandledThroughElseBranch
  Description: This test verifies that if a NOT expression type is passed directly to doExpression (not as part of NIN transformation), it is handled through the else branch.
Execution:
  Arrange: Create an Expression with ExpressionType.NOT, a left operand (nested expression), and potentially a right operand. Prepare a StringBuilder.
  Act: Call doExpression with the NOT expression and StringBuilder.
  Assert: Verify the StringBuilder contains the formatted output with " NOT " operator symbol between operands.
Validation:
  This test confirms that NOT expressions, when not created internally by NIN transformation, follow the standard expression formatting path. It validates that getOperationSymbol returns " NOT " for NOT type expressions.

*/

// ********RoostGPT********

package org.springframework.ai.vectorstore.neo4j.filter;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.ai.vectorstore.filter.Filter;
import org.springframework.ai.vectorstore.filter.Filter.Expression;
import org.springframework.ai.vectorstore.filter.Filter.Key;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.ai.vectorstore.filter.Filter.Group;
import org.springframework.ai.vectorstore.filter.converter.AbstractFilterExpressionConverter;

class Neo4JVectorFilterExpressionConverterDoExpressionTest {

	private Neo4jVectorFilterExpressionConverter converter;

	@BeforeEach
	void setUp() {
		converter = new Neo4jVectorFilterExpressionConverter();
	}

	@Test
	@Tag("valid")
	void ninExpressionConvertsToNotInExpression() {
		Key leftKey = new Key("status");
		List<String> rightValues = Arrays.asList("active", "pending");
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, leftKey, rightValues);
		StringBuilder context = new StringBuilder();
		converter.doExpression(ninExpression, context);
		String result = context.toString();
		assertTrue(result.contains("NOT"));
		assertTrue(result.contains("IN"));
	}

	@Test
	@Tag("valid")
	void eqExpressionConvertsToEqualsOperator() {
		Key leftKey = new Key("name");
		String rightValue = "John";
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, leftKey, rightValue);
		StringBuilder context = new StringBuilder();
		converter.doExpression(eqExpression, context);
		String result = context.toString();
		assertTrue(result.contains(" = "));
	}

	@Test
	@Tag("valid")
	void neExpressionConvertsToNotEqualsOperator() {
		Key leftKey = new Key("status");
		String rightValue = "inactive";
		Expression neExpression = new Expression(Filter.ExpressionType.NE, leftKey, rightValue);
		StringBuilder context = new StringBuilder();
		converter.doExpression(neExpression, context);
		String result = context.toString();
		assertTrue(result.contains(" <> "));
	}

	@Test
	@Tag("valid")
	void ltExpressionConvertsToLessThanOperator() {
		Key leftKey = new Key("age");
		Integer rightValue = 30;
		Expression ltExpression = new Expression(Filter.ExpressionType.LT, leftKey, rightValue);
		StringBuilder context = new StringBuilder();
		converter.doExpression(ltExpression, context);
		String result = context.toString();
		assertTrue(result.contains(" < "));
	}

	@Test
	@Tag("valid")
	void lteExpressionConvertsToLessThanOrEqualsOperator() {
		Key leftKey = new Key("age");
		Integer rightValue = 30;
		Expression lteExpression = new Expression(Filter.ExpressionType.LTE, leftKey, rightValue);
		StringBuilder context = new StringBuilder();
		converter.doExpression(lteExpression, context);
		String result = context.toString();
		assertTrue(result.contains(" <= "));
	}

	@Test
	@Tag("valid")
	void gtExpressionConvertsToGreaterThanOperator() {
		Key leftKey = new Key("age");
		Integer rightValue = 25;
		Expression gtExpression = new Expression(Filter.ExpressionType.GT, leftKey, rightValue);
		StringBuilder context = new StringBuilder();
		converter.doExpression(gtExpression, context);
		String result = context.toString();
		assertTrue(result.contains(" > "));
	}

	@Test
	@Tag("valid")
	void gteExpressionConvertsToGreaterThanOrEqualsOperator() {
		Key leftKey = new Key("age");
		Integer rightValue = 25;
		Expression gteExpression = new Expression(Filter.ExpressionType.GTE, leftKey, rightValue);
		StringBuilder context = new StringBuilder();
		converter.doExpression(gteExpression, context);
		String result = context.toString();
		assertTrue(result.contains(" >= "));
	}

	@Test
	@Tag("valid")
	void inExpressionConvertsToInOperator() {
		Key leftKey = new Key("category");
		List<String> rightValues = Arrays.asList("electronics", "books");
		Expression inExpression = new Expression(Filter.ExpressionType.IN, leftKey, rightValues);
		StringBuilder context = new StringBuilder();
		converter.doExpression(inExpression, context);
		String result = context.toString();
		assertTrue(result.contains(" IN "));
	}

	@Test
	@Tag("valid")
	void andExpressionConvertsToAndOperator() {
		Expression leftExpr = new Expression(Filter.ExpressionType.EQ, new Key("name"), "John");
		Expression rightExpr = new Expression(Filter.ExpressionType.EQ, new Key("age"), 30);
		Expression andExpression = new Expression(Filter.ExpressionType.AND, leftExpr, rightExpr);
		StringBuilder context = new StringBuilder();
		converter.doExpression(andExpression, context);
		String result = context.toString();
		assertTrue(result.contains(" AND "));
	}

	@Test
	@Tag("valid")
	void orExpressionConvertsToOrOperator() {
		Expression leftExpr = new Expression(Filter.ExpressionType.EQ, new Key("status"), "active");
		Expression rightExpr = new Expression(Filter.ExpressionType.EQ, new Key("status"), "pending");
		Expression orExpression = new Expression(Filter.ExpressionType.OR, leftExpr, rightExpr);
		StringBuilder context = new StringBuilder();
		converter.doExpression(orExpression, context);
		String result = context.toString();
		assertTrue(result.contains(" OR "));
	}

	@Test
	@Tag("valid")
	void ninExpressionWithMultipleValuesConvertsCorrectly() {
		Key leftKey = new Key("status");
		List<String> rightValues = Arrays.asList("active", "pending", "suspended");
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, leftKey, rightValues);
		StringBuilder context = new StringBuilder();
		converter.doExpression(ninExpression, context);
		String result = context.toString();
		assertTrue(result.contains("NOT"));
		assertTrue(result.contains("IN"));
	}

	@Test
	@Tag("boundary")
	void expressionWithNullLeftOperandHandledGracefully() {
		Expression expression = new Expression(Filter.ExpressionType.EQ, null, "value");
		StringBuilder context = new StringBuilder();
		assertDoesNotThrow(() -> converter.doExpression(expression, context));
	}

	@Test
	@Tag("boundary")
	void expressionWithNullRightOperandHandledGracefully() {
		Key leftKey = new Key("field");
		Expression expression = new Expression(Filter.ExpressionType.EQ, leftKey, null);
		StringBuilder context = new StringBuilder();
		assertDoesNotThrow(() -> converter.doExpression(expression, context));
	}

	@Test
	@Tag("valid")
	void ninExpressionInvokesDoNotMethod() {
		Key leftKey = new Key("category");
		List<String> rightValues = Arrays.asList("electronics");
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, leftKey, rightValues);
		StringBuilder context = new StringBuilder();
		converter.doExpression(ninExpression, context);
		String result = context.toString();
		assertTrue(result.startsWith("NOT"));
	}

	@Test
	@Tag("valid")
	void expressionWithEmptyStringBuilderProducesCorrectOutput() {
		Key leftKey = new Key("name");
		String rightValue = "Test";
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, leftKey, rightValue);
		StringBuilder context = new StringBuilder();
		converter.doExpression(eqExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertFalse(result.isEmpty());
	}

	@Test
	@Tag("valid")
	void expressionAppendsToExistingStringBuilderContent() {
		Key leftKey = new Key("status");
		String rightValue = "active";
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, leftKey, rightValue);
		StringBuilder context = new StringBuilder("WHERE ");
		converter.doExpression(eqExpression, context);
		String result = context.toString();
		assertTrue(result.startsWith("WHERE"));
	}

	@Test
	@Tag("valid")
	void multipleSequentialExpressionsAppendCorrectly() {
		Key leftKey1 = new Key("name");
		Expression expr1 = new Expression(Filter.ExpressionType.EQ, leftKey1, "John");
		Key leftKey2 = new Key("age");
		Expression expr2 = new Expression(Filter.ExpressionType.GT, leftKey2, 25);
		StringBuilder context = new StringBuilder();
		converter.doExpression(expr1, context);
		converter.doExpression(expr2, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.length() > 0);
	}

	@Test
	@Tag("valid")
	void ninExpressionWithKeyLeftOperandTransformsCorrectly() {
		Key leftKey = new Key("status");
		List<String> rightValues = Arrays.asList("inactive", "deleted");
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, leftKey, rightValues);
		StringBuilder context = new StringBuilder();
		converter.doExpression(ninExpression, context);
		String result = context.toString();
		assertTrue(result.contains("NOT"));
		assertTrue(result.contains("IN"));
	}

	@Test
	@Tag("valid")
	void expressionWithNestedLeftExpressionConvertsCorrectly() {
		Expression nestedLeft = new Expression(Filter.ExpressionType.EQ, new Key("name"), "John");
		Expression rightExpr = new Expression(Filter.ExpressionType.EQ, new Key("age"), 30);
		Expression andExpression = new Expression(Filter.ExpressionType.AND, nestedLeft, rightExpr);
		StringBuilder context = new StringBuilder();
		converter.doExpression(andExpression, context);
		String result = context.toString();
		assertTrue(result.contains(" AND "));
	}

	@Test
	@Tag("valid")
	void expressionWithNestedRightExpressionConvertsCorrectly() {
		Expression leftExpr = new Expression(Filter.ExpressionType.EQ, new Key("status"), "active");
		Expression nestedRight = new Expression(Filter.ExpressionType.GT, new Key("age"), 25);
		Expression orExpression = new Expression(Filter.ExpressionType.OR, leftExpr, nestedRight);
		StringBuilder context = new StringBuilder();
		converter.doExpression(orExpression, context);
		String result = context.toString();
		assertTrue(result.contains(" OR "));
	}

	@Test
	@Tag("valid")
	void ninExpressionCreatesCorrectNotExpressionStructure() {
		Key leftKey = new Key("status");
		List<String> rightValues = Arrays.asList("active", "pending");
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, leftKey, rightValues);
		StringBuilder context = new StringBuilder();
		converter.doExpression(ninExpression, context);
		String result = context.toString();
		assertTrue(result.contains("NOT"));
		assertTrue(result.contains("IN"));
	}

	@Test
	@Tag("valid")
	void eqExpressionWithStringValueFormatsCorrectly() {
		Key leftKey = new Key("name");
		String rightValue = "TestName";
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, leftKey, rightValue);
		StringBuilder context = new StringBuilder();
		converter.doExpression(eqExpression, context);
		String result = context.toString();
		assertTrue(result.contains(" = "));
	}

	@Test
	@Tag("valid")
	void eqExpressionWithNumericValueFormatsCorrectly() {
		Key leftKey = new Key("count");
		Integer rightValue = 100;
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, leftKey, rightValue);
		StringBuilder context = new StringBuilder();
		converter.doExpression(eqExpression, context);
		String result = context.toString();
		assertTrue(result.contains(" = "));
	}

	@Test
	@Tag("valid")
	void eqExpressionWithBooleanValueFormatsCorrectly() {
		Key leftKey = new Key("isActive");
		Boolean rightValue = true;
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, leftKey, rightValue);
		StringBuilder context = new StringBuilder();
		converter.doExpression(eqExpression, context);
		String result = context.toString();
		assertTrue(result.contains(" = "));
	}

	@Test
	@Tag("boundary")
	void inExpressionWithEmptyListHandledCorrectly() {
		Key leftKey = new Key("category");
		List<String> emptyList = Collections.emptyList();
		Expression inExpression = new Expression(Filter.ExpressionType.IN, leftKey, emptyList);
		StringBuilder context = new StringBuilder();
		assertDoesNotThrow(() -> converter.doExpression(inExpression, context));
		String result = context.toString();
		assertTrue(result.contains(" IN "));
	}

	@Test
	@Tag("boundary")
	void ninExpressionWithEmptyListHandledCorrectly() {
		Key leftKey = new Key("status");
		List<String> emptyList = Collections.emptyList();
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, leftKey, emptyList);
		StringBuilder context = new StringBuilder();
		assertDoesNotThrow(() -> converter.doExpression(ninExpression, context));
		String result = context.toString();
		assertTrue(result.contains("NOT"));
	}

	@Test
	@Tag("boundary")
	void inExpressionWithSingleValueListFormatsCorrectly() {
		Key leftKey = new Key("type");
		List<String> singleValue = Collections.singletonList("premium");
		Expression inExpression = new Expression(Filter.ExpressionType.IN, leftKey, singleValue);
		StringBuilder context = new StringBuilder();
		converter.doExpression(inExpression, context);
		String result = context.toString();
		assertTrue(result.contains(" IN "));
	}

	@Test
	@Tag("integration")
	void complexNestedNinExpressionTransformsCorrectly() {
		Key ninKey = new Key("status");
		List<String> ninValues = Arrays.asList("deleted", "archived");
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, ninKey, ninValues);

		Expression rightExpr = new Expression(Filter.ExpressionType.EQ, new Key("active"), true);
		Expression andExpression = new Expression(Filter.ExpressionType.AND, ninExpression, rightExpr);
		StringBuilder context = new StringBuilder();
		converter.doExpression(andExpression, context);
		String result = context.toString();
		assertTrue(result.contains("NOT"));
		assertTrue(result.contains(" AND "));
	}

	@Test
	@Tag("valid")
	void operatorSymbolsIncludeCorrectSpacing() {
		Key leftKey = new Key("field");
		Expression eqExpr = new Expression(Filter.ExpressionType.EQ, leftKey, "value");
		StringBuilder context1 = new StringBuilder();
		converter.doExpression(eqExpr, context1);
		assertTrue(context1.toString().contains(" = "));
		Expression neExpr = new Expression(Filter.ExpressionType.NE, leftKey, "value");
		StringBuilder context2 = new StringBuilder();
		converter.doExpression(neExpr, context2);
		assertTrue(context2.toString().contains(" <> "));
		Expression ltExpr = new Expression(Filter.ExpressionType.LT, leftKey, 10);
		StringBuilder context3 = new StringBuilder();
		converter.doExpression(ltExpr, context3);
		assertTrue(context3.toString().contains(" < "));
	}

	@Test
	@Tag("valid")
	void notExpressionTypeHandledThroughElseBranch() {
		Expression innerExpr = new Expression(Filter.ExpressionType.EQ, new Key("status"), "active");
		Expression notExpression = new Expression(Filter.ExpressionType.NOT, innerExpr, null);
		StringBuilder context = new StringBuilder();
		converter.doExpression(notExpression, context);
		String result = context.toString();
		assertTrue(result.contains(" NOT "));
	}

}