/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-11-java using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=doNot_82558cd573
ROOST_METHOD_SIG_HASH=doNot_ecb1a8c56c

Scenario 1: Valid NOT Expression Type Processes Successfully

Details:
  TestName: doNotWithValidNotExpressionType
  Description: This test verifies that the doNot method correctly processes an Expression with ExpressionType.NOT and appends the expected "NOT " prefix followed by the converted left operand to the context StringBuilder.

Execution:
  Arrange: Create a Filter.Expression with ExpressionType.NOT and a valid left operand (e.g., another Expression or Key). Create an empty StringBuilder as the context.
  Act: Invoke the doNot method with the NOT expression and the StringBuilder context.
  Assert: Verify that the StringBuilder context starts with "NOT " followed by the converted representation of the left operand.

Validation:
  The assertion verifies that the method correctly handles NOT expressions by prefixing the output with "NOT " and delegating the left operand conversion to convertOperand. This is significant because NOT expressions in Neo4j queries require explicit negation syntax, and this test ensures the converter produces valid query fragments.

---

Scenario 2: Expression Type AND Throws RuntimeException

Details:
  TestName: doNotWithAndExpressionTypeThrowsException
  Description: This test verifies that the doNot method throws a RuntimeException when provided with an Expression of type AND instead of NOT.

Execution:
  Arrange: Create a Filter.Expression with ExpressionType.AND and valid left and right operands. Create an empty StringBuilder as the context.
  Act: Invoke the doNot method with the AND expression and the StringBuilder context.
  Assert: Verify that a RuntimeException is thrown with a message containing "Unsupported expression type AND. Only NOT is supported here".

Validation:
  The assertion confirms that the method enforces type safety by rejecting non-NOT expression types. This is critical for maintaining query correctness and preventing malformed Neo4j queries from being generated.

---

Scenario 3: Expression Type OR Throws RuntimeException

Details:
  TestName: doNotWithOrExpressionTypeThrowsException
  Description: This test verifies that the doNot method throws a RuntimeException when provided with an Expression of type OR instead of NOT.

Execution:
  Arrange: Create a Filter.Expression with ExpressionType.OR and valid left and right operands. Create an empty StringBuilder as the context.
  Act: Invoke the doNot method with the OR expression and the StringBuilder context.
  Assert: Verify that a RuntimeException is thrown with a message containing "Unsupported expression type OR. Only NOT is supported here".

Validation:
  The assertion ensures that OR expressions are properly rejected by the doNot method, maintaining the integrity of the NOT-specific processing logic.

---

Scenario 4: Expression Type EQ Throws RuntimeException

Details:
  TestName: doNotWithEqExpressionTypeThrowsException
  Description: This test verifies that the doNot method throws a RuntimeException when provided with an Expression of type EQ (equals) instead of NOT.

Execution:
  Arrange: Create a Filter.Expression with ExpressionType.EQ and valid left and right operands. Create an empty StringBuilder as the context.
  Act: Invoke the doNot method with the EQ expression and the StringBuilder context.
  Assert: Verify that a RuntimeException is thrown with a message indicating that EQ is unsupported.

Validation:
  The assertion validates that comparison expressions are not mistakenly processed as NOT expressions, ensuring proper separation of concerns in the expression conversion logic.

---

Scenario 5: Expression Type IN Throws RuntimeException

Details:
  TestName: doNotWithInExpressionTypeThrowsException
  Description: This test verifies that the doNot method throws a RuntimeException when provided with an Expression of type IN instead of NOT.

Execution:
  Arrange: Create a Filter.Expression with ExpressionType.IN and valid left and right operands. Create an empty StringBuilder as the context.
  Act: Invoke the doNot method with the IN expression and the StringBuilder context.
  Assert: Verify that a RuntimeException is thrown with a message indicating that IN is unsupported in this context.

Validation:
  The assertion confirms that IN expressions must be handled through the appropriate method path rather than doNot, maintaining proper query generation flow.

---

Scenario 6: NOT Expression With Key As Left Operand

Details:
  TestName: doNotWithKeyAsLeftOperand
  Description: This test verifies that the doNot method correctly processes a NOT expression where the left operand is a Key object, producing the expected Neo4j query fragment.

Execution:
  Arrange: Create a Filter.Key with a specific key name. Create a Filter.Expression with ExpressionType.NOT and the Key as the left operand. Create an empty StringBuilder as the context.
  Act: Invoke the doNot method with the NOT expression and the StringBuilder context.
  Assert: Verify that the StringBuilder contains "NOT " followed by the properly formatted key representation.

Validation:
  The assertion ensures that Key operands within NOT expressions are correctly converted, which is essential for generating valid Neo4j property access patterns in negated conditions.

---

Scenario 7: NOT Expression With Nested Expression As Left Operand

Details:
  TestName: doNotWithNestedExpressionAsLeftOperand
  Description: This test verifies that the doNot method correctly handles a NOT expression where the left operand is another Expression (nested expression scenario).

Execution:
  Arrange: Create an inner Filter.Expression (e.g., with ExpressionType.EQ). Create an outer Filter.Expression with ExpressionType.NOT and the inner expression as the left operand. Create an empty StringBuilder as the context.
  Act: Invoke the doNot method with the outer NOT expression and the StringBuilder context.
  Assert: Verify that the StringBuilder contains "NOT " followed by the converted representation of the nested expression.

Validation:
  The assertion validates that complex nested expressions are properly handled, ensuring that the NOT operator correctly wraps compound conditions in Neo4j queries.

---

Scenario 8: NOT Expression With Group As Left Operand

Details:
  TestName: doNotWithGroupAsLeftOperand
  Description: This test verifies that the doNot method correctly processes a NOT expression where the left operand is a Group object, ensuring proper parenthetical grouping in the output.

Execution:
  Arrange: Create a Filter.Group containing an inner expression. Create a Filter.Expression with ExpressionType.NOT and the Group as the left operand. Create an empty StringBuilder as the context.
  Act: Invoke the doNot method with the NOT expression and the StringBuilder context.
  Assert: Verify that the StringBuilder contains "NOT " followed by the properly formatted group representation with parentheses.

Validation:
  The assertion ensures that grouped expressions within NOT operations maintain their logical grouping, which is critical for preserving operator precedence in complex Neo4j queries.

---

Scenario 9: Expression Type NIN Throws RuntimeException

Details:
  TestName: doNotWithNinExpressionTypeThrowsException
  Description: This test verifies that the doNot method throws a RuntimeException when directly called with an Expression of type NIN, as NIN should be transformed before reaching doNot.

Execution:
  Arrange: Create a Filter.Expression with ExpressionType.NIN and valid left and right operands. Create an empty StringBuilder as the context.
  Act: Invoke the doNot method with the NIN expression and the StringBuilder context.
  Assert: Verify that a RuntimeException is thrown with a message indicating that NIN is unsupported in this context.

Validation:
  The assertion confirms that NIN expressions are properly rejected when passed directly to doNot, as they should be transformed to NOT(IN) expressions through doExpression first.

---

Scenario 10: Context StringBuilder Preserves Existing Content

Details:
  TestName: doNotPreservesExistingContextContent
  Description: This test verifies that the doNot method appends to the existing content in the StringBuilder context rather than replacing it.

Execution:
  Arrange: Create a Filter.Expression with ExpressionType.NOT and a valid left operand. Create a StringBuilder with pre-existing content (e.g., "WHERE ").
  Act: Invoke the doNot method with the NOT expression and the pre-populated StringBuilder context.
  Assert: Verify that the StringBuilder contains the original content followed by "NOT " and the converted left operand.

Validation:
  The assertion ensures that the method correctly appends to the query being built rather than overwriting previous content, which is essential for constructing complete Neo4j queries incrementally.

*/

// ********RoostGPT********

package org.springframework.ai.vectorstore.neo4j.filter;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.ai.vectorstore.filter.Filter;
import org.springframework.ai.vectorstore.filter.Filter.Expression;
import org.springframework.ai.vectorstore.filter.Filter.Group;
import org.springframework.ai.vectorstore.filter.Filter.Key;
import org.springframework.ai.vectorstore.filter.Filter.Value;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.ai.vectorstore.filter.converter.AbstractFilterExpressionConverter;

class Neo4JVectorFilterExpressionConverterDoNotTest {

	private Neo4jVectorFilterExpressionConverter converter;

	@BeforeEach
	void setUp() {
		converter = new Neo4jVectorFilterExpressionConverter();
	}

	@Test
	@Tag("valid")
	void doNotWithValidNotExpressionType() {
		// Arrange
		Key key = new Key("testKey");
		Expression notExpression = new Expression(Filter.ExpressionType.NOT,
				new Expression(Filter.ExpressionType.EQ, key, new Value("testValue")), null);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doNot(notExpression, context);
		// Assert
		String result = context.toString();
		assertTrue(result.startsWith("NOT "), "Result should start with 'NOT '");
		assertNotNull(result);
		assertTrue(result.length() > 4, "Result should contain more than just 'NOT '");
	}

	@Test
	@Tag("invalid")
	void doNotWithAndExpressionTypeThrowsException() {
		// Arrange
		Key leftKey = new Key("leftKey");
		Key rightKey = new Key("rightKey");
		Expression andExpression = new Expression(Filter.ExpressionType.AND,
				new Expression(Filter.ExpressionType.EQ, leftKey, new Value("value1")),
				new Expression(Filter.ExpressionType.EQ, rightKey, new Value("value2")));
		StringBuilder context = new StringBuilder();
		// Act & Assert
		RuntimeException exception = assertThrows(RuntimeException.class,
				() -> converter.doNot(andExpression, context));
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("AND"));
		assertTrue(exception.getMessage().contains("Only NOT is supported here"));
	}

	@Test
	@Tag("invalid")
	void doNotWithOrExpressionTypeThrowsException() {
		// Arrange
		Key leftKey = new Key("leftKey");
		Key rightKey = new Key("rightKey");
		Expression orExpression = new Expression(Filter.ExpressionType.OR,
				new Expression(Filter.ExpressionType.EQ, leftKey, new Value("value1")),
				new Expression(Filter.ExpressionType.EQ, rightKey, new Value("value2")));
		StringBuilder context = new StringBuilder();
		// Act & Assert
		RuntimeException exception = assertThrows(RuntimeException.class, () -> converter.doNot(orExpression, context));
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("OR"));
		assertTrue(exception.getMessage().contains("Only NOT is supported here"));
	}

	@Test
	@Tag("invalid")
	void doNotWithEqExpressionTypeThrowsException() {
		// Arrange
		Key key = new Key("testKey");
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, key, new Value("testValue"));
		StringBuilder context = new StringBuilder();
		// Act & Assert
		RuntimeException exception = assertThrows(RuntimeException.class, () -> converter.doNot(eqExpression, context));
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("EQ"));
		assertTrue(exception.getMessage().contains("Only NOT is supported here"));
	}

	@Test
	@Tag("invalid")
	void doNotWithInExpressionTypeThrowsException() {
		// Arrange
		Key key = new Key("testKey");
		Expression inExpression = new Expression(Filter.ExpressionType.IN, key,
				new Value(java.util.List.of("value1", "value2")));
		StringBuilder context = new StringBuilder();
		// Act & Assert
		RuntimeException exception = assertThrows(RuntimeException.class, () -> converter.doNot(inExpression, context));
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("IN"));
		assertTrue(exception.getMessage().contains("Only NOT is supported here"));
	}

	@Test
	@Tag("valid")
	void doNotWithKeyAsLeftOperand() {
		// Arrange
		Key key = new Key("propertyName");
		Expression innerExpression = new Expression(Filter.ExpressionType.EQ, key, new Value("someValue"));
		Expression notExpression = new Expression(Filter.ExpressionType.NOT, innerExpression, null);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doNot(notExpression, context);
		// Assert
		String result = context.toString();
		assertTrue(result.startsWith("NOT "), "Result should start with 'NOT '");
		assertNotNull(result);
	}

	@Test
	@Tag("valid")
	void doNotWithNestedExpressionAsLeftOperand() {
		// Arrange
		Key key1 = new Key("key1");
		Key key2 = new Key("key2");
		Expression innerExpression = new Expression(Filter.ExpressionType.AND,
				new Expression(Filter.ExpressionType.EQ, key1, new Value("value1")),
				new Expression(Filter.ExpressionType.EQ, key2, new Value("value2")));
		Expression notExpression = new Expression(Filter.ExpressionType.NOT, innerExpression, null);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doNot(notExpression, context);
		// Assert
		String result = context.toString();
		assertTrue(result.startsWith("NOT "), "Result should start with 'NOT '");
		assertNotNull(result);
		assertTrue(result.length() > 4, "Result should contain the nested expression");
	}

	@Test
	@Tag("valid")
	void doNotWithGroupAsLeftOperand() {
		// Arrange
		Key key = new Key("groupKey");
		Expression innerExpression = new Expression(Filter.ExpressionType.EQ, key, new Value("groupValue"));
		Group group = new Group(innerExpression);
		Expression notExpression = new Expression(Filter.ExpressionType.NOT, group, null);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doNot(notExpression, context);
		// Assert
		String result = context.toString();
		assertTrue(result.startsWith("NOT "), "Result should start with 'NOT '");
		assertNotNull(result);
	}

	@Test
	@Tag("invalid")
	void doNotWithNinExpressionTypeThrowsException() {
		// Arrange
		Key key = new Key("testKey");
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, key,
				new Value(java.util.List.of("value1", "value2")));
		StringBuilder context = new StringBuilder();
		// Act & Assert
		RuntimeException exception = assertThrows(RuntimeException.class,
				() -> converter.doNot(ninExpression, context));
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("NIN"));
		assertTrue(exception.getMessage().contains("Only NOT is supported here"));
	}

	@Test
	@Tag("valid")
	void doNotPreservesExistingContextContent() {
		// Arrange
		Key key = new Key("preserveKey");
		Expression innerExpression = new Expression(Filter.ExpressionType.EQ, key, new Value("preserveValue"));
		Expression notExpression = new Expression(Filter.ExpressionType.NOT, innerExpression, null);
		StringBuilder context = new StringBuilder("WHERE ");
		// Act
		converter.doNot(notExpression, context);
		// Assert
		String result = context.toString();
		assertTrue(result.startsWith("WHERE "), "Result should preserve existing content");
		assertTrue(result.contains("NOT "), "Result should contain 'NOT '");
		assertTrue(result.indexOf("WHERE ") < result.indexOf("NOT "), "Original content should come before NOT");
	}

	@Test
	@Tag("invalid")
	void doNotWithNeExpressionTypeThrowsException() {
		// Arrange
		Key key = new Key("testKey");
		Expression neExpression = new Expression(Filter.ExpressionType.NE, key, new Value("testValue"));
		StringBuilder context = new StringBuilder();
		// Act & Assert
		RuntimeException exception = assertThrows(RuntimeException.class, () -> converter.doNot(neExpression, context));
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("NE"));
	}

	@Test
	@Tag("invalid")
	void doNotWithLtExpressionTypeThrowsException() {
		// Arrange
		Key key = new Key("testKey");
		Expression ltExpression = new Expression(Filter.ExpressionType.LT, key, new Value(10));
		StringBuilder context = new StringBuilder();
		// Act & Assert
		RuntimeException exception = assertThrows(RuntimeException.class, () -> converter.doNot(ltExpression, context));
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("LT"));
	}

	@Test
	@Tag("invalid")
	void doNotWithGtExpressionTypeThrowsException() {
		// Arrange
		Key key = new Key("testKey");
		Expression gtExpression = new Expression(Filter.ExpressionType.GT, key, new Value(10));
		StringBuilder context = new StringBuilder();
		// Act & Assert
		RuntimeException exception = assertThrows(RuntimeException.class, () -> converter.doNot(gtExpression, context));
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("GT"));
	}

	@Test
	@Tag("invalid")
	void doNotWithLteExpressionTypeThrowsException() {
		// Arrange
		Key key = new Key("testKey");
		Expression lteExpression = new Expression(Filter.ExpressionType.LTE, key, new Value(10));
		StringBuilder context = new StringBuilder();
		// Act & Assert
		RuntimeException exception = assertThrows(RuntimeException.class,
				() -> converter.doNot(lteExpression, context));
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("LTE"));
	}

	@Test
	@Tag("invalid")
	void doNotWithGteExpressionTypeThrowsException() {
		// Arrange
		Key key = new Key("testKey");
		Expression gteExpression = new Expression(Filter.ExpressionType.GTE, key, new Value(10));
		StringBuilder context = new StringBuilder();
		// Act & Assert
		RuntimeException exception = assertThrows(RuntimeException.class,
				() -> converter.doNot(gteExpression, context));
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("GTE"));
	}

	@Test
	@Tag("boundary")
	void doNotWithEmptyStringBuilder() {
		// Arrange
		Key key = new Key("emptyKey");
		Expression innerExpression = new Expression(Filter.ExpressionType.EQ, key, new Value("emptyValue"));
		Expression notExpression = new Expression(Filter.ExpressionType.NOT, innerExpression, null);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doNot(notExpression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertFalse(result.isEmpty(), "Result should not be empty");
		assertTrue(result.startsWith("NOT "), "Result should start with 'NOT '");
	}

}