/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-12-sqlite using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=doExpression_7373dbacf8
ROOST_METHOD_SIG_HASH=doExpression_f053663651

Scenario 1: Test NIN Expression Type Conversion

Details:
  TestName: ninExpressionTypeConvertsToNotInFormat
  Description: Verify that when an expression with NIN (Not In) type is passed, the method correctly transforms it into a NOT IN format by delegating to the doNot method with a wrapped IN expression.

Execution:
  Arrange: Create an Expression with type NIN, a Key as the left operand, and a list of values as the right operand.
  Act: Invoke doExpression with the NIN expression and a StringBuilder context.
  Assert: Verify that the context contains "NOT " prefix followed by the converted IN expression format.

Validation:
  The assertion verifies that NIN expressions are properly transformed into "NOT <left> IN <right>" format instead of "<left> NOT IN <right>". This is significant because Neo4j requires this specific syntax for negated IN operations.

---

Scenario 2: Test EQ Expression Type Conversion

Details:
  TestName: eqExpressionTypeProducesEqualitySymbol
  Description: Verify that an expression with EQ (Equals) type produces the correct equality operator " = " between the left and right operands.

Execution:
  Arrange: Create an Expression with type EQ, a Key as the left operand, and a value as the right operand.
  Act: Invoke doExpression with the EQ expression and a StringBuilder context.
  Assert: Verify that the context contains the left operand, " = " symbol, and right operand in sequence.

Validation:
  The assertion confirms that equality comparisons are correctly formatted for Neo4j queries. This is essential for filtering vector store results based on exact metadata matches.

---

Scenario 3: Test NE Expression Type Conversion

Details:
  TestName: neExpressionTypeProducesNotEqualSymbol
  Description: Verify that an expression with NE (Not Equals) type produces the correct inequality operator " <> " between operands.

Execution:
  Arrange: Create an Expression with type NE, a Key as the left operand, and a value as the right operand.
  Act: Invoke doExpression with the NE expression and a StringBuilder context.
  Assert: Verify that the context contains the left operand, " <> " symbol, and right operand in sequence.

Validation:
  The assertion ensures that not-equal comparisons use Neo4j's standard inequality operator. This supports filtering out specific metadata values from vector search results.

---

Scenario 4: Test LT Expression Type Conversion

Details:
  TestName: ltExpressionTypeProducesLessThanSymbol
  Description: Verify that an expression with LT (Less Than) type produces the correct " < " operator between operands.

Execution:
  Arrange: Create an Expression with type LT, a Key as the left operand, and a numeric value as the right operand.
  Act: Invoke doExpression with the LT expression and a StringBuilder context.
  Assert: Verify that the context contains the left operand, " < " symbol, and right operand in sequence.

Validation:
  The assertion confirms proper formatting of less-than comparisons for range-based filtering in Neo4j vector queries.

---

Scenario 5: Test LTE Expression Type Conversion

Details:
  TestName: lteExpressionTypeProducesLessThanOrEqualSymbol
  Description: Verify that an expression with LTE (Less Than or Equal) type produces the correct " <= " operator.

Execution:
  Arrange: Create an Expression with type LTE, a Key as the left operand, and a numeric value as the right operand.
  Act: Invoke doExpression with the LTE expression and a StringBuilder context.
  Assert: Verify that the context contains the left operand, " <= " symbol, and right operand in sequence.

Validation:
  The assertion ensures inclusive upper-bound comparisons are correctly formatted for Neo4j filter expressions.

---

Scenario 6: Test GT Expression Type Conversion

Details:
  TestName: gtExpressionTypeProducesGreaterThanSymbol
  Description: Verify that an expression with GT (Greater Than) type produces the correct " > " operator.

Execution:
  Arrange: Create an Expression with type GT, a Key as the left operand, and a numeric value as the right operand.
  Act: Invoke doExpression with the GT expression and a StringBuilder context.
  Assert: Verify that the context contains the left operand, " > " symbol, and right operand in sequence.

Validation:
  The assertion confirms proper formatting of greater-than comparisons for range-based filtering.

---

Scenario 7: Test GTE Expression Type Conversion

Details:
  TestName: gteExpressionTypeProducesGreaterThanOrEqualSymbol
  Description: Verify that an expression with GTE (Greater Than or Equal) type produces the correct " >= " operator.

Execution:
  Arrange: Create an Expression with type GTE, a Key as the left operand, and a numeric value as the right operand.
  Act: Invoke doExpression with the GTE expression and a StringBuilder context.
  Assert: Verify that the context contains the left operand, " >= " symbol, and right operand in sequence.

Validation:
  The assertion ensures inclusive lower-bound comparisons are correctly formatted for Neo4j filter expressions.

---

Scenario 8: Test IN Expression Type Conversion

Details:
  TestName: inExpressionTypeProducesInSymbol
  Description: Verify that an expression with IN type produces the correct " IN " operator for membership testing.

Execution:
  Arrange: Create an Expression with type IN, a Key as the left operand, and a list of values as the right operand.
  Act: Invoke doExpression with the IN expression and a StringBuilder context.
  Assert: Verify that the context contains the left operand, " IN " symbol, and right operand in sequence.

Validation:
  The assertion confirms that IN expressions are properly formatted for checking if a value exists within a collection in Neo4j queries.

---

Scenario 9: Test AND Expression Type Conversion

Details:
  TestName: andExpressionTypeProducesAndSymbol
  Description: Verify that an expression with AND type produces the correct " AND " logical operator between two sub-expressions.

Execution:
  Arrange: Create an Expression with type AND, with left and right operands being sub-expressions.
  Act: Invoke doExpression with the AND expression and a StringBuilder context.
  Assert: Verify that the context contains the left expression, " AND " symbol, and right expression in sequence.

Validation:
  The assertion ensures compound filter conditions using logical AND are correctly formatted for Neo4j queries.

---

Scenario 10: Test OR Expression Type Conversion

Details:
  TestName: orExpressionTypeProducesOrSymbol
  Description: Verify that an expression with OR type produces the correct " OR " logical operator between two sub-expressions.

Execution:
  Arrange: Create an Expression with type OR, with left and right operands being sub-expressions.
  Act: Invoke doExpression with the OR expression and a StringBuilder context.
  Assert: Verify that the context contains the left expression, " OR " symbol, and right expression in sequence.

Validation:
  The assertion ensures compound filter conditions using logical OR are correctly formatted for Neo4j queries.

---

Scenario 11: Test Expression With String Value Operand

Details:
  TestName: expressionWithStringValueOperandConvertsCorrectly
  Description: Verify that expressions with string values as right operands are properly converted and included in the output.

Execution:
  Arrange: Create an Expression with type EQ, a Key as the left operand, and a string value as the right operand.
  Act: Invoke doExpression with the expression and a StringBuilder context.
  Assert: Verify that the context contains the properly formatted string value.

Validation:
  The assertion confirms that string operands are correctly handled in the expression conversion, which is critical for text-based metadata filtering.

---

Scenario 12: Test Expression With Numeric Value Operand

Details:
  TestName: expressionWithNumericValueOperandConvertsCorrectly
  Description: Verify that expressions with numeric values as right operands are properly converted without quotes.

Execution:
  Arrange: Create an Expression with type GT, a Key as the left operand, and an integer or double value as the right operand.
  Act: Invoke doExpression with the expression and a StringBuilder context.
  Assert: Verify that the context contains the numeric value without string quotes.

Validation:
  The assertion ensures numeric operands are correctly formatted for Neo4j queries, enabling proper numeric comparisons.

---

Scenario 13: Test Context Accumulation With Multiple Expressions

Details:
  TestName: contextAccumulatesMultipleExpressionOutputs
  Description: Verify that when doExpression is called multiple times with the same StringBuilder, the outputs are properly accumulated.

Execution:
  Arrange: Create a StringBuilder with existing content and an Expression with type EQ.
  Act: Invoke doExpression with the expression and the pre-populated StringBuilder context.
  Assert: Verify that the context contains both the original content and the new expression output.

Validation:
  The assertion confirms that the method properly appends to existing context rather than replacing it, which is important for building complex compound expressions.

---

Scenario 14: Test NIN Expression With Empty List

Details:
  TestName: ninExpressionWithEmptyListHandledCorrectly
  Description: Verify that a NIN expression with an empty list as the right operand is correctly transformed.

Execution:
  Arrange: Create an Expression with type NIN, a Key as the left operand, and an empty list as the right operand.
  Act: Invoke doExpression with the NIN expression and a StringBuilder context.
  Assert: Verify that the context contains the NOT IN format with the empty list representation.

Validation:
  The assertion ensures edge cases with empty collections are handled properly, maintaining query validity.

---

Scenario 15: Test Expression With Key Containing Special Characters

Details:
  TestName: expressionWithKeyContainingSpecialCharactersConvertsCorrectly
  Description: Verify that expressions with keys containing special characters (like quotes) are properly escaped or handled.

Execution:
  Arrange: Create an Expression with type EQ, a Key containing special characters as the left operand, and a value as the right operand.
  Act: Invoke doExpression with the expression and a StringBuilder context.
  Assert: Verify that the context contains the properly formatted key with special characters handled.

Validation:
  The assertion confirms that metadata keys with special characters don't break the generated Neo4j query syntax.

*/

// ********RoostGPT********

package org.springframework.ai.vectorstore.neo4j.filter;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.ai.vectorstore.filter.Filter;
import org.springframework.ai.vectorstore.filter.Filter.Expression;
import org.springframework.ai.vectorstore.filter.Filter.Key;
import org.springframework.ai.vectorstore.filter.Filter.Value;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.ai.vectorstore.filter.Filter.Group;
import org.springframework.ai.vectorstore.filter.converter.AbstractFilterExpressionConverter;

class Neo4JVectorFilterExpressionConverterDoExpressionTest {

	private Neo4jVectorFilterExpressionConverter converter;

	@BeforeEach
	void setUp() {
		converter = new Neo4jVectorFilterExpressionConverter();
	}

	@Test
	@Tag("valid")
	void ninExpressionTypeConvertsToNotInFormat() {
		// Arrange
		Key key = new Key("category");
		Value value = new Value(Arrays.asList("electronics", "books"));
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, key, value);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doExpression(ninExpression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains("NOT"), "Result should contain NOT prefix");
		assertTrue(result.contains("IN"), "Result should contain IN operator");
	}

	@Test
	@Tag("valid")
	void eqExpressionTypeProducesEqualitySymbol() {
		// Arrange
		Key key = new Key("status");
		Value value = new Value("active");
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, key, value);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doExpression(eqExpression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" = "), "Result should contain equality symbol");
	}

	@Test
	@Tag("valid")
	void neExpressionTypeProducesNotEqualSymbol() {
		// Arrange
		Key key = new Key("type");
		Value value = new Value("deprecated");
		Expression neExpression = new Expression(Filter.ExpressionType.NE, key, value);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doExpression(neExpression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" <> "), "Result should contain not-equal symbol");
	}

	@Test
	@Tag("valid")
	void ltExpressionTypeProducesLessThanSymbol() {
		// Arrange
		Key key = new Key("price");
		Value value = new Value(100);
		Expression ltExpression = new Expression(Filter.ExpressionType.LT, key, value);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doExpression(ltExpression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" < "), "Result should contain less-than symbol");
	}

	@Test
	@Tag("valid")
	void lteExpressionTypeProducesLessThanOrEqualSymbol() {
		// Arrange
		Key key = new Key("quantity");
		Value value = new Value(50);
		Expression lteExpression = new Expression(Filter.ExpressionType.LTE, key, value);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doExpression(lteExpression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" <= "), "Result should contain less-than-or-equal symbol");
	}

	@Test
	@Tag("valid")
	void gtExpressionTypeProducesGreaterThanSymbol() {
		// Arrange
		Key key = new Key("rating");
		Value value = new Value(4.0);
		Expression gtExpression = new Expression(Filter.ExpressionType.GT, key, value);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doExpression(gtExpression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" > "), "Result should contain greater-than symbol");
	}

	@Test
	@Tag("valid")
	void gteExpressionTypeProducesGreaterThanOrEqualSymbol() {
		// Arrange
		Key key = new Key("score");
		Value value = new Value(80);
		Expression gteExpression = new Expression(Filter.ExpressionType.GTE, key, value);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doExpression(gteExpression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" >= "), "Result should contain greater-than-or-equal symbol");
	}

	@Test
	@Tag("valid")
	void inExpressionTypeProducesInSymbol() {
		// Arrange
		Key key = new Key("color");
		Value value = new Value(Arrays.asList("red", "blue", "green"));
		Expression inExpression = new Expression(Filter.ExpressionType.IN, key, value);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doExpression(inExpression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" IN "), "Result should contain IN symbol");
	}

	@Test
	@Tag("valid")
	void andExpressionTypeProducesAndSymbol() {
		// Arrange
		Expression leftExpr = new Expression(Filter.ExpressionType.EQ, new Key("status"), new Value("active"));
		Expression rightExpr = new Expression(Filter.ExpressionType.GT, new Key("count"), new Value(10));
		Expression andExpression = new Expression(Filter.ExpressionType.AND, leftExpr, rightExpr);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doExpression(andExpression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" AND "), "Result should contain AND symbol");
	}

	@Test
	@Tag("valid")
	void orExpressionTypeProducesOrSymbol() {
		// Arrange
		Expression leftExpr = new Expression(Filter.ExpressionType.EQ, new Key("type"), new Value("A"));
		Expression rightExpr = new Expression(Filter.ExpressionType.EQ, new Key("type"), new Value("B"));
		Expression orExpression = new Expression(Filter.ExpressionType.OR, leftExpr, rightExpr);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doExpression(orExpression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" OR "), "Result should contain OR symbol");
	}

	@Test
	@Tag("valid")
	void expressionWithStringValueOperandConvertsCorrectly() {
		// Arrange
		Key key = new Key("name");
		Value value = new Value("testValue");
		Expression expression = new Expression(Filter.ExpressionType.EQ, key, value);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doExpression(expression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertFalse(result.isEmpty(), "Result should not be empty");
		assertTrue(result.contains("testValue") || result.contains("'testValue'") || result.contains("\"testValue\""),
				"Result should contain the string value");
	}

	@Test
	@Tag("valid")
	void expressionWithNumericValueOperandConvertsCorrectly() {
		// Arrange
		Key key = new Key("amount");
		Value value = new Value(42.5);
		Expression expression = new Expression(Filter.ExpressionType.GT, key, value);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doExpression(expression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains("42.5"), "Result should contain the numeric value");
	}

	@Test
	@Tag("valid")
	void contextAccumulatesMultipleExpressionOutputs() {
		// Arrange
		StringBuilder context = new StringBuilder("EXISTING_CONTENT ");
		Key key = new Key("field");
		Value value = new Value("value");
		Expression expression = new Expression(Filter.ExpressionType.EQ, key, value);
		// Act
		converter.doExpression(expression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.startsWith("EXISTING_CONTENT "), "Result should preserve existing content");
		assertTrue(result.contains(" = "), "Result should contain the new expression");
	}

	@Test
	@Tag("boundary")
	void ninExpressionWithEmptyListHandledCorrectly() {
		// Arrange
		Key key = new Key("tags");
		Value value = new Value(Collections.emptyList());
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, key, value);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doExpression(ninExpression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains("NOT"), "Result should contain NOT for NIN with empty list");
	}

	@Test
	@Tag("boundary")
	void expressionWithKeyContainingSpecialCharactersConvertsCorrectly() {
		// Arrange
		Key key = new Key("field_name");
		Value value = new Value("test");
		Expression expression = new Expression(Filter.ExpressionType.EQ, key, value);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doExpression(expression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertFalse(result.isEmpty(), "Result should not be empty for keys with underscores");
	}

	@Test
	@Tag("valid")
	void expressionWithIntegerValueOperandConvertsCorrectly() {
		// Arrange
		Key key = new Key("count");
		Value value = new Value(100);
		Expression expression = new Expression(Filter.ExpressionType.LTE, key, value);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doExpression(expression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains("100"), "Result should contain the integer value");
		assertTrue(result.contains(" <= "), "Result should contain LTE operator");
	}

	@Test
	@Tag("valid")
	void inExpressionWithSingleValueListConvertsCorrectly() {
		// Arrange
		Key key = new Key("status");
		Value value = new Value(Collections.singletonList("active"));
		Expression inExpression = new Expression(Filter.ExpressionType.IN, key, value);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doExpression(inExpression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" IN "), "Result should contain IN operator");
	}

	@Test
	@Tag("valid")
	void ninExpressionWithMultipleValuesConvertsCorrectly() {
		// Arrange
		Key key = new Key("category");
		Value value = new Value(Arrays.asList("A", "B", "C", "D"));
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, key, value);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doExpression(ninExpression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains("NOT"), "Result should contain NOT for NIN expression");
	}

	@Test
	@Tag("valid")
	void expressionWithBooleanValueConvertsCorrectly() {
		// Arrange
		Key key = new Key("isActive");
		Value value = new Value(true);
		Expression expression = new Expression(Filter.ExpressionType.EQ, key, value);
		StringBuilder context = new StringBuilder();
		// Act
		converter.doExpression(expression, context);
		// Assert
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" = "), "Result should contain equality operator");
	}

	@Test
	@Tag("boundary")
	void expressionWithNullContextThrowsException() {
		// Arrange
		Key key = new Key("field");
		Value value = new Value("value");
		Expression expression = new Expression(Filter.ExpressionType.EQ, key, value);
		// Act & Assert
		assertThrows(NullPointerException.class, () -> {
			converter.doExpression(expression, null);
		});
	}

}