/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-maven-spring-ai using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=doKey_8c655f69d5
ROOST_METHOD_SIG_HASH=doKey_e82e12c6d2

Scenario 1: Basic Key Conversion with Simple String

Details:
  TestName: keyWithSimpleStringAppendsCorrectFormat
  Description: This test verifies that the doKey method correctly formats a simple key string without special characters. It should append "node.`metadata." prefix, the key value, and closing backtick to the StringBuilder context.
Execution:
  Arrange: Create a StringBuilder instance and a Key object with a simple string value like "username".
  Act: Invoke the doKey method with the created Key and StringBuilder.
  Assert: Verify that the StringBuilder contains "node.`metadata.username`".
Validation:
  This assertion verifies that the basic formatting structure is correctly applied to simple key names. The test ensures that the method properly constructs the Neo4j property path format with the metadata prefix and backtick escaping, which is essential for querying metadata fields in Neo4j vector store operations.

Scenario 2: Key Conversion with Double Quotes

Details:
  TestName: keyWithDoubleQuotesRemovesQuotes
  Description: This test checks that the doKey method correctly removes double quotes from the key string. The method should strip out any double quote characters while maintaining the rest of the key value.
Execution:
  Arrange: Create a StringBuilder instance and a Key object with a string containing double quotes like "user\"name\"field".
  Act: Invoke the doKey method with the Key containing double quotes and the StringBuilder.
  Assert: Verify that the StringBuilder contains "node.`metadata.usernamefield`" with quotes removed.
Validation:
  This assertion confirms that the replace operation for double quotes works correctly. This is critical because double quotes in property names could cause syntax errors in Neo4j queries. The test ensures data sanitization for safe query construction.

Scenario 3: Key Conversion with Empty String

Details:
  TestName: keyWithEmptyStringAppendsEmptyMetadata
  Description: This test validates the behavior when an empty string is provided as the key value. The method should still append the proper format structure even with an empty key.
Execution:
  Arrange: Create a StringBuilder instance and a Key object with an empty string "".
  Act: Invoke the doKey method with the empty Key and StringBuilder.
  Assert: Verify that the StringBuilder contains "node.`metadata.`".
Validation:
  This assertion ensures that the method handles edge cases gracefully without throwing exceptions. While an empty metadata key may not be practical in real scenarios, the method should not fail and should maintain consistent formatting. This test validates robustness in handling unexpected input.

Scenario 4: Key Conversion with Special Characters

Details:
  TestName: keyWithSpecialCharactersPreservesCharacters
  Description: This test verifies that special characters (except double quotes) are preserved in the key value. Characters like underscores, hyphens, dots, and numbers should remain unchanged.
Execution:
  Arrange: Create a StringBuilder instance and a Key object with special characters like "user_name-123.field".
  Act: Invoke the doKey method with the Key containing special characters and the StringBuilder.
  Assert: Verify that the StringBuilder contains "node.`metadata.user_name-123.field`".
Validation:
  This assertion confirms that only double quotes are removed and all other characters are preserved. This is important because metadata keys in real-world applications often contain various special characters for naming conventions. The test ensures that legitimate special characters are not inadvertently removed.

Scenario 5: Key Conversion with Multiple Double Quotes

Details:
  TestName: keyWithMultipleDoubleQuotesRemovesAllQuotes
  Description: This test checks that the doKey method removes all occurrences of double quotes from the key string, not just the first occurrence.
Execution:
  Arrange: Create a StringBuilder instance and a Key object with multiple double quotes like "\"user\"\"name\"".
  Act: Invoke the doKey method with the Key containing multiple double quotes and the StringBuilder.
  Assert: Verify that the StringBuilder contains "node.`metadata.username`" with all quotes removed.
Validation:
  This assertion validates that the replace operation works globally across the entire string. Multiple quotes could appear in malformed or escaped input, and the method must handle all occurrences to prevent query syntax errors in Neo4j.

Scenario 6: Key Conversion Appends to Existing Context

Details:
  TestName: keyAppendsToExistingStringBuilderContent
  Description: This test verifies that the doKey method correctly appends to a StringBuilder that already contains content, rather than replacing it.
Execution:
  Arrange: Create a StringBuilder with existing content like "WHERE " and a Key object with value "status".
  Act: Invoke the doKey method with the Key and the pre-populated StringBuilder.
  Assert: Verify that the StringBuilder contains "WHERE node.`metadata.status`".
Validation:
  This assertion ensures that the method works correctly in the context of building larger query strings. Since the method is part of a filter expression converter, it will typically be called as part of constructing a complete query. This test validates that the method integrates properly with existing query construction logic.

Scenario 7: Key Conversion with Unicode Characters

Details:
  TestName: keyWithUnicodeCharactersPreservesUnicode
  Description: This test validates that Unicode characters in the key value are preserved correctly. The method should handle international characters without corruption.
Execution:
  Arrange: Create a StringBuilder instance and a Key object with Unicode characters like "用户名" or "имя".
  Act: Invoke the doKey method with the Key containing Unicode characters and the StringBuilder.
  Assert: Verify that the StringBuilder contains the Unicode characters intact within the proper format structure.
Validation:
  This assertion confirms that the method is Unicode-safe and can handle internationalized metadata keys. In global applications, metadata keys might contain non-ASCII characters, and the method must preserve them correctly for proper Neo4j query execution.

Scenario 8: Key Conversion with Whitespace

Details:
  TestName: keyWithWhitespacePreservesSpaces
  Description: This test checks that whitespace characters (spaces, tabs) within the key value are preserved as-is.
Execution:
  Arrange: Create a StringBuilder instance and a Key object with whitespace like "user name" or "user\tname".
  Act: Invoke the doKey method with the Key containing whitespace and the StringBuilder.
  Assert: Verify that the StringBuilder preserves the whitespace in the output format.
Validation:
  This assertion ensures that whitespace is not trimmed or modified. While whitespace in metadata keys may be uncommon, the method should preserve the exact key value as provided. The backtick escaping in Neo4j allows for property names with spaces.

Scenario 9: Key Conversion with Backtick Characters

Details:
  TestName: keyWithBacktickCharactersPreservesBackticks
  Description: This test verifies the behavior when the key value itself contains backtick characters. The method should preserve backticks in the key value.
Execution:
  Arrange: Create a StringBuilder instance and a Key object with backticks like "user`name".
  Act: Invoke the doKey method with the Key containing backticks and the StringBuilder.
  Assert: Verify that the StringBuilder contains "node.`metadata.user`name`".
Validation:
  This assertion checks how the method handles backticks within the key value. Since backticks are used as delimiters in the output format, having them in the key value could potentially cause issues. This test documents the current behavior and highlights a potential edge case that might need special handling in production scenarios.

Scenario 10: Key Conversion with Mixed Quote Types

Details:
  TestName: keyWithMixedQuotesRemovesOnlyDoubleQuotes
  Description: This test validates that only double quotes are removed while single quotes are preserved in the key value.
Execution:
  Arrange: Create a StringBuilder instance and a Key object with both single and double quotes like "user'name\"field".
  Act: Invoke the doKey method with the Key containing mixed quotes and the StringBuilder.
  Assert: Verify that the StringBuilder contains "node.`metadata.user'namefield`" with only double quotes removed.
Validation:
  This assertion confirms that the replace operation is specific to double quotes only. Single quotes are valid characters in property names and should not be removed. This test ensures precise string manipulation that doesn't inadvertently affect other quote characters.

Scenario 11: Key Conversion with Null Key Value Handling

Details:
  TestName: keyWithNullValueThrowsNullPointerException
  Description: This test verifies the behavior when a Key object with a null key value is passed to the doKey method. The method should throw a NullPointerException when attempting to call replace on null.
Execution:
  Arrange: Create a StringBuilder instance and attempt to create a Key object that would have a null key() return value.
  Act: Invoke the doKey method with the null-valued Key and StringBuilder.
  Assert: Verify that a NullPointerException is thrown.
Validation:
  This assertion documents the method's behavior with null input. Since the method calls key.key().replace() without null checking, it will throw a NullPointerException. This test is important for understanding the method's contract and the need for null validation at higher levels of the application.

Scenario 12: Key Conversion with Very Long String

Details:
  TestName: keyWithVeryLongStringAppendsCompleteValue
  Description: This test validates that the doKey method can handle very long key strings without truncation or performance issues.
Execution:
  Arrange: Create a StringBuilder instance and a Key object with a very long string (e.g., 1000+ characters).
  Act: Invoke the doKey method with the long Key and StringBuilder.
  Assert: Verify that the StringBuilder contains the complete long string within the proper format structure.
Validation:
  This assertion ensures that there are no hidden length limitations in the method implementation. Long metadata keys, while unusual, should be handled correctly. This test validates that the StringBuilder append operations work correctly with large strings and that the replace operation processes the entire string.

Scenario 13: Key Conversion Maintains StringBuilder Reference

Details:
  TestName: keyModifiesSameStringBuilderInstance
  Description: This test verifies that the doKey method modifies the StringBuilder instance passed as a parameter rather than creating a new instance.
Execution:
  Arrange: Create a StringBuilder instance, store its reference, and create a Key object with value "field".
  Act: Invoke the doKey method with the Key and StringBuilder.
  Assert: Verify that the original StringBuilder reference contains the appended content and no new instance was created.
Validation:
  This assertion confirms that the method follows the expected pattern of modifying the passed StringBuilder in place. This is important for performance and memory efficiency, especially when building complex filter expressions with multiple method calls. The test ensures proper object reference handling.

*/

// ********RoostGPT********

package org.springframework.ai.vectorstore.neo4j.filter;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.ai.vectorstore.filter.Filter.Key;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.ai.vectorstore.filter.Filter;
import org.springframework.ai.vectorstore.filter.Filter.Expression;
import org.springframework.ai.vectorstore.filter.Filter.Group;
import org.springframework.ai.vectorstore.filter.converter.AbstractFilterExpressionConverter;

class Neo4JVectorFilterExpressionConverterDoKeyTest {

	private Neo4jVectorFilterExpressionConverter converter = new Neo4jVectorFilterExpressionConverter();

	@Test
	@Tag("valid")
	void keyWithSimpleStringAppendsCorrectFormat() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("username");

		converter.doKey(key, context);

		assertEquals("node.`metadata.username`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithDoubleQuotesRemovesQuotes() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("user\"name\"field");

		converter.doKey(key, context);

		assertEquals("node.`metadata.usernamefield`", context.toString());
	}

	@Test
	@Tag("boundary")
	void keyWithEmptyStringAppendsEmptyMetadata() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("");

		converter.doKey(key, context);

		assertEquals("node.`metadata.`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithSpecialCharactersPreservesCharacters() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("user_name-123.field");

		converter.doKey(key, context);

		assertEquals("node.`metadata.user_name-123.field`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithMultipleDoubleQuotesRemovesAllQuotes() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("\"user\"\"name\"");

		converter.doKey(key, context);

		assertEquals("node.`metadata.username`", context.toString());
	}

	@Test
	@Tag("integration")
	void keyAppendsToExistingStringBuilderContent() {
		StringBuilder context = new StringBuilder("WHERE ");
		Key key = new Key("status");

		converter.doKey(key, context);

		assertEquals("WHERE node.`metadata.status`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithUnicodeCharactersPreservesUnicode() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("用户名");

		converter.doKey(key, context);

		assertEquals("node.`metadata.用户名`", context.toString());

		context = new StringBuilder();
		key = new Key("имя");

		converter.doKey(key, context);

		assertEquals("node.`metadata.имя`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithWhitespacePreservesSpaces() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("user name");

		converter.doKey(key, context);

		assertEquals("node.`metadata.user name`", context.toString());

		context = new StringBuilder();
		key = new Key("user\tname");

		converter.doKey(key, context);

		assertEquals("node.`metadata.user\tname`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithBacktickCharactersPreservesBackticks() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("user`name");

		converter.doKey(key, context);

		assertEquals("node.`metadata.user`name`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithMixedQuotesRemovesOnlyDoubleQuotes() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("user'name\"field");

		converter.doKey(key, context);

		assertEquals("node.`metadata.user'namefield`", context.toString());
	}

	@Test
	@Tag("invalid")
	void keyWithNullValueThrowsNullPointerException() {
		StringBuilder context = new StringBuilder();
		Key key = new Key(null);

		assertThrows(NullPointerException.class, () -> {
			converter.doKey(key, context);
		});
	}

	@Test
	@Tag("boundary")
	void keyWithVeryLongStringAppendsCompleteValue() {
		StringBuilder context = new StringBuilder();
		String longString = "a".repeat(1000);
		Key key = new Key(longString);

		converter.doKey(key, context);

		String expected = "node.`metadata." + longString + "`";
		assertEquals(expected, context.toString());
		assertTrue(context.toString().length() > 1000);
	}

	@Test
	@Tag("valid")
	void keyModifiesSameStringBuilderInstance() {
		StringBuilder context = new StringBuilder();
		StringBuilder originalReference = context;
		Key key = new Key("field");

		converter.doKey(key, context);

		assertSame(originalReference, context);
		assertEquals("node.`metadata.field`", context.toString());
		assertNotNull(context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithNumericCharactersPreservesNumbers() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("field123");

		converter.doKey(key, context);

		assertEquals("node.`metadata.field123`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithLeadingAndTrailingDoubleQuotes() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("\"fieldname\"");

		converter.doKey(key, context);

		assertEquals("node.`metadata.fieldname`", context.toString());
	}

	@Test
	@Tag("boundary")
	void keyWithOnlyDoubleQuotes() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("\"\"\"");

		converter.doKey(key, context);

		assertEquals("node.`metadata.`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithDotSeparatedPath() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("user.profile.name");

		converter.doKey(key, context);

		assertEquals("node.`metadata.user.profile.name`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithUnderscorePrefix() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("_privateField");

		converter.doKey(key, context);

		assertEquals("node.`metadata._privateField`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithMixedCasing() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("UserName");

		converter.doKey(key, context);

		assertEquals("node.`metadata.UserName`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithNewlineCharacters() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("user\nname");

		converter.doKey(key, context);

		assertEquals("node.`metadata.user\nname`", context.toString());
	}

}