/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-11-java using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=doNot_82558cd573
ROOST_METHOD_SIG_HASH=doNot_ecb1a8c56c

Scenario 1: Valid NOT Expression Type Processing

Details:
  TestName: doNotWithValidNotExpressionType
  Description: Verify that the doNot method correctly processes an expression with NOT type by appending "NOT " prefix followed by the converted left operand to the context.
Execution:
  Arrange: Create a StringBuilder context. Create an Expression with ExpressionType.NOT and a valid left operand (e.g., a Key or another Expression).
  Act: Invoke the doNot method with the NOT expression and the StringBuilder context.
  Assert: Verify that the context StringBuilder contains "NOT " followed by the converted left operand string.
Validation:
  The assertion verifies that the method correctly formats NOT expressions by prefixing "NOT " to the converted left operand. This is essential for generating valid Neo4j query conditions that negate a specific filter criterion.

---

Scenario 2: Invalid Expression Type Throws RuntimeException

Details:
  TestName: doNotWithAndExpressionTypeThrowsException
  Description: Verify that the doNot method throws a RuntimeException when provided with an AND expression type instead of NOT.
Execution:
  Arrange: Create a StringBuilder context. Create an Expression with ExpressionType.AND and valid left and right operands.
  Act: Invoke the doNot method with the AND expression and the StringBuilder context.
  Assert: Verify that a RuntimeException is thrown with a message containing "Unsupported expression type AND. Only NOT is supported here".
Validation:
  The assertion confirms that the method enforces type safety by rejecting non-NOT expression types. This prevents incorrect query generation and ensures the method is used only for its intended purpose.

---

Scenario 3: Invalid Expression Type OR Throws RuntimeException

Details:
  TestName: doNotWithOrExpressionTypeThrowsException
  Description: Verify that the doNot method throws a RuntimeException when provided with an OR expression type.
Execution:
  Arrange: Create a StringBuilder context. Create an Expression with ExpressionType.OR and valid left and right operands.
  Act: Invoke the doNot method with the OR expression and the StringBuilder context.
  Assert: Verify that a RuntimeException is thrown with message indicating OR is unsupported.
Validation:
  The assertion ensures that OR expressions are properly rejected, maintaining the integrity of the NOT-specific processing logic.

---

Scenario 4: Invalid Expression Type EQ Throws RuntimeException

Details:
  TestName: doNotWithEqExpressionTypeThrowsException
  Description: Verify that the doNot method throws a RuntimeException when provided with an EQ (equals) expression type.
Execution:
  Arrange: Create a StringBuilder context. Create an Expression with ExpressionType.EQ and valid operands.
  Act: Invoke the doNot method with the EQ expression and the StringBuilder context.
  Assert: Verify that a RuntimeException is thrown with appropriate error message.
Validation:
  The assertion validates that equality expressions cannot be processed by doNot, ensuring proper method usage boundaries.

---

Scenario 5: NOT Expression With Key Left Operand

Details:
  TestName: doNotWithKeyAsLeftOperand
  Description: Verify that the doNot method correctly handles a NOT expression where the left operand is a Key object.
Execution:
  Arrange: Create a StringBuilder context. Create a Key object with a specific key name. Create an Expression with ExpressionType.NOT and the Key as the left operand.
  Act: Invoke the doNot method with the expression and context.
  Assert: Verify that the context contains "NOT " followed by the properly formatted key representation.
Validation:
  The assertion confirms that Key operands are correctly converted and prefixed with NOT, which is crucial for negating metadata field conditions in Neo4j queries.

---

Scenario 6: NOT Expression With Nested Expression As Left Operand

Details:
  TestName: doNotWithNestedExpressionAsLeftOperand
  Description: Verify that the doNot method correctly handles a NOT expression where the left operand is another Expression (e.g., an IN expression).
Execution:
  Arrange: Create a StringBuilder context. Create an inner Expression with ExpressionType.IN. Create an outer Expression with ExpressionType.NOT and the inner expression as the left operand.
  Act: Invoke the doNot method with the outer expression and context.
  Assert: Verify that the context contains "NOT " followed by the converted nested expression.
Validation:
  The assertion validates that nested expressions are properly converted, enabling complex negation patterns like "NOT (field IN [values])".

---

Scenario 7: NOT Expression With Group As Left Operand

Details:
  TestName: doNotWithGroupAsLeftOperand
  Description: Verify that the doNot method correctly handles a NOT expression where the left operand is a Group containing another expression.
Execution:
  Arrange: Create a StringBuilder context. Create a Group object containing an inner expression. Create an Expression with ExpressionType.NOT and the Group as the left operand.
  Act: Invoke the doNot method with the expression and context.
  Assert: Verify that the context contains "NOT " followed by the properly formatted group with parentheses.
Validation:
  The assertion ensures that grouped expressions are correctly negated, maintaining proper operator precedence in the generated Neo4j query.

---

Scenario 8: Invalid Expression Type IN Throws RuntimeException

Details:
  TestName: doNotWithInExpressionTypeThrowsException
  Description: Verify that the doNot method throws a RuntimeException when provided with an IN expression type directly.
Execution:
  Arrange: Create a StringBuilder context. Create an Expression with ExpressionType.IN and valid operands.
  Act: Invoke the doNot method with the IN expression and context.
  Assert: Verify that a RuntimeException is thrown indicating IN is unsupported in this context.
Validation:
  The assertion confirms that IN expressions must be wrapped in NOT expressions rather than passed directly to doNot.

---

Scenario 9: Invalid Expression Type NIN Throws RuntimeException

Details:
  TestName: doNotWithNinExpressionTypeThrowsException
  Description: Verify that the doNot method throws a RuntimeException when provided with a NIN (not in) expression type.
Execution:
  Arrange: Create a StringBuilder context. Create an Expression with ExpressionType.NIN and valid operands.
  Act: Invoke the doNot method with the NIN expression and context.
  Assert: Verify that a RuntimeException is thrown with appropriate error message.
Validation:
  The assertion validates that NIN expressions should be handled by doExpression which transforms them, not directly by doNot.

---

Scenario 10: Context StringBuilder Appends Correctly Without Overwriting

Details:
  TestName: doNotAppendsToExistingContextContent
  Description: Verify that the doNot method appends to existing content in the StringBuilder context rather than replacing it.
Execution:
  Arrange: Create a StringBuilder context with pre-existing content (e.g., "existing content "). Create an Expression with ExpressionType.NOT and a valid left operand.
  Act: Invoke the doNot method with the expression and the pre-populated context.
  Assert: Verify that the context starts with "existing content " followed by "NOT " and the converted operand.
Validation:
  The assertion ensures that the method properly appends to the context, allowing for building complex compound queries incrementally.

---

Scenario 11: Invalid Expression Type LT Throws RuntimeException

Details:
  TestName: doNotWithLtExpressionTypeThrowsException
  Description: Verify that the doNot method throws a RuntimeException when provided with a LT (less than) expression type.
Execution:
  Arrange: Create a StringBuilder context. Create an Expression with ExpressionType.LT and valid operands.
  Act: Invoke the doNot method with the LT expression and context.
  Assert: Verify that a RuntimeException is thrown.
Validation:
  The assertion confirms that comparison operators are rejected by doNot, enforcing proper method usage.

---

Scenario 12: Invalid Expression Type GTE Throws RuntimeException

Details:
  TestName: doNotWithGteExpressionTypeThrowsException
  Description: Verify that the doNot method throws a RuntimeException when provided with a GTE (greater than or equal) expression type.
Execution:
  Arrange: Create a StringBuilder context. Create an Expression with ExpressionType.GTE and valid operands.
  Act: Invoke the doNot method with the GTE expression and context.
  Assert: Verify that a RuntimeException is thrown with message indicating GTE is unsupported.
Validation:
  The assertion validates that GTE expressions cannot bypass the normal expression processing flow through doNot.

*/

// ********RoostGPT********

package org.springframework.ai.vectorstore.neo4j.filter;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.ai.vectorstore.filter.Filter;
import org.springframework.ai.vectorstore.filter.Filter.Expression;
import org.springframework.ai.vectorstore.filter.Filter.Group;
import org.springframework.ai.vectorstore.filter.Filter.Key;
import org.springframework.ai.vectorstore.filter.Filter.Value;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.ai.vectorstore.filter.converter.AbstractFilterExpressionConverter;

class Neo4JVectorFilterExpressionConverterDoNotTest {

	private Neo4jVectorFilterExpressionConverter converter;

	@BeforeEach
	void setUp() {
		converter = new Neo4jVectorFilterExpressionConverter();
	}

	@Test
	@Tag("valid")
	void doNotWithValidNotExpressionType() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("testField");
		Expression notExpression = new Expression(Filter.ExpressionType.NOT,
				new Expression(Filter.ExpressionType.EQ, key, new Value("testValue")), null);
		converter.doNot(notExpression, context);
		String result = context.toString();
		assertTrue(result.startsWith("NOT "));
		assertNotNull(result);
	}

	@Test
	@Tag("invalid")
	void doNotWithAndExpressionTypeThrowsException() {
		StringBuilder context = new StringBuilder();
		Key leftKey = new Key("field1");
		Key rightKey = new Key("field2");
		Expression andExpression = new Expression(Filter.ExpressionType.AND,
				new Expression(Filter.ExpressionType.EQ, leftKey, new Value("value1")),
				new Expression(Filter.ExpressionType.EQ, rightKey, new Value("value2")));
		RuntimeException exception = assertThrows(RuntimeException.class, () -> {
			converter.doNot(andExpression, context);
		});
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("AND"));
		assertTrue(exception.getMessage().contains("Only NOT is supported here"));
	}

	@Test
	@Tag("invalid")
	void doNotWithOrExpressionTypeThrowsException() {
		StringBuilder context = new StringBuilder();
		Key leftKey = new Key("field1");
		Key rightKey = new Key("field2");
		Expression orExpression = new Expression(Filter.ExpressionType.OR,
				new Expression(Filter.ExpressionType.EQ, leftKey, new Value("value1")),
				new Expression(Filter.ExpressionType.EQ, rightKey, new Value("value2")));
		RuntimeException exception = assertThrows(RuntimeException.class, () -> {
			converter.doNot(orExpression, context);
		});
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("OR"));
	}

	@Test
	@Tag("invalid")
	void doNotWithEqExpressionTypeThrowsException() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("testField");
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, key, new Value("testValue"));
		RuntimeException exception = assertThrows(RuntimeException.class, () -> {
			converter.doNot(eqExpression, context);
		});
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("EQ"));
	}

	@Test
	@Tag("valid")
	void doNotWithKeyAsLeftOperand() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("metadataField");
		Expression innerExpression = new Expression(Filter.ExpressionType.EQ, key, new Value("someValue"));
		Expression notExpression = new Expression(Filter.ExpressionType.NOT, innerExpression, null);
		converter.doNot(notExpression, context);
		String result = context.toString();
		assertTrue(result.startsWith("NOT "));
		assertFalse(result.isEmpty());
	}

	@Test
	@Tag("valid")
	void doNotWithNestedExpressionAsLeftOperand() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("category");
		Value values = new Value(java.util.List.of("A", "B", "C"));
		Expression inExpression = new Expression(Filter.ExpressionType.IN, key, values);
		Expression notExpression = new Expression(Filter.ExpressionType.NOT, inExpression, null);
		converter.doNot(notExpression, context);
		String result = context.toString();
		assertTrue(result.startsWith("NOT "));
		assertNotNull(result);
	}

	@Test
	@Tag("valid")
	void doNotWithGroupAsLeftOperand() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("status");
		Expression innerExpression = new Expression(Filter.ExpressionType.EQ, key, new Value("active"));
		Group group = new Group(innerExpression);
		Expression notExpression = new Expression(Filter.ExpressionType.NOT, group, null);
		converter.doNot(notExpression, context);
		String result = context.toString();
		assertTrue(result.startsWith("NOT "));
	}

	@Test
	@Tag("invalid")
	void doNotWithInExpressionTypeThrowsException() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("tags");
		Value values = new Value(java.util.List.of("tag1", "tag2"));
		Expression inExpression = new Expression(Filter.ExpressionType.IN, key, values);
		RuntimeException exception = assertThrows(RuntimeException.class, () -> {
			converter.doNot(inExpression, context);
		});
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("IN"));
	}

	@Test
	@Tag("invalid")
	void doNotWithNinExpressionTypeThrowsException() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("categories");
		Value values = new Value(java.util.List.of("cat1", "cat2"));
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, key, values);
		RuntimeException exception = assertThrows(RuntimeException.class, () -> {
			converter.doNot(ninExpression, context);
		});
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("NIN"));
	}

	@Test
	@Tag("valid")
	void doNotAppendsToExistingContextContent() {
		StringBuilder context = new StringBuilder("existing content ");
		Key key = new Key("field");
		Expression innerExpression = new Expression(Filter.ExpressionType.EQ, key, new Value("value"));
		Expression notExpression = new Expression(Filter.ExpressionType.NOT, innerExpression, null);
		converter.doNot(notExpression, context);
		String result = context.toString();
		assertTrue(result.startsWith("existing content "));
		assertTrue(result.contains("NOT "));
	}

	@Test
	@Tag("invalid")
	void doNotWithLtExpressionTypeThrowsException() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("price");
		Expression ltExpression = new Expression(Filter.ExpressionType.LT, key, new Value(100));
		RuntimeException exception = assertThrows(RuntimeException.class, () -> {
			converter.doNot(ltExpression, context);
		});
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("LT"));
	}

	@Test
	@Tag("invalid")
	void doNotWithGteExpressionTypeThrowsException() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("quantity");
		Expression gteExpression = new Expression(Filter.ExpressionType.GTE, key, new Value(50));
		RuntimeException exception = assertThrows(RuntimeException.class, () -> {
			converter.doNot(gteExpression, context);
		});
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("GTE"));
	}

	@Test
	@Tag("invalid")
	void doNotWithNeExpressionTypeThrowsException() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("status");
		Expression neExpression = new Expression(Filter.ExpressionType.NE, key, new Value("inactive"));
		RuntimeException exception = assertThrows(RuntimeException.class, () -> {
			converter.doNot(neExpression, context);
		});
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("NE"));
	}

	@Test
	@Tag("invalid")
	void doNotWithLteExpressionTypeThrowsException() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("score");
		Expression lteExpression = new Expression(Filter.ExpressionType.LTE, key, new Value(75));
		RuntimeException exception = assertThrows(RuntimeException.class, () -> {
			converter.doNot(lteExpression, context);
		});
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("LTE"));
	}

	@Test
	@Tag("invalid")
	void doNotWithGtExpressionTypeThrowsException() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("age");
		Expression gtExpression = new Expression(Filter.ExpressionType.GT, key, new Value(18));
		RuntimeException exception = assertThrows(RuntimeException.class, () -> {
			converter.doNot(gtExpression, context);
		});
		assertTrue(exception.getMessage().contains("Unsupported expression type"));
		assertTrue(exception.getMessage().contains("GT"));
	}

	@Test
	@Tag("boundary")
	void doNotWithEmptyStringBuilder() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("emptyTest");
		Expression innerExpression = new Expression(Filter.ExpressionType.EQ, key, new Value("test"));
		Expression notExpression = new Expression(Filter.ExpressionType.NOT, innerExpression, null);
		converter.doNot(notExpression, context);
		String result = context.toString();
		assertFalse(result.isEmpty());
		assertTrue(result.startsWith("NOT "));
	}

	@Test
	@Tag("valid")
	void doNotWithNumericValue() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("count");
		Expression innerExpression = new Expression(Filter.ExpressionType.EQ, key, new Value(42));
		Expression notExpression = new Expression(Filter.ExpressionType.NOT, innerExpression, null);
		converter.doNot(notExpression, context);
		String result = context.toString();
		assertTrue(result.startsWith("NOT "));
		assertNotNull(result);
	}

	@Test
	@Tag("valid")
	void doNotWithBooleanValue() {
		StringBuilder context = new StringBuilder();
		Key key = new Key("isActive");
		Expression innerExpression = new Expression(Filter.ExpressionType.EQ, key, new Value(true));
		Expression notExpression = new Expression(Filter.ExpressionType.NOT, innerExpression, null);
		converter.doNot(notExpression, context);
		String result = context.toString();
		assertTrue(result.startsWith("NOT "));
	}

}