/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-11-java using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=doKey_8c655f69d5
ROOST_METHOD_SIG_HASH=doKey_e82e12c6d2

Scenario 1: Simple Key Without Special Characters

Details:
  TestName: simpleKeyWithoutSpecialCharacters
  Description: Verify that the doKey method correctly formats a simple key without any special characters by prepending "node.`metadata." and appending "`" to the key value.
Execution:
  Arrange: Create a Key object with a simple string value like "author".
  Act: Invoke the doKey method with the Key object and a StringBuilder context.
  Assert: Verify that the StringBuilder contains "node.`metadata.author`".
Validation:
  The assertion verifies that the method correctly constructs the Neo4j property path format for metadata fields. This is essential for generating valid Cypher queries that access metadata properties stored in Neo4j nodes.

---

Scenario 2: Key With Double Quotes That Should Be Removed

Details:
  TestName: keyWithDoubleQuotesRemoved
  Description: Verify that the doKey method removes double quote characters from the key value when constructing the Neo4j property path.
Execution:
  Arrange: Create a Key object with a value containing double quotes like "\"fieldName\"".
  Act: Invoke the doKey method with the Key object and a StringBuilder context.
  Assert: Verify that the StringBuilder contains "node.`metadata.fieldName`" without any double quotes.
Validation:
  The assertion confirms that double quotes are properly stripped from the key, preventing syntax errors in the generated Cypher query. This sanitization is important for handling keys that may have been quoted in the original filter expression.

---

Scenario 3: Key With Embedded Double Quotes

Details:
  TestName: keyWithEmbeddedDoubleQuotes
  Description: Verify that the doKey method removes all double quote characters from a key that has quotes embedded within the string.
Execution:
  Arrange: Create a Key object with a value like "field\"Name\"Test".
  Act: Invoke the doKey method with the Key object and a StringBuilder context.
  Assert: Verify that the StringBuilder contains "node.`metadata.fieldNameTest`".
Validation:
  The assertion ensures that all occurrences of double quotes are removed from the key, not just leading or trailing ones. This handles edge cases where quotes might appear in the middle of a key name.

---

Scenario 4: Key With Empty String

Details:
  TestName: keyWithEmptyString
  Description: Verify that the doKey method handles an empty string key by still producing the correct prefix and suffix structure.
Execution:
  Arrange: Create a Key object with an empty string value "".
  Act: Invoke the doKey method with the Key object and a StringBuilder context.
  Assert: Verify that the StringBuilder contains "node.`metadata.`".
Validation:
  The assertion verifies that the method handles edge cases gracefully without throwing exceptions. While an empty key may not be semantically valid, the method should still produce syntactically consistent output.

---

Scenario 5: Key With Only Double Quotes

Details:
  TestName: keyWithOnlyDoubleQuotes
  Description: Verify that the doKey method handles a key consisting entirely of double quotes by removing all of them.
Execution:
  Arrange: Create a Key object with a value of "\"\"\"".
  Act: Invoke the doKey method with the Key object and a StringBuilder context.
  Assert: Verify that the StringBuilder contains "node.`metadata.`".
Validation:
  The assertion confirms that when a key contains only double quotes, they are all removed, resulting in an empty key name within the metadata path structure.

---

Scenario 6: Key With Spaces

Details:
  TestName: keyWithSpaces
  Description: Verify that the doKey method preserves spaces in the key value since only double quotes are removed.
Execution:
  Arrange: Create a Key object with a value like "field name with spaces".
  Act: Invoke the doKey method with the Key object and a StringBuilder context.
  Assert: Verify that the StringBuilder contains "node.`metadata.field name with spaces`".
Validation:
  The assertion verifies that spaces are preserved in the key name. The backtick escaping in Neo4j allows property names with spaces, so this behavior is correct and necessary for supporting such metadata field names.

---

Scenario 7: Key With Special Characters Other Than Double Quotes

Details:
  TestName: keyWithSpecialCharactersOtherThanDoubleQuotes
  Description: Verify that the doKey method preserves special characters like dots, underscores, and hyphens since only double quotes are removed.
Execution:
  Arrange: Create a Key object with a value like "field.name_with-special".
  Act: Invoke the doKey method with the Key object and a StringBuilder context.
  Assert: Verify that the StringBuilder contains "node.`metadata.field.name_with-special`".
Validation:
  The assertion confirms that special characters other than double quotes are preserved. The backtick escaping in Neo4j handles these characters, making this behavior correct for complex metadata field names.

---

Scenario 8: Key Appended To Existing StringBuilder Content

Details:
  TestName: keyAppendedToExistingStringBuilderContent
  Description: Verify that the doKey method correctly appends to a StringBuilder that already contains content.
Execution:
  Arrange: Create a Key object with a value "category" and a StringBuilder pre-populated with "WHERE ".
  Act: Invoke the doKey method with the Key object and the pre-populated StringBuilder context.
  Assert: Verify that the StringBuilder contains "WHERE node.`metadata.category`".
Validation:
  The assertion verifies that the method appends to existing content rather than replacing it. This is crucial for building complete Cypher query expressions where the key is part of a larger condition.

---

Scenario 9: Key With Unicode Characters

Details:
  TestName: keyWithUnicodeCharacters
  Description: Verify that the doKey method correctly handles keys containing Unicode characters.
Execution:
  Arrange: Create a Key object with a value like "日本語フィールド".
  Act: Invoke the doKey method with the Key object and a StringBuilder context.
  Assert: Verify that the StringBuilder contains "node.`metadata.日本語フィールド`".
Validation:
  The assertion confirms that Unicode characters are preserved in the key name. This ensures internationalization support for metadata field names in different languages.

---

Scenario 10: Key With Mixed Double Quotes And Other Characters

Details:
  TestName: keyWithMixedDoubleQuotesAndOtherCharacters
  Description: Verify that the doKey method removes only double quotes while preserving all other characters including single quotes and backticks.
Execution:
  Arrange: Create a Key object with a value like "field'name\"test`value".
  Act: Invoke the doKey method with the Key object and a StringBuilder context.
  Assert: Verify that the StringBuilder contains "node.`metadata.field'nametest`value`".
Validation:
  The assertion verifies that the replace operation targets only double quotes and leaves other quote-like characters intact. This precise behavior is important for accurate query generation.

*/

// ********RoostGPT********

package org.springframework.ai.vectorstore.neo4j.filter;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.ai.vectorstore.filter.Filter.Key;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;
import org.springframework.ai.vectorstore.filter.Filter;
import org.springframework.ai.vectorstore.filter.Filter.Expression;
import org.springframework.ai.vectorstore.filter.Filter.Group;
import org.springframework.ai.vectorstore.filter.converter.AbstractFilterExpressionConverter;

class Neo4JVectorFilterExpressionConverterDoKeyTest {

	private Neo4jVectorFilterExpressionConverter converter;

	@BeforeEach
	void setUp() {
		converter = new Neo4jVectorFilterExpressionConverter();
	}

	@Test
	@Tag("valid")
	void simpleKeyWithoutSpecialCharacters() {
		// Arrange
		Key key = new Key("author");
		StringBuilder context = new StringBuilder();
		// Act
		converter.doKey(key, context);
		// Assert
		assertEquals("node.`metadata.author`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithDoubleQuotesRemoved() {
		// Arrange
		Key key = new Key("\"fieldName\"");
		StringBuilder context = new StringBuilder();
		// Act
		converter.doKey(key, context);
		// Assert
		assertEquals("node.`metadata.fieldName`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithEmbeddedDoubleQuotes() {
		// Arrange
		Key key = new Key("field\"Name\"Test");
		StringBuilder context = new StringBuilder();
		// Act
		converter.doKey(key, context);
		// Assert
		assertEquals("node.`metadata.fieldNameTest`", context.toString());
	}

	@Test
	@Tag("boundary")
	void keyWithEmptyString() {
		// Arrange
		Key key = new Key("");
		StringBuilder context = new StringBuilder();
		// Act
		converter.doKey(key, context);
		// Assert
		assertEquals("node.`metadata.`", context.toString());
	}

	@Test
	@Tag("boundary")
	void keyWithOnlyDoubleQuotes() {
		// Arrange
		Key key = new Key("\"\"\"");
		StringBuilder context = new StringBuilder();
		// Act
		converter.doKey(key, context);
		// Assert
		assertEquals("node.`metadata.`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithSpaces() {
		// Arrange
		Key key = new Key("field name with spaces");
		StringBuilder context = new StringBuilder();
		// Act
		converter.doKey(key, context);
		// Assert
		assertEquals("node.`metadata.field name with spaces`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithSpecialCharactersOtherThanDoubleQuotes() {
		// Arrange
		Key key = new Key("field.name_with-special");
		StringBuilder context = new StringBuilder();
		// Act
		converter.doKey(key, context);
		// Assert
		assertEquals("node.`metadata.field.name_with-special`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyAppendedToExistingStringBuilderContent() {
		// Arrange
		Key key = new Key("category");
		StringBuilder context = new StringBuilder("WHERE ");
		// Act
		converter.doKey(key, context);
		// Assert
		assertEquals("WHERE node.`metadata.category`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithUnicodeCharacters() {
		// Arrange
		Key key = new Key("日本語フィールド");
		StringBuilder context = new StringBuilder();
		// Act
		converter.doKey(key, context);
		// Assert
		assertEquals("node.`metadata.日本語フィールド`", context.toString());
	}

	@Test
	@Tag("valid")
	void keyWithMixedDoubleQuotesAndOtherCharacters() {
		// Arrange
		Key key = new Key("field'name\"test`value");
		StringBuilder context = new StringBuilder();
		// Act
		converter.doKey(key, context);
		// Assert
		assertEquals("node.`metadata.field'nametest`value`", context.toString());
	}

}