/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-dec-11-java using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=doExpression_7373dbacf8
ROOST_METHOD_SIG_HASH=doExpression_f053663651

Scenario 1: Test NIN Expression Type Conversion

Details:
  TestName: ninExpressionTypeConvertsToNotInFormat
  Description: Verify that when an expression with NIN (Not In) type is passed, the method correctly transforms it into a NOT IN format by delegating to the doNot method with a wrapped IN expression.

Execution:
  Arrange: Create an Expression with type NIN, a Key as the left operand, and a list of values as the right operand.
  Act: Invoke doExpression with the NIN expression and a StringBuilder context.
  Assert: Verify that the context contains "NOT " prefix followed by the converted IN expression format.

Validation:
  The assertion verifies that NIN expressions are properly transformed into "NOT <left> IN <right>" format instead of "<left> NOT IN <right>". This is significant because Neo4j requires this specific syntax for negated IN operations.

---

Scenario 2: Test EQ Expression Type Conversion

Details:
  TestName: eqExpressionTypeProducesEqualitySymbol
  Description: Verify that an expression with EQ (Equals) type produces the correct equality operator " = " between the left and right operands.

Execution:
  Arrange: Create an Expression with type EQ, a Key as the left operand, and a value as the right operand.
  Act: Invoke doExpression with the EQ expression and a StringBuilder context.
  Assert: Verify that the context contains the left operand, " = " symbol, and right operand in sequence.

Validation:
  The assertion confirms that equality comparisons are correctly formatted for Neo4j queries. This is essential for filtering vector store results based on exact metadata matches.

---

Scenario 3: Test NE Expression Type Conversion

Details:
  TestName: neExpressionTypeProducesNotEqualSymbol
  Description: Verify that an expression with NE (Not Equals) type produces the correct inequality operator " <> " between operands.

Execution:
  Arrange: Create an Expression with type NE, a Key as the left operand, and a value as the right operand.
  Act: Invoke doExpression with the NE expression and a StringBuilder context.
  Assert: Verify that the context contains the left operand, " <> " symbol, and right operand in sequence.

Validation:
  The assertion ensures that not-equal comparisons use Neo4j's standard inequality operator. This supports filtering out specific metadata values from vector search results.

---

Scenario 4: Test LT Expression Type Conversion

Details:
  TestName: ltExpressionTypeProducesLessThanSymbol
  Description: Verify that an expression with LT (Less Than) type produces the correct " < " operator between operands.

Execution:
  Arrange: Create an Expression with type LT, a Key as the left operand, and a numeric value as the right operand.
  Act: Invoke doExpression with the LT expression and a StringBuilder context.
  Assert: Verify that the context contains the left operand, " < " symbol, and right operand in sequence.

Validation:
  The assertion confirms proper formatting of less-than comparisons for range-based filtering in Neo4j vector queries.

---

Scenario 5: Test LTE Expression Type Conversion

Details:
  TestName: lteExpressionTypeProducesLessThanOrEqualSymbol
  Description: Verify that an expression with LTE (Less Than or Equal) type produces the correct " <= " operator.

Execution:
  Arrange: Create an Expression with type LTE, a Key as the left operand, and a numeric value as the right operand.
  Act: Invoke doExpression with the LTE expression and a StringBuilder context.
  Assert: Verify that the context contains the left operand, " <= " symbol, and right operand in sequence.

Validation:
  The assertion ensures inclusive upper-bound comparisons are correctly formatted for Neo4j filter expressions.

---

Scenario 6: Test GT Expression Type Conversion

Details:
  TestName: gtExpressionTypeProducesGreaterThanSymbol
  Description: Verify that an expression with GT (Greater Than) type produces the correct " > " operator.

Execution:
  Arrange: Create an Expression with type GT, a Key as the left operand, and a numeric value as the right operand.
  Act: Invoke doExpression with the GT expression and a StringBuilder context.
  Assert: Verify that the context contains the left operand, " > " symbol, and right operand in sequence.

Validation:
  The assertion confirms proper formatting of greater-than comparisons for range-based filtering.

---

Scenario 7: Test GTE Expression Type Conversion

Details:
  TestName: gteExpressionTypeProducesGreaterThanOrEqualSymbol
  Description: Verify that an expression with GTE (Greater Than or Equal) type produces the correct " >= " operator.

Execution:
  Arrange: Create an Expression with type GTE, a Key as the left operand, and a numeric value as the right operand.
  Act: Invoke doExpression with the GTE expression and a StringBuilder context.
  Assert: Verify that the context contains the left operand, " >= " symbol, and right operand in sequence.

Validation:
  The assertion ensures inclusive lower-bound comparisons are correctly formatted for Neo4j filter expressions.

---

Scenario 8: Test IN Expression Type Conversion

Details:
  TestName: inExpressionTypeProducesInSymbol
  Description: Verify that an expression with IN type produces the correct " IN " operator for membership testing.

Execution:
  Arrange: Create an Expression with type IN, a Key as the left operand, and a list of values as the right operand.
  Act: Invoke doExpression with the IN expression and a StringBuilder context.
  Assert: Verify that the context contains the left operand, " IN " symbol, and right operand in sequence.

Validation:
  The assertion confirms that IN expressions are properly formatted for checking if a value exists within a collection in Neo4j queries.

---

Scenario 9: Test AND Expression Type Conversion

Details:
  TestName: andExpressionTypeProducesAndSymbol
  Description: Verify that an expression with AND type produces the correct " AND " logical operator between two sub-expressions.

Execution:
  Arrange: Create an Expression with type AND, with left and right operands being sub-expressions.
  Act: Invoke doExpression with the AND expression and a StringBuilder context.
  Assert: Verify that the context contains the left expression, " AND " symbol, and right expression in sequence.

Validation:
  The assertion ensures compound filter conditions using logical AND are correctly formatted for Neo4j queries.

---

Scenario 10: Test OR Expression Type Conversion

Details:
  TestName: orExpressionTypeProducesOrSymbol
  Description: Verify that an expression with OR type produces the correct " OR " logical operator between two sub-expressions.

Execution:
  Arrange: Create an Expression with type OR, with left and right operands being sub-expressions.
  Act: Invoke doExpression with the OR expression and a StringBuilder context.
  Assert: Verify that the context contains the left expression, " OR " symbol, and right expression in sequence.

Validation:
  The assertion ensures compound filter conditions using logical OR are correctly formatted for Neo4j queries.

---

Scenario 11: Test Expression With String Value Operand

Details:
  TestName: expressionWithStringValueOperandConvertsCorrectly
  Description: Verify that expressions with string values as right operands are properly converted and included in the output.

Execution:
  Arrange: Create an Expression with type EQ, a Key as the left operand, and a string value as the right operand.
  Act: Invoke doExpression with the expression and a StringBuilder context.
  Assert: Verify that the context contains the properly formatted string value.

Validation:
  The assertion confirms that string operands are correctly handled in the expression conversion, which is critical for text-based metadata filtering.

---

Scenario 12: Test Expression With Numeric Value Operand

Details:
  TestName: expressionWithNumericValueOperandConvertsCorrectly
  Description: Verify that expressions with numeric values as right operands are properly converted without quotes.

Execution:
  Arrange: Create an Expression with type GT, a Key as the left operand, and an integer or double value as the right operand.
  Act: Invoke doExpression with the expression and a StringBuilder context.
  Assert: Verify that the context contains the numeric value without string quotes.

Validation:
  The assertion ensures numeric operands are correctly formatted for Neo4j queries, enabling proper numeric comparisons.

---

Scenario 13: Test Context Accumulation With Multiple Expressions

Details:
  TestName: contextAccumulatesMultipleExpressionOutputs
  Description: Verify that when doExpression is called multiple times with the same StringBuilder, the outputs are properly accumulated.

Execution:
  Arrange: Create a StringBuilder with existing content and an Expression with type EQ.
  Act: Invoke doExpression with the expression and the pre-populated StringBuilder context.
  Assert: Verify that the context contains both the original content and the new expression output.

Validation:
  The assertion confirms that the method properly appends to existing context rather than replacing it, which is important for building complex compound expressions.

---

Scenario 14: Test NIN Expression With Empty List

Details:
  TestName: ninExpressionWithEmptyListHandledCorrectly
  Description: Verify that a NIN expression with an empty list as the right operand is correctly transformed.

Execution:
  Arrange: Create an Expression with type NIN, a Key as the left operand, and an empty list as the right operand.
  Act: Invoke doExpression with the NIN expression and a StringBuilder context.
  Assert: Verify that the context contains the NOT IN format with the empty list representation.

Validation:
  The assertion ensures edge cases with empty collections are handled properly, maintaining query validity.

---

Scenario 15: Test Expression With Key Containing Special Characters

Details:
  TestName: expressionWithKeyContainingSpecialCharactersConvertsCorrectly
  Description: Verify that expressions with keys containing special characters (like quotes) are properly escaped or handled.

Execution:
  Arrange: Create an Expression with type EQ, a Key containing special characters as the left operand, and a value as the right operand.
  Act: Invoke doExpression with the expression and a StringBuilder context.
  Assert: Verify that the context contains the properly formatted key with special characters handled.

Validation:
  The assertion confirms that metadata keys with special characters don't break the generated Neo4j query syntax.

*/

// ********RoostGPT********

package org.springframework.ai.vectorstore.neo4j.filter;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.ai.vectorstore.filter.Filter;
import org.springframework.ai.vectorstore.filter.Filter.Expression;
import org.springframework.ai.vectorstore.filter.Filter.Key;
import org.springframework.ai.vectorstore.filter.Filter.Value;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.ai.vectorstore.filter.Filter.Group;
import org.springframework.ai.vectorstore.filter.converter.AbstractFilterExpressionConverter;

class Neo4JVectorFilterExpressionConverterDoExpressionTest {

	private Neo4jVectorFilterExpressionConverter converter;

	@BeforeEach
	void setUp() {
		converter = new Neo4jVectorFilterExpressionConverter();
	}

	@Test
	@Tag("valid")
	void ninExpressionTypeConvertsToNotInFormat() {
		Key key = new Key("category");
		Value value = new Value(Arrays.asList("electronics", "books"));
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, key, value);
		StringBuilder context = new StringBuilder();
		converter.doExpression(ninExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains("NOT"));
	}

	@Test
	@Tag("valid")
	void eqExpressionTypeProducesEqualitySymbol() {
		Key key = new Key("status");
		Value value = new Value("active");
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, key, value);
		StringBuilder context = new StringBuilder();
		converter.doExpression(eqExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" = "));
	}

	@Test
	@Tag("valid")
	void neExpressionTypeProducesNotEqualSymbol() {
		Key key = new Key("status");
		Value value = new Value("inactive");
		Expression neExpression = new Expression(Filter.ExpressionType.NE, key, value);
		StringBuilder context = new StringBuilder();
		converter.doExpression(neExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" <> "));
	}

	@Test
	@Tag("valid")
	void ltExpressionTypeProducesLessThanSymbol() {
		Key key = new Key("price");
		Value value = new Value(100);
		Expression ltExpression = new Expression(Filter.ExpressionType.LT, key, value);
		StringBuilder context = new StringBuilder();
		converter.doExpression(ltExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" < "));
	}

	@Test
	@Tag("valid")
	void lteExpressionTypeProducesLessThanOrEqualSymbol() {
		Key key = new Key("quantity");
		Value value = new Value(50);
		Expression lteExpression = new Expression(Filter.ExpressionType.LTE, key, value);
		StringBuilder context = new StringBuilder();
		converter.doExpression(lteExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" <= "));
	}

	@Test
	@Tag("valid")
	void gtExpressionTypeProducesGreaterThanSymbol() {
		Key key = new Key("rating");
		Value value = new Value(4.0);
		Expression gtExpression = new Expression(Filter.ExpressionType.GT, key, value);
		StringBuilder context = new StringBuilder();
		converter.doExpression(gtExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" > "));
	}

	@Test
	@Tag("valid")
	void gteExpressionTypeProducesGreaterThanOrEqualSymbol() {
		Key key = new Key("score");
		Value value = new Value(80);
		Expression gteExpression = new Expression(Filter.ExpressionType.GTE, key, value);
		StringBuilder context = new StringBuilder();
		converter.doExpression(gteExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" >= "));
	}

	@Test
	@Tag("valid")
	void inExpressionTypeProducesInSymbol() {
		Key key = new Key("type");
		Value value = new Value(Arrays.asList("A", "B", "C"));
		Expression inExpression = new Expression(Filter.ExpressionType.IN, key, value);
		StringBuilder context = new StringBuilder();
		converter.doExpression(inExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" IN "));
	}

	@Test
	@Tag("valid")
	void andExpressionTypeProducesAndSymbol() {
		Key key1 = new Key("status");
		Value value1 = new Value("active");
		Expression leftExpr = new Expression(Filter.ExpressionType.EQ, key1, value1);
		Key key2 = new Key("priority");
		Value value2 = new Value("high");
		Expression rightExpr = new Expression(Filter.ExpressionType.EQ, key2, value2);
		Expression andExpression = new Expression(Filter.ExpressionType.AND, leftExpr, rightExpr);
		StringBuilder context = new StringBuilder();
		converter.doExpression(andExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" AND "));
	}

	@Test
	@Tag("valid")
	void orExpressionTypeProducesOrSymbol() {
		Key key1 = new Key("category");
		Value value1 = new Value("electronics");
		Expression leftExpr = new Expression(Filter.ExpressionType.EQ, key1, value1);
		Key key2 = new Key("category");
		Value value2 = new Value("books");
		Expression rightExpr = new Expression(Filter.ExpressionType.EQ, key2, value2);
		Expression orExpression = new Expression(Filter.ExpressionType.OR, leftExpr, rightExpr);
		StringBuilder context = new StringBuilder();
		converter.doExpression(orExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" OR "));
	}

	@Test
	@Tag("valid")
	void expressionWithStringValueOperandConvertsCorrectly() {
		Key key = new Key("name");
		Value value = new Value("test-value");
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, key, value);
		StringBuilder context = new StringBuilder();
		converter.doExpression(eqExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertFalse(result.isEmpty());
	}

	@Test
	@Tag("valid")
	void expressionWithNumericValueOperandConvertsCorrectly() {
		Key key = new Key("count");
		Value value = new Value(42);
		Expression gtExpression = new Expression(Filter.ExpressionType.GT, key, value);
		StringBuilder context = new StringBuilder();
		converter.doExpression(gtExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" > "));
	}

	@Test
	@Tag("valid")
	void contextAccumulatesMultipleExpressionOutputs() {
		StringBuilder context = new StringBuilder("WHERE ");
		Key key = new Key("field");
		Value value = new Value("value");
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, key, value);
		converter.doExpression(eqExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.startsWith("WHERE "));
		assertTrue(result.contains(" = "));
	}

	@Test
	@Tag("boundary")
	void ninExpressionWithEmptyListHandledCorrectly() {
		Key key = new Key("tags");
		Value value = new Value(Collections.emptyList());
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, key, value);
		StringBuilder context = new StringBuilder();
		converter.doExpression(ninExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains("NOT"));
	}

	@Test
	@Tag("boundary")
	void expressionWithKeyContainingSpecialCharactersConvertsCorrectly() {
		Key key = new Key("field\"name");
		Value value = new Value("test");
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, key, value);
		StringBuilder context = new StringBuilder();
		converter.doExpression(eqExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertFalse(result.isEmpty());
	}

	@Test
	@Tag("valid")
	void expressionWithDoubleValueOperandConvertsCorrectly() {
		Key key = new Key("temperature");
		Value value = new Value(36.5);
		Expression lteExpression = new Expression(Filter.ExpressionType.LTE, key, value);
		StringBuilder context = new StringBuilder();
		converter.doExpression(lteExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" <= "));
	}

	@Test
	@Tag("valid")
	void expressionWithBooleanValueOperandConvertsCorrectly() {
		Key key = new Key("isActive");
		Value value = new Value(true);
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, key, value);
		StringBuilder context = new StringBuilder();
		converter.doExpression(eqExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" = "));
	}

	@Test
	@Tag("valid")
	void inExpressionWithSingleElementListConvertsCorrectly() {
		Key key = new Key("status");
		Value value = new Value(Collections.singletonList("pending"));
		Expression inExpression = new Expression(Filter.ExpressionType.IN, key, value);
		StringBuilder context = new StringBuilder();
		converter.doExpression(inExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" IN "));
	}

	@Test
	@Tag("valid")
	void ninExpressionWithSingleElementListConvertsCorrectly() {
		Key key = new Key("role");
		Value value = new Value(Collections.singletonList("admin"));
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, key, value);
		StringBuilder context = new StringBuilder();
		converter.doExpression(ninExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains("NOT"));
	}

	@Test
	@Tag("valid")
	void nestedAndOrExpressionsConvertCorrectly() {
		Key key1 = new Key("a");
		Value value1 = new Value(1);
		Expression expr1 = new Expression(Filter.ExpressionType.EQ, key1, value1);
		Key key2 = new Key("b");
		Value value2 = new Value(2);
		Expression expr2 = new Expression(Filter.ExpressionType.EQ, key2, value2);
		Expression andExpr = new Expression(Filter.ExpressionType.AND, expr1, expr2);
		Key key3 = new Key("c");
		Value value3 = new Value(3);
		Expression expr3 = new Expression(Filter.ExpressionType.EQ, key3, value3);
		Expression orExpr = new Expression(Filter.ExpressionType.OR, andExpr, expr3);
		StringBuilder context = new StringBuilder();
		converter.doExpression(orExpr, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" OR "));
	}

	@Test
	@Tag("boundary")
	void expressionWithLongNumericValueConvertsCorrectly() {
		Key key = new Key("timestamp");
		Value value = new Value(1234567890123L);
		Expression gtExpression = new Expression(Filter.ExpressionType.GT, key, value);
		StringBuilder context = new StringBuilder();
		converter.doExpression(gtExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" > "));
	}

	@Test
	@Tag("valid")
	void expressionWithNegativeNumericValueConvertsCorrectly() {
		Key key = new Key("balance");
		Value value = new Value(-100);
		Expression ltExpression = new Expression(Filter.ExpressionType.LT, key, value);
		StringBuilder context = new StringBuilder();
		converter.doExpression(ltExpression, context);
		String result = context.toString();
		assertNotNull(result);
		assertTrue(result.contains(" < "));
	}

}