/*
 * Copyright 2023-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-spring-ai using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=builder_01208c362d
ROOST_METHOD_SIG_HASH=builder_5ad6c5d8b1

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/maven-spring-ai/1772161967/source/spring-ai/vector-stores/spring-ai-azure-cosmos-db-store/src/test/java/org/springframework/ai/vectorstore/cosmosdb/CosmosDBVectorStoreWithMetadataPartitionKeyIT.java
Tests:
    "@Test
public void testAddSearchAndDeleteDocuments() {

    Document document1 = new Document(UUID.randomUUID().toString(), "Sample content1", Map.of("key1", "value1"));
    assertThatThrownBy(() -> this.vectorStore.add(List.of(document1))).isInstanceOf(Exception.class).hasMessageContaining("Partition key 'country' not found in document metadata.");
    Document document2 = new Document(UUID.randomUUID().toString(), "Sample content1", Map.of("country", "UK"));
    this.vectorStore.add(List.of(document2));

    List<Document> results = this.vectorStore.similaritySearch(SearchRequest.builder().query("Sample content1").topK(1).build());

    assertThat(results).isNotEmpty();
    assertThat(results.get(0).getId()).isEqualTo(document2.getId());

    this.vectorStore.delete(List.of(document2.getId()));

    List<Document> results2 = this.vectorStore.similaritySearch(SearchRequest.builder().query("Sample content").topK(1).build());

    assertThat(results2).isEmpty();
}
"
    "@Test
void testSimilaritySearchWithFilter() {

    Map<String, Object> metadata1;
    metadata1 = new HashMap<>();
    metadata1.put("country", "UK");
    metadata1.put("year", 2021);
    metadata1.put("city", "London");
    Map<String, Object> metadata2;
    metadata2 = new HashMap<>();
    metadata2.put("country", "NL");
    metadata2.put("year", 2022);
    metadata2.put("city", "Amsterdam");
    Map<String, Object> metadata3;
    metadata3 = new HashMap<>();
    metadata3.put("country", "US");
    metadata3.put("year", 2019);
    metadata3.put("city", "Sofia");
    Map<String, Object> metadata4;
    metadata4 = new HashMap<>();
    metadata4.put("country", "US");
    metadata4.put("year", 2020);
    metadata4.put("city", "Sofia");
    Document document1 = new Document("1", "A document about the UK", metadata1);
    Document document2 = new Document("2", "A document about the Netherlands", metadata2);
    Document document3 = new Document("3", "A document about the US", metadata3);
    Document document4 = new Document("4", "A document about the US", metadata4);
    this.vectorStore.add(List.of(document1, document2, document3, document4));
    FilterExpressionBuilder b = new FilterExpressionBuilder();
    List<Document> results = this.vectorStore.similaritySearch(SearchRequest.builder().query("The World").topK(10).filterExpression((b.in("country", "UK", "NL")).build()).build());
    assertThat(results).hasSize(2);
    assertThat(results).extracting(Document::getId).containsExactlyInAnyOrder("1", "2");
    for (Document doc : results) {
        assertThat(doc.getMetadata().get("country")).isIn("UK", "NL");
        assertThat(doc.getMetadata().get("year")).isIn(2021, 2022);
        assertThat(doc.getMetadata().get("city")).isIn("London", "Amsterdam").isNotEqualTo("Sofia");
    }
    List<Document> results2 = this.vectorStore.similaritySearch(SearchRequest.builder().query("The World").topK(10).filterExpression(b.and(b.or(b.gte("year", 2021), b.eq("country", "NL")), b.ne("city", "Amsterdam")).build()).build());
    assertThat(results2).hasSize(1);
    assertThat(results2).extracting(Document::getId).containsExactlyInAnyOrder("1");
    List<Document> results3 = this.vectorStore.similaritySearch(SearchRequest.builder().query("The World").topK(10).filterExpression(b.and(b.eq("country", "US"), b.eq("year", 2020)).build()).build());
    assertThat(results3).hasSize(1);
    assertThat(results3).extracting(Document::getId).containsExactlyInAnyOrder("4");
    this.vectorStore.delete(List.of(document1.getId(), document2.getId(), document3.getId(), document4.getId()));

    List<Document> results4 = this.vectorStore.similaritySearch(SearchRequest.builder().query("The World").topK(1).build());

    assertThat(results4).isEmpty();
}
"

File Path: /var/tmp/Roost/RoostGPT/maven-spring-ai/1772161967/source/spring-ai/vector-stores/spring-ai-azure-cosmos-db-store/src/test/java/org/springframework/ai/vectorstore/cosmosdb/CosmosDBVectorStoreIT.java
Tests:
    "@Test
public void testAddSearchAndDeleteDocuments() {

    Document document1 = new Document(UUID.randomUUID().toString(), "Sample content1", Map.of("key1", "value1"));
    Document document2 = new Document(UUID.randomUUID().toString(), "Sample content2", Map.of("key2", "value2"));

    this.vectorStore.add(List.of(document1, document2));

    Document document3 = new Document(document1.getId(), "Sample content3", Map.of("key3", "value3"));
    assertThatThrownBy(() -> this.vectorStore.add(List.of(document3))).isInstanceOf(Exception.class).hasMessageContaining("Duplicate document id: " + document1.getId());

    List<Document> results = this.vectorStore.similaritySearch(SearchRequest.builder().query("Sample content").topK(1).build());

    assertThat(results).isNotEmpty();
    assertThat(results.get(0).getId()).isEqualTo(document1.getId());

    this.vectorStore.delete(List.of(document1.getId(), document2.getId()));

    List<Document> results2 = this.vectorStore.similaritySearch(SearchRequest.builder().query("Sample content").topK(1).build());

    assertThat(results2).isEmpty();
}
"
    "@Test
void testSimilaritySearchWithFilter() {

    Map<String, Object> metadata1;
    metadata1 = new HashMap<>();
    metadata1.put("country", "UK");
    metadata1.put("year", 2021);
    metadata1.put("city", "London");
    Map<String, Object> metadata2;
    metadata2 = new HashMap<>();
    metadata2.put("country", "NL");
    metadata2.put("year", 2022);
    metadata2.put("city", "Amsterdam");
    Map<String, Object> metadata3;
    metadata3 = new HashMap<>();
    metadata3.put("country", "US");
    metadata3.put("year", 2019);
    metadata3.put("city", "Sofia");
    Map<String, Object> metadata4;
    metadata4 = new HashMap<>();
    metadata4.put("country", "US");
    metadata4.put("year", 2020);
    metadata4.put("city", "Sofia");
    Document document1 = new Document("1", "A document about the UK", metadata1);
    Document document2 = new Document("2", "A document about the Netherlands", metadata2);
    Document document3 = new Document("3", "A document about the US", metadata3);
    Document document4 = new Document("4", "A document about the US", metadata4);
    this.vectorStore.add(List.of(document1, document2, document3, document4));
    FilterExpressionBuilder b = new FilterExpressionBuilder();
    List<Document> results = this.vectorStore.similaritySearch(SearchRequest.builder().query("The World").topK(10).filterExpression((b.in("country", "UK", "NL")).build()).build());
    assertThat(results).hasSize(2);
    assertThat(results).extracting(Document::getId).containsExactlyInAnyOrder("1", "2");
    for (Document doc : results) {
        assertThat(doc.getMetadata().get("country")).isIn("UK", "NL");
        assertThat(doc.getMetadata().get("year")).isIn(2021, 2022);
        assertThat(doc.getMetadata().get("city")).isIn("London", "Amsterdam").isNotEqualTo("Sofia");
    }
    List<Document> results2 = this.vectorStore.similaritySearch(SearchRequest.builder().query("The World").topK(10).filterExpression(b.and(b.or(b.gte("year", 2021), b.eq("country", "NL")), b.ne("city", "Amsterdam")).build()).build());
    assertThat(results2).hasSize(1);
    assertThat(results2).extracting(Document::getId).containsExactlyInAnyOrder("1");
    List<Document> results3 = this.vectorStore.similaritySearch(SearchRequest.builder().query("The World").topK(10).filterExpression(b.and(b.eq("country", "US"), b.eq("year", 2020)).build()).build());
    assertThat(results3).hasSize(1);
    assertThat(results3).extracting(Document::getId).containsExactlyInAnyOrder("4");
    this.vectorStore.delete(List.of(document1.getId(), document2.getId(), document3.getId(), document4.getId()));

    List<Document> results4 = this.vectorStore.similaritySearch(SearchRequest.builder().query("The World").topK(1).build());

    assertThat(results4).isEmpty();
}
"Scenario 1: Builder Creation with Valid Parameters

Details:
  TestName: builderCreatesBuilderInstanceWithValidParameters
  Description: This test ensures that the builder method successfully creates and returns a non-null Builder instance when provided with a valid CosmosAsyncClient and a valid EmbeddingModel. The primary functionality under test is the correct instantiation of the Builder.

Execution:
  Arrange: Mock or instantiate a valid CosmosAsyncClient and a valid EmbeddingModel as required by the builder method.
  Act: Call CosmosDBVectorStore.builder(cosmosClient, embeddingModel).
  Assert: Assert that the returned object is not null and that its type is CosmosDBVectorStore.Builder.

Validation:
  The assertion verifies that the builder factory method correctly constructs and returns a functional Builder instance when provided with all necessary and valid parameters. This test confirms the base path for object construction within the API and highlights correct usage of the static builder mechanic.

*/

// ********RoostGPT********

package org.springframework.ai.vectorstore.cosmosdb;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.azure.cosmos.CosmosAsyncClient;
import org.springframework.ai.embedding.EmbeddingModel;
import org.junit.jupiter.api.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import com.azure.cosmos.CosmosAsyncContainer;
import com.azure.cosmos.CosmosAsyncDatabase;
import com.azure.cosmos.implementation.guava25.collect.ImmutableList;
import com.azure.cosmos.models.CosmosBulkOperations;
import com.azure.cosmos.models.CosmosContainerProperties;
import com.azure.cosmos.models.CosmosItemOperation;
import com.azure.cosmos.models.CosmosQueryRequestOptions;
import com.azure.cosmos.models.CosmosVectorDataType;
import com.azure.cosmos.models.CosmosVectorDistanceFunction;
import com.azure.cosmos.models.CosmosVectorEmbedding;
import com.azure.cosmos.models.CosmosVectorEmbeddingPolicy;
import com.azure.cosmos.models.CosmosVectorIndexSpec;
import com.azure.cosmos.models.CosmosVectorIndexType;
import com.azure.cosmos.models.ExcludedPath;
import com.azure.cosmos.models.IncludedPath;
import com.azure.cosmos.models.IndexingMode;
import com.azure.cosmos.models.IndexingPolicy;
import com.azure.cosmos.models.PartitionKey;
import com.azure.cosmos.models.PartitionKeyDefinition;
import com.azure.cosmos.models.PartitionKind;
import com.azure.cosmos.models.SqlParameter;
import com.azure.cosmos.models.SqlQuerySpec;
import com.azure.cosmos.models.ThroughputProperties;
import com.azure.cosmos.util.CosmosPagedFlux;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.apache.commons.lang3.tuple.ImmutablePair;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import reactor.core.publisher.Flux;
import org.springframework.ai.document.Document;
import org.springframework.ai.embedding.EmbeddingOptions;
import org.springframework.ai.observation.conventions.VectorStoreProvider;
import org.springframework.ai.vectorstore.AbstractVectorStoreBuilder;
import org.springframework.ai.vectorstore.SearchRequest;
import org.springframework.ai.vectorstore.filter.Filter;
import org.springframework.ai.vectorstore.observation.AbstractObservationVectorStore;
import org.springframework.ai.vectorstore.observation.VectorStoreObservationContext;
import org.springframework.lang.Nullable;
import org.springframework.util.Assert;

public class CosmosDbVectorStoreBuilderTest extends AbstractObservationVectorStore {

	@Test
	@Tag("valid")
	public void testBuilderCreatesBuilderInstanceWithValidParameters() {
		CosmosAsyncClient mockCosmosClient = mock(CosmosAsyncClient.class);
		EmbeddingModel mockEmbeddingModel = mock(EmbeddingModel.class);
		CosmosDBVectorStore.Builder builder = CosmosDBVectorStore.builder(mockCosmosClient, mockEmbeddingModel);
		assertNotNull(builder, "Builder instance should not be null");
		assertTrue(builder instanceof CosmosDBVectorStore.Builder,
				"Returned object should be of type CosmosDBVectorStore.Builder");
	}

}